CREATE TABLE [dbo].[SubWorkOrderMaterialStockLineAudit] (
    [SWOMStockLineAuditId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [SWOMStockLineId]         BIGINT          NOT NULL,
    [SubWorkOrderMaterialsId] BIGINT          NOT NULL,
    [StockLineId]             BIGINT          NOT NULL,
    [ItemMasterId]            BIGINT          NOT NULL,
    [ConditionId]             BIGINT          NOT NULL,
    [Quantity]                DECIMAL (18, 6) NULL,
    [QtyReserved]             DECIMAL (18, 6) NULL,
    [QtyIssued]               DECIMAL (18, 6) NULL,
    [MasterCompanyId]         INT             NOT NULL,
    [CreatedBy]               VARCHAR (256)   NOT NULL,
    [UpdatedBy]               VARCHAR (256)   NOT NULL,
    [CreatedDate]             DATETIME2 (7)   NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   NOT NULL,
    [IsActive]                BIT             NOT NULL,
    [IsDeleted]               BIT             NOT NULL,
    [AltPartMasterPartId]     BIGINT          NULL,
    [EquPartMasterPartId]     BIGINT          NULL,
    [IsAltPart]               BIT             NULL,
    [IsEquPart]               BIT             NULL,
    [UnitCost]                DECIMAL (18, 6) NULL,
    [ExtendedCost]            DECIMAL (18, 6) NULL,
    [UnitPrice]               DECIMAL (18, 6) NULL,
    [ExtendedPrice]           DECIMAL (18, 6) NULL,
    [ProvisionId]             INT             DEFAULT ((2)) NOT NULL,
    [RepairOrderId]           BIGINT          NULL,
    [QuantityTurnIn]          DECIMAL (18, 6) CONSTRAINT [DF__SubWorkOr__Quant__425E39D1] DEFAULT ((0)) NULL,
    [Figure]                  NVARCHAR (50)   NULL,
    [Item]                    NVARCHAR (50)   NULL,
    [ReferenceNumber]         VARCHAR (100)   NULL,
    [ReservedById]            BIGINT          NULL,
    [ReservedDate]            DATETIME2 (7)   NULL,
    [IssuedById]              BIGINT          NULL,
    [IssuedDate]              DATETIME2 (7)   NULL,
    CONSTRAINT [PK_SubWorkOrderMaterialStockLineAudit] PRIMARY KEY CLUSTERED ([SWOMStockLineAuditId] ASC)
);

