CREATE TABLE [dbo].[SubWorkOrderMaterialStockLineKit] (
    [SWOMStockLineKitId]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [SubWorkOrderMaterialsKitId] BIGINT          NOT NULL,
    [StockLIneId]                BIGINT          NOT NULL,
    [ItemMasterId]               BIGINT          NOT NULL,
    [ConditionId]                BIGINT          NOT NULL,
    [Quantity]                   INT             NULL,
    [QtyReserved]                INT             NULL,
    [QtyIssued]                  INT             NULL,
    [MasterCompanyId]            INT             NOT NULL,
    [CreatedBy]                  VARCHAR (256)   NOT NULL,
    [UpdatedBy]                  VARCHAR (256)   NOT NULL,
    [CreatedDate]                DATETIME2 (7)   CONSTRAINT [DF_SubWorkOrderMaterialStockLineKit_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                DATETIME2 (7)   CONSTRAINT [DF_SubWorkOrderMaterialStockLineKit_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                   BIT             CONSTRAINT [DF_SubWorkOrderMaterialStockLineKit_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                  BIT             CONSTRAINT [DF_SubWorkOrderMaterialStockLineKit_IsDeleted] DEFAULT ((0)) NOT NULL,
    [AltPartMasterPartId]        BIGINT          NULL,
    [EquPartMasterPartId]        BIGINT          NULL,
    [IsAltPart]                  BIT             NULL,
    [IsEquPart]                  BIT             NULL,
    [UnitCost]                   DECIMAL (20, 2) NULL,
    [ExtendedCost]               DECIMAL (20, 2) NULL,
    [UnitPrice]                  DECIMAL (20, 2) NULL,
    [ExtendedPrice]              DECIMAL (20, 2) NULL,
    [ProvisionId]                INT             DEFAULT ((2)) NOT NULL,
    [RepairOrderId]              BIGINT          NULL,
    [QuantityTurnIn]             INT             DEFAULT ((0)) NULL,
    [Figure]                     NVARCHAR (50)   NULL,
    [Item]                       NVARCHAR (50)   NULL,
    CONSTRAINT [PK_SubWorkOrderMaterialStockLineKit] PRIMARY KEY CLUSTERED ([SWOMStockLineKitId] ASC),
    CONSTRAINT [FK_SubWorkOrderMaterialStockLineKit_ConditionId] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([ConditionId]),
    CONSTRAINT [FK_SubWorkOrderMaterialStockLineKit_ItemMasterId] FOREIGN KEY ([ItemMasterId]) REFERENCES [dbo].[ItemMaster] ([ItemMasterId]),
    CONSTRAINT [FK_SubWorkOrderMaterialStockLineKit_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId]),
    CONSTRAINT [FK_SubWorkOrderMaterialStockLineKit_ProvisionId] FOREIGN KEY ([ProvisionId]) REFERENCES [dbo].[Provision] ([ProvisionId]),
    CONSTRAINT [FK_SubWorkOrderMaterialStockLineKit_RepairOrderId] FOREIGN KEY ([RepairOrderId]) REFERENCES [dbo].[RepairOrder] ([RepairOrderId]),
    CONSTRAINT [FK_SubWorkOrderMaterialStockLineKit_StockLine] FOREIGN KEY ([StockLIneId]) REFERENCES [dbo].[Stockline] ([StockLineId]),
    CONSTRAINT [FK_SubWorkOrderMaterialStockLineKit_SubWorkOrderMaterials] FOREIGN KEY ([SubWorkOrderMaterialsKitId]) REFERENCES [dbo].[SubWorkOrderMaterialsKit] ([SubWorkOrderMaterialsKitId])
);

