CREATE TABLE [dbo].[SubWorkOrderMaterialsAudit] (
    [SubWorkOrderMaterialsAuditId]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [SubWorkOrderMaterialsId]       BIGINT          NOT NULL,
    [WorkOrderId]                   BIGINT          NOT NULL,
    [SubWorkOrderId]                BIGINT          NOT NULL,
    [SubWOPartNoId]                 BIGINT          NOT NULL,
    [ItemMasterId]                  BIGINT          NOT NULL,
    [TaskId]                        BIGINT          NOT NULL,
    [ConditionCodeId]               BIGINT          NOT NULL,
    [ItemClassificationId]          BIGINT          NOT NULL,
    [Quantity]                      DECIMAL (18, 6) NULL,
    [UnitOfMeasureId]               BIGINT          NOT NULL,
    [UnitCost]                      DECIMAL (20, 2) NOT NULL,
    [ExtendedCost]                  DECIMAL (20, 2) NOT NULL,
    [Price]                         DECIMAL (20, 2) NULL,
    [ExtendedPrice]                 DECIMAL (20, 2) NULL,
    [Memo]                          NVARCHAR (MAX)  NULL,
    [IsDeferred]                    BIT             NULL,
    [QuantityReserved]              DECIMAL (18, 6) NULL,
    [QuantityIssued]                DECIMAL (18, 6) NULL,
    [IssuedDate]                    DATETIME2 (7)   NULL,
    [ReservedDate]                  DATETIME2 (7)   NULL,
    [IsAltPart]                     BIT             NULL,
    [AltPartMasterPartId]           BIGINT          NULL,
    [IsFromWorkFlow]                BIT             NULL,
    [PartStatusId]                  INT             NULL,
    [IssuedById]                    BIGINT          NULL,
    [ReservedById]                  BIGINT          NULL,
    [IsEquPart]                     BIT             NULL,
    [ParentSubWorkOrderMaterialsId] BIGINT          NULL,
    [ItemMappingId]                 BIGINT          NULL,
    [TotalReserved]                 DECIMAL (18, 6) NULL,
    [TotalIssued]                   DECIMAL (18, 6) NULL,
    [ProvisionId]                   INT             NOT NULL,
    [MaterialMandatoriesId]         INT             NULL,
    [MasterCompanyId]               INT             NOT NULL,
    [CreatedBy]                     VARCHAR (256)   NOT NULL,
    [UpdatedBy]                     VARCHAR (256)   NOT NULL,
    [CreatedDate]                   DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                   DATETIME2 (7)   NOT NULL,
    [IsActive]                      BIT             NOT NULL,
    [IsDeleted]                     BIT             NOT NULL,
    [QuantityTurnIn]                DECIMAL (18, 6) NULL,
    [Condition]                     VARCHAR (50)    NULL,
    [UOM]                           VARCHAR (50)    NULL,
    [ItemClassification]            VARCHAR (100)   NULL,
    [Provision]                     VARCHAR (50)    NULL,
    [TaskName]                      VARCHAR (50)    NULL,
    [Site]                          VARCHAR (50)    NULL,
    [WareHouse]                     VARCHAR (50)    NULL,
    [Locations]                     VARCHAR (50)    NULL,
    [Shelf]                         VARCHAR (50)    NULL,
    [Bin]                           VARCHAR (50)    NULL,
    [TotalStocklineQtyReq]          DECIMAL (18, 6) CONSTRAINT [DF__SubWorkOr__Total__3CA5607B] DEFAULT ((0)) NULL,
    [POId]                          BIGINT          NULL,
    [PONum]                         VARCHAR (50)    NULL,
    [PONextDlvrDate]                DATETIME2 (7)   NULL,
    [QtyOnOrder]                    DECIMAL (18, 6) NULL,
    [QtyOnBkOrder]                  DECIMAL (18, 6) NULL,
    [QtyToTurnIn]                   DECIMAL (18, 6) NULL,
    [Figure]                        NVARCHAR (50)   NULL,
    [Item]                          NVARCHAR (50)   NULL,
    [EquPartMasterPartId]           BIGINT          NULL,
    [UnReservedQty]                 DECIMAL (18, 6) NULL,
    [UnIssuedQty]                   DECIMAL (18, 6) NULL,
    [TotalUnIssued]                 DECIMAL (18, 6) NULL,
    [TotalUnReserved]               DECIMAL (18, 6) NULL,
    CONSTRAINT [PK_SubWorkOrderMaterialsAudit] PRIMARY KEY CLUSTERED ([SubWorkOrderMaterialsAuditId] ASC)
);

