CREATE TABLE [dbo].[SubWorkOrderMaterialsKitAudit] (
    [SubWorkOrderMaterialsKitAuditId]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [SubWorkOrderMaterialsKitId]        BIGINT          NOT NULL,
    [SubWorkOrderMaterialsKitMappingId] BIGINT          NOT NULL,
    [WorkOrderId]                       BIGINT          NOT NULL,
    [SubWorkOrderId]                    BIGINT          NOT NULL,
    [SubWOPartNoId]                     BIGINT          NOT NULL,
    [ItemMasterId]                      BIGINT          NOT NULL,
    [TaskId]                            BIGINT          NOT NULL,
    [ConditionCodeId]                   BIGINT          NOT NULL,
    [ItemClassificationId]              BIGINT          NOT NULL,
    [Quantity]                          INT             DEFAULT ((0)) NOT NULL,
    [UnitOfMeasureId]                   BIGINT          NOT NULL,
    [UnitCost]                          DECIMAL (20, 2) DEFAULT ((0)) NOT NULL,
    [ExtendedCost]                      DECIMAL (20, 2) DEFAULT ((0)) NOT NULL,
    [Price]                             DECIMAL (20, 2) NULL,
    [ExtendedPrice]                     DECIMAL (20, 2) NULL,
    [Memo]                              NVARCHAR (MAX)  NULL,
    [IsDeferred]                        BIT             DEFAULT ((0)) NULL,
    [QuantityReserved]                  INT             NULL,
    [QuantityIssued]                    INT             NULL,
    [IssuedDate]                        DATETIME2 (7)   NULL,
    [ReservedDate]                      DATETIME2 (7)   NULL,
    [IsAltPart]                         BIT             NULL,
    [AltPartMasterPartId]               BIGINT          NULL,
    [IsFromWorkFlow]                    BIT             DEFAULT ((0)) NULL,
    [PartStatusId]                      INT             NULL,
    [IssuedById]                        BIGINT          NULL,
    [ReservedById]                      BIGINT          NULL,
    [IsEquPart]                         BIT             NULL,
    [ParentSubWorkOrderMaterialsId]     BIGINT          NULL,
    [ItemMappingId]                     BIGINT          NULL,
    [TotalReserved]                     INT             NULL,
    [TotalIssued]                       INT             NULL,
    [ProvisionId]                       INT             NOT NULL,
    [MaterialMandatoriesId]             INT             NULL,
    [MasterCompanyId]                   INT             NOT NULL,
    [CreatedBy]                         VARCHAR (256)   NOT NULL,
    [UpdatedBy]                         VARCHAR (256)   NOT NULL,
    [CreatedDate]                       DATETIME2 (7)   CONSTRAINT [DF_SubWorkOrderMaterialsKitAudit_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                       DATETIME2 (7)   CONSTRAINT [DF_SubWorkOrderMaterialsKitAudit_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                          BIT             CONSTRAINT [SubWorkOrderMaterialsKitAudit_DC_Active] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                         BIT             CONSTRAINT [SubWorkOrderMaterialsKitAudit_DC_Delete] DEFAULT ((0)) NOT NULL,
    [QuantityTurnIn]                    INT             NULL,
    [Condition]                         VARCHAR (50)    NULL,
    [UOM]                               VARCHAR (50)    NULL,
    [ItemClassification]                VARCHAR (100)   NULL,
    [Provision]                         VARCHAR (50)    NULL,
    [TaskName]                          VARCHAR (50)    NULL,
    [Site]                              VARCHAR (50)    NULL,
    [WareHouse]                         VARCHAR (50)    NULL,
    [Locations]                         VARCHAR (50)    NULL,
    [Shelf]                             VARCHAR (50)    NULL,
    [Bin]                               VARCHAR (50)    NULL,
    [TotalStocklineQtyReq]              INT             DEFAULT ((0)) NOT NULL,
    [POId]                              BIGINT          NULL,
    [PONum]                             VARCHAR (50)    NULL,
    [PONextDlvrDate]                    DATETIME2 (7)   NULL,
    [QtyOnOrder]                        INT             NULL,
    [QtyOnBkOrder]                      INT             NULL,
    [QtyToTurnIn]                       INT             NULL,
    [Figure]                            NVARCHAR (50)   NULL,
    [Item]                              NVARCHAR (50)   NULL,
    [EquPartMasterPartId]               BIGINT          NULL,
    CONSTRAINT [PK_SubWorkOrderMaterialsKitAudit] PRIMARY KEY CLUSTERED ([SubWorkOrderMaterialsKitAuditId] ASC)
);

