CREATE TABLE [dbo].[SubWorkOrderMaterialStockLineKitAudit] (
    [SWOMStockLineKitAuditId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [SWOMStockLineKitId]         BIGINT          NOT NULL,
    [SubWorkOrderMaterialsKitId] BIGINT          NOT NULL,
    [StockLIneId]                BIGINT          NOT NULL,
    [ItemMasterId]               BIGINT          NOT NULL,
    [ConditionId]                BIGINT          NOT NULL,
    [Quantity]                   INT             NULL,
    [QtyReserved]                INT             NULL,
    [QtyIssued]                  INT             NULL,
    [MasterCompanyId]            INT             NOT NULL,
    [CreatedBy]                  VARCHAR (256)   NOT NULL,
    [UpdatedBy]                  VARCHAR (256)   NOT NULL,
    [CreatedDate]                DATETIME2 (7)   CONSTRAINT [DF_SubWorkOrderMaterialStockLineKitAudit_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                DATETIME2 (7)   CONSTRAINT [DF_SubWorkOrderMaterialStockLineKitAudit_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                   BIT             CONSTRAINT [DF_SubWorkOrderMaterialStockLineKitAudit_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                  BIT             CONSTRAINT [DF_SubWorkOrderMaterialStockLineKitAudit_IsDeleted] DEFAULT ((0)) NOT NULL,
    [AltPartMasterPartId]        BIGINT          NULL,
    [EquPartMasterPartId]        BIGINT          NULL,
    [IsAltPart]                  BIT             NULL,
    [IsEquPart]                  BIT             NULL,
    [UnitCost]                   DECIMAL (20, 2) NULL,
    [ExtendedCost]               DECIMAL (20, 2) NULL,
    [UnitPrice]                  DECIMAL (20, 2) NULL,
    [ExtendedPrice]              DECIMAL (20, 2) NULL,
    [ProvisionId]                INT             DEFAULT ((2)) NOT NULL,
    [RepairOrderId]              BIGINT          NULL,
    [QuantityTurnIn]             INT             DEFAULT ((0)) NULL,
    [Figure]                     NVARCHAR (50)   NULL,
    [Item]                       NVARCHAR (50)   NULL,
    [ReferenceNumber]            VARCHAR (100)   NULL,
    CONSTRAINT [PK_SubWorkOrderMaterialStockLineKitAudit] PRIMARY KEY CLUSTERED ([SWOMStockLineKitAuditId] ASC)
);



