CREATE TABLE [dbo].[SubWorkOrderMaterialStockLineKitAudit] (
    [SWOMStockLineKitAuditId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [SWOMStockLineKitId]         BIGINT          NOT NULL,
    [SubWorkOrderMaterialsKitId] BIGINT          NOT NULL,
    [StockLineId]                BIGINT          NOT NULL,
    [ItemMasterId]               BIGINT          NOT NULL,
    [ConditionId]                BIGINT          NOT NULL,
    [Quantity]                   DECIMAL (18, 6) NULL,
    [QtyReserved]                DECIMAL (18, 6) NULL,
    [QtyIssued]                  DECIMAL (18, 6) NULL,
    [MasterCompanyId]            INT             NOT NULL,
    [CreatedBy]                  VARCHAR (256)   NOT NULL,
    [UpdatedBy]                  VARCHAR (256)   NOT NULL,
    [CreatedDate]                DATETIME2 (7)   CONSTRAINT [DF_SubWorkOrderMaterialStockLineKitAudit_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                DATETIME2 (7)   CONSTRAINT [DF_SubWorkOrderMaterialStockLineKitAudit_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                   BIT             CONSTRAINT [DF_SubWorkOrderMaterialStockLineKitAudit_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                  BIT             CONSTRAINT [DF_SubWorkOrderMaterialStockLineKitAudit_IsDeleted] DEFAULT ((0)) NOT NULL,
    [AltPartMasterPartId]        BIGINT          NULL,
    [EquPartMasterPartId]        BIGINT          NULL,
    [IsAltPart]                  BIT             NULL,
    [IsEquPart]                  BIT             NULL,
    [UnitCost]                   DECIMAL (18, 6) NULL,
    [ExtendedCost]               DECIMAL (18, 6) NULL,
    [UnitPrice]                  DECIMAL (18, 6) NULL,
    [ExtendedPrice]              DECIMAL (18, 6) NULL,
    [ProvisionId]                INT             DEFAULT ((2)) NOT NULL,
    [RepairOrderId]              BIGINT          NULL,
    [QuantityTurnIn]             DECIMAL (18, 6) CONSTRAINT [DF__SubWorkOr__Quant__44468243] DEFAULT ((0)) NULL,
    [Figure]                     NVARCHAR (50)   NULL,
    [Item]                       NVARCHAR (50)   NULL,
    [ReferenceNumber]            VARCHAR (100)   NULL,
    [ReservedById]               BIGINT          NULL,
    [ReservedDate]               DATETIME2 (7)   NULL,
    [IssuedById]                 BIGINT          NULL,
    [IssuedDate]                 DATETIME2 (7)   NULL,
    CONSTRAINT [PK_SubWorkOrderMaterialStockLineKitAudit] PRIMARY KEY CLUSTERED ([SWOMStockLineKitAuditId] ASC)
);

