CREATE TABLE [dbo].[VendorRFQRepairOrderAudit] (
    [VendorRFQRepairOrderAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [VendorRFQRepairOrderId]      BIGINT          NOT NULL,
    [VendorRFQRepairOrderNumber]  VARCHAR (50)    NULL,
    [OpenDate]                    DATETIME2 (7)   NOT NULL,
    [ClosedDate]                  DATETIME2 (7)   NULL,
    [NeedByDate]                  DATETIME2 (7)   NOT NULL,
    [PriorityId]                  BIGINT          NOT NULL,
    [Priority]                    VARCHAR (100)   NULL,
    [VendorId]                    BIGINT          NOT NULL,
    [VendorName]                  VARCHAR (100)   NULL,
    [VendorCode]                  VARCHAR (100)   NULL,
    [VendorContactId]             BIGINT          NOT NULL,
    [VendorContact]               VARCHAR (100)   NULL,
    [VendorContactPhone]          VARCHAR (100)   NULL,
    [CreditTermsId]               INT             NULL,
    [Terms]                       VARCHAR (100)   NULL,
    [CreditLimit]                 DECIMAL (18, 2) NULL,
    [RequisitionerId]             BIGINT          NOT NULL,
    [Requisitioner]               VARCHAR (100)   NULL,
    [StatusId]                    BIGINT          NOT NULL,
    [Status]                      VARCHAR (100)   NULL,
    [StatusChangeDate]            DATETIME2 (7)   NULL,
    [Resale]                      BIT             NULL,
    [DeferredReceiver]            BIT             NULL,
    [Memo]                        NVARCHAR (MAX)  NULL,
    [Notes]                       NVARCHAR (MAX)  NULL,
    [ManagementStructureId]       BIGINT          NOT NULL,
    [Level1]                      VARCHAR (200)   NULL,
    [Level2]                      VARCHAR (200)   NULL,
    [Level3]                      VARCHAR (200)   NULL,
    [Level4]                      VARCHAR (200)   NULL,
    [MasterCompanyId]             INT             CONSTRAINT [DF_VendorRFQRepairOrderAudit_MasterCompanyId] DEFAULT ((1)) NOT NULL,
    [CreatedBy]                   VARCHAR (256)   NOT NULL,
    [UpdatedBy]                   VARCHAR (256)   NOT NULL,
    [CreatedDate]                 DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                 DATETIME2 (7)   NULL,
    [IsActive]                    BIT             CONSTRAINT [DF_VendorRFQRepairOrderAudit_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                   BIT             CONSTRAINT [DF_VendorRFQRepairOrderAudit_IsDeleted] DEFAULT ((0)) NOT NULL,
    [PDFPath]                     NVARCHAR (100)  NULL,
    [FreightBilingMethodId]       INT             NULL,
    [TotalFreight]                DECIMAL (18, 2) NULL,
    [ChargesBilingMethodId]       INT             NULL,
    [TotalCharges]                DECIMAL (18, 2) NULL,
    [VendorReference]             VARCHAR (100)   NULL,
    [FunctionalCurrencyId]        INT             NULL,
    [ReportCurrencyId]            INT             NULL,
    [ForeignExchangeRate]         DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_VendorRFQRepairOrderAudit] PRIMARY KEY CLUSTERED ([VendorRFQRepairOrderAuditId] ASC)
);







