CREATE TABLE [dbo].[WorkOrderCostDetailsAudit] (
    [WorkOrderCostDetailsAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderCostDetailsId]      BIGINT          NOT NULL,
    [WorkOrderId]                 BIGINT          NOT NULL,
    [WOQuoteId]                   BIGINT          NULL,
    [WOPartNoId]                  BIGINT          NOT NULL,
    [WOBillingShippingId]         BIGINT          NULL,
    [Revenue]                     DECIMAL (18, 6) NULL,
    [PartsCost]                   DECIMAL (18, 6) NULL,
    [PartsRevPercentage]          DECIMAL (18, 6) NULL,
    [LaborCost]                   DECIMAL (18, 6) NULL,
    [LaborRevPercentage]          DECIMAL (18, 6) NULL,
    [OverHeadCost]                DECIMAL (18, 6) NULL,
    [OverHeadPercentage]          DECIMAL (18, 6) NULL,
    [OtherCost]                   DECIMAL (18, 6) NULL,
    [DirectCost]                  DECIMAL (18, 6) NULL,
    [DirectCostPercentage]        DECIMAL (18, 6) NULL,
    [Margin]                      DECIMAL (18, 6) NULL,
    [MarginPercentage]            DECIMAL (18, 6) NULL,
    [ChargesCost]                 DECIMAL (18, 6) NULL,
    [ExclusionCost]               DECIMAL (18, 6) NULL,
    [FreightCost]                 DECIMAL (18, 6) NULL,
    [TotalCost]                   DECIMAL (18, 6) NULL,
    [ActualRevenue]               DECIMAL (18, 6) NULL,
    [ActualMargin]                DECIMAL (18, 6) NULL,
    [ActualMarginPercentage]      DECIMAL (18, 6) NULL,
    [MasterCompanyId]             INT             NOT NULL,
    [CreatedBy]                   VARCHAR (256)   NOT NULL,
    [UpdatedBy]                   VARCHAR (256)   NOT NULL,
    [CreatedDate]                 DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                 DATETIME2 (7)   NOT NULL,
    [IsActive]                    BIT             NOT NULL,
    [IsDeleted]                   BIT             NOT NULL,
    CONSTRAINT [PK_WorkOrderCostDetailsAudit] PRIMARY KEY CLUSTERED ([WorkOrderCostDetailsAuditId] ASC)
);

