CREATE TABLE [dbo].[WorkOrderMainAudit] (
    [WorkOrderAuditId]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [WorkOrderId]             BIGINT         NOT NULL,
    [WorkOrderNum]            VARCHAR (20)   NULL,
    [CustomerId]              BIGINT         NULL,
    [CustomerName]            VARCHAR (100)  NULL,
    [CustomerCode]            VARCHAR (20)   NULL,
    [CustomerRef]             VARCHAR (20)   NULL,
    [CustomerContact]         VARCHAR (50)   NULL,
    [CustomerPhone]           VARCHAR (20)   NULL,
    [CustomerFax]             VARCHAR (20)   NULL,
    [CustomerContractRef]     VARCHAR (20)   NULL,
    [WorkOrderType]           VARCHAR (20)   NULL,
    [WorkOrderQuantity]       VARCHAR (20)   NULL,
    [OpenDate]                DATETIME2 (7)  NULL,
    [CustomerRequestDate]     DATETIME2 (7)  NULL,
    [PromiseDate]             DATETIME2 (7)  NULL,
    [EstimatedCompletionDate] DATETIME2 (7)  NULL,
    [WorkScope]               VARCHAR (20)   NULL,
    [WorkOrderProcessRef]     VARCHAR (20)   NULL,
    [PartNumber]              BIGINT         NULL,
    [PartNumberDescription]   VARCHAR (50)   NULL,
    [RevisedPartNumber]       BIGINT         NULL,
    [SerialNumber]            BIGINT         NULL,
    [PMA]                     VARCHAR (20)   NULL,
    [DER]                     VARCHAR (20)   NULL,
    [CMMPubRefNumber]         VARCHAR (30)   NULL,
    [Priority]                VARCHAR (20)   NULL,
    [ManagementStructureId]   BIGINT         NOT NULL,
    [EmployeeId]              INT            NULL,
    [Notes]                   NVARCHAR (MAX) NULL,
    [MasterCompanyId]         INT            NOT NULL,
    [CreatedBy]               VARCHAR (256)  NOT NULL,
    [UpdatedBy]               VARCHAR (256)  NOT NULL,
    [CreatedDate]             DATETIME2 (7)  NOT NULL,
    [UpdatedDate]             DATETIME2 (7)  NOT NULL,
    [IsActive]                BIT            NOT NULL,
    CONSTRAINT [PK_WorkOrderMainAudit] PRIMARY KEY CLUSTERED ([WorkOrderAuditId] ASC)
);



