CREATE TABLE [dbo].[WorkOrderQuoteMaterialKitMapping] (
    [WOQMaterialKitMappingId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderQuoteId]        BIGINT          NOT NULL,
    [WorkflowWorkOrderId]     BIGINT          NOT NULL,
    [kitId]                   BIGINT          NOT NULL,
    [KitNumber]               VARCHAR (256)   NULL,
    [ItemMasterId]            BIGINT          NOT NULL,
    [Quantity]                INT             NOT NULL,
    [UnitCost]                DECIMAL (20, 2) NOT NULL,
    [ExtendedCost]            DECIMAL (20, 2) NOT NULL,
    [MasterCompanyId]         INT             NOT NULL,
    [CreatedBy]               VARCHAR (256)   NOT NULL,
    [UpdatedBy]               VARCHAR (256)   NOT NULL,
    [CreatedDate]             DATETIME2 (7)   CONSTRAINT [DF_WorkOrderQuoteMaterialKitMapping_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   CONSTRAINT [DF_WorkOrderQuoteMaterialKitMapping_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                BIT             CONSTRAINT [DF__WorkOrderQuoteMaterialKitMapping__IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]               BIT             CONSTRAINT [DF__WorkOrderQuoteMaterialKitMapping__IsDeleted] DEFAULT ((0)) NOT NULL,
    [Memo]                    NVARCHAR (MAX)  NULL,
    [MarkupPercentageId]      BIGINT          NULL,
    [MarkupFixedPrice]        VARCHAR (15)    NULL,
    [BillingAmount]           DECIMAL (20, 2) NULL,
    [BillingRate]             DECIMAL (20, 2) NULL,
    [HeaderMarkupId]          BIGINT          NULL,
    [BillingMethodId]         INT             NULL,
    [BillingName]             VARCHAR (50)    NULL,
    [MarkUp]                  VARCHAR (50)    NULL,
    CONSTRAINT [PK_WorkOrderQuoteMaterialKitMapping] PRIMARY KEY CLUSTERED ([WOQMaterialKitMappingId] ASC),
    CONSTRAINT [FK_WorkOrderQuoteMaterialKitMapping_ItemMaster] FOREIGN KEY ([ItemMasterId]) REFERENCES [dbo].[ItemMaster] ([ItemMasterId]),
    CONSTRAINT [FK_WorkOrderQuoteMaterialKitMapping_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId])
);

