CREATE TABLE [dbo].[WorkOrderTeardownAudit] (
    [WorkOrderTeardownAuditId] BIGINT        IDENTITY (1, 1) NOT NULL,
    [WorkOrderTeardownId]      BIGINT        NOT NULL,
    [WorkOrderId]              BIGINT        NOT NULL,
    [WorkFlowWorkOrderId]      BIGINT        NOT NULL,
    [MasterCompanyId]          INT           NOT NULL,
    [CreatedBy]                VARCHAR (256) NULL,
    [UpdatedBy]                VARCHAR (256) NULL,
    [CreatedDate]              DATETIME2 (7) NOT NULL,
    [UpdatedDate]              DATETIME2 (7) NOT NULL,
    [IsActive]                 BIT           NOT NULL,
    [IsDeleted]                BIT           NOT NULL,
    [IsAdditionalComments]     BIT           NULL,
    [IsBulletinsModification]  BIT           NULL,
    [IsDiscovery]              BIT           NULL,
    [IsFinalInspection]        BIT           NULL,
    [IsFinalTest]              BIT           NULL,
    [IsPmaDerBulletins]        BIT           NULL,
    [IsPreAssemblyInspection]  BIT           NULL,
    [IsPreAssmentResults]      BIT           NULL,
    [IsPreliinaryReview]       BIT           NULL,
    [IsRemovalReasons]         BIT           NULL,
    [IsTestDataUsed]           BIT           NULL,
    [IsWorkPerformed]          BIT           NULL,
    [WOPartNoId]               BIGINT        NOT NULL,
    CONSTRAINT [PK_WorkOrderTeardownAudit] PRIMARY KEY CLUSTERED ([WorkOrderTeardownAuditId] ASC)
);

