CREATE TABLE [dbo].[WorkOrderLaborAudit] (
    [WorkOrderLaborAuditId]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderLaborId]            BIGINT          NOT NULL,
    [WorkOrderLaborAuditHeaderId] BIGINT          NULL,
    [TaskId]                      BIGINT          NULL,
    [ExpertiseId]                 SMALLINT        NULL,
    [EmployeeId]                  BIGINT          NULL,
    [Hours]                       DECIMAL (10, 2) NULL,
    [Adjustments]                 DECIMAL (10, 2) NULL,
    [AdjustedHours]               DECIMAL (10, 2) NULL,
    [StandardHours]               INT             NULL,
    [StandardMinute]              INT             NULL,
    [VarianceHours]               DECIMAL (10, 2) NULL,
    [VarianceMinute]              DECIMAL (10, 2) NULL,
    [Memo]                        NVARCHAR (MAX)  NULL,
    [CreatedBy]                   VARCHAR (256)   NULL,
    [UpdatedBy]                   VARCHAR (256)   NULL,
    [CreatedDate]                 DATETIME2 (7)   NULL,
    [UpdatedDate]                 DATETIME2 (7)   NULL,
    [IsActive]                    BIT             NULL,
    [IsDeleted]                   BIT             NULL,
    [StartDate]                   DATETIME2 (7)   NULL,
    [EndDate]                     DATETIME2 (7)   NULL,
    [BillableId]                  INT             NULL,
    [IsFromWorkFlow]              BIT             NULL,
    [MasterCompanyId]             INT             NULL,
    [TaskName]                    VARCHAR (256)   NULL,
    [LabourExpertise]             VARCHAR (256)   NULL,
    [LabourEmployee]              VARCHAR (256)   NULL,
    [Billable]                    VARCHAR (10)    NULL,
    [DirectLaborOHCost]           DECIMAL (18, 2) CONSTRAINT [DF__tmp_ms_xx__Direc__49E8B652] DEFAULT ((0)) NULL,
    [BurdaenRatePercentageId]     BIGINT          NULL,
    [BurdenRateAmount]            DECIMAL (18, 2) CONSTRAINT [DF__tmp_ms_xx__Burde__4ADCDA8B] DEFAULT ((0)) NULL,
    [TotalCostPerHour]            DECIMAL (18, 2) CONSTRAINT [DF__tmp_ms_xx__Total__4BD0FEC4] DEFAULT ((0)) NULL,
    [TotalCost]                   DECIMAL (18, 2) CONSTRAINT [DF__tmp_ms_xx__Total__4CC522FD] DEFAULT ((0)) NULL,
    [TaskStatusId]                BIGINT          NULL,
    [StatusChangedDate]           DATETIME2 (7)   NULL,
    [IsBegin]                     BIT             NULL,
    [IsAdjustmentTask]            BIT             NULL,
    CONSTRAINT [PK_WorkOrderLaborAudit] PRIMARY KEY CLUSTERED ([WorkOrderLaborAuditId] ASC)
);

