CREATE TABLE [dbo].[WorkOrderMPNCostDetailsAudit] (
    [WorkOrderMPNCostDetailsAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderMPNCostDetailsId]      BIGINT          NOT NULL,
    [WorkOrderId]                    BIGINT          NOT NULL,
    [WOQuoteId]                      BIGINT          NULL,
    [WOPartNoId]                     BIGINT          NOT NULL,
    [WOBillingShippingId]            BIGINT          NULL,
    [Revenue]                        DECIMAL (20, 2) NULL,
    [PartsCost]                      DECIMAL (20, 2) NULL,
    [PartsRevPercentage]             DECIMAL (20, 2) NULL,
    [LaborCost]                      DECIMAL (20, 2) NULL,
    [LaborRevPercentage]             DECIMAL (20, 2) NULL,
    [OverHeadCost]                   DECIMAL (20, 2) NULL,
    [OverHeadPercentage]             DECIMAL (20, 2) NULL,
    [OtherCost]                      DECIMAL (20, 2) NULL,
    [DirectCost]                     DECIMAL (20, 2) NULL,
    [DirectCostPercentage]           DECIMAL (20, 2) NULL,
    [Margin]                         DECIMAL (20, 2) NULL,
    [MarginPercentage]               DECIMAL (20, 2) NULL,
    [ChargesCost]                    DECIMAL (20, 2) NULL,
    [ExclusionCost]                  DECIMAL (20, 2) NULL,
    [FreightCost]                    DECIMAL (20, 2) NULL,
    [TotalCost]                      DECIMAL (20, 2) NULL,
    [ActualRevenue]                  DECIMAL (20, 2) NULL,
    [ActualMargin]                   DECIMAL (20, 2) NULL,
    [ActualMarginPercentage]         DECIMAL (20, 2) NULL,
    [MasterCompanyId]                INT             NOT NULL,
    [CreatedBy]                      VARCHAR (256)   NOT NULL,
    [UpdatedBy]                      VARCHAR (256)   NOT NULL,
    [CreatedDate]                    DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                    DATETIME2 (7)   NOT NULL,
    [IsActive]                       BIT             NOT NULL,
    [IsDeleted]                      BIT             NOT NULL,
    CONSTRAINT [PK_WorkOrderMPNCostDetailsAudit] PRIMARY KEY CLUSTERED ([WorkOrderMPNCostDetailsAuditId] ASC)
);

