CREATE TABLE [dbo].[WorkOrderFreightAudit] (
    [WorkOrderFreightAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderFreightId]      BIGINT          NOT NULL,
    [WorkOrderId]             BIGINT          NOT NULL,
    [WorkFlowWorkOrderId]     BIGINT          NOT NULL,
    [ShipViaId]               BIGINT          NOT NULL,
    [Weight]                  VARCHAR (50)    NULL,
    [Memo]                    NVARCHAR (MAX)  NULL,
    [Amount]                  DECIMAL (20, 3) NOT NULL,
    [MasterCompanyId]         INT             NOT NULL,
    [CreatedBy]               VARCHAR (256)   NOT NULL,
    [UpdatedBy]               VARCHAR (256)   NOT NULL,
    [CreatedDate]             DATETIME2 (7)   NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   NOT NULL,
    [IsActive]                BIT             NOT NULL,
    [IsDeleted]               BIT             NOT NULL,
    [TaskId]                  BIGINT          NOT NULL,
    [Length]                  DECIMAL (10, 2) NULL,
    [Width]                   DECIMAL (10, 2) NULL,
    [Height]                  DECIMAL (10, 2) NULL,
    [UOMId]                   BIGINT          NULL,
    [DimensionUOMId]          BIGINT          NULL,
    [CurrencyId]              BIGINT          NULL,
    [WOPartNoId]              BIGINT          NOT NULL,
    [Task]                    VARCHAR (256)   NOT NULL,
    [ShipVia]                 VARCHAR (256)   NOT NULL,
    [UOM]                     VARCHAR (256)   NULL,
    [DimentionUOM]            VARCHAR (256)   NULL,
    [Currency]                VARCHAR (256)   NULL,
    CONSTRAINT [PK_WorkOrderFreightAudit] PRIMARY KEY CLUSTERED ([WorkOrderFreightAuditId] ASC)
);

