CREATE TABLE [dbo].[WorkOrderQuoteMaterialKitMappingAudit] (
    [WorkOrderQuoteMaterialKitMappingAuditId] BIGINT IDENTITY (1, 1) NOT NULL,
    [WOQMaterialKitMappingId]                BIGINT NOT NULL,
    [WorkOrderQuoteId]                       BIGINT NOT NULL,
    [WorkflowWorkOrderId]                    BIGINT NOT NULL,
    [kitId]                                  BIGINT NOT NULL,
    [KitNumber]                              VARCHAR (256) NULL,
    [ItemMasterId]                           BIGINT NOT NULL,
    [TaskId]                                 BIGINT NULL,
    [Quantity]                               DECIMAL (18, 6) NULL,
    [UnitCost]                               DECIMAL (28, 6) NULL,
    [ExtendedCost]                           DECIMAL (28, 6) NULL,
    [MasterCompanyId]                        INT NOT NULL,
    [CreatedBy]                              VARCHAR (256) NOT NULL,
    [UpdatedBy]                              VARCHAR (256) NOT NULL,
    [CreatedDate]                            DATETIME2 (7) NOT NULL,
    [UpdatedDate]                            DATETIME2 (7) NOT NULL,
    [IsActive]                               BIT NOT NULL,
    [IsDeleted]                              BIT NOT NULL,
    [Memo]                                   NVARCHAR (MAX) NULL,
    [MarkupPercentageId]                     BIGINT NULL,
    [MarkupFixedPrice]                       VARCHAR (15) NULL,
    [BillingAmount]                          DECIMAL (28, 6) NULL,
    [BillingRate]                            DECIMAL (28, 6) NULL,
    [HeaderMarkupId]                         BIGINT NULL,
    [BillingMethodId]                        INT NULL,
    [BillingName]                            VARCHAR (50) NULL,
    [MarkUp]                                 VARCHAR (50) NULL,
    CONSTRAINT [PK_WorkOrderQuoteMaterialKitMappingAudit] PRIMARY KEY CLUSTERED ([WorkOrderQuoteMaterialKitMappingAuditId] ASC)
);
