CREATE TABLE [dbo].[WorkOrderUnIssuedStock] (
    [WOUnIssuedStockId]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [WorkOrderMaterialsId] BIGINT        NOT NULL,
    [StockLIneId]          BIGINT        NOT NULL,
    [ConditionId]          BIGINT        NOT NULL,
    [ItemMasterId]         BIGINT        NOT NULL,
    [Quantity]             INT           NOT NULL,
    [AltPartMasterPartId]  BIGINT        NULL,
    [EquPartMasterPartId]  BIGINT        NULL,
    [IsAltPart]            BIT           NULL,
    [IsEquPart]            BIT           NULL,
    [UnIssuedById]         BIGINT        NOT NULL,
    [UnIssuedDate]         DATETIME2 (7) NOT NULL,
    [MasterCompanyId]      INT           NOT NULL,
    [CreatedBy]            VARCHAR (256) NOT NULL,
    [UpdatedBy]            VARCHAR (256) NOT NULL,
    [CreatedDate]          DATETIME2 (7) CONSTRAINT [DF_WorkOrderUnIssuedStock_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]          DATETIME2 (7) CONSTRAINT [DF_WorkOrderUnIssuedStock_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]             BIT           CONSTRAINT [DF_WorkOrderUnIssuedStock_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]            BIT           CONSTRAINT [DF_WorkOrderUnIssuedStock_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_WorkOrderUnIssuedStock] PRIMARY KEY CLUSTERED ([WOUnIssuedStockId] ASC),
    CONSTRAINT [FK_WorkOrderUnIssuedStock_ConditionId] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([ConditionId]),
    CONSTRAINT [FK_WorkOrderUnIssuedStock_ItemMasterId] FOREIGN KEY ([ItemMasterId]) REFERENCES [dbo].[ItemMaster] ([ItemMasterId]),
    CONSTRAINT [FK_WorkOrderUnIssuedStock_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId]),
    CONSTRAINT [FK_WorkOrderUnIssuedStock_StockLine] FOREIGN KEY ([StockLIneId]) REFERENCES [dbo].[Stockline] ([StockLineId]),
    CONSTRAINT [FK_WorkOrderUnIssuedStock_UnIssuedById] FOREIGN KEY ([UnIssuedById]) REFERENCES [dbo].[Employee] ([EmployeeId]),
    CONSTRAINT [FK_WorkOrderUnIssuedStock_WorkOrderMaterials] FOREIGN KEY ([WorkOrderMaterialsId]) REFERENCES [dbo].[WorkOrderMaterials] ([WorkOrderMaterialsId])
);

