CREATE TABLE [dbo].[WorkOrderWorkFlowAudit] (
    [WorkFlowWorkOrderAuditId]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkFlowWorkOrderId]       BIGINT          NOT NULL,
    [WorkOrderId]               BIGINT          NOT NULL,
    [WorkflowDescription]       VARCHAR (500)   NULL,
    [Version]                   VARCHAR (10)    NULL,
    [WorkScopeId]               BIGINT          NULL,
    [ItemMasterId]              BIGINT          NULL,
    [CustomerId]                BIGINT          NULL,
    [CurrencyId]                INT             NULL,
    [WorkflowExpirationDate]    DATETIME2 (7)   NULL,
    [IsCalculatedBERThreshold]  BIT             NULL,
    [IsFixedAmount]             BIT             NULL,
    [FixedAmount]               DECIMAL (18, 6) NULL,
    [IsPercentageOfNew]         BIT             NULL,
    [CostOfNew]                 DECIMAL (18, 6) NULL,
    [PercentageOfNew]           INT             NULL,
    [IsPercentageOfReplacement] BIT             NULL,
    [CostOfReplacement]         DECIMAL (18, 6) NULL,
    [PercentageOfReplacement]   INT             NULL,
    [Memo]                      NVARCHAR (MAX)  NULL,
    [BERThresholdAmount]        DECIMAL (18, 6) NULL,
    [WorkOrderNumber]           VARCHAR (256)   NULL,
    [OtherCost]                 DECIMAL (18, 6) NULL,
    [MasterCompanyId]           INT             NOT NULL,
    [CreatedBy]                 VARCHAR (256)   NOT NULL,
    [UpdatedBy]                 VARCHAR (256)   NOT NULL,
    [CreatedDate]               DATETIME2 (7)   NOT NULL,
    [UpdatedDate]               DATETIME2 (7)   NOT NULL,
    [IsActive]                  BIT             NOT NULL,
    [IsDeleted]                 BIT             NOT NULL,
    [WorkflowCreateDate]        DATETIME        NULL,
    [WorkflowId]                BIGINT          NULL,
    [WorkFlowWorkOrderNo]       VARCHAR (30)    NULL,
    [ChangedPartNumberId]       BIGINT          NULL,
    [MaterilaCost]              DECIMAL (18, 6) NULL,
    [ExpertiseCost]             DECIMAL (18, 6) NULL,
    [ChargesCost]               DECIMAL (18, 6) NULL,
    [Total]                     DECIMAL (18, 6) NULL,
    [PerOfBerThreshold]         INT             NULL,
    [WorkOrderPartNoId]         BIGINT          NOT NULL,
    CONSTRAINT [PK_WorkFlowWorkOrderAudit] PRIMARY KEY CLUSTERED ([WorkFlowWorkOrderAuditId] ASC)
);

