CREATE TABLE [dbo].[WorkOrderQuoteChargesAudit] (
    [WorkOrderQuoteChargesAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderQuoteChargesId]      BIGINT          NOT NULL,
    [WorkOrderQuoteDetailsId]      BIGINT          NOT NULL,
    [ChargesTypeId]                BIGINT          NOT NULL,
    [VendorId]                     BIGINT          NULL,
    [Quantity]                     INT             NOT NULL,
    [MarkupPercentageId]           BIGINT          NULL,
    [Description]                  VARCHAR (256)   NULL,
    [UnitCost]                     DECIMAL (20, 2) NOT NULL,
    [ExtendedCost]                 DECIMAL (20, 2) NOT NULL,
    [MasterCompanyId]              INT             NOT NULL,
    [CreatedBy]                    VARCHAR (256)   NOT NULL,
    [UpdatedBy]                    VARCHAR (256)   NOT NULL,
    [CreatedDate]                  DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                  DATETIME2 (7)   NOT NULL,
    [IsActive]                     BIT             NOT NULL,
    [IsDeleted]                    BIT             NOT NULL,
    [TaskId]                       BIGINT          NOT NULL,
    [MarkupFixedPrice]             VARCHAR (15)    NULL,
    [BillingAmount]                DECIMAL (20, 2) NULL,
    [BillingRate]                  DECIMAL (20, 2) NULL,
    [HeaderMarkupId]               BIGINT          NULL,
    [RefNum]                       VARCHAR (20)    NULL,
    [BillingMethodId]              INT             NULL,
    [TaskName]                     VARCHAR (100)   NULL,
    [ChargeType]                   VARCHAR (50)    NULL,
    [GlAccountName]                VARCHAR (50)    NULL,
    [VendorName]                   VARCHAR (50)    NULL,
    [BillingName]                  VARCHAR (50)    NULL,
    [MarkUp]                       VARCHAR (50)    NULL,
    [UOMId]                        BIGINT          NULL,
    CONSTRAINT [PK_WorkOrderQuoteChargesAudit] PRIMARY KEY CLUSTERED ([WorkOrderQuoteChargesAuditId] ASC)
);



