CREATE TABLE [dbo].[WorkOrderApprovalAudit] (
    [WorkOrderApprovalAuditId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [WorkOrderApprovalId]      BIGINT         NOT NULL,
    [WorkOrderId]              BIGINT         NOT NULL,
    [WorkOrderQuoteId]         BIGINT         NULL,
    [WorkOrderPartNoId]        BIGINT         NOT NULL,
    [CustomerId]               BIGINT         NOT NULL,
    [WorkOrderDetailId]        BIGINT         NULL,
    [InternalMemo]             NVARCHAR (MAX) NULL,
    [MasterCompanyId]          INT            NOT NULL,
    [CreatedBy]                VARCHAR (256)  NOT NULL,
    [UpdatedBy]                VARCHAR (256)  NOT NULL,
    [CreatedDate]              DATETIME2 (7)  NOT NULL,
    [UpdatedDate]              DATETIME2 (7)  NOT NULL,
    [IsActive]                 BIT            NOT NULL,
    [IsDeleted]                BIT            NOT NULL,
    [InternalSentDate]         DATETIME2 (7)  NULL,
    [InternalApprovedDate]     DATETIME2 (7)  NULL,
    [InternalApprovedById]     BIGINT         NULL,
    [CustomerSentDate]         DATETIME2 (7)  NULL,
    [CustomerApprovedDate]     DATETIME2 (7)  NULL,
    [CustomerApprovedById]     BIGINT         NULL,
    [ApprovalActionId]         INT            NULL,
    [CustomerStatusId]         INT            NULL,
    [InternalStatusId]         INT            NULL,
    [CustomerMemo]             NVARCHAR (MAX) NULL,
    [InternalRejectedDate]     DATETIME       NULL,
    [InternalRejectedID]       BIGINT         NULL,
    [CustomerRejectedDate]     DATETIME       NULL,
    [CustomerRejectedbyID]     BIGINT         NULL,
    [InternalSentToId]         BIGINT         NULL,
    [InternalSentToName]       VARCHAR (100)  NULL,
    [InternalSentById]         BIGINT         NULL,
    CONSTRAINT [PK_WorkOrderApprovalsAudit] PRIMARY KEY CLUSTERED ([WorkOrderApprovalAuditId] ASC)
);

