CREATE TABLE [dbo].[AllAddressAudit] (
    [AllAddressAuditId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [AllAddressId]      BIGINT         NOT NULL,
    [ReffranceId]       BIGINT         NOT NULL,
    [ModuleId]          BIGINT         NOT NULL,
    [UserType]          INT            NOT NULL,
    [UserTypeName]      VARCHAR (100)  NULL,
    [UserId]            BIGINT         NOT NULL,
    [UserName]          VARCHAR (256)  NULL,
    [SiteId]            BIGINT         NOT NULL,
    [SiteName]          VARCHAR (256)  NULL,
    [AddressId]         BIGINT         NOT NULL,
    [IsModuleOnly]      BIT            NOT NULL,
    [IsShippingAdd]     BIT            NOT NULL,
    [ShippingAccountNo] VARCHAR (100)  NULL,
    [Memo]              NVARCHAR (MAX) NULL,
    [ContactId]         BIGINT         NOT NULL,
    [ContactName]       VARCHAR (200)  NULL,
    [ContactPhoneNo]    VARCHAR (50)   NULL,
    [Line1]             VARCHAR (50)   NULL,
    [Line2]             VARCHAR (50)   NULL,
    [Line3]             VARCHAR (50)   NULL,
    [City]              VARCHAR (50)   NULL,
    [StateOrProvince]   VARCHAR (50)   NULL,
    [PostalCode]        VARCHAR (20)   NULL,
    [CountryId]         INT            NULL,
    [Country]           VARCHAR (50)   NULL,
    [MasterCompanyId]   INT            NOT NULL,
    [CreatedBy]         VARCHAR (256)  NOT NULL,
    [UpdatedBy]         VARCHAR (256)  NOT NULL,
    [CreatedDate]       DATETIME2 (7)  NOT NULL,
    [UpdatedDate]       DATETIME2 (7)  NOT NULL,
    [IsActive]          BIT            NOT NULL,
    [IsDeleted]         BIT            NOT NULL,
    [IsPrimary]         BIT            CONSTRAINT [DF_AllAddressAudit_IsPrimary] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_AllAddressAudit] PRIMARY KEY CLUSTERED ([AllAddressAuditId] ASC)
);



