CREATE TABLE [dbo].[AssetInventoryHistory] (
    [InventoryHistoryId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [InventoryId]        BIGINT          NOT NULL,
    [AssetRecordId_o]    BIGINT          NOT NULL,
    [AssetRecordId_m]    BIGINT          NULL,
    [InventoryNumber]    VARCHAR (150)   NULL,
    [StkLineNumber]      VARCHAR (150)   NULL,
    [PurchaseOrderId]    BIGINT          NULL,
    [PONum]              VARCHAR (150)   NULL,
    [POCost]             DECIMAL (18, 2) NULL,
    [ConditionId]        INT             NULL,
    [ConditionName]      VARCHAR (150)   NULL,
    [RepairOrderId]      BIGINT          NULL,
    [RONum]              VARCHAR (150)   NULL,
    [WorkscoprId]        BIGINT          NULL,
    [WorkscopeName]      VARCHAR (50)    NULL,
    [RepairCost]         DECIMAL (18, 2) NULL,
    [VendorId]           BIGINT          NULL,
    [VendorName]         VARCHAR (150)   NULL,
    [RecdDate]           DATETIME        NULL,
    [Cost]               DECIMAL (18, 2) NULL,
    [LotNum]             VARCHAR (100)   NULL,
    [WONum]              VARCHAR (100)   NULL,
    [PreviousInventory]  NVARCHAR (100)  NULL,
    [Note]               NVARCHAR (MAX)  NULL,
    [WorkOrderId]        BIGINT          NULL,
    [WorkOrderType]      CHAR (1)        NULL,
    CONSTRAINT [PK_AssetInventoryHistory] PRIMARY KEY CLUSTERED ([InventoryHistoryId] ASC)
);

