CREATE TABLE [dbo].[AuditVendorRMACustomsInfo] (
    [AuditVendorRMACustomsInfoId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [RMAShippingId]               BIGINT          NOT NULL,
    [EntryType]                   VARCHAR (100)   NULL,
    [EPU]                         VARCHAR (100)   NULL,
    [CustomsValue]                DECIMAL (20, 2) NULL,
    [NetMass]                     DECIMAL (20, 2) NULL,
    [EntryStatus]                 VARCHAR (100)   NULL,
    [EntryNumber]                 VARCHAR (100)   NULL,
    [VATValue]                    DECIMAL (20, 2) NULL,
    [UCR]                         VARCHAR (100)   NULL,
    [MasterUCR]                   VARCHAR (100)   NULL,
    [MovementRefNo]               VARCHAR (100)   NULL,
    [CommodityCode]               VARCHAR (100)   NULL,
    [MasterCompanyId]             INT             NOT NULL,
    [CreatedBy]                   VARCHAR (256)   NOT NULL,
    [UpdatedBy]                   VARCHAR (256)   NOT NULL,
    [CreatedDate]                 DATETIME2 (7)   CONSTRAINT [DF_AuditVendorRMACustomsInfo_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                 DATETIME2 (7)   CONSTRAINT [DF_AuditVendorRMACustomsInfo_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                    BIT             CONSTRAINT [DF_AVCI_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                   BIT             CONSTRAINT [DF_AVCI_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CustomCurrencyId]            INT             NULL,
    CONSTRAINT [PK_AuditVendorRMACustomsInfo] PRIMARY KEY CLUSTERED ([AuditVendorRMACustomsInfoId] ASC),
    CONSTRAINT [FK_AuditVendorRMACustomsInfo_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId]),
    CONSTRAINT [FK_AuditVendorRMACustomsInfo_RMAShipping] FOREIGN KEY ([RMAShippingId]) REFERENCES [dbo].[RMAShipping] ([RMAShippingId])
);

