CREATE TABLE [dbo].[CreditMemoChargesAudit] (
    [CreditMemoChargestAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [CreditMemoChargestId]      BIGINT          NOT NULL,
    [CreditMemoHeaderId]        BIGINT          NOT NULL,
    [CreditMemoDetailId]        BIGINT          NULL,
    [ChargesTypeId]             BIGINT          NOT NULL,
    [VendorId]                  BIGINT          NULL,
    [Quantity]                  DECIMAL (18, 6) NULL,
    [MarkupPercentageId]        BIGINT          NULL,
    [Description]               VARCHAR (256)   NULL,
    [UnitCost]                  DECIMAL (18, 6) NULL,
    [ExtendedCost]              DECIMAL (18, 6) NULL,
    [MasterCompanyId]           INT             NOT NULL,
    [MarkupFixedPrice]          DECIMAL (18, 6) NULL,
    [BillingMethodId]           INT             NULL,
    [BillingAmount]             DECIMAL (18, 6) NULL,
    [BillingRate]               DECIMAL (18, 6) NULL,
    [HeaderMarkupId]            BIGINT          NULL,
    [RefNum]                    VARCHAR (20)    NULL,
    [CreatedBy]                 VARCHAR (256)   NOT NULL,
    [UpdatedBy]                 VARCHAR (256)   NOT NULL,
    [CreatedDate]               DATETIME2 (7)   NOT NULL,
    [UpdatedDate]               DATETIME2 (7)   NOT NULL,
    [IsActive]                  BIT             NOT NULL,
    [IsDeleted]                 BIT             NOT NULL,
    [HeaderMarkupPercentageId]  BIGINT          NULL,
    [VendorName]                VARCHAR (100)   NULL,
    [ChargeName]                VARCHAR (50)    NULL,
    [MarkupName]                VARCHAR (50)    NULL,
    [ItemMasterId]              BIGINT          NULL,
    [ConditionId]               BIGINT          NULL,
    [PartNumber]                VARCHAR (100)   NULL,
    CONSTRAINT [PK_CreditMemoChargesAudit] PRIMARY KEY CLUSTERED ([CreditMemoChargestAuditId] ASC)
);

