CREATE TABLE [dbo].[CustomerRfq] (
    [CustomerRfqId]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [RfqId]               NVARCHAR (200)  NULL,
    [RfqCreatedDate]      DATETIME2 (7)   NULL,
    [IntegrationPortalId] INT             NULL,
    [Type]                VARCHAR (50)    NULL,
    [Notes]               VARCHAR (MAX)   NULL,
    [BuyerName]           VARCHAR (250)   NULL,
    [BuyerCompanyName]    VARCHAR (250)   NULL,
    [BuyerAddress]        VARCHAR (250)   NULL,
    [BuyerCity]           VARCHAR (50)    NULL,
    [BuyerCountry]        VARCHAR (50)    NULL,
    [BuyerState]          VARCHAR (50)    NULL,
    [BuyerZip]            VARCHAR (50)    NULL,
    [LinePartNumber]      VARCHAR (250)   NULL,
    [LineDescription]     VARCHAR (250)   NULL,
    [AltPartNumber]       VARCHAR (250)   NULL,
    [Quantity]            DECIMAL (18, 6) NULL,
    [Condition]           VARCHAR (250)   NULL,
    [MasterCompanyId]     INT             NOT NULL,
    [CreatedBy]           VARCHAR (50)    NOT NULL,
    [CreatedDate]         DATETIME2 (7)   CONSTRAINT [DF_CustomerRfq_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedBy]           VARCHAR (50)    NOT NULL,
    [UpdatedDate]         DATETIME2 (7)   CONSTRAINT [DF_CustomerRfq_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]            BIT             CONSTRAINT [DF_CustomerRfqIsActi_59FA5E80] DEFAULT ((1)) NOT NULL,
    [IsDeleted]           BIT             CONSTRAINT [DF_CustomerRfqIsDele_5AEE82B9] DEFAULT ((0)) NOT NULL,
    [IsQuote]             INT             NULL,
    [IsMRO]               BIT             DEFAULT ((0)) NULL,
    [ModuleId]            INT             NULL,
    [ReferenceId]         BIGINT          NULL,
    [EmployeeId]          BIGINT          NULL,
    [DateAssigned]        DATETIME        NULL,
    [QuotedBy]            VARCHAR (256)   NULL,
    [QuotedDate]          DATETIME        NULL,
    [QuoteSendReviewId]   INT             NULL,
    [CustomerId]          BIGINT          NULL,
    [FollowUpDate]        DATETIME2 (7)   NULL,
    [CustomerContactId]   BIGINT          NULL,
    [Guid]                VARCHAR (100)   NULL,
    [PriorityCodeId]      VARCHAR (50)    NULL,
    [PriorityCodeName]    VARCHAR (100)   NULL,
    [ResponsesDueBy]      DATETIME2 (7)   NULL,
    [CloseDate]           DATETIME2 (7)   NULL,
    [BuyerId]             BIGINT          NULL,
    [BuyerCompanyPhone]   VARCHAR (50)    NULL,
    [BuyerContactId]      BIGINT          NULL,
    [BuyerPhone]          VARCHAR (50)    NULL,
    [BuyerEmail]          VARCHAR (200)   NULL,
    [SellerId]            BIGINT          NULL,
    [SellerSiteId]        BIGINT          NULL,
    [SellerCompanyId]     BIGINT          NULL,
    [SellerCompany]       VARCHAR (250)   NULL,
    [SellerName]          VARCHAR (250)   NULL,
    [SellerPhone]         VARCHAR (50)    NULL,
    [SellerEmail]         VARCHAR (200)   NULL,
    [SellerUserName]      VARCHAR (200)   NULL,
    [RfqItemId]           BIGINT          NULL,
    [StatusId]            INT             NULL,
    [StatusName]          VARCHAR (100)   NULL,
    [ConditionCode]       VARCHAR (100)   NULL,
    [IsOverhaul]          BIT             NULL,
    [ReqDeliveryDays]     INT             NULL,
    [SenderInvQuantity]   DECIMAL (18, 6) NULL,
    [SenderListingInv]    BIT             NULL,
    [SupplierPartNumber]  VARCHAR (250)   NULL,
    [SupplierQuantity]    DECIMAL (18, 6) NULL,
    CONSTRAINT [PK_CustomerRfq] PRIMARY KEY CLUSTERED ([CustomerRfqId] ASC),
    CONSTRAINT [FK_CustomerRfq_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId])
);

