CREATE TABLE [dbo].[CustomerCCPaymentsAudit] (
    [CustomerCCPaymentsAuditId]       BIGINT        IDENTITY (1, 1) NOT NULL,
    [CustomerCCPaymentsId]            BIGINT        NOT NULL,
    [LegalEntityId]                   BIGINT        NOT NULL,
    [CustomerName]                    VARCHAR (100) NULL,
    [CompanyBankAccount]              BIGINT        NOT NULL,
    [MerchantID]                      VARCHAR (230) NULL,
    [CurrencyId]                      VARCHAR (50)  NULL,
    [SupportedPaymentMethods]         VARCHAR (150) NULL,
    [GatewayRequestTypes]             VARCHAR (150) NULL,
    [TestMode]                        BIT           NULL,
    [PayerAuthentication]             BIT           NULL,
    [IgnoreAVSResponse]               BIT           NULL,
    [IgnoreCSCResponse]               BIT           NULL,
    [DisableSendingRecurringRequests] BIT           NULL,
    [Inactive]                        BIT           NULL,
    [PartialAVSMatch]                 INT           NULL,
    [NoAVSMatch]                      INT           NULL,
    [AVSServiceNotAvailable]          INT           NULL,
    [NoCSCMatch]                      INT           NULL,
    [CSCNotSubmitted]                 INT           NULL,
    [CSCServiceNotAvailable]          INT           NULL,
    [CSCNotSupportedbyCardholderBank] INT           NULL,
    [MasterCompanyId]                 INT           NOT NULL,
    [CreatedBy]                       VARCHAR (256) NOT NULL,
    [UpdatedBy]                       VARCHAR (256) NOT NULL,
    [CreatedDate]                     DATETIME2 (7) CONSTRAINT [DF_CustomerCCPaymentsAudit_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedDate]                     DATETIME2 (7) CONSTRAINT [DF_CustomerCCPaymentsAudit_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]                        BIT           CONSTRAINT [CustomerCCPaymentsAudit_DC_Active] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                       BIT           CONSTRAINT [CustomerCCPaymentsAudit_DC_Delete] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CustomerCCPaymentsAudit] PRIMARY KEY CLUSTERED ([CustomerCCPaymentsAuditId] ASC)
);



