CREATE TABLE [dbo].[CustomerAging] (
    [CustomerAgingId]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [CustomerId]            BIGINT          NOT NULL,
    [CustomerName]          VARCHAR (100)   NULL,
    [CustomerCode]          VARCHAR (100)   NULL,
    [CreditTermsId]         INT             NULL,
    [CreditTermName]        VARCHAR (30)    NULL,
    [NetDays]               TINYINT         NULL,
    [CreditLimit]           DECIMAL (18, 2) NULL,
    [AsOfDate]              DATE            NOT NULL,
    [TotalInvoices]         INT             NULL,
    [TotalOutstanding]      DECIMAL (18, 6) NULL,
    [CurrentAmount]         DECIMAL (18, 6) CONSTRAINT [DF_CustomerAging_Current] DEFAULT ((0)) NOT NULL,
    [Days1_30]              DECIMAL (18, 6) CONSTRAINT [DF_CustomerAging_1_30] DEFAULT ((0)) NOT NULL,
    [Days31_60]             DECIMAL (18, 6) CONSTRAINT [DF_CustomerAging_31_60] DEFAULT ((0)) NOT NULL,
    [Days61_90]             DECIMAL (18, 6) CONSTRAINT [DF_CustomerAging_61_90] DEFAULT ((0)) NOT NULL,
    [Days91_120]            DECIMAL (18, 6) CONSTRAINT [DF_CustomerAging_91_120] DEFAULT ((0)) NOT NULL,
    [Days120Plus]           DECIMAL (18, 6) CONSTRAINT [DF_CustomerAging_120Plus] DEFAULT ((0)) NOT NULL,
    [MasterCompanyId]       INT             NOT NULL,
    [CreatedBy]             VARCHAR (256)   NOT NULL,
    [UpdatedBy]             VARCHAR (256)   NOT NULL,
    [CreatedDate]           DATETIME2 (7)   CONSTRAINT [DF_CustomerAging_CreatedDate] DEFAULT (GETDATE()) NOT NULL,
    [UpdatedDate]           DATETIME2 (7)   CONSTRAINT [DF_CustomerAging_UpdatedDate] DEFAULT (GETDATE()) NOT NULL,
    [IsActive]              BIT             CONSTRAINT [DF_CustomerAging_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]             BIT             CONSTRAINT [DF_CustomerAging_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CustomerAging] PRIMARY KEY CLUSTERED ([CustomerAgingId] ASC),
    CONSTRAINT [UQ_CustomerAging_Customer_Date] UNIQUE NONCLUSTERED ([CustomerId] ASC, [AsOfDate] ASC, [MasterCompanyId] ASC),
    CONSTRAINT [FK_CustomerAging_CreditTerms]  FOREIGN KEY ([CreditTermsId])  REFERENCES [dbo].[CreditTerms]   ([CreditTermsId]),
    CONSTRAINT [FK_CustomerAging_Customer]     FOREIGN KEY ([CustomerId])     REFERENCES [dbo].[Customer]       ([CustomerId]),
    CONSTRAINT [FK_CustomerAging_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId])
);
