CREATE TABLE [dbo].[ExchangeSalesOrderBillingInvoicingAudit] (
    [AuditSOBillingInvoicingId]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [SOBillingInvoicingId]                BIGINT          NOT NULL,
    [ExchangeSalesOrderId]                BIGINT          NOT NULL,
    [InvoiceTypeId]                       BIGINT          NOT NULL,
    [InvoiceNo]                           VARCHAR (256)   NOT NULL,
    [CustomerId]                          BIGINT          NOT NULL,
    [InvoiceDate]                         DATETIME2 (7)   NULL,
    [PrintDate]                           DATETIME2 (7)   NULL,
    [ShipDate]                            DATETIME2 (7)   NULL,
    [EmployeeId]                          BIGINT          NOT NULL,
    [RevType]                             VARCHAR (50)    NULL,
    [SoldToCustomerId]                    BIGINT          NOT NULL,
    [SoldToSiteId]                        BIGINT          NOT NULL,
    [BillToCustomerId]                    BIGINT          NOT NULL,
    [BillToSiteId]                        BIGINT          NOT NULL,
    [BillToAttention]                     VARCHAR (256)   NULL,
    [ShipToCustomerId]                    BIGINT          NOT NULL,
    [ShipToSiteId]                        BIGINT          NOT NULL,
    [ShipToAttention]                     VARCHAR (256)   NULL,
    [IsPartialInvoice]                    BIT             NOT NULL,
    [CurrencyId]                          INT             NULL,
    [AvailableCredit]                     DECIMAL (18, 6) NULL,
    [MasterCompanyId]                     INT             NOT NULL,
    [CreatedBy]                           VARCHAR (256)   NOT NULL,
    [UpdatedBy]                           VARCHAR (256)   NOT NULL,
    [CreatedDate]                         DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                         DATETIME2 (7)   NOT NULL,
    [IsActive]                            BIT             NOT NULL,
    [IsDeleted]                           BIT             NOT NULL,
    [InvoiceStatus]                       VARCHAR (50)    NULL,
    [InvoiceFilePath]                     VARCHAR (MAX)   NULL,
    [GrandTotal]                          DECIMAL (18, 6) NULL,
    [Level1]                              VARCHAR (200)   NULL,
    [Level2]                              VARCHAR (200)   NULL,
    [Level3]                              VARCHAR (200)   NULL,
    [Level4]                              VARCHAR (200)   NULL,
    [SubTotal]                            DECIMAL (18, 6) NULL,
    [TaxRate]                             DECIMAL (18, 6) NULL,
    [SalesTax]                            DECIMAL (18, 6) NULL,
    [OtherTax]                            DECIMAL (18, 6) NULL,
    [MiscCharges]                         DECIMAL (18, 6) NULL,
    [Freight]                             DECIMAL (18, 6) NULL,
    [PeriodicBillingAmount]               DECIMAL (18, 6) NULL,
    [CogsAmount]                          DECIMAL (18, 6) NULL,
    [BillingAmount]                       DECIMAL (18, 6) NULL,
    [ExchangeSalesOrderScheduleBillingId] BIGINT          NULL,
    [cogs]                                INT             NULL,
    [PostedDate]                          DATETIME2 (7)   NULL,
    [BillingId]                           BIGINT          DEFAULT ((0)) NOT NULL,
    [CreditMemoUsed]                      DECIMAL (18, 2) NULL,
    [RemainingAmount]                     DECIMAL (18, 6) NULL,
    [QuickBooksReferenceId]               VARCHAR (200)   NULL,
    [IsUpdated]                           BIT             NULL,
    [LastSyncDate]                        DATETIME2 (7)   NULL,
    [SyncToken]                           VARCHAR (200)   NULL,
    [IsQuickBookGeneratedInvoice]         BIT             NULL,
    [IntegrationTypeId]                   INT             NULL,
    CONSTRAINT [PK_ExchangeSalesOrderBillingInvoicingAudit] PRIMARY KEY CLUSTERED ([AuditSOBillingInvoicingId] ASC)
);

