CREATE TABLE [dbo].[ExchangeSalesOrderScheduleBillingAudit] (
    [ExchangeSalesOrderScheduleBillingAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [ExchangeSalesOrderScheduleBillingId]      BIGINT          NOT NULL,
    [ExchangeSalesOrderPartId]                 BIGINT          NOT NULL,
    [ExchangeSalesOrderId]                     BIGINT          NOT NULL,
    [ScheduleBillingDate]                      DATETIME2 (7)   NULL,
    [PeriodicBillingAmount]                    DECIMAL (18, 6) NULL,
    [Cogs]                                     INT             NOT NULL,
    [CogsAmount]                               DECIMAL (18, 6) NULL,
    [Qty]                                      DECIMAL (18, 6) NULL,
    [BillingTypeId]                            INT             NULL,
    [UnitOfMeasureId]                          BIGINT          NULL,
    [Notes]                                    NVARCHAR (MAX)  NULL,
    [Memo]                                     NVARCHAR (MAX)  NULL,
    [Type]                                     NVARCHAR (50)   DEFAULT ('Part') NOT NULL,
    [StatusId]                                 INT             DEFAULT ((1)) NOT NULL,
    [ExchangeSalesOrderChargesId]              BIGINT          NULL,
    [ExchangeSalesOrderFreightId]              BIGINT          NULL,
    [IsPartEntry]                              BIT             DEFAULT ((0)) NOT NULL,
    [BillingAmount]                            DECIMAL (18, 6) NULL,
    [MarkupPercentageId]                       INT             NULL,
    [ExtendedCost]                             DECIMAL (18, 6) NULL,
    CONSTRAINT [PK_ExchangeSalesOrderScheduleBillingAudit] PRIMARY KEY CLUSTERED ([ExchangeSalesOrderScheduleBillingAuditId] ASC)
);

