CREATE TABLE [dbo].[ExchangeQuotePartAudit] (
    [AuditExchangeQuotePartAuditId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [ExchangeQuotePartId]           BIGINT         NOT NULL,
    [ExchangeQuoteId]               BIGINT         NOT NULL,
    [ItemMasterId]                  BIGINT         NULL,
    [StockLineId]                   BIGINT         NULL,
    [ExchangeCurrencyId]            BIGINT         NULL,
    [LoanCurrencyId]                BIGINT         NULL,
    [ExchangeListPrice]             NUMERIC (9, 2) NULL,
    [EntryDate]                     DATETIME2 (7)  NULL,
    [ExchangeOverhaulPrice]         NUMERIC (9, 2) NULL,
    [ExchangeCorePrice]             NUMERIC (9, 2) NULL,
    [EstOfFeeBilling]               INT            NULL,
    [BillingStartDate]              DATETIME2 (7)  NULL,
    [ExchangeOutrightPrice]         NUMERIC (9, 2) NULL,
    [DaysForCoreReturn]             INT            NULL,
    [BillingIntervalDays]           INT            NULL,
    [CurrencyId]                    INT            NULL,
    [Currency]                      VARCHAR (50)   NULL,
    [DepositeAmount]                NUMERIC (9, 2) NULL,
    [CoreDueDate]                   DATETIME2 (7)  NULL,
    [MasterCompanyId]               INT            NOT NULL,
    [CreatedBy]                     VARCHAR (256)  NOT NULL,
    [CreatedDate]                   DATETIME2 (7)  NOT NULL,
    [UpdatedBy]                     VARCHAR (256)  NOT NULL,
    [UpdatedDate]                   DATETIME2 (7)  NOT NULL,
    [IsDeleted]                     BIT            NOT NULL,
    [IsActive]                      BIT            NOT NULL,
    [ConditionId]                   BIGINT         NULL,
    [StockLineName]                 NVARCHAR (100) NULL,
    [PartNumber]                    NVARCHAR (100) NULL,
    [PartDescription]               NVARCHAR (MAX) NULL,
    [ConditionName]                 NVARCHAR (100) NULL,
    [IsRemark]                      BIT            NULL,
    [RemarkText]                    VARCHAR (MAX)  NULL,
    [ExchangeOverhaulCost]          NUMERIC (9, 2) NULL,
    [QtyQuoted]                     INT            NULL,
    [MethodType]                    CHAR (1)       NULL,
    [IsConvertedToSalesOrder]       BIT            NOT NULL,
    [CustomerRequestDate]           DATETIME2 (7)  NULL,
    [PromisedDate]                  DATETIME2 (7)  NULL,
    [EstimatedShipDate]             DATETIME2 (7)  NULL,
    CONSTRAINT [PK_ExchangeQuotePartAudit] PRIMARY KEY CLUSTERED ([AuditExchangeQuotePartAuditId] ASC)
);

