CREATE TABLE [dbo].[ExchangeQuoteChargesAudit] (
    [AuditExchangeQuoteChargesId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [ExchangeQuoteChargesId]      BIGINT          NOT NULL,
    [ExchangeQuoteId]             BIGINT          NOT NULL,
    [ExchangeQuotePartId]         BIGINT          NULL,
    [ChargesTypeId]               BIGINT          NULL,
    [VendorId]                    BIGINT          NULL,
    [Quantity]                    INT             NULL,
    [MarkupPercentageId]          BIGINT          NULL,
    [Description]                 VARCHAR (256)   NULL,
    [UnitCost]                    DECIMAL (20, 2) NULL,
    [ExtendedCost]                DECIMAL (20, 2) NULL,
    [MasterCompanyId]             INT             NOT NULL,
    [MarkupFixedPrice]            DECIMAL (20, 2) NULL,
    [BillingMethodId]             INT             NULL,
    [BillingAmount]               DECIMAL (20, 2) NULL,
    [BillingRate]                 DECIMAL (20, 2) NULL,
    [HeaderMarkupId]              BIGINT          NULL,
    [RefNum]                      VARCHAR (20)    NULL,
    [CreatedBy]                   VARCHAR (256)   NOT NULL,
    [UpdatedBy]                   VARCHAR (256)   NOT NULL,
    [CreatedDate]                 DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                 DATETIME2 (7)   NOT NULL,
    [IsActive]                    BIT             NOT NULL,
    [IsDeleted]                   BIT             NOT NULL,
    [HeaderMarkupPercentageId]    BIGINT          NULL,
    [VendorName]                  NVARCHAR (100)  NULL,
    [ChargeName]                  NVARCHAR (100)  NULL,
    [MarkupName]                  NVARCHAR (100)  NULL,
    [UOMId]                       BIGINT          NULL,
    CONSTRAINT [PK_ExchangeQuoteChargesAudit] PRIMARY KEY CLUSTERED ([AuditExchangeQuoteChargesId] ASC)
);



