CREATE TABLE [dbo].[ExchangeSalesOrderChargesAudit] (
    [AuditExchangeSalesOrderChargesId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [ExchangeSalesOrderChargesId]      BIGINT          NOT NULL,
    [ExchangeSalesOrderId]             BIGINT          NOT NULL,
    [ExchangeSalesOrderPartId]         BIGINT          NULL,
    [ChargesTypeId]                    BIGINT          NULL,
    [VendorId]                         BIGINT          NULL,
    [Quantity]                         INT             NULL,
    [MarkupPercentageId]               BIGINT          NULL,
    [Description]                      VARCHAR (256)   NULL,
    [UnitCost]                         DECIMAL (20, 2) NULL,
    [ExtendedCost]                     DECIMAL (20, 2) NULL,
    [MasterCompanyId]                  INT             NOT NULL,
    [MarkupFixedPrice]                 DECIMAL (20, 2) NULL,
    [BillingMethodId]                  INT             NULL,
    [BillingAmount]                    DECIMAL (20, 2) NULL,
    [BillingRate]                      DECIMAL (20, 2) NULL,
    [HeaderMarkupId]                   BIGINT          NULL,
    [RefNum]                           VARCHAR (20)    NULL,
    [CreatedBy]                        VARCHAR (256)   NOT NULL,
    [UpdatedBy]                        VARCHAR (256)   NOT NULL,
    [CreatedDate]                      DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                      DATETIME2 (7)   NOT NULL,
    [IsActive]                         BIT             NOT NULL,
    [IsDeleted]                        BIT             NOT NULL,
    [HeaderMarkupPercentageId]         BIGINT          NULL,
    [VendorName]                       NVARCHAR (100)  NULL,
    [ChargeName]                       NVARCHAR (100)  NULL,
    [MarkupName]                       NVARCHAR (100)  NULL,
    [IsInsert]                         BIT             DEFAULT ((0)) NOT NULL,
    [UomId]                            BIGINT          NULL,
    [UomName]                          NVARCHAR (200)  NULL,
    CONSTRAINT [PK_ExchangeSalesOrderChargesAudit] PRIMARY KEY CLUSTERED ([AuditExchangeSalesOrderChargesId] ASC),
    CONSTRAINT [FK_ExchangeSalesOrderCharges_ExchangeSalesOrderChargesAudit] FOREIGN KEY ([ExchangeSalesOrderChargesId]) REFERENCES [dbo].[ExchangeSalesOrderCharges] ([ExchangeSalesOrderChargesId])
);

