CREATE TABLE [dbo].[ExchangeSalesOrderStockLineAudit] (
    [SOStockLineAuditId]       BIGINT          IDENTITY (1, 1) NOT NULL,
    [SOStockLineId]            BIGINT          NOT NULL,
    [ExchangeSalesOrderId]     BIGINT          NOT NULL,
    [ExchangeSalesOrderPartId] BIGINT          NOT NULL,
    [StockLIneId]              BIGINT          NOT NULL,
    [ItemMasterId]             BIGINT          NOT NULL,
    [ConditionId]              BIGINT          NOT NULL,
    [Quantity]                 INT             NULL,
    [QtyReserved]              INT             NULL,
    [QtyIssued]                INT             NULL,
    [AltPartMasterPartId]      BIGINT          NULL,
    [EquPartMasterPartId]      BIGINT          NULL,
    [IsAltPart]                BIT             NULL,
    [IsEquPart]                BIT             NULL,
    [UnitCost]                 DECIMAL (20, 2) NULL,
    [ExtendedCost]             DECIMAL (20, 2) NULL,
    [UnitPrice]                DECIMAL (20, 2) NULL,
    [ExtendedPrice]            DECIMAL (20, 2) NULL,
    [MasterCompanyId]          INT             NOT NULL,
    [CreatedBy]                VARCHAR (256)   NOT NULL,
    [UpdatedBy]                VARCHAR (256)   NOT NULL,
    [CreatedDate]              DATETIME2 (7)   NOT NULL,
    [UpdatedDate]              DATETIME2 (7)   NOT NULL,
    [IsActive]                 BIT             NOT NULL,
    [IsDeleted]                BIT             NOT NULL,
    CONSTRAINT [PK_ExchangeSalesOrderStockLineAudit] PRIMARY KEY CLUSTERED ([SOStockLineAuditId] ASC)
);

