CREATE TABLE [dbo].[ExchangeSalesOrderStockAudit] (
    [SOStockAuditId]           BIGINT        IDENTITY (1, 1) NOT NULL,
    [ExchangeSalesOrderId]     BIGINT        NOT NULL,
    [ExchangeSalesOrderPartId] BIGINT        NOT NULL,
    [StockLIneId]              BIGINT        NOT NULL,
    [ConditionId]              BIGINT        NOT NULL,
    [ItemMasterId]             BIGINT        NOT NULL,
    [AltPartMasterPartId]      BIGINT        NULL,
    [EquPartMasterPartId]      BIGINT        NULL,
    [IsAltPart]                BIT           NULL,
    [IsEquPart]                BIT           NULL,
    [QtyReserved]              INT           NULL,
    [QtyUnReserved]            INT           NULL,
    [QtyIssued]                INT           NULL,
    [QtyUnIssued]              INT           NULL,
    [ResIssuedById]            BIGINT        NOT NULL,
    [ResIssuedDate]            DATETIME2 (7) NOT NULL,
    [PartStatusId]             INT           NOT NULL,
    [MasterCompanyId]          INT           NOT NULL,
    [CreatedBy]                VARCHAR (256) NOT NULL,
    [UpdatedBy]                VARCHAR (256) NOT NULL,
    [CreatedDate]              DATETIME2 (7) NOT NULL,
    [UpdatedDate]              DATETIME2 (7) NOT NULL,
    [IsActive]                 BIT           NOT NULL,
    [IsDeleted]                BIT           NOT NULL,
    CONSTRAINT [PK_ExchangeSalesOrderStockAudit] PRIMARY KEY CLUSTERED ([SOStockAuditId] ASC)
);

