CREATE TABLE [dbo].[ExchangeSalesOrderBillingInvoicingItemAudit] (
    [AuditExchangeSOBillingInvoicingItemId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [ExchangeSOBillingInvoicingItemId]      BIGINT          NOT NULL,
    [SOBillingInvoicingId]                  BIGINT          NOT NULL,
    [NoofPieces]                            DECIMAL (18, 6) NULL,
    [ExchangeSalesOrderPartId]              BIGINT          NOT NULL,
    [ItemMasterId]                          BIGINT          NOT NULL,
    [MasterCompanyId]                       INT             NOT NULL,
    [CreatedBy]                             VARCHAR (256)   NOT NULL,
    [UpdatedBy]                             VARCHAR (256)   NOT NULL,
    [CreatedDate]                           DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                           DATETIME2 (7)   NOT NULL,
    [IsActive]                              BIT             NOT NULL,
    [IsDeleted]                             BIT             NOT NULL,
    [UnitPrice]                             DECIMAL (18, 6) NULL,
    [ExchangeSalesOrderShippingId]          BIGINT          NULL,
    [ExchangeSalesOrderScheduleBillingId]   BIGINT          NULL,
    [MiscCharges]                           DECIMAL (18, 6) NULL,
    [Freight]                               DECIMAL (18, 6) NULL,
    [SubTotal]                              DECIMAL (18, 6) NULL,
    [OtherTaxPercent]                       DECIMAL (18, 6) NULL,
    [SalesTaxPercent]                       DECIMAL (18, 6) NULL,
    [GrandTotal]                            DECIMAL (18, 6) NULL,
    [OtherTax]                              DECIMAL (18, 6) NULL,
    [SalesTax]                              DECIMAL (18, 6) NULL,
    [CogsAmount]                            DECIMAL (18, 6) NULL,
    CONSTRAINT [PK_ExchangeSalesOrderBillingInvoicingItemAudit] PRIMARY KEY CLUSTERED ([AuditExchangeSOBillingInvoicingItemId] ASC)
);

