CREATE TABLE [dbo].[ItemMasterAudit] (
    [ItemMasterAuditId]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [ItemMasterId]                      BIGINT          NOT NULL,
    [ItemTypeId]                        INT             NOT NULL,
    [PartAlternatePartId]               BIGINT          NULL,
    [ItemGroupId]                       BIGINT          NULL,
    [ItemClassificationId]              BIGINT          CONSTRAINT [DF_ItemMasterAudit_ItemClassificationId_1] DEFAULT ((0)) NULL,
    [IsHazardousMaterial]               BIT             CONSTRAINT [DF_ItemMasterAudit_IsHazardousMaterial_1] DEFAULT ((0)) NULL,
    [IsExpirationDateAvailable]         BIT             CONSTRAINT [DF_ItemMasterAudit_IsExpirationDateAvailable_1] DEFAULT ((0)) NULL,
    [ExpirationDate]                    DATE            NULL,
    [IsReceivedDateAvailable]           BIT             CONSTRAINT [DF_ItemMasterAudit_IsReceivedDateAvailable_1] DEFAULT ((0)) NULL,
    [DaysReceived]                      INT             CONSTRAINT [DF_ItemMasterAudit_DaysReceived_1] DEFAULT ((0)) NULL,
    [IsManufacturingDateAvailable]      BIT             CONSTRAINT [DF_ItemMasterAudit_IsManufacturingDateAvailable_1] DEFAULT ((0)) NULL,
    [ManufacturingDays]                 INT             CONSTRAINT [DF_ItemMasterAudit_ManufacturingDays_1] DEFAULT ((0)) NULL,
    [IsTagDateAvailable]                BIT             CONSTRAINT [DF_ItemMasterAudit_IsTagDateAvailable_1] DEFAULT ((0)) NULL,
    [TagDays]                           INT             CONSTRAINT [DF_ItemMasterAudit_TagDays_1] DEFAULT ((0)) NULL,
    [IsOpenDateAvailable]               BIT             CONSTRAINT [DF_ItemMasterAudit_IsOpenDateAvailable_1] DEFAULT ((0)) NULL,
    [OpenDays]                          INT             CONSTRAINT [DF_ItemMasterAudit_OpenDays_1] DEFAULT ((0)) NULL,
    [IsShippedDateAvailable]            BIT             CONSTRAINT [DF_ItemMasterAudit_IsShippedDateAvailable_1] DEFAULT ((0)) NULL,
    [ShippedDays]                       INT             CONSTRAINT [DF_ItemMasterAudit_ShippedDays_1] DEFAULT ((0)) NULL,
    [IsOtherDateAvailable]              BIT             CONSTRAINT [DF_ItemMasterAudit_IsOtherDateAvailable_1] DEFAULT ((0)) NULL,
    [OtherDays]                         INT             CONSTRAINT [DF_ItemMasterAudit_OtherDays_1] DEFAULT ((0)) NULL,
    [ProvisionId]                       INT             NULL,
    [ManufacturerId]                    BIGINT          CONSTRAINT [DF_ItemMasterAudit_ManufacturerId_1] DEFAULT ((0)) NULL,
    [IsDER]                             BIT             CONSTRAINT [DF_ItemMasterAudit_IsDER_1] DEFAULT ((0)) NULL,
    [NationalStockNumber]               VARCHAR (50)    NULL,
    [IsSchematic]                       BIT             CONSTRAINT [DF_ItemMasterAudit_IsSchematic_1] DEFAULT ((0)) NULL,
    [OverhaulHours]                     INT             CONSTRAINT [DF_ItemMasterAudit_OverhaulHours_1] DEFAULT ((0)) NULL,
    [RPHours]                           INT             CONSTRAINT [DF_ItemMasterAudit_RPHours_1] DEFAULT ((0)) NULL,
    [TestHours]                         INT             CONSTRAINT [DF_ItemMasterAudit_TestHours_1] DEFAULT ((0)) NULL,
    [RFQTracking]                       BIT             CONSTRAINT [DF_ItemMasterAudit_RFQTracking_1] DEFAULT ((0)) NULL,
    [GLAccountId]                       BIGINT          NULL,
    [PurchaseUnitOfMeasureId]           BIGINT          CONSTRAINT [DF_ItemMasterAudit_PurchaseUnitOfMeasureId_1] DEFAULT ((0)) NULL,
    [StockUnitOfMeasureId]              BIGINT          NULL,
    [ConsumeUnitOfMeasureId]            BIGINT          NULL,
    [LeadTimeDays]                      INT             CONSTRAINT [DF_ItemMasterAudit_LeadTimeDays_1] DEFAULT ((0)) NULL,
    [ReorderPoint]                      DECIMAL (18, 6) CONSTRAINT [DF_ItemMasterAudit_ReorderPoint_1] DEFAULT ((0)) NULL,
    [ReorderQuantiy]                    DECIMAL (18, 6) CONSTRAINT [DF_ItemMasterAudit_ReorderQuantiy_1] DEFAULT ((0)) NULL,
    [MinimumOrderQuantity]              DECIMAL (18, 6) CONSTRAINT [DF_ItemMasterAudit_MinimumOrderQuantity_1] DEFAULT ((0)) NULL,
    [PartListPrice]                     DECIMAL (18, 6) NULL,
    [PriorityId]                        BIGINT          NULL,
    [WarningId]                         BIGINT          NULL,
    [Memo]                              NVARCHAR (MAX)  NULL,
    [ExportCountryId]                   SMALLINT        NULL,
    [ExportValue]                       DECIMAL (18, 6) NULL,
    [ExportCurrencyId]                  INT             NULL,
    [ExportWeight]                      DECIMAL (18, 6) NULL,
    [ExportWeightUnit]                  VARCHAR (30)    NULL,
    [ExportSizeLength]                  DECIMAL (18, 6) NULL,
    [ExportSizeWidth]                   DECIMAL (18, 6) NULL,
    [ExportSizeHeight]                  DECIMAL (18, 6) NULL,
    [ExportSizeUnit]                    VARCHAR (30)    NULL,
    [ExportClassificationId]            TINYINT         NULL,
    [PurchaseCurrencyId]                INT             NULL,
    [SalesIsFixedPrice]                 BIT             NULL,
    [SalesCurrencyId]                   INT             NULL,
    [SalesLastSalePriceDate]            DATETIME2 (7)   NULL,
    [SalesLastSalesDiscountPercentDate] DATETIME2 (7)   NULL,
    [IsActive]                          BIT             CONSTRAINT [DF_ItemMasterAudit_IsActive_1] DEFAULT ((1)) NULL,
    [CurrencyId]                        INT             NULL,
    [MasterCompanyId]                   INT             NOT NULL,
    [CreatedBy]                         VARCHAR (256)   NULL,
    [UpdatedBy]                         VARCHAR (256)   NULL,
    [CreatedDate]                       DATETIME2 (7)   CONSTRAINT [DF_ItemMasterAudit_CreatedDate_1] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                       DATETIME2 (7)   CONSTRAINT [DF_ItemMasterAudit_UpdatedDate_1] DEFAULT (getdate()) NOT NULL,
    [TurnTimeOverhaulHours]             INT             CONSTRAINT [DF_ItemMasterAudit_TurnTimeOverhaulHours_1] DEFAULT ((0)) NULL,
    [TurnTimeRepairHours]               INT             CONSTRAINT [DF_ItemMasterAudit_TurnTimeRepairHours_1] DEFAULT ((0)) NULL,
    [SoldUnitOfMeasureId]               BIGINT          NULL,
    [IsDeleted]                         BIT             CONSTRAINT [DF_ItemMasterAudit_IsDeleted_1] DEFAULT ((0)) NULL,
    [ExportUomId]                       BIGINT          NULL,
    [partnumber]                        VARCHAR (50)    NULL,
    [PartDescription]                   NVARCHAR (MAX)  NULL,
    [isTimeLife]                        BIT             CONSTRAINT [DF_ItemMasterAudit_isTimeLife_1] DEFAULT ((0)) NULL,
    [isSerialized]                      BIT             CONSTRAINT [DF_ItemMasterAudit_isSerialized_1] DEFAULT ((0)) NULL,
    [ManagementStructureId]             BIGINT          NULL,
    [ShelfLife]                         BIT             CONSTRAINT [DF_ItemMasterAudit_ShelfLife_1] DEFAULT ((0)) NULL,
    [DiscountPurchasePercent]           TINYINT         NULL,
    [UnitCost]                          DECIMAL (18, 6) NULL,
    [ListPrice]                         DECIMAL (18, 6) NULL,
    [PriceDate]                         DATETIME2 (7)   NULL,
    [ItemNonStockClassificationId]      BIGINT          NULL,
    [StockLevel]                        DECIMAL (18, 6) CONSTRAINT [DF_ItemMasterAudit_StockLevel_1] DEFAULT ((0)) NULL,
    [ExportECCN]                        VARCHAR (200)   NULL,
    [ITARNumber]                        VARCHAR (200)   NULL,
    [ShelfLifeAvailable]                DECIMAL (18, 6) CONSTRAINT [DF_ItemMasterAudit_ShelfLifeAvailable_1] DEFAULT ((0)) NULL,
    [mfgHours]                          DECIMAL (18, 6) CONSTRAINT [DF_ItemMasterAudit_mfgHours_1] DEFAULT ((0)) NULL,
    [IsPma]                             BIT             CONSTRAINT [DF_ItemMasterAudit_IsPma_1] DEFAULT ((0)) NULL,
    [turnTimeMfg]                       DECIMAL (18, 6) CONSTRAINT [DF_ItemMasterAudit_turnTimeMfg_1] DEFAULT ((0)) NULL,
    [turnTimeBenchTest]                 DECIMAL (18, 6) CONSTRAINT [DF_ItemMasterAudit_turnTimeBenchTest_1] DEFAULT ((0)) NULL,
    [IsExportUnspecified]               BIT             NULL,
    [IsExportNONMilitary]               BIT             NULL,
    [IsExportMilitary]                  BIT             NULL,
    [IsExportDual]                      BIT             NULL,
    [IsOemPNId]                         BIGINT          NULL,
    [MasterPartId]                      BIGINT          NULL,
    [RepairUnitOfMeasureId]             BIGINT          NULL,
    [RevisedPartId]                     BIGINT          NULL,
    [SiteId]                            BIGINT          CONSTRAINT [DF_ItemMasterAudit_SiteId_1] DEFAULT ((0)) NULL,
    [WarehouseId]                       BIGINT          NULL,
    [LocationId]                        BIGINT          NULL,
    [ShelfId]                           BIGINT          NULL,
    [BinId]                             BIGINT          NULL,
    [ItemMasterAssetTypeId]             BIGINT          CONSTRAINT [DF_ItemMasterAudit_ItemMasterAssetTypeId_1] DEFAULT ((0)) NULL,
    [IsHotItem]                         BIT             CONSTRAINT [DF_ItemMasterAudit_IsHotItem_1] DEFAULT ((0)) NULL,
    [ExportSizeUnitOfMeasureId]         BIGINT          NULL,
    [IsAcquiredMethodBuy]               BIT             CONSTRAINT [DF_ItemMasterAudit_IsAcquiredMethodBuy_1] DEFAULT ((0)) NULL,
    [IsOEM]                             BIT             CONSTRAINT [DF_ItemMasterAudit_IsOEM_1] DEFAULT ((0)) NULL,
    [RevisedPart]                       VARCHAR (250)   NULL,
    [OEMPN]                             VARCHAR (250)   NULL,
    [ItemClassificationName]            VARCHAR (250)   NULL,
    [ItemGroup]                         VARCHAR (250)   NULL,
    [AssetAcquistionType]               VARCHAR (250)   NULL,
    [ManufacturerName]                  VARCHAR (250)   NULL,
    [PurchaseUnitOfMeasure]             VARCHAR (250)   NULL,
    [StockUnitOfMeasure]                VARCHAR (250)   NULL,
    [ConsumeUnitOfMeasure]              VARCHAR (250)   NULL,
    [PurchaseCurrency]                  VARCHAR (50)    NULL,
    [SalesCurrency]                     VARCHAR (50)    NULL,
    [GLAccount]                         VARCHAR (250)   NULL,
    [Priority]                          VARCHAR (250)   NULL,
    [SiteName]                          VARCHAR (250)   NULL,
    [WarehouseName]                     VARCHAR (250)   NULL,
    [LocationName]                      VARCHAR (250)   NULL,
    [ShelfName]                         VARCHAR (250)   NULL,
    [BinName]                           VARCHAR (250)   NULL,
    [CurrentStlNo]                      BIGINT          NULL,
    [MTBUR]                             INT             DEFAULT ((0)) NULL,
    [NE]                                INT             DEFAULT ((0)) NULL,
    [NS]                                INT             DEFAULT ((0)) NULL,
    [OH]                                INT             DEFAULT ((0)) NULL,
    [REP]                               INT             DEFAULT ((0)) NULL,
    [SVC]                               INT             DEFAULT ((0)) NULL,
    [Figure]                            VARCHAR (15)    NULL,
    [Item]                              VARCHAR (15)    NULL,
    [UNCode]                            BIT             NULL,
    [InventoryGLSettingId]              BIGINT          NULL,
    [GoodsReceivedNotInvoicesGLAccId]   BIGINT          NULL,
    [WorkInProgressGLAccId]             BIGINT          NULL,
    [InventoryToBillGLAccId]            BIGINT          NULL,
    [FinishedGoodsGLAccId]              BIGINT          NULL,
    [InventoryExchAgreementGLAccId]     BIGINT          NULL,
    [InventoryReserveGLAccId]           BIGINT          NULL,
    [COGS_WorkOrderGLAccId]             BIGINT          NULL,
    [COGS_SalesOrderGLAccId]            BIGINT          NULL,
    [COGS_QtyVarianceGLAccId]           BIGINT          NULL,
    [COGS_UnitCostVarianceGLAccId]      BIGINT          NULL,
    [RevenueMroGLAccId]                 BIGINT          NULL,
    [RevenueSoGLAccId]                  BIGINT          NULL,
    [RevenueExchGLAccId]                BIGINT          NULL,
    [COGS_ExchSalesOrderGLAccId]        BIGINT          NULL,
    [GoodsReceivedNotInvoicesGLAccName] VARCHAR (255)   NULL,
    [WorkInProgressGLAccName]           VARCHAR (255)   NULL,
    [InventoryToBillGLAccName]          VARCHAR (255)   NULL,
    [FinishedGoodsGLAccName]            VARCHAR (255)   NULL,
    [InventoryExchAgreementGLAccName]   VARCHAR (255)   NULL,
    [InventoryReserveGLAccName]         VARCHAR (255)   NULL,
    [COGS_WorkOrderGLAccName]           VARCHAR (255)   NULL,
    [COGS_SalesOrderGLAccName]          VARCHAR (255)   NULL,
    [COGS_QtyVarianceGLAccName]         VARCHAR (255)   NULL,
    [COGS_UnitCostVarianceGLAccName]    VARCHAR (255)   NULL,
    [RevenueMroGLAccName]               VARCHAR (255)   NULL,
    [RevenueSoGLAccName]                VARCHAR (255)   NULL,
    [RevenueExchGLAccName]              VARCHAR (255)   NULL,
    [COGS_ExchSalesOrderGLAccName]      VARCHAR (255)   NULL,
    [QuickBooksReferenceId]             VARCHAR (200)   NULL,
    [IsUpdated]                         BIT             NULL,
    [LastSyncDate]                      DATETIME2 (7)   NULL,
    [SyncToken]                         VARCHAR (200)   NULL,
    [WorkOrderFormTypeId]               INT             NULL,
    [IsFlightHoursAvailable]            BIT             NULL,
    [IsFlightCyclesAvailable]           BIT             NULL,
    [IsLandingsAvailable]               BIT             NULL,
    [IsStartsAvailable]                 BIT             NULL,
    [IsCalendarTimeAvailable]           BIT             NULL,
    [FlightHours]                       VARCHAR (200)   NULL,
    [FlightMinutes]                     VARCHAR (200)   NULL,
    [FlightCycles]                      INT             NULL,
    [Landings]                          INT             NULL,
    [Starts]                            INT             NULL,
    [CalendarDate]                      DATETIME2 (7)   NULL,    
    [IntegrationTypeId]                 INT             NULL,
    [IsNonStock]                        BIT             NULL,
    [InWarranty]                        BIT             NULL,
    [MfgExpirationDate]                 DATETIME        NULL,
    [IsMfgExpirationDate]               BIT             NULL,
    [IsService]                         BIT             NULL,
    [IsKitAssy]                         BIT             NULL,
    [Model]                             VARCHAR (200)   NULL,
    CONSTRAINT [PK_ItemMasterAudit] PRIMARY KEY CLUSTERED ([ItemMasterAuditId] ASC)
);

