CREATE TABLE [dbo].[ItemMasterPurchaseSaleAudit] (
    [ItemMasterId]                            BIGINT          NOT NULL,
    [PartNumber]                              VARCHAR (50)    NOT NULL,
    [PP_UOMId]                                BIGINT          NOT NULL,
    [PP_CurrencyId]                           INT             NOT NULL,
    [PP_FXRatePerc]                           DECIMAL (18, 2) NOT NULL,
    [PP_VendorListPrice]                      DECIMAL (18, 2) NULL,
    [PP_LastListPriceDate]                    DATETIME2 (7)   NULL,
    [PP_PurchaseDiscPerc]                     INT             NULL,
    [PP_PurchaseDiscAmount]                   DECIMAL (18, 2) NULL,
    [PP_LastPurchaseDiscDate]                 DATETIME2 (7)   NULL,
    [PP_UnitPurchasePrice]                    DECIMAL (18, 2) NULL,
    [SP_FSP_UOMId]                            BIGINT          NULL,
    [SP_FSP_CurrencyId]                       INT             NULL,
    [SP_FSP_FXRatePerc]                       DECIMAL (18, 2) NOT NULL,
    [SP_FSP_FlatPriceAmount]                  DECIMAL (18, 2) NULL,
    [SP_FSP_LastFlatPriceDate]                DATETIME2 (7)   NULL,
    [SP_CalSPByPP_MarkUpPercOnListPrice]      INT             NULL,
    [SP_CalSPByPP_MarkUpAmount]               DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_LastMarkUpDate]             DATETIME2 (7)   NULL,
    [SP_CalSPByPP_BaseSalePrice]              DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_SaleDiscPerc]               INT             NULL,
    [SP_CalSPByPP_SaleDiscAmount]             DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_LastSalesDiscDate]          DATETIME2 (7)   NULL,
    [SP_CalSPByPP_UnitSalePrice]              DECIMAL (18, 2) NULL,
    [MasterCompanyId]                         INT             NOT NULL,
    [CreatedBy]                               VARCHAR (256)   NOT NULL,
    [UpdatedBy]                               VARCHAR (256)   NOT NULL,
    [CreatedDate]                             DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                             DATETIME2 (7)   NOT NULL,
    [IsActive]                                BIT             NOT NULL,
    [IsDeleted]                               BIT             NOT NULL,
    [ItemMasterPurchaseSaleId]                BIGINT          NOT NULL,
    [AuditItemMasterPurchaseSaleId]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [ConditionId]                             BIGINT          NULL,
    [SalePriceSelectId]                       INT             NULL,
    [ConditionName]                           VARCHAR (200)   NULL,
    [PP_UOMName]                              VARCHAR (200)   NULL,
    [SP_FSP_UOMName]                          VARCHAR (200)   NULL,
    [PP_CurrencyName]                         VARCHAR (200)   NULL,
    [SP_FSP_CurrencyName]                     VARCHAR (200)   NULL,
    [PP_PurchaseDiscPercValue]                DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_SaleDiscPercValue]          DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_MarkUpPercOnListPriceValue] DECIMAL (18, 2) NULL,
    [SalePriceSelectName]                     VARCHAR (200)   NULL,
    PRIMARY KEY CLUSTERED ([AuditItemMasterPurchaseSaleId] ASC)
);

