CREATE TABLE [dbo].[ReceivingCustomerWorkAudit] (
    [AuditReceivingCustomerWorkId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [ReceivingCustomerWorkId]      BIGINT         NOT NULL,
    [EmployeeId]                   BIGINT         NOT NULL,
    [CustomerId]                   BIGINT         NOT NULL,
    [ReceivingNumber]              VARCHAR (50)   NOT NULL,
    [CustomerContactId]            BIGINT         NOT NULL,
    [ItemMasterId]                 BIGINT         NOT NULL,
    [RevisePartId]                 BIGINT         NULL,
    [IsSerialized]                 BIT            NULL,
    [SerialNumber]                 VARCHAR (100)  NULL,
    [Quantity]                     INT            NOT NULL,
    [ConditionId]                  BIGINT         NOT NULL,
    [SiteId]                       BIGINT         NOT NULL,
    [WarehouseId]                  BIGINT         NULL,
    [LocationId]                   BIGINT         NULL,
    [Shelfid]                      BIGINT         NULL,
    [BinId]                        BIGINT         NULL,
    [OwnerTypeId]                  INT            NULL,
    [Owner]                        BIGINT         NULL,
    [IsCustomerStock]              BIT            NOT NULL,
    [TraceableToTypeId]            INT            NULL,
    [TraceableTo]                  BIGINT         NULL,
    [ObtainFromTypeId]             INT            NULL,
    [ObtainFrom]                   BIGINT         NULL,
    [IsMFGDate]                    BIT            NULL,
    [MFGDate]                      DATETIME2 (7)  NULL,
    [MFGTrace]                     VARCHAR (100)  NULL,
    [MFGLotNo]                     VARCHAR (100)  NULL,
    [IsExpDate]                    BIT            NULL,
    [ExpDate]                      DATETIME2 (7)  NULL,
    [IsTimeLife]                   BIT            NULL,
    [TagDate]                      DATETIME2 (7)  NULL,
    [TagType]                      VARCHAR (8000) NULL,
    [TagTypeIds]                   BIGINT         NULL,
    [TimeLifeDate]                 DATETIME2 (7)  NULL,
    [TimeLifeOrigin]               VARCHAR (MAX)  NULL,
    [TimeLifeCyclesId]             BIGINT         NULL,
    [Memo]                         NVARCHAR (MAX) NULL,
    [PartCertificationNumber]      VARCHAR (30)   NULL,
    [ManagementStructureId]        BIGINT         NOT NULL,
    [StockLineId]                  BIGINT         NULL,
    [WorkOrderId]                  BIGINT         NULL,
    [MasterCompanyId]              INT            NOT NULL,
    [CreatedBy]                    VARCHAR (256)  NOT NULL,
    [UpdatedBy]                    VARCHAR (256)  NOT NULL,
    [CreatedDate]                  DATETIME2 (7)  NOT NULL,
    [UpdatedDate]                  DATETIME2 (7)  NOT NULL,
    [IsActive]                     BIT            NOT NULL,
    [IsDeleted]                    BIT            NOT NULL,
    [IsSkipSerialNo]               BIT            NULL,
    [IsSkipTimeLife]               BIT            NULL,
    [Reference]                    VARCHAR (256)  NOT NULL,
    [CertifiedBy]                  VARCHAR (256)  NULL,
    [ReceivedDate]                 DATETIME2 (7)  NOT NULL,
    [CustReqDate]                  DATETIME2 (7)  NOT NULL,
    [Level1]                       VARCHAR (200)  NULL,
    [Level2]                       VARCHAR (200)  NULL,
    [Level3]                       VARCHAR (200)  NULL,
    [Level4]                       VARCHAR (200)  NULL,
    [EmployeeName]                 VARCHAR (200)  NULL,
    [CustomerName]                 VARCHAR (200)  NULL,
    [WorkScopeId]                  BIGINT         NULL,
    [CustomerCode]                 VARCHAR (100)  NULL,
    [ManufacturerName]             VARCHAR (100)  NULL,
    [InspectedById]                BIGINT         NULL,
    [CertifiedDate]                DATETIME2 (7)  NULL,
    [ObtainFromName]               VARCHAR (256)  NULL,
    [OwnerName]                    VARCHAR (256)  NULL,
    [TraceableToName]              VARCHAR (256)  NULL,
    [PartNumber]                   VARCHAR (250)  NULL,
    [WorkScope]                    VARCHAR (250)  NULL,
    [Condition]                    VARCHAR (100)  NULL,
    [Site]                         VARCHAR (250)  NULL,
    [Warehouse]                    VARCHAR (250)  NULL,
    [Location]                     VARCHAR (250)  NULL,
    [Shelf]                        VARCHAR (250)  NULL,
    [Bin]                          VARCHAR (250)  NULL,
    [InspectedBy]                  VARCHAR (100)  NULL,
    [InspectedDate]                DATETIME       NULL,
    [TaggedById]                   BIGINT         NULL,
    [TaggedBy]                     VARCHAR (100)  NULL,
    [ACTailNum]                    NVARCHAR (500) NULL,
    [TaggedByType]                 INT            NULL,
    [TaggedByTypeName]             VARCHAR (250)  NULL,
    [CertifiedById]                BIGINT         NULL,
    [CertifiedTypeId]              INT            NULL,
    [CertifiedType]                VARCHAR (250)  NULL,
    [CertTypeId]                   VARCHAR (MAX)  NULL,
    [CertType]                     VARCHAR (MAX)  NULL,
    [RemovalReasonId]              BIGINT         NULL,
    [RemovalReasons]               VARCHAR (200)  NULL,
    [RemovalReasonsMemo]           NVARCHAR (MAX) NULL,
    [ExchangeSalesOrderId]         BIGINT         NULL,
    [CustReqTagTypeId]             BIGINT         NULL,
    [CustReqTagType]               VARCHAR (100)  NULL,
    [CustReqCertTypeId]            VARCHAR (MAX)  NULL,
    [CustReqCertType]              VARCHAR (MAX)  NULL,
    [RepairOrderPartRecordId]      BIGINT         NULL,
    [IsExchangeBatchEntry]         BIT            NULL,
    CONSTRAINT [PK_ReceivingCustomerWorkAudit] PRIMARY KEY CLUSTERED ([AuditReceivingCustomerWorkId] ASC)
);

