CREATE TABLE [dbo].[ReceivingEquipment] (
    [ReceivingEquipmentId]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [ItemCategoryId]                 TINYINT         NOT NULL,
    [IsMasterEquipment]              BIT             NOT NULL,
    [PartId]                         BIGINT          NOT NULL,
    [IsCalibrationRequired]          BIT             NOT NULL,
    [IsCalibrationFrequencyInMonths] BIT             NULL,
    [IsCertificationRequired]        BIT             NOT NULL,
    [CertificationFrequency]         VARCHAR (30)    NULL,
    [AssetNumber]                    VARCHAR (30)    NULL,
    [EquipmentTypeId]                TINYINT         NULL,
    [EquipmentPlatformId]            TINYINT         NULL,
    [IsSerialized]                   BIT             NULL,
    [AcquiredModeId]                 TINYINT         NULL,
    [IsExpirationDatePresent]        BIT             NULL,
    [ReceivedDate]                   DATETIME2 (7)   NULL,
    [ManufacturingDate]              DATETIME2 (7)   NULL,
    [TagDate]                        DATETIME2 (7)   NULL,
    [ExpirationDate]                 DATETIME2 (7)   NULL,
    [IsManufacturingInfoAvailable]   BIT             NULL,
    [PlatformId]                     TINYINT         NULL,
    [ModelId]                        SMALLINT        NULL,
    [DashNumber]                     VARCHAR (30)    NULL,
    [ATAMain]                        VARCHAR (30)    NULL,
    [ATAMainSub1]                    VARCHAR (30)    NULL,
    [ATAMainSub2]                    VARCHAR (30)    NULL,
    [ListPrice]                      NUMERIC (18, 2) NULL,
    [CurrencyId]                     SMALLINT        NULL,
    [PriceDate]                      DATETIME2 (7)   NULL,
    [InspectionRequired]             BIT             NULL,
    [InspectionNotes]                NVARCHAR (MAX)  NULL,
    [VerificationRequired]           BIT             NULL,
    [VerificationNotes]              NVARCHAR (MAX)  NULL,
    [Schematic]                      BIT             NULL,
    [SchematicFile]                  NVARCHAR (MAX)  NULL,
    [CompanyId]                      INT             NULL,
    [BusinessUnitId]                 INT             NULL,
    [DivisionId]                     INT             NULL,
    [DepartmentId]                   INT             NULL,
    [MasterCompanyId]                INT             NULL,
    [RecordCreateDate]               DATETIME2 (7)   NOT NULL,
    [RecordModifiedDate]             DATETIME2 (7)   NULL,
    [LastModifedBy]                  INT             NULL,
    [CreatedBy]                      VARCHAR (256)   NULL,
    [UpdatedBy]                      VARCHAR (256)   NULL,
    [CreatedDate]                    DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                    DATETIME2 (7)   NOT NULL,
    [IsActive]                       BIT             NULL,
    CONSTRAINT [PK_ReceivingEquipment] PRIMARY KEY CLUSTERED ([ReceivingEquipmentId] ASC)
);

