CREATE TABLE [dbo].[RMAPickTicket] (
    [RMAPickTicketId]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [RMAPickTicketNumber] VARCHAR (50)   NOT NULL,
    [VendorRMAId]         BIGINT         NOT NULL,
    [CreatedBy]           VARCHAR (256)  NOT NULL,
    [CreatedDate]         DATETIME2 (7)  CONSTRAINT [DF_RMAPickTicket_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedBy]           VARCHAR (256)  NOT NULL,
    [UpdatedDate]         DATETIME2 (7)  CONSTRAINT [DF_RMAPickTicket_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]            BIT            CONSTRAINT [DF_RMAPickTicket_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]           BIT            CONSTRAINT [DF_RMAPickTicket_IsDeleted] DEFAULT ((0)) NOT NULL,
    [VendorRMADetailId]   BIGINT         NULL,
    [Qty]                 INT            NULL,
    [QtyToShip]           INT            NULL,
    [MasterCompanyId]     INT            NOT NULL,
    [Status]              INT            NULL,
    [PickedById]          BIGINT         NULL,
    [ConfirmedById]       INT            NULL,
    [Memo]                NVARCHAR (MAX) NULL,
    [IsConfirmed]         BIT            NULL,
    [ConfirmedDate]       DATETIME2 (7)  NULL,
    [PDFPath]             NVARCHAR (MAX) NULL,
    [QtyRemaining]        INT            NULL,
    CONSTRAINT [PK_RMAPickTicket] PRIMARY KEY CLUSTERED ([RMAPickTicketId] ASC),
    CONSTRAINT [FK_RMAPickTicket_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId]),
    CONSTRAINT [FK_RMAPickTicket_VendorRMAId] FOREIGN KEY ([VendorRMAId]) REFERENCES [dbo].[VendorRMA] ([VendorRMAId])
);

