CREATE TABLE [dbo].[SalesOrderReservePartsAudit] (
    [AuditSalesOrderReservePartId] BIGINT        IDENTITY (1, 1) NOT NULL,
    [SalesOrderReservePartId]      BIGINT        NOT NULL,
    [SalesOrderId]                 BIGINT        NULL,
    [StockLineId]                  BIGINT        NOT NULL,
    [ItemMasterId]                 BIGINT        NOT NULL,
    [PartStatusId]                 INT           NOT NULL,
    [IsEquPart]                    BIT           NOT NULL,
    [EquPartMasterPartId]          BIGINT        NULL,
    [IsAltPart]                    BIT           NOT NULL,
    [AltPartMasterPartId]          BIGINT        NULL,
    [QtyToReserve]                 INT           NULL,
    [QtyToIssued]                  INT           NULL,
    [ReservedById]                 BIGINT        NULL,
    [ReservedDate]                 DATETIME2 (7) NULL,
    [IssuedById]                   BIGINT        NULL,
    [IssuedDate]                   DATETIME2 (7) NULL,
    [CreatedBy]                    VARCHAR (256) NOT NULL,
    [CreatedDate]                  DATETIME2 (7) NOT NULL,
    [UpdatedBy]                    VARCHAR (256) NOT NULL,
    [UpdatedDate]                  DATETIME2 (7) NOT NULL,
    [IsActive]                     BIT           NOT NULL,
    [IsDeleted]                    BIT           NOT NULL,
    [SalesOrderPartId]             BIGINT        NOT NULL,
    [TotalReserved]                INT           NULL,
    [TotalIssued]                  INT           NULL,
    [MasterCompanyId]              INT           NULL,
    CONSTRAINT [PK_SalesOrderReservePartsAudit] PRIMARY KEY CLUSTERED ([AuditSalesOrderReservePartId] ASC)
);

