CREATE TABLE [dbo].[SalesOrderQuoteAudit] (
    [AuditSalesOrderQuoteId]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [SalesOrderQuoteId]        BIGINT          NOT NULL,
    [QuoteTypeId]              INT             NOT NULL,
    [OpenDate]                 DATETIME2 (7)   NULL,
    [ValidForDays]             INT             NOT NULL,
    [QuoteExpireDate]          DATETIME2 (7)   NOT NULL,
    [AccountTypeId]            INT             NOT NULL,
    [CustomerId]               BIGINT          NOT NULL,
    [CustomerContactId]        BIGINT          NULL,
    [CustomerReference]        VARCHAR (100)   NULL,
    [ContractReference]        VARCHAR (100)   NULL,
    [SalesPersonId]            BIGINT          NULL,
    [AgentName]                VARCHAR (50)    NULL,
    [CustomerSeviceRepId]      BIGINT          NULL,
    [ProbabilityId]            BIGINT          NULL,
    [LeadSourceId]             INT             NULL,
    [CreditLimit]              DECIMAL (18, 2) NULL,
    [CreditTermId]             INT             NULL,
    [EmployeeId]               BIGINT          NOT NULL,
    [RestrictPMA]              BIT             NOT NULL,
    [RestrictDER]              BIT             NOT NULL,
    [ApprovedDate]             DATETIME2 (7)   NULL,
    [CurrencyId]               INT             NULL,
    [CustomerWarningId]        BIGINT          NULL,
    [Memo]                     NVARCHAR (MAX)  NULL,
    [Notes]                    NVARCHAR (MAX)  NULL,
    [MasterCompanyId]          INT             NOT NULL,
    [CreatedBy]                VARCHAR (256)   NOT NULL,
    [CreatedDate]              DATETIME2 (7)   NOT NULL,
    [UpdatedBy]                VARCHAR (256)   NOT NULL,
    [UpdatedDate]              DATETIME2 (7)   NOT NULL,
    [IsDeleted]                BIT             NOT NULL,
    [StatusId]                 INT             NOT NULL,
    [StatusChangeDate]         DATETIME2 (7)   NOT NULL,
    [ManagementStructureId]    BIGINT          NOT NULL,
    [Version]                  INT             NOT NULL,
    [AgentId]                  BIGINT          NULL,
    [QtyRequested]             INT             NULL,
    [QtyToBeQuoted]            INT             NULL,
    [SalesOrderQuoteNumber]    VARCHAR (50)    NOT NULL,
    [QuoteSentDate]            DATETIME2 (7)   NULL,
    [IsNewVersionCreated]      BIT             NOT NULL,
    [IsActive]                 BIT             NOT NULL,
    [QuoteParentId]            BIGINT          NULL,
    [QuoteTypeName]            VARCHAR (50)    NULL,
    [AccountTypeName]          VARCHAR (50)    NULL,
    [CustomerName]             VARCHAR (100)   NULL,
    [SalesPersonName]          VARCHAR (50)    NULL,
    [CustomerServiceRepName]   VARCHAR (50)    NULL,
    [ProbabilityName]          VARCHAR (50)    NULL,
    [LeadSourceName]           VARCHAR (50)    NULL,
    [CreditTermName]           VARCHAR (50)    NULL,
    [EmployeeName]             VARCHAR (50)    NULL,
    [CurrencyName]             VARCHAR (50)    NULL,
    [CustomerWarningName]      VARCHAR (500)   NULL,
    [ManagementStructureName]  VARCHAR (50)    NULL,
    [CustomerContactName]      VARCHAR (200)   NULL,
    [VersionNumber]            VARCHAR (50)    NULL,
    [CustomerCode]             VARCHAR (50)    NULL,
    [CustomerContactEmail]     VARCHAR (50)    NULL,
    [CreditLimitName]          VARCHAR (50)    NULL,
    [StatusName]               VARCHAR (50)    NULL,
    [ManagementStructureName1] VARCHAR (50)    NULL,
    [ManagementStructureName2] VARCHAR (50)    NULL,
    [ManagementStructureName3] VARCHAR (50)    NULL,
    [ManagementStructureName4] VARCHAR (50)    NULL,
    [EnforceEffectiveDate]     DATETIME2 (7)   NULL,
    [IsEnforceApproval]        BIT             NULL,
    [TotalFreight]             DECIMAL (20, 2) NULL,
    [TotalCharges]             DECIMAL (20, 2) NULL,
    [FreightBilingMethodId]    INT             NULL,
    [ChargesBilingMethodId]    INT             NULL,
    [FunctionalCurrencyId]     INT             NULL,
    [ReportCurrencyId]         INT             NULL,
    [ForeignExchangeRate]      DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_SalesOrderQuoteAudit] PRIMARY KEY CLUSTERED ([AuditSalesOrderQuoteId] ASC),
    CONSTRAINT [FK_SalesOrderQuoteAudit_SalesOrderQuote] FOREIGN KEY ([SalesOrderQuoteId]) REFERENCES [dbo].[SalesOrderQuote] ([SalesOrderQuoteId])
);







