CREATE TABLE [dbo].[SalesOrderChargesAudit] (
    [AuditSalesOrderChargesId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [SalesOrderChargesId]      BIGINT          NOT NULL,
    [SalesOrderQuoteId]        BIGINT          NULL,
    [SalesOrderId]             BIGINT          NOT NULL,
    [SalesOrderPartId]         BIGINT          NULL,
    [ChargesTypeId]            BIGINT          NULL,
    [VendorId]                 BIGINT          NULL,
    [Quantity]                 INT             NULL,
    [MarkupPercentageId]       BIGINT          NULL,
    [Description]              VARCHAR (256)   NULL,
    [UnitCost]                 DECIMAL (20, 2) NULL,
    [ExtendedCost]             DECIMAL (20, 2) NULL,
    [MasterCompanyId]          INT             NOT NULL,
    [MarkupFixedPrice]         DECIMAL (20, 2) NULL,
    [BillingMethodId]          INT             NULL,
    [BillingAmount]            DECIMAL (20, 2) NULL,
    [BillingRate]              DECIMAL (20, 2) NULL,
    [HeaderMarkupId]           BIGINT          NULL,
    [RefNum]                   VARCHAR (20)    NULL,
    [CreatedBy]                VARCHAR (256)   NOT NULL,
    [UpdatedBy]                VARCHAR (256)   NOT NULL,
    [CreatedDate]              DATETIME2 (7)   NOT NULL,
    [UpdatedDate]              DATETIME2 (7)   NOT NULL,
    [IsActive]                 BIT             NOT NULL,
    [IsDeleted]                BIT             NOT NULL,
    [HeaderMarkupPercentageId] BIGINT          NULL,
    [VendorName]               VARCHAR (100)   NULL,
    [ChargeName]               VARCHAR (50)    NULL,
    [MarkupName]               VARCHAR (50)    NULL,
    [ItemMasterId]             BIGINT          NULL,
    [ConditionId]              BIGINT          NULL,
    [UOMId]                    BIGINT          NULL,
    CONSTRAINT [PK_SalesOrderChargesAudit] PRIMARY KEY CLUSTERED ([AuditSalesOrderChargesId] ASC)
);



