CREATE TABLE [dbo].[SalesOrderStockLineAudit] (
    [SOStockLineAuditId]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [SOStockLineId]       BIGINT          NOT NULL,
    [SalesOrderId]        BIGINT          NOT NULL,
    [SalesOrderPartId]    BIGINT          NOT NULL,
    [StockLineId]         BIGINT          NOT NULL,
    [ItemMasterId]        BIGINT          NOT NULL,
    [ConditionId]         BIGINT          NOT NULL,
    [Quantity]            DECIMAL (18, 6) NULL,
    [QtyReserved]         DECIMAL (18, 6) NULL,
    [QtyIssued]           DECIMAL (18, 6) NULL,
    [AltPartMasterPartId] BIGINT          NULL,
    [EquPartMasterPartId] BIGINT          NULL,
    [IsAltPart]           BIT             NULL,
    [IsEquPart]           BIT             NULL,
    [UnitCost]            DECIMAL (20, 6) NULL,
    [ExtendedCost]        DECIMAL (20, 6) NULL,
    [UnitPrice]           DECIMAL (20, 6) NULL,
    [ExtendedPrice]       DECIMAL (20, 6) NULL,
    [MasterCompanyId]     INT             NOT NULL,
    [CreatedBy]           VARCHAR (256)   NOT NULL,
    [UpdatedBy]           VARCHAR (256)   NOT NULL,
    [CreatedDate]         DATETIME2 (7)   NOT NULL,
    [UpdatedDate]         DATETIME2 (7)   NOT NULL,
    [IsActive]            BIT             NOT NULL,
    [IsDeleted]           BIT             NOT NULL,
    CONSTRAINT [PK_SalesOrderStockLineAudit] PRIMARY KEY CLUSTERED ([SOStockLineAuditId] ASC)
);

