CREATE TABLE [dbo].[ShippingBillingAddressAudit] (
    [SBAId]           BIGINT        IDENTITY (1, 1) NOT NULL,
    [ModuleId]        BIGINT        NOT NULL,
    [ReferenceId]     BIGINT        NOT NULL,
    [AddressId]       BIGINT        NOT NULL,
    [AddressType]     INT           NOT NULL,
    [MasterCompanyId] INT           NOT NULL,
    [IsPrimary]       BIT           NOT NULL,
    [SiteName]        VARCHAR (256) NULL,
    [Line1]           VARCHAR (50)  NULL,
    [Line2]           VARCHAR (50)  NULL,
    [City]            VARCHAR (50)  NULL,
    [StateOrProvince] VARCHAR (50)  NULL,
    [PostalCode]      VARCHAR (20)  NOT NULL,
    [CountryId]       SMALLINT      NOT NULL,
    [CreatedBy]       VARCHAR (256) NULL,
    [UpdatedBy]       VARCHAR (256) NULL,
    [CreatedDate]     DATETIME2 (7) NOT NULL,
    [UpdatedDate]     DATETIME2 (7) NOT NULL,
    [IsActive]        BIT           NULL,
    [IsDeleted]       BIT           CONSTRAINT [ShippingBillingAddressAudit_DC_Delete] DEFAULT ((0)) NOT NULL,
    [ContactTagId]    BIGINT        NULL,
    [Attention]       VARCHAR (250) NULL,
    CONSTRAINT [PK_ShippingBillingAddress] PRIMARY KEY CLUSTERED ([SBAId] ASC)
);

