CREATE TABLE [dbo].[SpeedQuoteSettingsAudit] (
    [SpeedQuoteSettingAuditId] BIGINT        IDENTITY (1, 1) NOT NULL,
    [SpeedQuoteSettingId]      BIGINT        NOT NULL,
    [QuoteTypeId]              INT           NOT NULL,
    [ValidDays]                INT           NOT NULL,
    [Prefix]                   VARCHAR (20)  NOT NULL,
    [Sufix]                    VARCHAR (20)  NOT NULL,
    [StartCode]                BIGINT        NOT NULL,
    [CurrentNumber]            BIGINT        NOT NULL,
    [DefaultStatusId]          INT           NOT NULL,
    [DefaultPriorityId]        BIGINT        NOT NULL,
    [SQListViewId]             INT           NOT NULL,
    [SQListStatusId]           INT           NOT NULL,
    [MasterCompanyId]          INT           NOT NULL,
    [CreatedBy]                VARCHAR (256) NOT NULL,
    [UpdatedBy]                VARCHAR (256) NOT NULL,
    [CreatedDate]              DATETIME2 (7) NOT NULL,
    [UpdatedDate]              DATETIME2 (7) NOT NULL,
    [IsActive]                 BIT           NOT NULL,
    [IsDeleted]                BIT           NOT NULL,
    [IsApprovalRule]           BIT           NULL,
    [EffectiveDate]            DATETIME2 (7) NULL,
    CONSTRAINT [PK_SpeedQuoteSettingsAudit] PRIMARY KEY CLUSTERED ([SpeedQuoteSettingAuditId] ASC)
);

