CREATE TABLE [dbo].[StockLineDraftAudit] (
    [StockLineDraftAuditId]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [StockLineDraftId]                    BIGINT          NOT NULL,
    [PartNumber]                          VARCHAR (50)    NOT NULL,
    [StockLineNumber]                     VARCHAR (50)    NULL,
    [StocklineMatchKey]                   VARCHAR (100)   NULL,
    [ControlNumber]                       VARCHAR (50)    NULL,
    [ItemMasterId]                        BIGINT          NULL,
    [Quantity]                            INT             NOT NULL,
    [ConditionId]                         BIGINT          NULL,
    [SerialNumber]                        VARCHAR (30)    NULL,
    [ShelfLife]                           BIT             NULL,
    [ShelfLifeExpirationDate]             DATETIME2 (7)   NULL,
    [WarehouseId]                         BIGINT          NULL,
    [LocationId]                          BIGINT          NULL,
    [ObtainFrom]                          BIGINT          NULL,
    [Owner]                               BIGINT          NULL,
    [TraceableTo]                         BIGINT          NULL,
    [ManufacturerId]                      BIGINT          NULL,
    [Manufacturer]                        VARCHAR (50)    NULL,
    [ManufacturerLotNumber]               VARCHAR (50)    NULL,
    [ManufacturingDate]                   DATETIME2 (7)   NULL,
    [ManufacturingBatchNumber]            VARCHAR (50)    NULL,
    [PartCertificationNumber]             VARCHAR (50)    NULL,
    [CertifiedBy]                         VARCHAR (100)   NULL,
    [CertifiedDate]                       DATETIME2 (7)   NULL,
    [TagDate]                             DATETIME2 (7)   NULL,
    [TagTypeIds]                          VARCHAR (MAX)   NULL,
    [TagType]                             VARCHAR (MAX)   NULL,
    [CertifiedDueDate]                    DATETIME2 (7)   NULL,
    [CalibrationMemo]                     NVARCHAR (MAX)  NULL,
    [OrderDate]                           DATETIME2 (7)   NULL,
    [PurchaseOrderId]                     BIGINT          NULL,
    [PurchaseOrderUnitCost]               DECIMAL (18, 2) NULL,
    [InventoryUnitCost]                   DECIMAL (18, 2) NULL,
    [RepairOrderId]                       BIGINT          NULL,
    [RepairOrderUnitCost]                 DECIMAL (18, 2) NULL,
    [ReceivedDate]                        DATETIME2 (7)   NULL,
    [ReceiverNumber]                      VARCHAR (50)    NULL,
    [ReconciliationNumber]                VARCHAR (50)    NULL,
    [UnitSalesPrice]                      DECIMAL (18, 2) NULL,
    [CoreUnitCost]                        DECIMAL (18, 2) NULL,
    [GLAccountId]                         BIGINT          NULL,
    [AssetId]                             BIGINT          NULL,
    [IsHazardousMaterial]                 BIT             NULL,
    [IsPMA]                               BIT             NULL,
    [IsDER]                               BIT             NULL,
    [OEM]                                 BIT             NULL,
    [Memo]                                NVARCHAR (MAX)  NULL,
    [ManagementStructureEntityId]         BIGINT          NULL,
    [LegalEntityId]                       BIGINT          NULL,
    [MasterCompanyId]                     INT             NOT NULL,
    [CreatedBy]                           VARCHAR (256)   NOT NULL,
    [UpdatedBy]                           VARCHAR (256)   NOT NULL,
    [CreatedDate]                         DATETIME2 (7)   CONSTRAINT [DF_StockLineDraftAudit_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                         DATETIME2 (7)   CONSTRAINT [DF_StockLineDraftAudit_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [isSerialized]                        BIT             NULL,
    [ShelfId]                             BIGINT          NULL,
    [BinId]                               BIGINT          NULL,
    [SiteId]                              BIGINT          NULL,
    [ObtainFromType]                      INT             NULL,
    [OwnerType]                           INT             NULL,
    [TraceableToType]                     INT             NULL,
    [UnitCostAdjustmentReasonTypeId]      INT             NULL,
    [UnitSalePriceAdjustmentReasonTypeId] INT             NULL,
    [IdNumber]                            VARCHAR (100)   NULL,
    [QuantityToReceive]                   INT             NOT NULL,
    [PurchaseOrderExtendedCost]           DECIMAL (18)    CONSTRAINT [DF_StockLineDraftAudit_PurchaseOrderExtendedCost] DEFAULT ((0)) NOT NULL,
    [ManufacturingTrace]                  NVARCHAR (200)  NULL,
    [ExpirationDate]                      DATETIME2 (7)   NULL,
    [AircraftTailNumber]                  NVARCHAR (200)  NULL,
    [ShippingViaId]                       BIGINT          NULL,
    [EngineSerialNumber]                  NVARCHAR (200)  NULL,
    [QuantityRejected]                    INT             CONSTRAINT [DF_StockLineDraftAudit_QuantityRejected] DEFAULT ((0)) NOT NULL,
    [PurchaseOrderPartRecordId]           BIGINT          NULL,
    [ShippingAccount]                     NVARCHAR (200)  NULL,
    [ShippingReference]                   NVARCHAR (200)  NULL,
    [TimeLifeCyclesId]                    BIGINT          NULL,
    [TimeLifeDetailsNotProvided]          BIT             CONSTRAINT [DF_StockLineDraftAudit_TimeLifeDetailsNotProvided] DEFAULT ((0)) NOT NULL,
    [WorkOrderId]                         BIGINT          NULL,
    [WorkOrderMaterialsId]                BIGINT          NULL,
    [QuantityReserved]                    INT             NULL,
    [QuantityTurnIn]                      INT             NULL,
    [QuantityIssued]                      INT             NULL,
    [QuantityOnHand]                      INT             NULL,
    [QuantityAvailable]                   INT             NULL,
    [QuantityOnOrder]                     INT             NULL,
    [QtyReserved]                         INT             NULL,
    [QtyIssued]                           INT             NULL,
    [BlackListed]                         BIT             CONSTRAINT [DF_StockLineDraftAudit_BlackListed] DEFAULT ((0)) NOT NULL,
    [BlackListedReason]                   VARCHAR (500)   NULL,
    [Incident]                            BIT             CONSTRAINT [DF_StockLineDraftAudit_Incident] DEFAULT ((0)) NOT NULL,
    [IncidentReason]                      VARCHAR (500)   NULL,
    [Accident]                            BIT             CONSTRAINT [DF_StockLineDraftAudit_Accident] DEFAULT ((0)) NOT NULL,
    [AccidentReason]                      VARCHAR (500)   NULL,
    [RepairOrderPartRecordId]             BIGINT          NULL,
    [isActive]                            BIT             CONSTRAINT [DF_StockLineDraftAudit_isActive] DEFAULT ((1)) NOT NULL,
    [isDeleted]                           BIT             CONSTRAINT [DF_StockLineDraftAudit_isDeleted] DEFAULT ((0)) NOT NULL,
    [WorkOrderExtendedCost]               DECIMAL (20, 2) NOT NULL,
    [RepairOrderExtendedCost]             DECIMAL (18, 2) NULL,
    [NHAItemMasterId]                     BIGINT          NULL,
    [TLAItemMasterId]                     BIGINT          NULL,
    [IsParent]                            BIT             NULL,
    [ParentId]                            BIGINT          NULL,
    [IsSameDetailsForAllParts]            BIT             NULL,
    [Level1]                              VARCHAR (200)   NULL,
    [Level2]                              VARCHAR (200)   NULL,
    [Level3]                              VARCHAR (200)   NULL,
    [Level4]                              VARCHAR (200)   NULL,
    [Condition]                           VARCHAR (250)   NULL,
    [Warehouse]                           VARCHAR (250)   NULL,
    [Location]                            VARCHAR (250)   NULL,
    [ObtainFromName]                      VARCHAR (250)   NULL,
    [OwnerName]                           VARCHAR (250)   NULL,
    [TraceableToName]                     VARCHAR (250)   NULL,
    [GLAccount]                           VARCHAR (250)   NULL,
    [AssetName]                           VARCHAR (250)   NULL,
    [LegalEntityName]                     VARCHAR (250)   NULL,
    [ShelfName]                           VARCHAR (250)   NULL,
    [BinName]                             VARCHAR (250)   NULL,
    [SiteName]                            VARCHAR (250)   NULL,
    [ObtainFromTypeName]                  VARCHAR (250)   NULL,
    [OwnerTypeName]                       VARCHAR (250)   NULL,
    [TraceableToTypeName]                 VARCHAR (250)   NULL,
    [UnitCostAdjustmentReasonType]        VARCHAR (250)   NULL,
    [UnitSalePriceAdjustmentReasonType]   VARCHAR (250)   NULL,
    [ShippingVia]                         VARCHAR (250)   NULL,
    [WorkOrder]                           VARCHAR (250)   NULL,
    [WorkOrderMaterialsName]              VARCHAR (250)   NULL,
    [TagTypeId]                           BIGINT          NULL,
    [StockLineDraftNumber]                VARCHAR (250)   NULL,
    [StockLineId]                         BIGINT          NULL,
    [TaggedBy]                            BIGINT          NULL,
    [TaggedByName]                        VARCHAR (250)   NULL,
    [UnitOfMeasureId]                     BIGINT          NULL,
    [UnitOfMeasure]                       VARCHAR (250)   NULL,
    [RevisedPartId]                       BIGINT          NULL,
    [RevisedPartNumber]                   VARCHAR (250)   NULL,
    [TaggedByType]                        INT             NULL,
    [TaggedByTypeName]                    VARCHAR (250)   NULL,
    [CertifiedById]                       BIGINT          NULL,
    [CertifiedTypeId]                     INT             NULL,
    [CertifiedType]                       VARCHAR (250)   NULL,
    [CertTypeId]                          VARCHAR (MAX)   NULL,
    [CertType]                            VARCHAR (MAX)   NULL,
    [IsCustomerStock]                     BIT             DEFAULT ((0)) NULL,
    [isCustomerstockType]                 BIT             NULL,
    [CustomerId]                          BIGINT          NULL,
    [CalibrationVendorId]                 BIGINT          NULL,
    [PerformedById]                       BIGINT          NULL,
    [LastCalibrationDate]                 DATETIME        NULL,
    [NextCalibrationDate]                 DATETIME        NULL,
    [LotId]                               BIGINT          NULL,
    [SalesOrderId]                        BIGINT          NULL,
    [SubWorkOrderId]                      BIGINT          NULL,
    [ExchangeSalesOrderId]                BIGINT          NULL,
    [WOQty]                               INT             NULL,
    [SOQty]                               INT             NULL,
    [ForStockQty]                         INT             NULL,
    [IsLotAssigned]                       BIT             NULL,
    [LOTQty]                              INT             NULL,
    [LOTQtyReserve]                       INT             NULL,
    [OriginalCost]                        DECIMAL (18, 2) NULL,
    [POOriginalCost]                      DECIMAL (18, 2) NULL,
    [ROOriginalCost]                      DECIMAL (18, 2) NULL,
    [VendorRMAId]                         BIGINT          NULL,
    [VendorRMADetailId]                   BIGINT          NULL,
    [LotMainStocklineId]                  BIGINT          NULL,
    [IsFromInitialPO]                     BIT             NULL,
    [LotSourceId]                         INT             NULL,
    [Adjustment]                          DECIMAL (18, 2) NULL,
    [SerialNumberNotProvided]             BIT             NULL,
    [ShippingReferenceNumberNotProvided]  BIT             NULL,
    [IsStkTimeLife]                       BIT             NULL,
    [SalesPriceExpiryDate]                DATETIME2 (7)   NULL,
    CONSTRAINT [PK_StockLineDraftAudit] PRIMARY KEY CLUSTERED ([StockLineDraftAuditId] ASC)
);

