

CREATE   FUNCTION GetSpace(@TotalString INT ,@StingLength INT)
RETURNS INT
AS
BEGIN
	DECLARE @SPACECOUNT AS MONEY
	SELECT @SPACECOUNT = (@TotalString - @StingLength)
	IF(@SPACECOUNT < 0) 
	BEGIN
		SELECT @SPACECOUNT = 0;
	END	
	RETURN @SPACECOUNT;
END