CREATE TABLE [dbo].[AircraftInstalledPartDetails] (
    [AircraftInstalledPartDetailsId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [AircraftRegistryId]             BIGINT          NOT NULL,
    [ATAChapterId]                   BIGINT          NOT NULL,
    [ItemMasterId]                   BIGINT          NOT NULL,
    [PartNumber]                     VARCHAR (50)    NULL,
    [PartDescription]                NVARCHAR (MAX)  NULL,
    [IsLLP]                          BIT             DEFAULT ((0)) NOT NULL,
    [IsSerialized]                   BIT             DEFAULT ((0)) NOT NULL,
    [SerialNumber]                   VARCHAR (100)   NULL,
    [DateInstalled]                  DATETIME2 (7)   NULL,
    [PositionCode]                   VARCHAR (256)   NULL,
    [Hours]                          DECIMAL (18, 2) NULL,
    [Minutes]                        DECIMAL (18, 2) NULL,
    [FlightHours]                    DECIMAL (18, 2) NULL,
    [Cycles]                         DECIMAL (18, 2) NULL,
    [Landings]                       BIGINT          NULL,
    [EngineStarts]                   BIGINT          NULL,
    [Memo]                           NVARCHAR (MAX)  NULL,
    [MasterCompanyId]                INT             NOT NULL,
    [CreatedBy]                      VARCHAR (256)   NOT NULL,
    [UpdatedBy]                      VARCHAR (256)   NOT NULL,
    [CreatedDate]                    DATETIME2 (7)   DEFAULT (getutcdate()) NOT NULL,
    [UpdatedDate]                    DATETIME2 (7)   NOT NULL,
    [IsActive]                       BIT             DEFAULT ((1)) NOT NULL,
    [IsDeleted]                      BIT             DEFAULT ((0)) NOT NULL,
    [StockLineId]                    BIGINT          NULL,
    [ConditionId]                    BIGINT          NULL,
    [Quantity]                       DECIMAL (18, 6) NULL,
    [PositionCodeId]                 BIGINT          NULL,
    PRIMARY KEY CLUSTERED ([AircraftInstalledPartDetailsId] ASC),
    CONSTRAINT [FK_AircraftInstalledPartDetails_AircraftRegistryId] FOREIGN KEY ([AircraftRegistryId]) REFERENCES [dbo].[AircraftRegistryHeader] ([AircraftRegistryId]),
    CONSTRAINT [FK_AircraftInstalledPartDetails_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId])
);

