CREATE TABLE [dbo].[AircraftEffectivity] (
    [AircraftEffectivityId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [AircraftPublicationId] BIGINT         NOT NULL,
    [MakeTypeId]            BIGINT         NOT NULL,
    [MakeType]              VARCHAR (100)  NULL,
    [AircraftModelId]       BIGINT         NULL,
    [AircraftModel]         VARCHAR (100)  NULL,
    [AircraftSubModel]      VARCHAR (100)  NULL,
    [SerialNum]             VARCHAR (100)  NULL,
    [ItemMasterId]          BIGINT         NOT NULL,
    [PartNumber]            VARCHAR (50)   NULL,
    [PartDescription]       NVARCHAR (MAX) NULL,
    [Notes]                 VARCHAR (MAX)  NULL,
    [MasterCompanyId]       INT            NOT NULL,
    [CreatedBy]             VARCHAR (256)  NOT NULL,
    [UpdatedBy]             VARCHAR (256)  NOT NULL,
    [CreatedDate]           DATETIME2 (7)  CONSTRAINT [DF_AE_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedDate]           DATETIME2 (7)  CONSTRAINT [DF_AE_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]              BIT            CONSTRAINT [DF_AE_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]             BIT            CONSTRAINT [DF_AE_IsDeleted] DEFAULT ((0)) NOT NULL,
    [ComplianceDate]        DATETIME2 (7)  NULL,
    [Ractification]         VARCHAR (256)  NULL,
    [ACPSectionId]          BIGINT         NULL,
    [ComponentSerialNum]    VARCHAR (100)  NULL,
    [ComponentToSerialNum]  VARCHAR (100)  NULL,
    CONSTRAINT [PK_AircraftEffectivity] PRIMARY KEY CLUSTERED ([AircraftEffectivityId] ASC),
    CONSTRAINT [FK_AE_AircraftPublication] FOREIGN KEY ([AircraftPublicationId]) REFERENCES [dbo].[AircraftPublication] ([AircraftPublicationId]),
    CONSTRAINT [FK_AE_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId])
);

