CREATE TABLE [dbo].[BillingInvoicingItems] (
    [BillingInvoicingItemId]      BIGINT          IDENTITY (1, 1) NOT NULL,
    [BillingInvoicingId]          BIGINT          NOT NULL,
    [ModuleId]                    INT             NOT NULL,
    [ReferenceId]                 BIGINT          NOT NULL,
    [SubModuleId]                 INT             NOT NULL,
    [SubReferenceId]              BIGINT          NOT NULL,
    [ItemMasterId]                BIGINT          NOT NULL,
    [StocklineId]                 BIGINT          NULL,
    [ConditionId]                 BIGINT          NULL,
    [CostPlusType]                VARCHAR (50)    NULL,
    [UnitPrice]                   DECIMAL (18, 6) NULL,
    [QtyBilled]                   DECIMAL (18, 6) NULL,
    [PartCost]                    DECIMAL (18, 6) NULL,
    [IsTotalCheck]                BIT             NULL,
    [TotalBillingCost]            DECIMAL (18, 6) NULL,
    [TotalBillingCostPercent]     BIGINT          NULL,
    [TotalBillingCostPlus]        DECIMAL (18, 6) NULL,
    [IsMaterialCheck]             BIT             NULL,
    [MaterialCost]                DECIMAL (18, 6) NULL,
    [MaterialCostPercent]         BIGINT          NULL,
    [MaterialCostPlus]            DECIMAL (18, 6) NULL,
    [IsLaborCheck]                BIT             NULL,
    [LaborCost]                   DECIMAL (18, 6) NULL,
    [LaborCostPercent]            BIGINT          NULL,
    [LaborCostPlus]               DECIMAL (18, 6) NULL,
    [IsFreightCheck]              BIT             NULL,
    [Freight]                     DECIMAL (18, 6) NULL,
    [FreightCostPercent]          BIGINT          NULL,
    [FreightCostPlus]             DECIMAL (18, 6) NULL,
    [IsMiscChargesCheck]          BIT             NULL,
    [MiscCharges]                 DECIMAL (18, 6) NULL,
    [MiscChargesCostPercent]      BIGINT          NULL,
    [MiscChargesCostPlus]         DECIMAL (18, 6) NULL,
    [SubTotal]                    DECIMAL (18, 6) NULL,
    [SalesTaxPercent]             BIGINT          NULL,
    [SalesTax]                    DECIMAL (18, 6) NULL,
    [OtherTaxPercent]             BIGINT          NULL,
    [OtherTax]                    DECIMAL (18, 6) NULL,
    [GrandTotal]                  DECIMAL (18, 6) NULL,
    [DepositAmount]               DECIMAL (18, 6) NULL,
    [RemainingAmount]             DECIMAL (18, 6) NULL,
    [PDFPath]                     NVARCHAR (MAX)  NULL,
    [VersionNo]                   VARCHAR (20)    NULL,
    [IsVersionIncrease]           BIT             CONSTRAINT [DF_BillingInvoicingItems_IsVersionIncrease] DEFAULT ((0)) NULL,
    [IsPerformaInvoice]           BIT             CONSTRAINT [DF_BillingInvoicingItems_IsPerformaInvoice] DEFAULT ((0)) NULL,
    [MasterCompanyId]             INT             NOT NULL,
    [CreatedBy]                   VARCHAR (256)   NOT NULL,
    [UpdatedBy]                   VARCHAR (256)   NOT NULL,
    [CreatedDate]                 DATETIME2 (7)   CONSTRAINT [DF_BillingInvoicingItems_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedDate]                 DATETIME2 (7)   CONSTRAINT [DF_BillingInvoicingItems_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]                    BIT             CONSTRAINT [DF_BillingInvoicingItems_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                   BIT             CONSTRAINT [DF_BillingInvoicingItems_IsDeleted] DEFAULT ((0)) NOT NULL,
    [ShippingId]                  BIGINT          NULL,
    [WorkFlowWorkOrderId]         BIGINT          NULL,
    [OldBillingInvoicingId]       BIGINT          NULL,
    [OldWOBillingInvoicingItemId] BIGINT          NULL,
    [ShipDate]                    DATETIME2 (7)   NULL,
    [SerialNumber]                VARCHAR (256)   NULL,
    CONSTRAINT [PK_BillingInvoicingItems] PRIMARY KEY CLUSTERED ([BillingInvoicingItemId] ASC),
    CONSTRAINT [FK_BillingInvoicingItems_BillingInvoicing] FOREIGN KEY ([BillingInvoicingId]) REFERENCES [dbo].[BillingInvoicing] ([BillingInvoicingId])
);
GO
CREATE NONCLUSTERED INDEX [IX_BillingInvoicingItems_BillingInvoicingId_SubReferenceId]
    ON [dbo].[BillingInvoicingItems]([BillingInvoicingId] ASC, [SubReferenceId] ASC)
    INCLUDE([ModuleId], [IsPerformaInvoice]) WITH (FILLFACTOR = 90, DATA_COMPRESSION = PAGE);
-- Added 2026-08-11: supports USP_Lot_GetAllLotViewsByLotId_Filter's LEFT JOIN
-- "sop.SalesOrderPartId = sobii.SubReferenceId AND sobi.BillingInvoicingId = sobii.BillingInvoicingId"
-- (see UOM_USP_Lot_GetAllLotViewsByLotId_Filter_Deploy.sql for the full review).

