CREATE TABLE [dbo].[BillingInvoicingItems] (
    [BillingInvoicingItemId]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [BillingInvoicingId]      BIGINT          NOT NULL,
    [ModuleId]                INT             NOT NULL,
    [ReferenceId]             BIGINT          NOT NULL,
    [SubModuleId]             INT             NOT NULL,
    [SubReferenceId]          BIGINT          NOT NULL,
    [ItemMasterId]            BIGINT          NOT NULL,
    [StocklineId]             BIGINT          NULL,
    [ConditionId]             BIGINT          NULL,
    [CostPlusType]            VARCHAR (50)    NULL,
    [UnitPrice]               DECIMAL (18, 2) NULL,
    [QtyBilled]               INT             NULL,
    [PartCost]                DECIMAL (18, 2) NULL,
    [IsTotalCheck]            BIT             NULL,
    [TotalBillingCost]        DECIMAL (18, 2) NULL,
    [TotalBillingCostPercent] BIGINT          NULL,
    [TotalBillingCostPlus]    DECIMAL (18)    NULL,
    [IsMaterialCheck]         BIT             NULL,
    [MaterialCost]            DECIMAL (18, 2) NULL,
    [MaterialCostPercent]     BIGINT          NULL,
    [MaterialCostPlus]        DECIMAL (18, 2) NULL,
    [IsLaborCheck]            BIT             NULL,
    [LaborCost]               DECIMAL (18, 2) NULL,
    [LaborCostPercent]        BIGINT          NULL,
    [LaborCostPlus]           DECIMAL (18, 2) NULL,
    [IsFreightCheck]          BIT             NULL,
    [Freight]                 DECIMAL (18, 2) NULL,
    [FreightCostPercent]      BIGINT          NULL,
    [FreightCostPlus]         DECIMAL (18, 2) NULL,
    [IsMiscChargesCheck]      BIT             NULL,
    [MiscCharges]             DECIMAL (18, 2) NULL,
    [MiscChargesCostPercent]  BIGINT          NULL,
    [MiscChargesCostPlus]     DECIMAL (18, 2) NULL,
    [SubTotal]                DECIMAL (18, 2) NULL,
    [SalesTaxPercent]         BIGINT          NULL,
    [SalesTax]                DECIMAL (18, 2) NULL,
    [OtherTaxPercent]         BIGINT          NULL,
    [OtherTax]                DECIMAL (18, 2) NULL,
    [GrandTotal]              DECIMAL (18, 2) NULL,
    [PDFPath]                 NVARCHAR (MAX)  NULL,
    [VersionNo]               VARCHAR (20)    NULL,
    [IsVersionIncrease]       BIT             CONSTRAINT [DF_BillingInvoicingItems_IsVersionIncrease] DEFAULT ((0)) NULL,
    [IsPerformaInvoice]       BIT             CONSTRAINT [DF_BillingInvoicingItems_IsPerformaInvoice] DEFAULT ((0)) NULL,
    [MasterCompanyId]         INT             NOT NULL,
    [CreatedBy]               VARCHAR (256)   NOT NULL,
    [UpdatedBy]               VARCHAR (256)   NOT NULL,
    [CreatedDate]             DATETIME2 (7)   CONSTRAINT [DF_BillingInvoicingItems_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   CONSTRAINT [DF_BillingInvoicingItems_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]                BIT             CONSTRAINT [DF_BillingInvoicingItems_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]               BIT             CONSTRAINT [DF_BillingInvoicingItems_IsDeleted] DEFAULT ((0)) NOT NULL,
    [ShippingId]              BIGINT          NULL,
    CONSTRAINT [PK_BillingInvoicingItems] PRIMARY KEY CLUSTERED ([BillingInvoicingItemId] ASC),
    CONSTRAINT [FK_BillingInvoicingItems_BillingInvoicing] FOREIGN KEY ([BillingInvoicingId]) REFERENCES [dbo].[BillingInvoicing] ([BillingInvoicingId])
);

