CREATE TABLE [dbo].[BillingInvoicing] (
    [BillingInvoicingId]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [ModuleId]                    INT             NOT NULL,
    [ReferenceId]                 BIGINT          NOT NULL,
    [CustomerId]                  BIGINT          NULL,
    [InvoiceTypeId]               INT             NOT NULL,
    [InvoiceNo]                   VARCHAR (256)   NOT NULL,
    [InvoiceDate]                 DATETIME2 (7)   NULL,
    [InvoiceTime]                 VARCHAR (10)    NULL,
    [PrintDate]                   DATETIME2 (7)   NULL,
    [EmployeeId]                  BIGINT          NOT NULL,
    [CurrencyId]                  INT             NULL,
    [RevisionTypeId]              BIGINT          NULL,
    [InvoiceStatusId]             INT             NULL,
    [InvoiceStatus]               VARCHAR (50)    NULL,
    [InvoiceFilePath]             VARCHAR (1000)  NULL,
    [RevType]                     VARCHAR (200)   NULL,
    [VersionNo]                   VARCHAR (10)    NULL,
    [CostPlusType]                VARCHAR (50)    NULL,
    [IsPerformaInvoice]           BIT             CONSTRAINT [DF_BillingInvoicing_IsPerformaInvoice] DEFAULT ((0)) NULL,
    [IsVersionIncrease]           BIT             CONSTRAINT [DF_BillingInvoicing_IsVersionIncrease] DEFAULT ((0)) NULL,
    [PostedDate]                  DATETIME2 (7)   NULL,
    [SubTotal]                    DECIMAL (18, 6) CONSTRAINT [DF_BillingInvoicing_SubTotal] DEFAULT ((0)) NULL,
    [OtherTax]                    DECIMAL (18, 6) CONSTRAINT [DF_BillingInvoicing_OtherTax] DEFAULT ((0)) NULL,
    [SalesTax]                    DECIMAL (18, 6) CONSTRAINT [DF_BillingInvoicing_SalesTax] DEFAULT ((0)) NULL,
    [DepositAmount]               DECIMAL (18, 6) NULL,
    [GrandTotal]                  DECIMAL (18, 6) NULL,
    [IsInvoicePosted]             BIT             CONSTRAINT [DF__BillingIn__IsInv__4FAC7CA0] DEFAULT ((0)) NULL,
    [UsedDeposit]                 DECIMAL (18, 6) CONSTRAINT [DF__BillingIn__UsedD__50A0A0D9] DEFAULT ((0)) NULL,
    [ProformaDeposit]             DECIMAL (18, 6) CONSTRAINT [DF__BillingIn__Profo__5194C512] DEFAULT ((0)) NULL,
    [RemainingAmount]             DECIMAL (18, 6) NULL,
    [Notes]                       NVARCHAR (MAX)  NULL,
    [WorkOrderShippingId]         BIGINT          NULL,
    [ManagementStructureId]       BIGINT          NOT NULL,
    [MasterCompanyId]             INT             NOT NULL,
    [CreatedBy]                   VARCHAR (256)   NOT NULL,
    [UpdatedBy]                   VARCHAR (256)   NOT NULL,
    [CreatedDate]                 DATETIME2 (7)   CONSTRAINT [DF_BillingInvoicing_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedDate]                 DATETIME2 (7)   CONSTRAINT [DF_BillingInvoicing_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]                    BIT             CONSTRAINT [DF_BillingInvoicing_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                   BIT             CONSTRAINT [DF_BillingInvoicing_IsDeleted] DEFAULT ((0)) NOT NULL,
    [IsReversedJE]                BIT             CONSTRAINT [DF_BillingInvoicing_IsReversedJE] DEFAULT ((0)) NULL,
    [QuickBooksReferenceId]       VARCHAR (200)   NULL,
    [IsUpdated]                   BIT             CONSTRAINT [DF_BillingInvoicing_IsUpdated] DEFAULT ((0)) NULL,
    [LastSyncDate]                DATETIME2 (7)   NULL,
    [SyncToken]                   VARCHAR (200)   NULL,
    [IsCreatedFromQuote]          BIT             CONSTRAINT [DF_BillingInvoicing_IsCreatedFromQuote] DEFAULT ((0)) NULL,
    [IsQuickBookGeneratedInvoice] BIT             NULL,
    [OldBillingInvoicingId]       BIGINT          NULL,
    [CreditMemoUsed]              DECIMAL (18, 6) CONSTRAINT [DF__BillingIn__Credi__55BA5BB1] DEFAULT ((0)) NULL,
    [OriginCountryId]             INT             NULL,
    [ShipToCountryId]             INT             NULL,
    [SignEmpId]                   BIGINT          NULL,
    [SignEmpDate]                 DATETIME2 (7)   NULL,
    [IsStandardInvoicePosted]     BIT             NULL,
    [CreditMemoHeaderId]          BIGINT          NULL,
    [IntegrationTypeId]           INT             NULL,
    CONSTRAINT [PK_BillingInvoicing] PRIMARY KEY CLUSTERED ([BillingInvoicingId] ASC)
);
GO
CREATE NONCLUSTERED INDEX [IX_BillingInvoicing_ReferenceId_ModuleId]
    ON [dbo].[BillingInvoicing]([ReferenceId] ASC, [ModuleId] ASC)
    INCLUDE([InvoiceNo], [InvoiceDate], [IsVersionIncrease], [IsPerformaInvoice], [MasterCompanyId]) WITH (FILLFACTOR = 90, DATA_COMPRESSION = PAGE);
-- Added 2026-08-11: supports USP_Lot_GetAllLotViewsByLotId_Filter's LEFT JOIN
-- "so.SalesOrderId = sobi.ReferenceId ... AND sobi.ModuleId = @SOModuleId" (see
-- UOM_USP_Lot_GetAllLotViewsByLotId_Filter_Deploy.sql for the full review).

