CREATE TABLE [dbo].[CycleCountApprovalAudit] (
    [CycleCountApprovalAuditId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [CycleCountApprovalId]      BIGINT         NOT NULL,
    [CycleCountId]              BIGINT         NOT NULL,
    [CycleCountDetailId]        BIGINT         NOT NULL,
    [InternalSentToId]          BIGINT         NULL,
    [InternalSentToName]        VARCHAR (100)  NULL,
    [InternalSentById]          BIGINT         NULL,
    [SentDate]                  DATETIME2 (7)  NULL,
    [ApprovedDate]              DATETIME2 (7)  NULL,
    [ApprovedById]              BIGINT         NULL,
    [ApprovedByName]            VARCHAR (200)  NULL,
    [RejectedDate]              DATETIME2 (7)  NULL,
    [RejectedBy]                BIGINT         NULL,
    [RejectedByName]            VARCHAR (200)  NULL,
    [StatusId]                  INT            NULL,
    [StatusName]                VARCHAR (50)   NULL,
    [ActionId]                  INT            NULL,
    [Memo]                      NVARCHAR (MAX) NULL,
    [MasterCompanyId]           INT            NOT NULL,
    [CreatedBy]                 VARCHAR (256)  NOT NULL,
    [UpdatedBy]                 VARCHAR (256)  NOT NULL,
    [CreatedDate]               DATETIME2 (7)  NOT NULL,
    [UpdatedDate]               DATETIME2 (7)  NOT NULL,
    [IsActive]                  BIT            CONSTRAINT [DF_CycleCountApprovalAudit_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                 BIT            CONSTRAINT [DF_CycleCountApprovalAudit_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_CycleCountApprovalAudit] PRIMARY KEY CLUSTERED ([CycleCountApprovalAuditId] ASC)
);

