CREATE TABLE [dbo].[CycleCountDetailAudit] (
    [CycleCountDetailAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [CycleCountDetailId]      BIGINT          NOT NULL,
    [CycleCountId]            BIGINT          NOT NULL,
    [StockLineId]             BIGINT          NOT NULL,
    [StockLineNumber]         VARCHAR (50)    NOT NULL,
    [ControlNumber]           VARCHAR (50)    NOT NULL,
    [IdNumber]                VARCHAR (50)    NULL,
    [SerialNumber]            VARCHAR (50)    NULL,
    [ItemMasterId]            BIGINT          NOT NULL,
    [PartNumber]              VARCHAR (50)    NOT NULL,
    [PartDescription]         NVARCHAR (MAX)  NULL,
    [ManufacturerId]          BIGINT          NULL,
    [ManufacturerName]        VARCHAR (100)   NULL,
    [ConditionId]             BIGINT          NOT NULL,
    [ConditionName]           VARCHAR (50)    NULL,
    [UnitOfMeasureId]         BIGINT          NOT NULL,
    [UnitOfMeasureName]       VARCHAR (50)    NULL,
    [UnitCost]                DECIMAL (18, 2) NULL,
    [CurrencyId]              BIGINT          NULL,
    [CurrencyName]            VARCHAR (50)    NULL,
    [SiteId]                  BIGINT          NOT NULL,
    [Site]                    VARCHAR (50)    NULL,
    [WarehouseId]             BIGINT          NULL,
    [Warehouse]               VARCHAR (50)    NULL,
    [LocationId]              BIGINT          NULL,
    [Location]                VARCHAR (50)    NULL,
    [ShelfId]                 BIGINT          NULL,
    [Shelf]                   VARCHAR (50)    NULL,
    [BinId]                   BIGINT          NULL,
    [Bin]                     VARCHAR (50)    NULL,
    [CurrentStockQuantity]    INT             NOT NULL,
    [CountedQuantity]         INT             NOT NULL,
    [DifferenceQuantity]      INT             NOT NULL,
    [DifferenceAmount]        DECIMAL (18, 2) NOT NULL,
    [IsCustomerStock]         BIT             NULL,
    [ManagementStructureId]   BIGINT          NOT NULL,
    [LegalEntityId]           BIGINT          NULL,
    [MasterCompanyId]         INT             NOT NULL,
    [CreatedBy]               VARCHAR (256)   NOT NULL,
    [UpdatedBy]               VARCHAR (256)   NOT NULL,
    [CreatedDate]             DATETIME2 (7)   CONSTRAINT [DF_CycleCountDetailAudit_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   CONSTRAINT [DF_CycleCountDetailAudit_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                BIT             CONSTRAINT [DF_CycleCountDetailAudit_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]               BIT             CONSTRAINT [DF_CycleCountDetailAudit_IsDeleted] DEFAULT ((0)) NOT NULL,
    [AdjustmentReasonId]      BIGINT          NULL,
    CONSTRAINT [PK_CycleCountDetailAudit] PRIMARY KEY CLUSTERED ([CycleCountDetailAuditId] ASC)
);

