CREATE TABLE [dbo].[ILSRFQPart] (
    [ILSRFQPartId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [ILSRFQDetailId]  BIGINT          NULL,
    [PartNumber]      VARCHAR (70)    NULL,
    [AltPartNumber]   VARCHAR (70)    NULL,
    [Exchange]        VARCHAR (70)    NULL,
    [Description]     VARCHAR (MAX)   NULL,
    [Qty]             DECIMAL (18, 6) NULL,
    [RequestedQty]    DECIMAL (18, 6) NULL,
    [Condition]       VARCHAR (20)    NULL,
    [IsEmail]         BIT             NULL,
    [IsFax]           BIT             NULL,
    [MasterCompanyId] INT             NOT NULL,
    [CreatedBy]       VARCHAR (256)   NULL,
    [UpdatedBy]       VARCHAR (256)   NULL,
    [CreatedDate]     DATETIME2 (7)   CONSTRAINT [DF_ILSRFQPart_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]     DATETIME2 (7)   CONSTRAINT [DF_ILSRFQPart_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsDeleted]       BIT             CONSTRAINT [DF_ILSRFQPart_IsDeleted] DEFAULT ((0)) NULL,
    [IsActive]        BIT             CONSTRAINT [DF_ILSRFQPart_IsActive] DEFAULT ((0)) NULL,
    [VendorName]      VARCHAR (150)   NULL,
    [CustomerRfqId]   BIGINT          NULL,
    [Address1]        VARCHAR (250)   NULL,
    [Address2]        VARCHAR (250)   NULL,
    [City]            VARCHAR (50)    NULL,
    [StateProvince]   VARCHAR (50)    NULL,
    [PostalCode]      VARCHAR (50)    NULL,
    [Country]         VARCHAR (50)    NULL,
    CONSTRAINT [PK_ILSRFQPart] PRIMARY KEY CLUSTERED ([ILSRFQPartId] ASC),
    CONSTRAINT [FK_ILSRFQPart_ILSRFQDetail] FOREIGN KEY ([ILSRFQDetailId]) REFERENCES [dbo].[ILSRFQDetail] ([ILSRFQDetailId])
);

