CREATE TABLE [dbo].[ImportModuleFieldMaster] (
    [ImportModuleFieldMasterId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [ModuleId]                  BIGINT         NOT NULL,
    [FieldName]                 VARCHAR (100)  NOT NULL,
    [HeaderName]                VARCHAR (100)  NOT NULL,
    [FieldWidth]                VARCHAR (10)   NOT NULL,
    [FieldType]                 VARCHAR (50)   NULL,
    [FieldAlign]                INT            NULL,
    [FieldSortOrder]            INT            NULL,
    [FieldExcelWidth]           DECIMAL (9, 2) NULL,
    [DropdownListType]          VARCHAR (100)  NULL,
    [DropdownListTable]         VARCHAR (100)  NULL,
    [DropdownListId]            VARCHAR (100)  NULL,
    [DropdownListValue]         VARCHAR (100)  NULL,
    [DropdownListValueId]       VARCHAR (100)  NULL,
    [IsAutoGenerate]            BIT            CONSTRAINT [DF__ImportModuleFieldMaster__IsAutoGenerate] DEFAULT ((0)) NULL,
    [IsModuleTableColumn]       BIT            NULL,
    [IsMultiValue]              BIT            NULL,
    [IsToolTipShow]             BIT            NULL,
    [IsRequired]                BIT            NULL,
    [IsEditable]                BIT            NULL,
    [ParentTableRereneceTypeId] NVARCHAR (MAX) NULL,
    [ChildTableRereneceTypeId]  NVARCHAR (MAX) NULL,
    [MasterCompanyId]           INT            NOT NULL,
    [CreatedBy]                 VARCHAR (50)   NOT NULL,
    [CreatedDate]               DATETIME2 (7)  CONSTRAINT [DF_ImportModuleFieldMaster_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedBy]                 VARCHAR (50)   NOT NULL,
    [UpdatedDate]               DATETIME2 (7)  CONSTRAINT [DF_ImportModuleFieldMaster_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]                  BIT            CONSTRAINT [DF__ImportModuleFieldMaster__IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                 BIT            CONSTRAINT [DF__ImportModuleFieldMaster__IsDeleted] DEFAULT ((0)) NOT NULL,
    [ReferenceColumn]           VARCHAR (150)  NULL,
    [IsChekColumnReference]     BIT            NULL,
    [ChekDuplticateRef1]        VARCHAR (150)  NULL,
    [ChekDuplticateRef2]        VARCHAR (150)  NULL,
    [DisplaySortOrder]          INT            NULL,
    [SourceTableName]           VARCHAR (150)  NULL,
    [SourceColumnName]          VARCHAR (150)  NULL,
    [JoinCondition]             VARCHAR (MAX)  NULL,
    [IsMultipleRows]            BIT            DEFAULT ((0)) NOT NULL,
    [MultiValueQuery]           NVARCHAR (MAX) NULL,
    [IsUseJoinCondition]        BIT            CONSTRAINT [DF_ImportModuleFieldMaster_IsUseJoinCondition] DEFAULT ((0)) NULL,
    [ParentTable]               VARCHAR (150)  NULL,
    CONSTRAINT [PK_ImportModuleFieldMaster] PRIMARY KEY CLUSTERED ([ImportModuleFieldMasterId] ASC)
);

