CREATE TABLE [dbo].[InventoryGLSettingAudit] (
    [InventoryGLSettingAuditId]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [InventoryGLSettingId]              BIGINT         NULL,
    [StockInventoryName]                VARCHAR (150)  NULL,
    [InventoryGLAccId]                  BIGINT         NULL,
    [InventoryGLAccCode]                NVARCHAR (250) NULL,
    [GoodsReceivedNotInvoicesGLAccId]   BIGINT         NULL,
    [GoodsReceivedNotInvoicesGLAccCode] NVARCHAR (250) NULL,
    [WorkInProgressGLAccId]             BIGINT         NULL,
    [WorkInProgressGLAccCode]           NVARCHAR (250) NULL,
    [InventoryToBillGLAccId]            BIGINT         NULL,
    [InventoryToBillGLAccCode]          NVARCHAR (250) NULL,
    [FinishedGoodsGLAccId]              BIGINT         NULL,
    [FinishedGoodsGLAccCode]            NVARCHAR (250) NULL,
    [InventoryExchAgreementGLAccId]     BIGINT         NULL,
    [InventoryExchAgreementGLAccCode]   NVARCHAR (250) NULL,
    [InventoryReserveGLAccId]           BIGINT         NULL,
    [InventoryReserveGLAccCode]         NVARCHAR (250) NULL,
    [COGS_WorkOrderGLAccId]             BIGINT         NULL,
    [COGS_WorkOrderGLAccCode]           NVARCHAR (250) NULL,
    [COGS_SalesOrderGLAccId]            BIGINT         NULL,
    [COGS_SalesOrderGLAccCode]          NVARCHAR (250) NULL,
    [COGS_ExchSalesOrderGLAccId]        BIGINT         NULL,
    [COGS_ExchSalesOrderGLAccCode]      NVARCHAR (250) NULL,
    [COGS_QtyVarianceGLAccId]           BIGINT         NULL,
    [COGS_QtyVarianceGLAccCode]         NVARCHAR (250) NULL,
    [COGS_UnitCostVarianceGLAccId]      BIGINT         NULL,
    [COGS_UnitCostVarianceGLAccCode]    NVARCHAR (250) NULL,
    [RevenueMroGLAccId]                 BIGINT         NULL,
    [RevenueMroGLAccCode]               NVARCHAR (250) NULL,
    [RevenueSoGLAccId]                  BIGINT         NULL,
    [RevenueSoGLAccCode]                NVARCHAR (250) NULL,
    [RevenueExchGLAccId]                BIGINT         NULL,
    [RevenueExchGLAccCode]              NVARCHAR (250) NULL,
    [MasterCompanyId]                   INT            NULL,
    [CreatedBy]                         VARCHAR (256)  NULL,
    [UpdatedBy]                         VARCHAR (256)  NULL,
    [CreatedDate]                       DATETIME       NULL,
    [UpdatedDate]                       DATETIME       NULL,
    [Memo]                              VARCHAR (MAX)  NULL,
    [IsActive]                          BIT            NULL,
    [IsDeleted]                         BIT            NULL,
    [IsStock]                           BIT            NULL
);

