CREATE TABLE [dbo].[LeaseStocklineAudit] (
    [LeaseStocklineAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [LeaseStocklineId]      BIGINT          NULL,
    [LeaseHeaderId]         BIGINT          NULL,
    [ItemMasterId]          BIGINT          NULL,
    [PN]                    NVARCHAR (100)  NULL,
    [PNDescription]         NVARCHAR (500)  NULL,
    [QtyOrder]              INT             NULL,
    [QtyReserved]           INT             NULL,
    [SN]                    NVARCHAR (100)  NULL,
    [StockLineId]           BIGINT          NULL,
    [StocklineNumber]       VARCHAR (100)   NULL,
    [ConditionId]           BIGINT          NULL,
    [OutrightPrice]         DECIMAL (18, 6) NULL,
    [FlatRate]              DECIMAL (18, 6) NULL,
    [PricingMethod]         NVARCHAR (100)  NULL,
    [BillingInterval]       NVARCHAR (100)  NULL,
    [MinimumCycles]         DECIMAL (18, 6) NULL,
    [MinimumTimes]          DECIMAL (18, 6) NULL,
    [MaximumCycles]         DECIMAL (18, 6) NULL,
    [MaximumTimes]          DECIMAL (18, 6) NULL,
    [UsagePerUnitCycles]    DECIMAL (18, 6) NULL,
    [UsagePerUnitTimes]     DECIMAL (18, 6) NULL,
    [OverrunPerUnitCycles]  DECIMAL (18, 6) NULL,
    [OverrunPerUnitTimes]   DECIMAL (18, 6) NULL,
    [Maintenance]           DECIMAL (18, 6) NULL,
    [Insurance]             DECIMAL (18, 6) NULL,
    [Taxes]                 DECIMAL (18, 6) NULL,
    [RateUnit]              NVARCHAR (50)   NULL,
    [BillingMethod]         NVARCHAR (50)   NULL,
    [MaintenancePer]        NVARCHAR (50)   NULL,
    [InsurancePer]          NVARCHAR (50)   NULL,
    [TaxesPer]              NVARCHAR (50)   NULL,
    [Notes]                 NVARCHAR (MAX)  NULL,
    [StartDate]             DATETIME        NULL,
    [EndDate]               DATETIME        NULL,
    [ReservedBy]            VARCHAR (256)   NULL,
    [UnReservedBy]          VARCHAR (256)   NULL,
    [RepairOrderId]         BIGINT          NULL,
    [RONumber]              VARCHAR (100)   NULL,
    [WorkOrderId]           BIGINT          NULL,
    [WorkOrderNo]           VARCHAR (100)   NULL,
    [IsActive]              BIT             NULL,
    [IsDeleted]             BIT             NULL,
    [MasterCompanyId]       INT             NULL,
    [CreatedBy]             VARCHAR (256)   NULL,
    [CreatedDate]           DATETIME        NULL,
    [UpdatedBy]             VARCHAR (256)   NULL,
    [UpdatedDate]           DATETIME        NULL,
    CONSTRAINT [PK_LeaseStocklineAudit] PRIMARY KEY CLUSTERED ([LeaseStocklineAuditId] ASC)
);

