CREATE TABLE [dbo].[LeasePickTicketAudit] (
    [LeasePickTicketAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [LeasePickTicketId]      BIGINT          NULL,
    [LeasePickTicketNumber]  VARCHAR (50)    NULL,
    [LeaseHeaderId]          BIGINT          NULL,
    [LeaseStocklineId]       BIGINT          NULL,
    [StockLineId]            BIGINT          NULL,
    [ItemMasterId]           BIGINT          NULL,
    [ConditionId]            BIGINT          NULL,
    [QtyReserved]            DECIMAL (18, 6) NULL,
    [QtyPicked]              DECIMAL (18, 6) NULL,
    [QtyRemaining]           DECIMAL (18, 6) NULL,
    [Status]                 INT             NULL,
    [PickedById]             BIGINT          NULL,
    [PickedDate]             DATETIME2 (7)   NULL,
    [ConfirmedById]          BIGINT          NULL,
    [IsConfirmed]            BIT             NULL,
    [ConfirmedDate]          DATETIME2 (7)   NULL,
    [Memo]                   NVARCHAR (MAX)  NULL,
    [PDFPath]                NVARCHAR (MAX)  NULL,
    [MasterCompanyId]        INT             NULL,
    [CreatedBy]              VARCHAR (256)   NULL,
    [CreatedDate]            DATETIME2 (7)   NULL,
    [UpdatedBy]              VARCHAR (256)   NULL,
    [UpdatedDate]            DATETIME2 (7)   NULL,
    [IsActive]               BIT             NULL,
    [IsDeleted]              BIT             NULL,
    CONSTRAINT [PK_LeasePickTicketAudit] PRIMARY KEY CLUSTERED ([LeasePickTicketAuditId] ASC)
);
