CREATE TABLE [dbo].[LeaseShippingAudit] (
    [LeaseShippingAuditId]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [LeaseShippingId]                    BIGINT          NULL,
    [LeaseHeaderId]                      BIGINT          NULL,
    [LeaseShippingNum]                   VARCHAR (50)    NULL,
    [LeaseShippingStatusId]              BIGINT          NULL,
    [OpenDate]                           DATETIME2 (7)   NULL,
    [CustomerId]                         BIGINT          NULL,
    [ShipViaId]                          BIGINT          NULL,
    [ShipDate]                           DATETIME2 (7)   NULL,
    [AirwayBill]                         VARCHAR (50)    NULL,
    [HouseAirwayBill]                    VARCHAR (50)    NULL,
    [TrackingNum]                        VARCHAR (50)    NULL,
    [Weight]                             DECIMAL (18, 6) NULL,
    [SoldToName]                         VARCHAR (256)   NULL,
    [SoldToAddress1]                     VARCHAR (256)   NULL,
    [SoldToAddress2]                     VARCHAR (256)   NULL,
    [SoldToCity]                         VARCHAR (256)   NULL,
    [SoldToState]                        VARCHAR (256)   NULL,
    [SoldToZip]                          VARCHAR (20)    NULL,
    [SoldToCountryId]                    SMALLINT        NULL,
    [ShipToName]                         VARCHAR (256)   NULL,
    [ShipToSiteName]                     VARCHAR (256)   NULL,
    [ShipToSiteId]                       BIGINT          NULL,
    [ShipToAddress1]                     VARCHAR (256)   NULL,
    [ShipToAddress2]                     VARCHAR (256)   NULL,
    [ShipToCity]                         VARCHAR (256)   NULL,
    [ShipToState]                        VARCHAR (256)   NULL,
    [ShipToZip]                          VARCHAR (20)    NULL,
    [ShipToCountryId]                    SMALLINT        NULL,
    [OriginName]                         VARCHAR (256)   NULL,
    [OriginAddress1]                     VARCHAR (256)   NULL,
    [OriginAddress2]                     VARCHAR (256)   NULL,
    [OriginCity]                         VARCHAR (256)   NULL,
    [OriginState]                        VARCHAR (256)   NULL,
    [OriginZip]                          VARCHAR (20)    NULL,
    [OriginCountryId]                    SMALLINT        NULL,
    [MasterCompanyId]                    INT             NULL,
    [CreatedBy]                          VARCHAR (256)   NULL,
    [UpdatedBy]                          VARCHAR (256)   NULL,
    [CreatedDate]                        DATETIME2 (7)   CONSTRAINT [DF_LeaseShippingAudit_CreatedDate] DEFAULT (getdate()) NULL,
    [UpdatedDate]                        DATETIME2 (7)   CONSTRAINT [DF_LeaseShippingAudit_UpdatedDate] DEFAULT (getdate()) NULL,
    [IsActive]                           BIT             CONSTRAINT [DF_LeaseShippingAudit_IsActive] DEFAULT ((1)) NULL,
    [IsDeleted]                          BIT             CONSTRAINT [DF_LeaseShippingAudit_IsDeleted] DEFAULT ((0)) NULL,
    [Shipment]                           VARCHAR (100)   NULL,
    [SoldToSiteId]                       BIGINT          NULL,
    [SoldToSiteName]                     VARCHAR (256)   CONSTRAINT [DF_LeaseShippingAudit_SoldToSiteName] DEFAULT ('') NULL,
    [SoldToCountryName]                  VARCHAR (256)   CONSTRAINT [DF_LeaseShippingAudit_SoldToCountryName] DEFAULT ('') NULL,
    [ShipToCustomerId]                   BIGINT          NULL,
    [ShipToCountryName]                  VARCHAR (256)   CONSTRAINT [DF_LeaseShippingAudit_ShipToCountryName] DEFAULT ('') NULL,
    [OriginCountryName]                  VARCHAR (256)   CONSTRAINT [DF_LeaseShippingAudit_OriginCountryName] DEFAULT ('') NULL,
    [OriginSiteId]                       BIGINT          CONSTRAINT [DF_LeaseShippingAudit_OriginSiteId] DEFAULT ((0)) NULL,
    [IsSameForShipTo]                    BIT             NULL,
    [ShipSizeLength]                     DECIMAL (18, 6) CONSTRAINT [DF_LeaseShippingAudit_ShipSizeLength] DEFAULT ((0)) NULL,
    [ShipSizeWidth]                      DECIMAL (18, 6) CONSTRAINT [DF_LeaseShippingAudit_ShipSizeWidth] DEFAULT ((0)) NULL,
    [ShipSizeHeight]                     DECIMAL (18, 6) CONSTRAINT [DF_LeaseShippingAudit_ShipSizeHeight] DEFAULT ((0)) NULL,
    [ShipWeightUnit]                     BIGINT          NULL,
    [ShipSizeUnitOfMeasureId]            BIGINT          NULL,
    [PickTicketId]                       BIGINT          NULL,
    [NoOfContainer]                      INT             NULL,
    [shipAttention]                      VARCHAR (100)   NULL,
    [soldAttention]                      VARCHAR (100)   NULL,
    [CustomerDomensticShippingShipViaId] BIGINT          NULL,
    [ShippingAccountInfo]                VARCHAR (200)   NULL,
    [NoOfItems]                          DECIMAL (18, 6) NULL,
    [IsCustomerShipping]                 BIT             NULL,
    [IsManualShipping]                   BIT             NULL,
    [ManufactureCountryId]               INT             NULL,
    [QtyUOM]                             DECIMAL (18, 6) NULL,
    [UnitPrice]                          DECIMAL (18, 6) NULL,
    [UnitPriceCurrencyId]                INT             NULL,
    [Notes]                              VARCHAR (MAX)   NULL,
    [isIgnoreAWB]                        BIT             NULL,
    [isBypassShipping]                   BIT             NULL,
    CONSTRAINT [PK_LeaseShippingAudit] PRIMARY KEY CLUSTERED ([LeaseShippingAuditId] ASC)
);

