CREATE TABLE [dbo].[LeaseHeaderAudit] (
    [LeaseHeaderAuditId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [LeaseHeaderId]         BIGINT          NOT NULL,
    [LeaseNumber]           VARCHAR (50)    NULL,
    [LeaseName]             VARCHAR (200)   NULL,
    [LeaseTypeId]           INT             NULL,
    [LeaseStatusId]         INT             CONSTRAINT [DF_LeaseHeaderAudit_LeaseStatusId] DEFAULT ((1)) NULL,
    [ManagementStructureId] BIGINT          NULL,
    [CustomerId]            BIGINT          NULL,
    [CustomerRef]           VARCHAR (100)   NULL,
    [CustomerContactId]     BIGINT          NULL,
    [Email]                 VARCHAR (256)   NULL,
    [SalespersonEmployeeId] BIGINT          NULL,
    [LocalCurrencyId]       INT             NULL,
    [ForeignCurrencyId]     INT             NULL,
    [ForeignExchangeRate]   DECIMAL (18, 6) NULL,
    [EmployeeId]            BIGINT          NULL,
    [Memo]                  VARCHAR (MAX)   NULL,
    [Notes]                 VARCHAR (MAX)   NULL,
    [MasterCompanyId]       INT             NULL,
    [CreatedBy]             VARCHAR (256)   NULL,
    [UpdatedBy]             VARCHAR (256)   NULL,
    [CreatedDate]           DATETIME2 (7)   CONSTRAINT [DF_LeaseHeaderAudit_CreatedDate] DEFAULT (getutcdate()) NULL,
    [UpdatedDate]           DATETIME2 (7)   CONSTRAINT [DF_LeaseHeaderAudit_UpdatedDate] DEFAULT (getutcdate()) NULL,
    [IsActive]              BIT             CONSTRAINT [DF_LeaseHeaderAudit_Active] DEFAULT ((1)) NULL,
    [IsDeleted]             BIT             CONSTRAINT [DF_LeaseHeaderAudit_Delete] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_LeaseHeaderAudit] PRIMARY KEY CLUSTERED ([LeaseHeaderAuditId] ASC)
);

