CREATE TABLE [dbo].[LeaseCustomsInfoAudit] (
    [LeaseCustomsInfoAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [LeaseCustomsInfoId]      BIGINT          NOT NULL,
    [LeaseShippingId]         BIGINT          NOT NULL,
    [EntryType]               VARCHAR (100)   NULL,
    [EPU]                     VARCHAR (100)   NULL,
    [CustomsValue]            DECIMAL (20, 6) NULL,
    [NetMass]                 DECIMAL (20, 6) NULL,
    [EntryStatus]             VARCHAR (100)   NULL,
    [EntryNumber]             VARCHAR (100)   NULL,
    [VATValue]                DECIMAL (20, 6) NULL,
    [UCR]                     VARCHAR (100)   NULL,
    [MasterUCR]               VARCHAR (100)   NULL,
    [MovementRefNo]           VARCHAR (100)   NULL,
    [CommodityCode]           VARCHAR (100)   NULL,
    [MasterCompanyId]         INT             NOT NULL,
    [CreatedBy]               VARCHAR (256)   NOT NULL,
    [UpdatedBy]               VARCHAR (256)   NOT NULL,
    [CreatedDate]             DATETIME2 (7)   CONSTRAINT [DF_LeaseCustomsInfoAudit_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   CONSTRAINT [DF_LeaseCustomsInfoAudit_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                BIT             CONSTRAINT [DF_LeaseCustomsInfoAudit_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]               BIT             CONSTRAINT [DF_LeaseCustomsInfoAudit_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CustomCurrencyId]        INT             NULL,
    CONSTRAINT [PK_LeaseCustomsInfoAudit] PRIMARY KEY CLUSTERED ([LeaseCustomsInfoAuditId] ASC)
);

