CREATE TABLE [dbo].[PriceMasterHistory] (
    [PriceMasterHistoryId]               BIGINT          IDENTITY (1, 1) NOT NULL,
    [ModuleId]                           BIGINT          NULL,
    [ModuleName]                         VARCHAR (200)   NULL,
    [RefferenceId]                       BIGINT          NULL,
    [RefferenceNumber]                   VARCHAR (100)   NULL,
    [ItemMasterId]                       BIGINT          NULL,
    [PartNumber]                         VARCHAR (50)    NULL,
    [PNDescription]                      VARCHAR (200)   NULL,
    [Manufacturer]                       VARCHAR (200)   NULL,
    [ItemMasterPurchaseSaleId]           BIGINT          NULL,
    [ConditionId]                        BIGINT          NULL,
    [ConditionName]                      VARCHAR (50)    NULL,
    [PP_UOMId]                           BIGINT          NULL,
    [PP_UOMName]                         VARCHAR (50)    NULL,
    [PP_CurrencyId]                      INT             NULL,
    [PP_CurrencyName]                    VARCHAR (50)    NULL,
    [PP_VendorListPrice]                 DECIMAL (18, 2) NULL,
    [PP_PurchaseDiscPerc]                INT             NULL,
    [PP_PurchaseDiscAmount]              DECIMAL (18, 2) NULL,
    [PP_UnitPurchasePrice]               DECIMAL (18, 2) NULL,
    [SalePriceSelectId]                  BIGINT          NULL,
    [SalePriceSelectName]                VARCHAR (50)    NULL,
    [SP_FSP_UOMId]                       BIGINT          NULL,
    [SP_FSP_UOMName]                     VARCHAR (50)    NULL,
    [SP_FSP_CurrencyId]                  INT             NULL,
    [SP_FSP_CurrencyName]                VARCHAR (50)    NULL,
    [SP_FSP_FlatPriceAmount]             DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_MarkUpPercOnListPrice] INT             NULL,
    [SP_CalSPByPP_MarkUpAmount]          DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_UnitSalePrice]         DECIMAL (18, 2) NULL,
    [CreatedBy]                          VARCHAR (100)   NULL,
    [CreatedDate]                        DATETIME2 (7)   NULL,
    [UpdatedBy]                          VARCHAR (100)   NULL,
    [UpdatedDate]                        DATETIME2 (7)   NULL,
    [IsActive]                           BIT             NULL,
    [IsDeleted]                          BIT             NULL
);

