CREATE TABLE [dbo].[SalesOrderPartV1] (
    [SalesOrderPartId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [SalesOrderId]        BIGINT          NOT NULL,
    [ItemMasterId]        BIGINT          NOT NULL,
    [ConditionId]         BIGINT          NOT NULL,
    [QtyRequested]        INT             NOT NULL,
    [QtyOrder]            INT             NOT NULL,
    [QtyReserved]         INT             NOT NULL,
    [CurrencyId]          INT             NULL,
    [PriorityId]          BIGINT          NOT NULL,
    [StatusId]            INT             NOT NULL,
    [FxRate]              DECIMAL (18, 4) NULL,
    [CustomerRequestDate] DATETIME2 (7)   NULL,
    [PromisedDate]        DATETIME2 (7)   NULL,
    [EstimatedShipDate]   DATETIME2 (7)   NULL,
    [POId]                BIGINT          NULL,
    [PONumber]            VARCHAR (256)   NULL,
    [PONextDlvrDate]      DATETIME2 (7)   NULL,
    [Notes]               NVARCHAR (MAX)  NULL,
    [MasterCompanyId]     INT             NOT NULL,
    [CreatedBy]           VARCHAR (256)   NOT NULL,
    [CreatedDate]         DATETIME2 (7)   CONSTRAINT [DF_SalesOrderPartV1_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedBy]           VARCHAR (256)   NOT NULL,
    [UpdatedDate]         DATETIME2 (7)   CONSTRAINT [DF_SalesOrderPartV1_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]            BIT             CONSTRAINT [DF_SalesOrderPartV1_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]           BIT             CONSTRAINT [DF_SalesOrderPartV1_IsDeleted] DEFAULT ((0)) NOT NULL,
    [OldSalesOrderPartId] BIGINT          NULL,
    CONSTRAINT [PK_SalesOrderPartV1] PRIMARY KEY CLUSTERED ([SalesOrderPartId] ASC),
    CONSTRAINT [FK_SalesOrderPartV1_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId]),
    CONSTRAINT [FK_SalesOrderPartV1_Priority] FOREIGN KEY ([PriorityId]) REFERENCES [dbo].[Priority] ([PriorityId])
);

