CREATE TABLE [dbo].[SalesOrderStocklineV1Audit] (
    [AuditSalesOrderStocklineId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [SalesOrderStocklineId]      BIGINT          NOT NULL,
    [SalesOrderPartId]           BIGINT          NOT NULL,
    [StockLineId]                BIGINT          NOT NULL,
    [ConditionId]                BIGINT          NOT NULL,
    [QtyOrder]                   DECIMAL (18, 6) NULL,
    [QtyReserved]                DECIMAL (18, 6) NULL,
    [QtyAvailable]               DECIMAL (18, 6) NULL,
    [QtyOH]                      DECIMAL (18, 6) NULL,
    [CustomerRequestDate]        DATETIME2 (7)   NULL,
    [PromisedDate]               DATETIME2 (7)   NULL,
    [EstimatedShipDate]          DATETIME2 (7)   NULL,
    [StatusId]                   INT             NOT NULL,
    [MasterCompanyId]            INT             NOT NULL,
    [CreatedBy]                  VARCHAR (256)   NOT NULL,
    [CreatedDate]                DATETIME2 (7)   NOT NULL,
    [UpdatedBy]                  VARCHAR (256)   NOT NULL,
    [UpdatedDate]                DATETIME2 (7)   NOT NULL,
    [IsActive]                   BIT             NOT NULL,
    [IsDeleted]                  BIT             NOT NULL,
    [StocklineNumber]            VARCHAR (100)   NULL,
    [ConditionName]              VARCHAR (100)   NULL,
    [StatusName]                 VARCHAR (100)   NULL,
    [Notes]                      NVARCHAR (MAX)  NULL,
    [ECCN]                       VARCHAR (200)   NULL,
    [HSCODE]                     VARCHAR (200)   NULL,
    [Weight]                     DECIMAL (10, 2) NULL,
    [SizeLength]                 DECIMAL (10, 2) NULL,
    [SizeWidth]                  DECIMAL (10, 2) NULL,
    [SizeHeight]                 DECIMAL (10, 2) NULL,
    [ReferenceNumber]            VARCHAR (100)   NULL,
    [PriorityId]                 BIGINT          NULL,
    CONSTRAINT [PK_SalesOrderStocklineV1Audit] PRIMARY KEY CLUSTERED ([AuditSalesOrderStocklineId] ASC)
);

