CREATE TABLE [dbo].[SalesOrderPartV1Audit] (
    [AuditSalesOrderPartId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [SalesOrderPartId]      BIGINT          NOT NULL,
    [SalesOrderId]          BIGINT          NOT NULL,
    [ItemMasterId]          BIGINT          NOT NULL,
    [ConditionId]           BIGINT          NOT NULL,
    [QtyRequested]          DECIMAL (18, 6) NULL,
    [QtyOrder]              DECIMAL (18, 6) NULL,
    [QtyReserved]           DECIMAL (18, 6) NULL,
    [CurrencyId]            INT             NULL,
    [PriorityId]            BIGINT          NOT NULL,
    [StatusId]              INT             NOT NULL,
    [FxRate]                DECIMAL (18, 6) NULL,
    [CustomerRequestDate]   DATETIME2 (7)   NULL,
    [PromisedDate]          DATETIME2 (7)   NULL,
    [EstimatedShipDate]     DATETIME2 (7)   NULL,
    [POId]                  BIGINT          NULL,
    [PONumber]              VARCHAR (256)   NULL,
    [PONextDlvrDate]        DATETIME2 (7)   NULL,
    [Notes]                 NVARCHAR (MAX)  NULL,
    [MasterCompanyId]       INT             NOT NULL,
    [CreatedBy]             VARCHAR (256)   NOT NULL,
    [CreatedDate]           DATETIME2 (7)   NOT NULL,
    [UpdatedBy]             VARCHAR (256)   NOT NULL,
    [UpdatedDate]           DATETIME2 (7)   NOT NULL,
    [IsActive]              BIT             NOT NULL,
    [IsDeleted]             BIT             NOT NULL,
    [OldSalesOrderPartId]   BIGINT          NULL,
    [PartNumber]            VARCHAR (200)   NULL,
    [PartDescription]       VARCHAR (MAX)   NULL,
    [ConditionName]         VARCHAR (100)   NULL,
    [CurrencyName]          VARCHAR (100)   NULL,
    [PriorityName]          VARCHAR (100)   NULL,
    [StatusName]            VARCHAR (100)   NULL,
    [SalesOrderQuotePartId] BIGINT          NULL,
    [LotId]                 BIGINT          NULL,
    [IsLotAssigned]         BIT             NULL,
    [ECCN]                  VARCHAR (200)   NULL,
    [HSCODE]                VARCHAR (200)   NULL,
    [Weight]                DECIMAL (18, 6) NULL,
    [SizeLength]            DECIMAL (18, 6) NULL,
    [SizeWidth]             DECIMAL (18, 6) NULL,
    [SizeHeight]            DECIMAL (18, 6) NULL,
    [AltOrEqType]           VARCHAR (50)    NULL,
    [UnitSalesPrice]        DECIMAL (18, 6) NULL,
    [ToTalReservedQty]      DECIMAL (18, 6) NULL,
    [SequenceNumber] BIGINT NULL,
    CONSTRAINT [PK_SalesOrderPartV1Audit] PRIMARY KEY CLUSTERED ([AuditSalesOrderPartId] ASC)
);

