CREATE TABLE [dbo].[SalesOrderPartCostAudit] (
    [AuditSalesOrderPartCostId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [SalesOrderPartCostId]      BIGINT          NOT NULL,
    [SalesOrderId]              BIGINT          NOT NULL,
    [SalesOrderPartId]          BIGINT          NOT NULL,
    [UnitSalesPrice]            DECIMAL (18, 6) NULL,
    [UnitSalesPriceExtended]    DECIMAL (18, 6) NULL,
    [UnitCost]                  DECIMAL (18, 6) NULL,
    [UnitCostExtended]          DECIMAL (18, 6) NULL,
    [MarkUpPercentage]          DECIMAL (18, 6) NULL,
    [MarkUpAmount]              DECIMAL (18, 6) NULL,
    [MarginAmount]              DECIMAL (18, 6) NULL,
    [MarginPercentage]          DECIMAL (18, 6) NULL,
    [DiscountPercentage]        DECIMAL (18, 6) NULL,
    [DiscountAmount]            DECIMAL (18, 6) NULL,
    [TaxPercentage]             DECIMAL (18, 6) NULL,
    [TaxAmount]                 DECIMAL (18, 6) NULL,
    [NetSaleAmount]             DECIMAL (18, 6) NULL,
    [MiscCharges]               DECIMAL (18, 6) NULL,
    [Freight]                   DECIMAL (18, 6) NULL,
    [TotalRevenue]              DECIMAL (18, 6) NULL,
    [MasterCompanyId]           INT             NOT NULL,
    [CreatedBy]                 VARCHAR (256)   NOT NULL,
    [CreatedDate]               DATETIME2 (7)   NOT NULL,
    [UpdatedBy]                 VARCHAR (256)   NOT NULL,
    [UpdatedDate]               DATETIME2 (7)   NOT NULL,
    [IsActive]                  BIT             NOT NULL,
    [IsDeleted]                 BIT             NOT NULL,
    [NetSaleAmountPerUnit]      DECIMAL (18, 6) NULL,
    CONSTRAINT [PK_SalesOrderPartCostAudit] PRIMARY KEY CLUSTERED ([AuditSalesOrderPartCostId] ASC)
);

