CREATE TABLE [dbo].[StockInventorySearchParams] (
    [StockInventorySearchParamsId] BIGINT        IDENTITY (1, 1) NOT NULL,
    [UrlName]                      VARCHAR (500) NULL,
    [FromReceivedDate]             DATETIME2 (7) NULL,
    [ToReceivedDate]               DATETIME2 (7) NULL,
    [FromStocklineId]              VARCHAR (500) NULL,
    [ToStocklineId]                VARCHAR (500) NULL,
    [FromUnitCost]                 VARCHAR (500) NULL,
    [ToUnitCost]                   VARCHAR (500) NULL,
    [ItemMasterId]                 BIGINT        NULL,
    [VendorId]                     BIGINT        NULL,
    [ConditionId]                  BIGINT        NULL,
    [LotId]                        BIGINT        NULL,
    [TraceableTo]                  BIGINT        NULL,
    [SiteId]                       BIGINT        NULL,
    [WarehouseId]                  BIGINT        NULL,
    [LocationId]                   BIGINT        NULL,
    [ShelfId]                      BIGINT        NULL,
    [BinId]                        BIGINT        NULL,
    [PoRoRefrences]                VARCHAR (500) NULL,
    [Level1]                       VARCHAR (500) NULL,
    [Level2]                       VARCHAR (500) NULL,
    [Level3]                       VARCHAR (500) NULL,
    [Level4]                       VARCHAR (500) NULL,
    [Level5]                       VARCHAR (500) NULL,
    [Level6]                       VARCHAR (500) NULL,
    [Level7]                       VARCHAR (500) NULL,
    [Level8]                       VARCHAR (500) NULL,
    [Level9]                       VARCHAR (500) NULL,
    [Level10]                      VARCHAR (500) NULL,
    [MasterCompanyId]              INT           NOT NULL,
    [CreatedBy]                    VARCHAR (50)  NOT NULL,
    [CreatedDate]                  DATETIME2 (7) CONSTRAINT [DF_StockInventorySearchParams_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedBy]                    VARCHAR (50)  NOT NULL,
    [UpdatedDate]                  DATETIME2 (7) CONSTRAINT [DF_StockInventorySearchParams_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]                     BIT           CONSTRAINT [DF_StockInventorySearchParams_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                    BIT           CONSTRAINT [DF_StockInventorySearchParams_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_StockInventorySearchParams] PRIMARY KEY CLUSTERED ([StockInventorySearchParamsId] ASC)
);

