CREATE TABLE [dbo].[SubWorkOrderTaskHistory] (
    [SubWorkOrderTaskHistoryId]                       BIGINT         IDENTITY (1, 1) NOT NULL,
    [SubWorkOrderTaskId]                              BIGINT         NOT NULL,
    [TaskName]                                        VARCHAR (200)  NULL,
    [Descrepancy]                                     VARCHAR (MAX)  NULL,
    [Resolution]                                      VARCHAR (MAX)  NULL,
    [TechId]                                          BIGINT         NULL,
    [TechName]                                        VARCHAR (100)  NULL,
    [TechUpdatedDate]                                 DATETIME2 (7)  NULL,
    [InspectorId]                                     BIGINT         NULL,
    [InspectorName]                                   VARCHAR (100)  NULL,
    [InspectorUpdatedDate]                            DATETIME2 (7)  NULL,
    [PrintInWO]                                       BIT            NULL,
    [PrintInWOQ]                                      BIT            NULL,
    [IsParent]                                        BIT            NULL,
    [ParentId]                                        BIGINT         NULL,
    [InstructionTitle]                                VARCHAR (8000) NULL,
    [InstructionDetails]                              VARCHAR (MAX)  NULL,
    [SequenceNumber]                                  INT            NULL,
    [IsActive]                                        BIT            NULL,
    [IsDeleted]                                       BIT            NULL,
    [UpdatedBy]                                       VARCHAR (256)  NULL,
    [UpdatedDate]                                     DATETIME2 (7)  NULL,
    [SubWorkOrderTaskInstructionId]                   BIGINT         NULL,
    [SubWorkOrderTaskInstructionTechId]               BIGINT         NULL,
    [SubWorkOrderTaskInstructionTechName]             VARCHAR (100)  NULL,
    [SubWorkOrderTaskInstructionTechUpdatedDate]      DATETIME2 (7)  NULL,
    [SubWorkOrderTaskInstructionInspectorId]          BIGINT         NULL,
    [SubWorkOrderTaskInstructionInspectorName]        VARCHAR (100)  NULL,
    [SubWorkOrderTaskInstructionInspectorUpdatedDate] DATETIME2 (7)  NULL,
    [SubWorkOrderTaskInstructionPrintInWO]            BIT            NULL,
    [SubWorkOrderTaskInstructionPrintInWOQ]           BIT            NULL
);

