CREATE TABLE [dbo].[SupportEmail] (
    [SupportEmailId]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [CustomerTicketId] BIGINT         NULL,
    [MessageId]        NVARCHAR (255) NULL,
    [Subject]          VARCHAR (500)  NOT NULL,
    [EmailBody]        NVARCHAR (MAX) NOT NULL,
    [ToEmail]          NVARCHAR (320) NOT NULL,
    [FromEmail]        NVARCHAR (320) NOT NULL,
    [CC]               NVARCHAR (320) NULL,
    [BCC]              NVARCHAR (320) NULL,
    [EmailReadBy]      NVARCHAR (320) NULL,
    [HasAttachments]   BIT            NULL,
    [EmailSection]     INT            NOT NULL,
    [ReceivedDate]     DATETIME2 (7)  NULL,
    [MasterCompanyId]  INT            NOT NULL,
    [CreatedBy]        VARCHAR (256)  NOT NULL,
    [UpdatedBy]        VARCHAR (256)  NOT NULL,
    [CreatedDate]      DATETIME2 (7)  CONSTRAINT [DF_SupportEmail_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedDate]      DATETIME2 (7)  CONSTRAINT [DF_SupportEmail_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]         BIT            CONSTRAINT [DF_SupportEmail_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]        BIT            CONSTRAINT [DF_SupportEmail_IsDeleted] DEFAULT ((0)) NOT NULL,
    [IsRead]           BIT            DEFAULT ((0)) NULL,
    [IsProcessed]      BIT            NULL,
    [EmailStatusId]    INT            NULL,
    [AttemptCount]     INT            NULL,
    CONSTRAINT [PK_SupportEmail] PRIMARY KEY CLUSTERED ([SupportEmailId] ASC),
    CONSTRAINT [FK_SupportEmail_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId])
);

