CREATE TABLE [dbo].[VendorAging] (
    [VendorAgingId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [VendorId]         BIGINT          NOT NULL,
    [VendorName]       VARCHAR (100)   NULL,
    [VendorCode]       VARCHAR (100)   NULL,
    [CreditTermsId]    INT             NULL,
    [CreditTermName]   VARCHAR (30)    NULL,
    [NetDays]          TINYINT         NULL,
    [CreditLimit]      DECIMAL (18, 2) NULL,
    [AsOfDate]         DATE            NOT NULL,
    [TotalInvoices]    INT             NULL,
    [TotalOutstanding] DECIMAL (18, 6) NULL,
    [CurrentAmount]    DECIMAL (18, 6) CONSTRAINT [DF_VendorAging_CurrentAmount] DEFAULT ((0)) NOT NULL,
    [Days1_30]         DECIMAL (18, 6) CONSTRAINT [DF_VendorAging_Days1_30] DEFAULT ((0)) NOT NULL,
    [Days31_60]        DECIMAL (18, 6) CONSTRAINT [DF_VendorAging_Days31_60] DEFAULT ((0)) NOT NULL,
    [Days61_90]        DECIMAL (18, 6) CONSTRAINT [DF_VendorAging_Days61_90] DEFAULT ((0)) NOT NULL,
    [Days91_120]       DECIMAL (18, 6) CONSTRAINT [DF_VendorAging_Days91_120] DEFAULT ((0)) NOT NULL,
    [Days120Plus]      DECIMAL (18, 6) CONSTRAINT [DF_VendorAging_Days120Plus] DEFAULT ((0)) NOT NULL,
    [MasterCompanyId]  INT             NOT NULL,
    [CreatedBy]        VARCHAR (256)   NOT NULL,
    [UpdatedBy]        VARCHAR (256)   NOT NULL,
    [CreatedDate]      DATETIME2 (7)   CONSTRAINT [DF_VendorAging_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]      DATETIME2 (7)   CONSTRAINT [DF_VendorAging_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]         BIT             CONSTRAINT [DF_VendorAging_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]        BIT             CONSTRAINT [DF_VendorAging_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_VendorAging] PRIMARY KEY CLUSTERED ([VendorAgingId] ASC),
    CONSTRAINT [FK_VendorAging_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId]),
    CONSTRAINT [FK_VendorAging_Vendor] FOREIGN KEY ([VendorId]) REFERENCES [dbo].[Vendor] ([VendorId])
);
