CREATE TABLE [dbo].[VendorReadyToPayApproval] (
    [VendorReadyToPayApprovalId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [LegalEntityId]              BIGINT         NOT NULL,
    [ReadyToPayDetailsId]        BIGINT         NOT NULL,
    [Memo]                       NVARCHAR (MAX) NULL,
    [SentDate]                   DATETIME2 (7)  NULL,
    [ApprovedDate]               DATETIME2 (7)  NULL,
    [ApprovedById]               BIGINT         NULL,
    [ApprovedByName]             VARCHAR (200)  NULL,
    [RejectedDate]               DATETIME2 (7)  NULL,
    [RejectedBy]                 BIGINT         NULL,
    [RejectedByName]             VARCHAR (200)  NULL,
    [StatusId]                   INT            NULL,
    [StatusName]                 VARCHAR (50)   NULL,
    [ActionId]                   INT            NULL,
    [MasterCompanyId]            INT            NOT NULL,
    [CreatedBy]                  VARCHAR (256)  NOT NULL,
    [UpdatedBy]                  VARCHAR (256)  NOT NULL,
    [CreatedDate]                DATETIME2 (7)  NOT NULL,
    [UpdatedDate]                DATETIME2 (7)  NOT NULL,
    [IsActive]                   BIT            CONSTRAINT [VendorReadyToPayApproval_DC_Active] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                  BIT            CONSTRAINT [VendorReadyToPayApproval_DC_Delete] DEFAULT ((0)) NOT NULL,
    [InternalSentToId]           BIGINT         NULL,
    [InternalSentToName]         VARCHAR (100)  NULL,
    [InternalSentById]           BIGINT         NULL,
    CONSTRAINT [PK_VendorReadyToPayApproval] PRIMARY KEY CLUSTERED ([VendorReadyToPayApprovalId] ASC),
    CONSTRAINT [FK_VendorReadyToPayApproval_ApprovalStatus] FOREIGN KEY ([StatusId]) REFERENCES [dbo].[ApprovalStatus] ([ApprovalStatusId]),
    CONSTRAINT [FK_VendorReadyToPayApproval_EmployeeApprovedby] FOREIGN KEY ([ApprovedById]) REFERENCES [dbo].[Employee] ([EmployeeId]),
    CONSTRAINT [FK_VendorReadyToPayApproval_EmployeeRejectedBy] FOREIGN KEY ([RejectedBy]) REFERENCES [dbo].[Employee] ([EmployeeId]),
    CONSTRAINT [FK_VendorReadyToPayApproval_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId]),
    CONSTRAINT [FK_VendorReadyToPayApproval_VendorReadyToPayDetails] FOREIGN KEY ([ReadyToPayDetailsId]) REFERENCES [dbo].[VendorReadyToPayDetails] ([ReadyToPayDetailsId])
);

