CREATE TABLE [dbo].[VendorProformaInvoicePartDetailsAudit] (
    [VendorProformaInvoicePartDetailsAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [VendorProformaInvoicePartDetailsId]      BIGINT          NOT NULL,
    [VendorProformaInvoiceId]                 BIGINT          NOT NULL,
    [EntryDate]                               DATETIME2 (7)   NOT NULL,
    [Amount]                                  DECIMAL (18, 6) NULL,
    [CurrencyId]                              BIGINT          NULL,
    [FXRate]                                  DECIMAL (18, 6) NULL,
    [GlAccountId]                             BIGINT          NOT NULL,
    [InvoiceNumber]                           VARCHAR (256)   NULL,
    [InvoiceDate]                             DATETIME2 (7)   NULL,
    [ManagementStructureId]                   INT             NOT NULL,
    [LastMSLevel]                             VARCHAR (200)   NULL,
    [AllMSlevels]                             VARCHAR (MAX)   NULL,
    [Memo]                                    VARCHAR (MAX)   NULL,
    [JournalType]                             VARCHAR (200)   NULL,
    [Item]                                    VARCHAR (250)   NULL,
    [Description]                             VARCHAR (500)   NULL,
    [UnitOfMeasureId]                         BIGINT          NULL,
    [Qty]                                     DECIMAL (18, 6) NULL,
    [ExtendedPrice]                           DECIMAL (18, 6) NULL,
    [TaxTypeId]                               BIGINT          NULL,
    [MasterCompanyId]                         INT             NOT NULL,
    [CreatedBy]                               VARCHAR (100)   NOT NULL,
    [CreatedDate]                             DATETIME2 (7)   NOT NULL,
    [UpdatedBy]                               VARCHAR (100)   NOT NULL,
    [UpdatedDate]                             DATETIME2 (7)   NOT NULL,
    [IsActive]                                BIT             NOT NULL,
    [IsDeleted]                               BIT             NOT NULL,
    CONSTRAINT [PK_VendorProformaInvoicePartDetailsAudit] PRIMARY KEY CLUSTERED ([VendorProformaInvoicePartDetailsAuditId] ASC)
);

