CREATE TABLE [dbo].[WorkOrderTaskHistory] (
    [WorkOrderTaskHistoryId]                       BIGINT         IDENTITY (1, 1) NOT NULL,
    [WorkOrderTaskId]                              BIGINT         NOT NULL,
    [TaskName]                                     VARCHAR (200)  NULL,
    [Descrepancy]                                  VARCHAR (MAX)  NULL,
    [Resolution]                                   VARCHAR (MAX)  NULL,
    [TechId]                                       BIGINT         NULL,
    [TechName]                                     VARCHAR (100)  NULL,
    [TechUpdatedDate]                              DATETIME2 (7)  NULL,
    [InspectorId]                                  BIGINT         NULL,
    [InspectorName]                                VARCHAR (100)  NULL,
    [InspectorUpdatedDate]                         DATETIME2 (7)  NULL,
    [PrintInWO]                                    BIT            NULL,
    [PrintInWOQ]                                   BIT            NULL,
    [IsParent]                                     BIT            NULL,
    [ParentId]                                     BIGINT         NULL,
    [InstructionTitle]                             VARCHAR (8000) NULL,
    [InstructionDetails]                           VARCHAR (MAX)  NULL,
    [SequenceNumber]                               INT            NULL,
    [IsActive]                                     BIT            NULL,
    [IsDeleted]                                    BIT            NULL,
    [UpdatedBy]                                    VARCHAR (256)  NULL,
    [UpdatedDate]                                  DATETIME2 (7)  NULL,
    [WorkOrderTaskInstructionId]                   BIGINT         NULL,
    [WorkOrderTaskInstructionTechId]               BIGINT         NULL,
    [WorkOrderTaskInstructionTechName]             VARCHAR (100)  NULL,
    [WorkOrderTaskInstructionTechUpdatedDate]      DATETIME2 (7)  NULL,
    [WorkOrderTaskInstructionInspectorId]          BIGINT         NULL,
    [WorkOrderTaskInstructionInspectorName]        VARCHAR (100)  NULL,
    [WorkOrderTaskInstructionInspectorUpdatedDate] DATETIME2 (7)  NULL,
    [WorkOrderTaskInstructionPrintInWO]            BIT            NULL,
    [WorkOrderTaskInstructionPrintInWOQ]           BIT            NULL,
    [WorkOrderTaskInstructionSequence]             INT            NULL
);

