CREATE TABLE [dbo].[WorksheetHeader] (
    [WorksheetHeaderId]            BIGINT         IDENTITY (1, 1) NOT NULL,
    [WorksheetNumber]              VARCHAR (50)   NULL,
    [MakeTypeId]                   BIGINT         NOT NULL,
    [MakeType]                     VARCHAR (100)  NULL,
    [AircraftModelId]              BIGINT         NULL,
    [AircraftModel]                VARCHAR (100)  NULL,
    [WorksheetType]                VARCHAR (50)   NULL,
    [WorkOrderNo]                  VARCHAR (50)   NULL,
    [AFHours]                      VARCHAR (50)   NULL,
    [InspectionType]               BIGINT         NULL,
    [InspectionDate]               DATE           NULL,
    [QualitySafetyDeptSignOutBy]   BIGINT         NULL,
    [QualitySafetyDeptSignOutDate] DATETIME       NULL,
    [QualitySafetyDeptSignInBy]    BIGINT         NULL,
    [QualitySafetyDeptSignInDate]  DATETIME       NULL,
    [ReleaseToServiceBy]           BIGINT         NULL,
    [ReleaseDate]                  DATETIME       NULL,
    [CreatedBy]                    VARCHAR (256)  NOT NULL,
    [CreatedDate]                  DATETIME2 (7)  CONSTRAINT [DF_WorksheetHeader_CreatedDate] DEFAULT (sysdatetime()) NOT NULL,
    [MasterCompanyId]              INT            NOT NULL,
    [IsActive]                     BIT            CONSTRAINT [DF_WorksheetHeader_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                    BIT            CONSTRAINT [DF_WorksheetHeader_IsDeleted] DEFAULT ((0)) NOT NULL,
    [UpdatedBy]                    VARCHAR (256)  CONSTRAINT [DF_WorksheetHeader_UpdatedBy] DEFAULT ('') NOT NULL,
    [UpdatedDate]                  DATETIME2 (7)  CONSTRAINT [DF_WorksheetHeader_UpdatedDate] DEFAULT (sysdatetime()) NOT NULL,
    [AMONumber]                    VARCHAR (100)  NULL,
    [TechnicalRecordsWO]           VARCHAR (100)  NULL,
    [CalmSysWO]                    VARCHAR (100)  NULL,
    [AircraftReg]                  VARCHAR (50)   NULL,
    [CertificationStatement]       VARCHAR (2000) NULL,
    [ReleaseLicenseNumber]         VARCHAR (100)  NULL,
    [WorksheetTypeId]              BIGINT         NULL,
    [TailNum]                      VARCHAR (100)  NULL,
    [SerialNum]                    VARCHAR (100)  NULL,
    CONSTRAINT [PK_WorksheetHeader] PRIMARY KEY CLUSTERED ([WorksheetHeaderId] ASC),
    CONSTRAINT [FK_WorksheetHeader_AircraftModel] FOREIGN KEY ([AircraftModelId]) REFERENCES [dbo].[AircraftModel] ([AircraftModelId]),
    CONSTRAINT [FK_WorksheetHeader_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId])
);

