CREATE TABLE [dbo].[AircraftPublication] (
    [AircraftPublicationId]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [AircraftPublicationNumber] VARCHAR (100)  NOT NULL,
    [PubDate]                   DATETIME2 (7)  NULL,
    [PublicationTypeId]         BIGINT         NOT NULL,
    [PubNum]                    VARCHAR (50)   NULL,
    [RevisionNum]               VARCHAR (50)   NULL,
    [AircraftSectionId]         BIGINT         NULL,
    [Subject]                   NVARCHAR (MAX) NULL,
    [PublishedById]             BIGINT         NOT NULL,
    [PublishedByRefId]          BIGINT         NULL,
    [PublishedByOthers]         VARCHAR (100)  NULL,
    [ComplianceCategoryId]      BIGINT         NOT NULL,
    [ComplianceCategory]        VARCHAR (50)   NULL,
    [Timeframe]                 NVARCHAR (MAX) NULL,
    [PurposeReasonBackground]   NVARCHAR (MAX) NULL,
    [EntryDate]                 DATETIME2 (7)  NOT NULL,
    [VerifiedBy]                BIGINT         NOT NULL,
    [MasterCompanyId]           INT            NOT NULL,
    [CreatedBy]                 VARCHAR (256)  NOT NULL,
    [UpdatedBy]                 VARCHAR (256)  NOT NULL,
    [CreatedDate]               DATETIME2 (7)  DEFAULT (getutcdate()) NOT NULL,
    [UpdatedDate]               DATETIME2 (7)  NOT NULL,
    [IsActive]                  BIT            DEFAULT ((1)) NOT NULL,
    [IsDeleted]                 BIT            DEFAULT ((0)) NOT NULL,
    [ComplianceDate]            DATETIME2 (7)  NULL,
    [RactificationDate]         DATETIME2 (7)  NULL,
    [Applicability]             BIT            NULL,
    [MEL]                       BIT            NULL,
    PRIMARY KEY CLUSTERED ([AircraftPublicationId] ASC),
    CONSTRAINT [FK_AircraftPublication_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId])
);

