CREATE TABLE [dbo].[AircraftMaintenanceProgram] (
    [ProgramId]                   BIGINT        IDENTITY (1, 1) NOT NULL,
    [AircraftRegistryId]          BIGINT        NOT NULL,
    [VersionNumber]               VARCHAR (50)  NULL,
    [TailNumber]                  VARCHAR (50)  NOT NULL,
    [AircraftMake]                VARCHAR (100) NULL,
    [AircraftModel]               VARCHAR (100) NULL,
    [SerialNumber]                VARCHAR (100) NULL,
    [MaintenanceType]             VARCHAR (200) NULL,
    [NextScheduledMaintenance]    DATETIME2 (7) NULL,
    [TemplateId]                  BIGINT        NULL,
    [TemplateVersionNumber]       VARCHAR (50)  NULL,
    [FlightHoursLimitHours]       INT           NULL,
    [FlightHoursLimitMinutes]     INT           NULL,
    [CyclesLimit]                 BIGINT        NULL,
    [TimeLimit]                   BIGINT        NULL,
    [LandingsLimit]               BIGINT        NULL,
    [EngineStartsLimit]           BIGINT        NULL,
    [FlightHoursRecordedHours]    INT           NULL,
    [FlightHoursRecordedMinutes]  INT           NULL,
    [CyclesRecorded]              BIGINT        NULL,
    [TimeRecorded]                BIGINT        NULL,
    [LandingsRecorded]            BIGINT        NULL,
    [EngineStartsRecorded]        BIGINT        NULL,
    [FlightHoursRemainingHours]   INT           NULL,
    [FlightHoursRemainingMinutes] INT           NULL,
    [CyclesRemaining]             BIGINT        NULL,
    [TimeRemaining]               BIGINT        NULL,
    [LandingsRemaining]           BIGINT        NULL,
    [EngineStartsRemaining]       BIGINT        NULL,
    [IsScheduled]                 BIT           CONSTRAINT [DF_AircraftMaintenanceProgram_IsScheduled] DEFAULT ((0)) NULL,
    [MasterCompanyId]             INT           NOT NULL,
    [CreatedBy]                   VARCHAR (256) NOT NULL,
    [UpdatedBy]                   VARCHAR (256) NULL,
    [CreatedDate]                 DATETIME2 (7) CONSTRAINT [DF_AMP_CreatedDate] DEFAULT (sysdatetime()) NOT NULL,
    [UpdatedDate]                 DATETIME2 (7) CONSTRAINT [DF_AMP_UpdatedDate] DEFAULT (sysdatetime()) NOT NULL,
    [IsActive]                    BIT           CONSTRAINT [DF_AMP_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                   BIT           CONSTRAINT [DF_AMP_IsDeleted] DEFAULT ((0)) NOT NULL,
    [MaintenanceTypeId]           BIGINT        NULL,
    [MaintenanceClassId]          BIGINT        NULL,
    [MtcCategoryId]               BIGINT        NULL,
    [IsMtceRecordUpdated]         BIT           CONSTRAINT [DF__AircraftM__IsMtc__1F89FEE0] DEFAULT ((0)) NULL,
    CONSTRAINT [PK_AircraftMaintenanceProgram] PRIMARY KEY CLUSTERED ([ProgramId] ASC),
    CONSTRAINT [CK_AMP_Minutes] CHECK (([FlightHoursLimitMinutes] IS NULL OR [FlightHoursLimitMinutes]>=(0) AND [FlightHoursLimitMinutes]<=(59)) AND ([FlightHoursRecordedMinutes] IS NULL OR [FlightHoursRecordedMinutes]>=(0) AND [FlightHoursRecordedMinutes]<=(59)) AND ([FlightHoursRemainingMinutes] IS NULL OR [FlightHoursRemainingMinutes]>=(0) AND [FlightHoursRemainingMinutes]<=(59))),
    CONSTRAINT [FK_AircraftMaintenanceProgram_AircraftRegistry] FOREIGN KEY ([AircraftRegistryId]) REFERENCES [dbo].[AircraftRegistryHeader] ([AircraftRegistryId]),
    CONSTRAINT [FK_AMP_MaintenanceClass] FOREIGN KEY ([MaintenanceClassId]) REFERENCES [dbo].[MaintenanceClass] ([MaintenanceClassId]),
    CONSTRAINT [FK_AMP_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId]),
    CONSTRAINT [FK_AMP_Workflow] FOREIGN KEY ([TemplateId]) REFERENCES [dbo].[Workflow] ([WorkflowId])
);

