CREATE TABLE [dbo].[DeprNonDeprTangibleAssetsAudit] (
    [AuditDeprNonDeprTangibleAssetsId] BIGINT        IDENTITY (1, 1) NOT NULL,
    [DeprNonDeprTangibleAssetsId]      BIGINT        NOT NULL,
    [DeprNonDeprTangibleClassTypeId]   BIGINT        NULL,
    [TangibleClassId]                  BIGINT        NOT NULL,
    [Description]                      VARCHAR (500) NULL,
    [AssetDeprMethodId]                BIGINT        NULL,
    [CalibratedGLAccountId]            BIGINT        NULL,
    [AcquiredGLAccountId]              BIGINT        NULL,
    [DeprExpenseGLAccountId]           BIGINT        NULL,
    [AccumDeprGLAccountId]             BIGINT        NULL,
    [AssetSaleGLAccountId]             BIGINT        NULL,
    [AssetWriteOffGLAccountId]         BIGINT        NULL,
    [AssetWriteDownGLAccountId]        BIGINT        NULL,
    [ManagementStructureId]            BIGINT        NULL,
    [MasterCompanyId]                  INT           NOT NULL,
    [CreatedBy]                        VARCHAR (256) NOT NULL,
    [UpdatedBy]                        VARCHAR (256) NOT NULL,
    [CreatedDate]                      DATETIME2 (7) CONSTRAINT [DF_DeprNonDeprTangibleAssetsAudit_CreatedDate_1] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedDate]                      DATETIME2 (7) CONSTRAINT [DF_DeprNonDeprTangibleAssetsAudit_UpdatedDate_1] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]                         BIT           NOT NULL,
    [IsDeleted]                        BIT           CONSTRAINT [DF_DeprNonDeprTangibleAssetsAudit_IsDeleted_1] DEFAULT ((0)) NOT NULL,
    [ResidualPercentage]               BIGINT        NULL,
    [AssetLife]                        INT           NULL,
    [DepreciationFrequencyId]          BIGINT        NULL,
    CONSTRAINT [PK_DeprNonDeprTangibleAssetsAudit] PRIMARY KEY CLUSTERED ([AuditDeprNonDeprTangibleAssetsId] ASC)
);

