CREATE TABLE [dbo].[DeprNonDeprTangibleAssetsAudit] (
    [AuditDeprNonDeprTangibleAssetsId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [DeprNonDeprTangibleAssetsId]      BIGINT         NOT NULL,
    [TangibleClassId]                  BIGINT         NOT NULL,
    [AssetAttributeTypeName]           VARCHAR (30)   NOT NULL,
    [Description]                      VARCHAR (500)  NOT NULL,
    [AssetDeprMethodId]                BIGINT         NOT NULL,
    [CalibratedGLAccountId]            BIGINT         NULL,
    [AcquiredGLAccountId]              BIGINT         NULL,
    [DeprExpenseGLAccountId]           BIGINT         NULL,
    [AccumDeprGLAccountId]             BIGINT         NULL,
    [AssetSaleGLAccountId]             BIGINT         NULL,
    [AssetWriteOffGLAccountId]         BIGINT         NULL,
    [AssetWriteDownGLAccountId]        BIGINT         NULL,
    [ManagementStructureId]            BIGINT         NULL,
    [MasterCompanyId]                  INT            NOT NULL,
    [CreatedBy]                        VARCHAR (256)  NOT NULL,
    [UpdatedBy]                        VARCHAR (256)  NOT NULL,
    [CreatedDate]                      DATETIME2 (7)  NOT NULL,
    [UpdatedDate]                      DATETIME2 (7)  NOT NULL,
    [IsActive]                         BIT            NOT NULL,
    [IsDeleted]                        BIT            NOT NULL,
    [SelectedCompanyIds]               VARCHAR (1000) NOT NULL,
    [ResidualPercentage]               BIGINT         NULL,
    [AssetLife]                        INT            NULL,
    [DepreciationFrequencyId]          BIGINT         NULL,
    [TangibleClass]                    VARCHAR (100)  NULL,
    [AssetDepreciationMethodName]      VARCHAR (100)  NULL,
    [AssetDepreciationIntervalName]    VARCHAR (100)  NULL,
    [PercentValue]                     VARCHAR (100)  NULL,
    [CalibratedGLAccount]              VARCHAR (100)  NULL,
    [AcquiredGLAccount]                VARCHAR (100)  NULL,
    [DeprExpenseGLAccount]             VARCHAR (100)  NULL,
    [AccumDeprGLAccount]               VARCHAR (100)  NULL,
    [AssetSaleGLAccount]               VARCHAR (100)  NULL,
    [AssetWriteOffGLAccount]           VARCHAR (100)  NULL,
    [AssetWriteDownGLAccount]          VARCHAR (100)  NULL,
    [LegalEntity]                      VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_DeprNonDeprTangibleAssetsAudit] PRIMARY KEY CLUSTERED ([AuditDeprNonDeprTangibleAssetsId] ASC)
);

