CREATE TABLE [dbo].[EngineRegistryHeader] (
    [EngineRegistryId]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [MakeTypeId]           BIGINT          NULL,
    [MakeType]             VARCHAR (100)   NULL,
    [EngineModelId]        BIGINT          NULL,
    [EngineModel]          VARCHAR (100)   NULL,
    [EngineSubModel]       VARCHAR (100)   NULL,
    [NumOfEngines]         INT             NULL,
    [TailNum]              VARCHAR (50)    NULL,
    [SerialNum]            VARCHAR (100)   NULL,
    [ManufacturedDate]     DATETIME2 (7)   NULL,
    [PlaceInServiceDate]   DATETIME2 (7)   NULL,
    [TotalTSN]             DECIMAL (18, 2) NULL,
    [TotalCSN]             DECIMAL (18, 2) NULL,
    [Hobbs]                DECIMAL (18, 2) NULL,
    [EngineLocation]       VARCHAR (200)   NULL,
    [NextScheduled]        DATETIME2 (7)   NULL,
    [MEL]                  BIT             NULL,
    [EngineStatusId]       BIGINT          NULL,
    [EngineStatus]         VARCHAR (100)   NULL,
    [MaintenanceStatusId]  BIGINT          NULL,
    [MaintenanceStatus]    VARCHAR (100)   NULL,
    [CustomerId]           BIGINT          NULL,
    [CustomerName]         VARCHAR (100)   NULL,
    [Memo]                 VARCHAR (MAX)   NULL,
    [StockLineId]          BIGINT          NULL,
    [IsActive]             BIT             CONSTRAINT [DF_EngineRegistry_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]            BIT             CONSTRAINT [DF_EngineRegistry_IsDeleted] DEFAULT ((0)) NOT NULL,
    [MasterCompanyId]      INT             NOT NULL,
    [CreatedBy]            VARCHAR (256)   NOT NULL,
    [UpdatedBy]            VARCHAR (256)   NOT NULL,
    [CreatedDate]          DATETIME2 (7)   CONSTRAINT [DF_EngineRegistry_CreatedDate] DEFAULT (sysdatetime()) NOT NULL,
    [UpdatedDate]          DATETIME2 (7)   CONSTRAINT [DF_EngineRegistry_UpdatedDate] DEFAULT (sysdatetime()) NOT NULL,
    [EngineRegistryNumber] VARCHAR (30)    NULL,
    [LastMaintenanceDate]  DATETIME        NULL,
    [TotalTSNMM]           DECIMAL (18, 6) NULL,
    [TotalCSNMM]           DECIMAL (18, 6) NULL,
    [LastFlownDate]        DATETIME2 (7)   NULL,
    [Description]          VARCHAR (256)   NULL,
    [EngineName]           VARCHAR (256)   NULL,
    CONSTRAINT [PK_EngineRegistry] PRIMARY KEY CLUSTERED ([EngineRegistryId] ASC),
    CONSTRAINT [FK_EngineRegistry_MaintenanceStatus] FOREIGN KEY ([MaintenanceStatusId]) REFERENCES [dbo].[MaintenanceStatus] ([MaintenanceStatusId]),
    CONSTRAINT [FK_EngineRegistry_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId])
);

