CREATE TABLE [dbo].[LeaseStocklineAudit] (
    [LeaseStocklineAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [LeaseStocklineId]      BIGINT          NOT NULL,
    [LeasePartId]           BIGINT          NOT NULL,
    [PNDescription]         NVARCHAR (500)  NULL,
    [QtyOrder]              INT             NOT NULL,
    [QtyReserved]           INT             NOT NULL,
    [QtyAvailable]          INT             NOT NULL,
    [QtyOH]                 INT             NOT NULL,
    [SN]                    NVARCHAR (100)  NULL,
    [StockLineId]           BIGINT          NOT NULL,
    [StocklineNumber]       VARCHAR (100)   NULL,
    [ConditionId]           BIGINT          NOT NULL,
    [OutrightPrice]         DECIMAL (18, 2) NULL,
    [FlatRate]              DECIMAL (18, 2) NULL,
    [PricingMethod]         NVARCHAR (100)  NULL,
    [BillingInterval]       NVARCHAR (100)  NULL,
    [MinimumCycles]         DECIMAL (18, 2) NULL,
    [MinimumTimes]          DECIMAL (18, 2) NULL,
    [MaximumCycles]         DECIMAL (18, 2) NULL,
    [MaximumTimes]          DECIMAL (18, 2) NULL,
    [UsagePerUnitCycles]    DECIMAL (18, 2) NULL,
    [UsagePerUnitTimes]     DECIMAL (18, 2) NULL,
    [OverrunPerUnitCycles]  DECIMAL (18, 2) NULL,
    [OverrunPerUnitTimes]   DECIMAL (18, 2) NULL,
    [Maintenance]           DECIMAL (18, 2) NULL,
    [Insurance]             DECIMAL (18, 2) NULL,
    [Taxes]                 DECIMAL (18, 2) NULL,
    [RepairOrderId]         BIGINT          NULL,
    [RONumber]              VARCHAR (100)   NULL,
    [WorkOrderId]           BIGINT          NULL,
    [WorkOrderNo]           VARCHAR (100)   NULL,
    [IsActive]              BIT             NOT NULL,
    [IsDeleted]             BIT             NOT NULL,
    [MasterCompanyId]       INT             NOT NULL,
    [CreatedBy]             BIGINT          NULL,
    [CreatedDate]           DATETIME        NULL,
    [UpdatedBy]             BIGINT          NULL,
    [UpdatedDate]           DATETIME        NULL,
    [RateUnit]              NVARCHAR (50)   NULL,
    [BillingMethod]         NVARCHAR (50)   NULL,
    [MaintenancePer]        NVARCHAR (50)   NULL,
    [InsurancePer]          NVARCHAR (50)   NULL,
    [TaxesPer]              NVARCHAR (50)   NULL,
    CONSTRAINT [PK_LeaseStocklineAudit] PRIMARY KEY CLUSTERED ([LeaseStocklineAuditId] ASC)
);

