CREATE TABLE [dbo].[LotConsignmentAudit] (
    [ConsignmentAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [ConsignmentId]      BIGINT          NOT NULL,
    [ConsignmentNumber]  VARCHAR (100)   NULL,
    [ConsigneeName]      VARCHAR (256)   NULL,
    [MasterCompanyId]    INT             NULL,
    [CreatedBy]          VARCHAR (256)   NOT NULL,
    [UpdatedBy]          VARCHAR (256)   NULL,
    [CreatedDate]        DATETIME2 (7)   NOT NULL,
    [UpdatedDate]        DATETIME2 (7)   NULL,
    [IsActive]           BIT             NULL,
    [IsDeleted]          BIT             NULL,
    [ConsignmentName]    NVARCHAR (MAX)  NULL,
    [LotId]              BIGINT          NULL,
    [IsRevenue]          BIT             NULL,
    [IsMargin]           BIT             NULL,
    [IsFixedAmount]      BIT             NULL,
    [PercentId]          BIGINT          NULL,
    [PerAmount]          DECIMAL (18, 2) NULL,
    [ConsigneeTypeId]    INT             NULL,
    [ConsigneeId]        BIGINT          NULL,
    [IsRevenueSplit]     BIT             NULL,
    [ConsignorPercentId] BIGINT          NULL,
    CONSTRAINT [PK_LotConsignmentAudit] PRIMARY KEY CLUSTERED ([ConsignmentAuditId] ASC)
);

