CREATE TABLE [dbo].[VendorRFQRepairOrderPartAudit] (
    [VendorRFQROPartRecordAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [VendorRFQROPartRecordId]      BIGINT          NOT NULL,
    [VendorRFQRepairOrderId]       BIGINT          NOT NULL,
    [ItemMasterId]                 BIGINT          NOT NULL,
    [PartNumber]                   VARCHAR (250)   NULL,
    [PartDescription]              VARCHAR (MAX)   NULL,
    [AltEquiPartNumberId]          BIGINT          NULL,
    [AltEquiPartNumber]            VARCHAR (250)   NULL,
    [AltEquiPartDescription]       VARCHAR (MAX)   NULL,
    [RevisedPartId]                BIGINT          NULL,
    [RevisedPartNumber]            VARCHAR (250)   NULL,
    [StockType]                    VARCHAR (50)    NULL,
    [ManufacturerId]               BIGINT          NOT NULL,
    [Manufacturer]                 VARCHAR (250)   NULL,
    [PriorityId]                   BIGINT          CONSTRAINT [DF_VendorRFQRepairOrderPartAudit_PriorityId] DEFAULT ((0)) NOT NULL,
    [Priority]                     VARCHAR (50)    NULL,
    [NeedByDate]                   DATETIME2 (7)   NOT NULL,
    [PromisedDate]                 DATETIME2 (7)   NULL,
    [ConditionId]                  BIGINT          NOT NULL,
    [Condition]                    VARCHAR (256)   NULL,
    [WorkPerformedId]              BIGINT          NULL,
    [WorkPerformed]                VARCHAR (250)   NULL,
    [QuantityOrdered]              INT             NOT NULL,
    [UnitCost]                     DECIMAL (20, 2) NULL,
    [ExtendedCost]                 DECIMAL (20, 2) NULL,
    [WorkOrderId]                  BIGINT          NULL,
    [WorkOrderNo]                  VARCHAR (250)   NULL,
    [SubWorkOrderId]               BIGINT          NULL,
    [SubWorkOrderNo]               VARCHAR (250)   NULL,
    [SalesOrderId]                 BIGINT          NULL,
    [SalesOrderNo]                 VARCHAR (250)   NULL,
    [ItemTypeId]                   INT             NULL,
    [ItemType]                     VARCHAR (100)   NULL,
    [UOMId]                        BIGINT          NULL,
    [UnitOfMeasure]                VARCHAR (250)   NULL,
    [ManagementStructureId]        BIGINT          NOT NULL,
    [Level1]                       VARCHAR (200)   NULL,
    [Level2]                       VARCHAR (200)   NULL,
    [Level3]                       VARCHAR (200)   NULL,
    [Level4]                       VARCHAR (200)   NULL,
    [Memo]                         NVARCHAR (MAX)  NULL,
    [MasterCompanyId]              INT             NULL,
    [CreatedBy]                    VARCHAR (256)   NOT NULL,
    [UpdatedBy]                    VARCHAR (256)   NOT NULL,
    [CreatedDate]                  DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                  DATETIME2 (7)   NULL,
    [IsActive]                     BIT             CONSTRAINT [DF_VendorRFQRepairOrderPartAudit_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                    BIT             CONSTRAINT [DF_VendorRFQRepairOrderPartAudit_IsDeleted] DEFAULT ((0)) NOT NULL,
    [RepairOrderId]                BIGINT          NULL,
    [RepairOrderNumber]            VARCHAR (50)    NULL,
    CONSTRAINT [PK_VendorRFQRepairOrderPartAudit] PRIMARY KEY CLUSTERED ([VendorRFQROPartRecordAuditId] ASC)
);

