CREATE TABLE [dbo].[WorkOrederMaterialsROHistory] (
    [WOMROHistorId]        BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderId]          BIGINT          NOT NULL,
    [WorkOrderMaterialsId] BIGINT          NOT NULL,
    [RepairOrderId]        BIGINT          NOT NULL,
    [RepairOrderPartId]    BIGINT          NOT NULL,
    [StocklineId]          BIGINT          NOT NULL,
    [VendorId]             BIGINT          NOT NULL,
    [PartNumber]           VARCHAR (50)    NULL,
    [PNDescription]        VARCHAR (MAX)   NULL,
    [SerialNum]            NVARCHAR (50)   NULL,
    [Quantity]             INT             NULL,
    [POCost]               DECIMAL (18, 2) NULL,
    [RepairCost]           DECIMAL (18, 2) NULL,
    [UnitCost]             DECIMAL (18, 2) NULL,
    [ExtendedCost]         DECIMAL (18, 2) NULL,
    [RODate]               DATETIME2 (7)   NOT NULL,
    [RORecDate]            DATETIME2 (7)   NOT NULL,
    [MasterCompanyId]      INT             NOT NULL,
    [CreatedBy]            VARCHAR (256)   NOT NULL,
    [UpdatedBy]            VARCHAR (256)   NOT NULL,
    [CreatedDate]          DATETIME2 (7)   CONSTRAINT [DF__WorkOrederMaterialsROHistory_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]          DATETIME2 (7)   CONSTRAINT [DF_WorkOrederMaterialsROHistory_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]             BIT             CONSTRAINT [DF_WorkOrederMaterialsROHistory_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]            BIT             CONSTRAINT [DF_WorkOrederMaterialsROHistory_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_WorkOrederMaterialsROHistory_WOMROHistorId] PRIMARY KEY CLUSTERED ([WOMROHistorId] ASC),
    CONSTRAINT [FK_WorkOrederMaterialsROHistory_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId])
);

