CREATE TABLE [dbo].[WorkOrderQuoteLaborAudit] (
    [WorkOrderQuoteLaborAuditId]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderQuoteLaborId]       BIGINT          NOT NULL,
    [WorkOrderQuoteLaborHeaderId] BIGINT          NOT NULL,
    [ExpertiseId]                 SMALLINT        NOT NULL,
    [Hours]                       DECIMAL (10, 2) NOT NULL,
    [BillableId]                  INT             NOT NULL,
    [CreatedBy]                   VARCHAR (256)   NOT NULL,
    [UpdatedBy]                   VARCHAR (256)   NOT NULL,
    [CreatedDate]                 DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                 DATETIME2 (7)   NOT NULL,
    [IsActive]                    BIT             NOT NULL,
    [IsDeleted]                   BIT             NOT NULL,
    [TaskId]                      BIGINT          NOT NULL,
    [DirectLaborOHCost]           DECIMAL (20, 2) NOT NULL,
    [MarkupPercentageId]          BIGINT          NULL,
    [BurdenRateAmount]            DECIMAL (20, 2) NULL,
    [TotalCostPerHour]            DECIMAL (20, 2) NULL,
    [TotalCost]                   DECIMAL (20, 2) NULL,
    [BillingRate]                 DECIMAL (20, 2) NULL,
    [BillingAmount]               DECIMAL (20, 2) NULL,
    [BurdaenRatePercentageId]     BIGINT          NULL,
    [BillingMethodId]             INT             NULL,
    [MasterCompanyId]             INT             NULL,
    [TaskName]                    VARCHAR (100)   NULL,
    [Expertise]                   VARCHAR (50)    NULL,
    [Billabletype]                VARCHAR (50)    NULL,
    [BurdaenRatePercentage]       VARCHAR (50)    NULL,
    [BillingName]                 VARCHAR (50)    NULL,
    [MarkUp]                      VARCHAR (50)    NULL,
    [EmployeeId]                  BIGINT          NULL,
    CONSTRAINT [PK_WorkOrderQuoteLaborAudit] PRIMARY KEY CLUSTERED ([WorkOrderQuoteLaborAuditId] ASC)
);

