CREATE TABLE [dbo].[WorkOrderStockAudit] (
    [WOStockAuditId]       BIGINT        IDENTITY (1, 1) NOT NULL,
    [WorkOrderMaterialsId] BIGINT        NOT NULL,
    [StockLIneId]          BIGINT        NOT NULL,
    [ConditionId]          BIGINT        NOT NULL,
    [ItemMasterId]         BIGINT        NOT NULL,
    [AltPartMasterPartId]  BIGINT        NULL,
    [EquPartMasterPartId]  BIGINT        NULL,
    [IsAltPart]            BIT           NULL,
    [IsEquPart]            BIT           NULL,
    [QtyReserved]          INT           NULL,
    [QtyUnReserved]        INT           NULL,
    [QtyIssued]            INT           NULL,
    [QtyUnIssued]          INT           NULL,
    [ResIssuedById]        BIGINT        NOT NULL,
    [ResIssuedDate]        DATETIME2 (7) NOT NULL,
    [PartStatusId]         INT           NOT NULL,
    [MasterCompanyId]      INT           NOT NULL,
    [CreatedBy]            VARCHAR (256) NOT NULL,
    [UpdatedBy]            VARCHAR (256) NOT NULL,
    [CreatedDate]          DATETIME2 (7) CONSTRAINT [DF_WorkOrderStockAudit_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]          DATETIME2 (7) CONSTRAINT [DF_WorkOrderStockAudit_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]             BIT           CONSTRAINT [DF_WorkOrderStockAudit_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]            BIT           CONSTRAINT [DF_WorkOrderStockAudit_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_WorkOrderStockAudit] PRIMARY KEY CLUSTERED ([WOStockAuditId] ASC),
    CONSTRAINT [FK_WorkOrderStockAudit_ConditionId] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([ConditionId]),
    CONSTRAINT [FK_WorkOrderStockAudit_ItemMasterId] FOREIGN KEY ([ItemMasterId]) REFERENCES [dbo].[ItemMaster] ([ItemMasterId]),
    CONSTRAINT [FK_WorkOrderStockAudit_MasterCompanyId] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId]),
    CONSTRAINT [FK_WorkOrderStockAudit_ReservedById] FOREIGN KEY ([ResIssuedById]) REFERENCES [dbo].[Employee] ([EmployeeId]),
    CONSTRAINT [FK_WorkOrderStockAudit_StockLIneId] FOREIGN KEY ([StockLIneId]) REFERENCES [dbo].[Stockline] ([StockLineId])
);

