CREATE TABLE [dbo].[WorkOrderShippingAudit] (
    [WorkOrderShippingAuditId]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderShippingId]                BIGINT          NOT NULL,
    [WorkOrderId]                        BIGINT          NOT NULL,
    [WorkOrderPartNoId]                  BIGINT          NULL,
    [WorkflowWorkOrderId]                BIGINT          NOT NULL,
    [WOShippingNum]                      VARCHAR (50)    NULL,
    [WOShippingStatusId]                 BIGINT          NOT NULL,
    [OpenDate]                           DATETIME2 (7)   NOT NULL,
    [CustomerId]                         BIGINT          NOT NULL,
    [ShipViaId]                          BIGINT          NOT NULL,
    [ShipDate]                           DATETIME2 (7)   NOT NULL,
    [AirwayBill]                         VARCHAR (50)    NULL,
    [HouseAirwayBill]                    VARCHAR (50)    NULL,
    [TrackingNum]                        VARCHAR (50)    NULL,
    [Weight]                             DECIMAL (10, 2) NOT NULL,
    [SoldToName]                         VARCHAR (256)   NOT NULL,
    [SoldToAddress1]                     VARCHAR (256)   NOT NULL,
    [SoldToAddress2]                     VARCHAR (256)   NULL,
    [SoldToCity]                         VARCHAR (256)   NOT NULL,
    [SoldToState]                        VARCHAR (256)   NOT NULL,
    [SoldToZip]                          VARCHAR (20)    NOT NULL,
    [SoldToCountryId]                    SMALLINT        NOT NULL,
    [ShipToName]                         VARCHAR (256)   NOT NULL,
    [ShipToSiteName]                     VARCHAR (256)   NOT NULL,
    [ShipToSiteId]                       BIGINT          NOT NULL,
    [ShipToAddress1]                     VARCHAR (256)   NOT NULL,
    [ShipToAddress2]                     VARCHAR (256)   NOT NULL,
    [ShipToCity]                         VARCHAR (256)   NOT NULL,
    [ShipToState]                        VARCHAR (256)   NOT NULL,
    [ShipToZip]                          VARCHAR (20)    NOT NULL,
    [ShipToCountryId]                    SMALLINT        NOT NULL,
    [OriginName]                         VARCHAR (256)   NOT NULL,
    [OriginAddress1]                     VARCHAR (256)   NOT NULL,
    [OriginAddress2]                     VARCHAR (256)   NULL,
    [OriginCity]                         VARCHAR (256)   NOT NULL,
    [OriginState]                        VARCHAR (256)   NOT NULL,
    [OriginZip]                          VARCHAR (20)    NOT NULL,
    [OriginCountryId]                    SMALLINT        NOT NULL,
    [MasterCompanyId]                    INT             NOT NULL,
    [CreatedBy]                          VARCHAR (256)   NOT NULL,
    [UpdatedBy]                          VARCHAR (256)   NOT NULL,
    [CreatedDate]                        DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                        DATETIME2 (7)   NOT NULL,
    [IsActive]                           BIT             NOT NULL,
    [IsDeleted]                          BIT             NOT NULL,
    [Shipment]                           VARCHAR (100)   NULL,
    [SoldToSiteId]                       BIGINT          NOT NULL,
    [SoldToSiteName]                     VARCHAR (256)   NOT NULL,
    [SoldToCountryName]                  VARCHAR (256)   NOT NULL,
    [ShipToCustomerId]                   BIGINT          NOT NULL,
    [ShipToCountryName]                  VARCHAR (256)   NOT NULL,
    [OriginCountryName]                  VARCHAR (256)   NOT NULL,
    [OriginSiteId]                       BIGINT          NOT NULL,
    [IsSameForShipTo]                    BIT             NULL,
    [ShipSizeLength]                     DECIMAL (10, 2) NULL,
    [ShipSizeWidth]                      DECIMAL (10, 2) NULL,
    [ShipSizeHeight]                     DECIMAL (10, 2) NULL,
    [ShipWeightUnit]                     BIGINT          NULL,
    [ShipSizeUnitOfMeasureId]            BIGINT          NULL,
    [PickTicketId]                       BIGINT          NULL,
    [NoOfContainer]                      INT             NULL,
    [shipAttention]                      VARCHAR (100)   NULL,
    [soldAttention]                      VARCHAR (100)   NULL,
    [CustomerDomensticShippingShipViaId] BIGINT          NULL,
    [ShippingAccountInfo]                VARCHAR (200)   NULL,
    [NoOfItems]                          INT             NULL,
    [IsCustomerShipping]                 BIT             NULL,
    [IsManualShipping]                   BIT             NULL,
    [ManufactureCountryId]               INT             NULL,
    [QtyUOM]                             BIGINT          NULL,
    [UnitPrice]                          DECIMAL (20, 2) NULL,
    [UnitPriceCurrencyId]                INT             NULL,
    [Notes]                              VARCHAR (MAX)   NULL,
    [isIgnoreAWB]                        BIT             NULL,
    CONSTRAINT [PK_WorkOrderShippingAudit] PRIMARY KEY CLUSTERED ([WorkOrderShippingAuditId] ASC)
);





