CREATE TABLE [dbo].[WorkOrderQuoteMaterialAudit] (
    [WorkOrderQuoteMaterialAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderQuoteMaterialId]      BIGINT          NOT NULL,
    [WorkOrderQuoteDetailsId]       BIGINT          NOT NULL,
    [ItemMasterId]                  BIGINT          NOT NULL,
    [ConditionCodeId]               BIGINT          NOT NULL,
    [ItemClassificationId]          BIGINT          NOT NULL,
    [Quantity]                      INT             NOT NULL,
    [UnitOfMeasureId]               BIGINT          NOT NULL,
    [UnitCost]                      DECIMAL (20, 2) NOT NULL,
    [ExtendedCost]                  DECIMAL (20, 2) NOT NULL,
    [Memo]                          NVARCHAR (MAX)  NULL,
    [IsDefered]                     BIT             NULL,
    [MasterCompanyId]               INT             NOT NULL,
    [CreatedBy]                     VARCHAR (256)   NOT NULL,
    [UpdatedBy]                     VARCHAR (256)   NOT NULL,
    [CreatedDate]                   DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                   DATETIME2 (7)   NOT NULL,
    [IsActive]                      BIT             NOT NULL,
    [IsDeleted]                     BIT             NOT NULL,
    [MarkupPercentageId]            BIGINT          NULL,
    [TaskId]                        BIGINT          NOT NULL,
    [MarkupFixedPrice]              VARCHAR (15)    NULL,
    [BillingAmount]                 DECIMAL (20, 2) NULL,
    [BillingRate]                   DECIMAL (20, 2) NULL,
    [HeaderMarkupId]                BIGINT          NULL,
    [ProvisionId]                   INT             NOT NULL,
    [MaterialMandatoriesId]         INT             NULL,
    [BillingMethodId]               INT             NULL,
    [TaskName]                      VARCHAR (100)   NULL,
    [PartNumber]                    VARCHAR (50)    NULL,
    [PartDescription]               VARCHAR (500)   NULL,
    [Provision]                     VARCHAR (50)    NULL,
    [UomName]                       VARCHAR (50)    NULL,
    [Conditiontype]                 VARCHAR (50)    NULL,
    [Stocktype]                     VARCHAR (50)    NULL,
    [BillingName]                   VARCHAR (50)    NULL,
    [MarkUp]                        VARCHAR (50)    NULL,
    CONSTRAINT [PK_WorkOrderQuoteMaterialAudit] PRIMARY KEY CLUSTERED ([WorkOrderQuoteMaterialAuditId] ASC)
);

