CREATE TABLE [dbo].[WorkOrderUnReservedStock] (
    [WOUnReservedStockId]  BIGINT        IDENTITY (1, 1) NOT NULL,
    [WorkOrderMaterialsId] BIGINT        NOT NULL,
    [StockLIneId]          BIGINT        NOT NULL,
    [ConditionId]          BIGINT        NOT NULL,
    [ItemMasterId]         BIGINT        NOT NULL,
    [Quantity]             INT           NOT NULL,
    [AltPartMasterPartId]  BIGINT        NULL,
    [EquPartMasterPartId]  BIGINT        NULL,
    [IsAltPart]            BIT           NULL,
    [IsEquPart]            BIT           NULL,
    [UnReservedById]       BIGINT        NOT NULL,
    [UnReservedDate]       DATETIME2 (7) NOT NULL,
    [MasterCompanyId]      INT           NOT NULL,
    [CreatedBy]            VARCHAR (256) NOT NULL,
    [UpdatedBy]            VARCHAR (256) NOT NULL,
    [CreatedDate]          DATETIME2 (7) CONSTRAINT [DF_WorkOrderUnReservedStock_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]          DATETIME2 (7) CONSTRAINT [DF_WorkOrderUnReservedStock_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]             BIT           CONSTRAINT [DF_WorkOrderUnReservedStock_IsActive] DEFAULT ((0)) NOT NULL,
    [IsDeleted]            BIT           CONSTRAINT [DF_WorkOrderUnReservedStock_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_WorkOrderUnReservedStock] PRIMARY KEY CLUSTERED ([WOUnReservedStockId] ASC),
    CONSTRAINT [FK_WorkOrderUnReservedStock_ConditionId] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([ConditionId]),
    CONSTRAINT [FK_WorkOrderUnReservedStock_ItemMasterId] FOREIGN KEY ([ItemMasterId]) REFERENCES [dbo].[ItemMaster] ([ItemMasterId]),
    CONSTRAINT [FK_WorkOrderUnReservedStock_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId]),
    CONSTRAINT [FK_WorkOrderUnReservedStock_StockLine] FOREIGN KEY ([StockLIneId]) REFERENCES [dbo].[Stockline] ([StockLineId]),
    CONSTRAINT [FK_WorkOrderUnReservedStock_UnReservedById] FOREIGN KEY ([UnReservedById]) REFERENCES [dbo].[Employee] ([EmployeeId]),
    CONSTRAINT [FK_WorkOrderUnReservedStock_WorkOrderMaterials] FOREIGN KEY ([WorkOrderMaterialsId]) REFERENCES [dbo].[WorkOrderMaterials] ([WorkOrderMaterialsId])
);

