CREATE TABLE [dbo].[SpeedQuotePartAudit] (
    [AuditSpeedQuotePartId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [SpeedQuotePartId]         BIGINT          NOT NULL,
    [SpeedQuoteId]             BIGINT          NULL,
    [ItemMasterId]             BIGINT          NULL,
    [QuantityRequested]        INT             NULL,
    [ConditionId]              BIGINT          CONSTRAINT [DF_SpeedQuotePartAudit_ConditionId_1] DEFAULT ((0)) NOT NULL,
    [UnitSalePrice]            NUMERIC (18, 2) NULL,
    [UnitCost]                 NUMERIC (18, 2) CONSTRAINT [DF_SpeedQuotePartAudit_UnitCost_1] DEFAULT ((0)) NULL,
    [MarginAmount]             NUMERIC (18, 2) CONSTRAINT [DF_SpeedQuotePartAudit_MarginAmount_1] DEFAULT ((0)) NULL,
    [MarginPercentage]         NUMERIC (18, 2) NULL,
    [SalesPriceExtended]       NUMERIC (18, 2) CONSTRAINT [DF_SpeedQuotePartAudit_SalesPriceExtended_1] DEFAULT ((0)) NULL,
    [UnitCostExtended]         NUMERIC (18, 2) CONSTRAINT [DF_SpeedQuotePartAudit_UnitCostExtended_1] DEFAULT ((0)) NULL,
    [MarginAmountExtended]     NUMERIC (18, 2) CONSTRAINT [DF_SpeedQuotePartAudit_MarginAmountExtended_1] DEFAULT ((0)) NULL,
    [MarginPercentageExtended] NUMERIC (18, 2) CONSTRAINT [DF_SpeedQuotePartAudit_MarginPercentageExtended_1] DEFAULT ((0)) NULL,
    [CreatedBy]                VARCHAR (256)   NOT NULL,
    [CreatedDate]              DATETIME2 (7)   CONSTRAINT [DF_SpeedQuotePartAudit_CreatedDate_1] DEFAULT (getdate()) NOT NULL,
    [UpdatedBy]                VARCHAR (256)   NOT NULL,
    [UpdatedDate]              DATETIME2 (7)   CONSTRAINT [DF_SpeedQuotePartAudit_UpdatedDate_1] DEFAULT (getdate()) NOT NULL,
    [IsDeleted]                BIT             CONSTRAINT [DF_SpeedQuotePartAudit_IsDeleted_1] DEFAULT ((0)) NOT NULL,
    [IsActive]                 BIT             CONSTRAINT [DF_SpeedQuotePartAudit_IsActive_1] DEFAULT ((1)) NOT NULL,
    [MasterCompanyId]          INT             NOT NULL,
    [Notes]                    NVARCHAR (MAX)  NULL,
    [CurrencyId]               INT             NULL,
    [PartNumber]               NVARCHAR (100)  NULL,
    [PartDescription]          NVARCHAR (MAX)  NULL,
    [ConditionName]            NVARCHAR (100)  NULL,
    [CurrencyName]             NVARCHAR (100)  NULL,
    [ManufacturerId]           BIGINT          NULL,
    [Manufacturer]             VARCHAR (50)    NULL,
    [Type]                     VARCHAR (50)    NULL,
    [TAT]                      INT             CONSTRAINT [DF_SpeedQuotePartAudit_TAT_1] DEFAULT ((0)) NULL,
    [StatusId]                 INT             NULL,
    [StatusName]               NVARCHAR (100)  NULL,
    [ItemNo]                   INT             DEFAULT ((0)) NOT NULL,
    [Code]                     VARCHAR (100)   NULL,
    CONSTRAINT [PK_SpeedQuotePartAudit] PRIMARY KEY CLUSTERED ([AuditSpeedQuotePartId] ASC)
);

