CREATE TABLE [dbo].[VendorProformaInvoiceHeaderAudit] (
    [VendorProformaInvoiceAuditId] BIGINT        IDENTITY (1, 1) NOT NULL,
    [VendorProformaInvoiceId]      BIGINT        NOT NULL,
    [VendorProformaInvoiceNo]      VARCHAR (150) NULL,
    [VendorId]                     BIGINT        NOT NULL,
    [VendorName]                   VARCHAR (256) NOT NULL,
    [VendorCode]                   VARCHAR (256) NOT NULL,
    [PaymentTermsId]               BIGINT        NOT NULL,
    [PaymentMethodId]              BIGINT        NULL,
    [EmployeeId]                   BIGINT        NULL,
    [IsEnforcePoRoApproval]        BIT           NULL,
    [ApproverId]                   BIGINT        NULL,
    [ApprovedBy]                   VARCHAR (100) NULL,
    [DateApproved]                 DATETIME2 (7) NULL,
    [EntryDate]                    DATETIME2 (7) NULL,
    [InvoiceNumber]                VARCHAR (150) NULL,
    [InvoiceDate]                  DATETIME2 (7) NULL,
    [AccountingCalendarId]         BIGINT        NULL,
    [CurrencyId]                   BIGINT        NULL,
    [PostedDate]                   DATETIME2 (7) NULL,
    [IsUsedInVendorPayment]        BIT           NULL,
    [StatusId]                     INT           NOT NULL,
    [ManagementStructureId]        INT           NOT NULL,
    [MasterCompanyId]              INT           NOT NULL,
    [CreatedBy]                    VARCHAR (100) NOT NULL,
    [CreatedDate]                  DATETIME2 (7) NOT NULL,
    [UpdatedBy]                    VARCHAR (100) NOT NULL,
    [UpdatedDate]                  DATETIME2 (7) NOT NULL,
    [IsActive]                     BIT           NOT NULL,
    [IsDeleted]                    BIT           NOT NULL,
    [ReferenceId]                  BIGINT        NULL,
    [ReferenceNumber]              VARCHAR (150) NULL,
    [ReferenceModuleId]            INT           NULL,
    [ReferenceModuleName]          VARCHAR (150) NULL,
    [IsPurchaseOrder]              BIT           NOT NULL,
    [ControlNumber]                VARCHAR (150) NULL,
    CONSTRAINT [PK_VendorProformaInvoiceHeaderAudit] PRIMARY KEY CLUSTERED ([VendorProformaInvoiceAuditId] ASC)
);

