CREATE TABLE [dbo].[WorkflowMaterialAudit] (
    [WorkflowMaterialAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkflowMaterialListId]  BIGINT          NOT NULL,
    [WorkflowId]              BIGINT          NOT NULL,
    [ItemMasterId]            BIGINT          NOT NULL,
    [TaskId]                  BIGINT          NULL,
    [Quantity]                SMALLINT        NULL,
    [UnitOfMeasureId]         BIGINT          NULL,
    [ConditionCodeId]         BIGINT          NULL,
    [UnitCost]                DECIMAL (18, 2) NULL,
    [ExtendedCost]            DECIMAL (18, 2) NULL,
    [Price]                   DECIMAL (18, 2) NULL,
    [ProvisionId]             INT             NULL,
    [IsDeferred]              BIT             NULL,
    [WorkflowActionId]        TINYINT         NOT NULL,
    [Memo]                    NVARCHAR (MAX)  NULL,
    [MasterCompanyId]         INT             NOT NULL,
    [CreatedBy]               VARCHAR (256)   NULL,
    [UpdatedBy]               VARCHAR (256)   NULL,
    [CreatedDate]             DATETIME2 (7)   NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   NOT NULL,
    [IsActive]                BIT             NULL,
    [IsDeleted]               BIT             NOT NULL,
    [MaterialMandatoriesName] VARCHAR (256)   NULL,
    [PartNumber]              VARCHAR (256)   NULL,
    [PartDescription]         VARCHAR (MAX)   NULL,
    [ItemClassificationId]    BIGINT          NULL,
    [ExtendedPrice]           DECIMAL (18, 2) NULL,
    [Order]                   INT             NULL,
    [MaterialMandatoriesId]   INT             NULL,
    [WFParentId]              BIGINT          NULL,
    [IsVersionIncrease]       BIT             NULL,
    [Figure]                  NVARCHAR (50)   NULL,
    [Item]                    NVARCHAR (50)   NULL,
    CONSTRAINT [PK_WorkflowMaterialAudit] PRIMARY KEY CLUSTERED ([WorkflowMaterialAuditId] ASC)
);

