CREATE TABLE [dbo].[WorkOrderBillingInvoicingItemAudit] (
    [AuditWOBillingInvoicingItemId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [WOBillingInvoicingItemId]      BIGINT          NULL,
    [WOBillingInvoicingId]          BIGINT          NULL,
    [NoofPieces]                    INT             NULL,
    [WorkOrderPartId]               BIGINT          NULL,
    [ItemMasterId]                  BIGINT          NULL,
    [MasterCompanyId]               INT             NULL,
    [CreatedBy]                     VARCHAR (256)   NULL,
    [UpdatedBy]                     VARCHAR (256)   NULL,
    [CreatedDate]                   DATETIME2 (7)   NULL,
    [UpdatedDate]                   DATETIME2 (7)   NULL,
    [IsActive]                      BIT             NULL,
    [IsDeleted]                     BIT             NULL,
    [UnitPrice]                     DECIMAL (20, 2) NULL,
    [MaterialCost]                  DECIMAL (18, 2) NULL,
    [LaborCost]                     DECIMAL (18, 2) NULL,
    [MiscCharges]                   DECIMAL (20, 2) NULL,
    [Freight]                       DECIMAL (20, 2) NULL,
    [SubTotal]                      DECIMAL (20, 2) NULL,
    [TaxRate]                       DECIMAL (20, 2) NULL,
    [SalesTax]                      DECIMAL (20, 2) NULL,
    [OtherTaxRate]                  DECIMAL (18, 2) NULL,
    [OtherTax]                      DECIMAL (20, 2) NULL,
    [GrandTotal]                    DECIMAL (18, 2) NULL,
    [PDFPath]                       NVARCHAR (MAX)  NULL,
    [VersionNo]                     VARCHAR (20)    NULL,
    [IsVersionIncrease]             BIT             NULL,
    [ConditionId]                   BIGINT          NULL,
    [IsPerformaInvoice]             BIT             NULL,
    [IsInvoicePosted]               BIT             NULL,
    CONSTRAINT [PK_WorkOrderBillingInvoicingItemAudit] PRIMARY KEY CLUSTERED ([AuditWOBillingInvoicingItemId] ASC)
);

