CREATE TABLE [dbo].[WorkOrderPreAssemblyInspectionAudit] (
    [WorkOrderPreAssemblyInspectionAuditId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [WorkOrderPreAssemblyInspectionId]      BIGINT         NOT NULL,
    [WorkOrderTeardownId]                   BIGINT         NULL,
    [Memo]                                  NVARCHAR (MAX) NULL,
    [TechnicianId]                          BIGINT         NULL,
    [TechnicianDate]                        DATETIME2 (7)  NULL,
    [InspectorId]                           BIGINT         NULL,
    [InspectorDate]                         DATETIME2 (7)  NULL,
    [ReasonId]                              BIGINT         NULL,
    [SubWorkOrderTeardownId]                BIGINT         NULL,
    [ReasonName]                            VARCHAR (200)  NULL,
    [InspectorName]                         VARCHAR (100)  NULL,
    [TechnicalName]                         VARCHAR (100)  NULL,
    [CreatedBy]                             VARCHAR (256)  NOT NULL,
    [UpdatedBy]                             VARCHAR (256)  NOT NULL,
    [CreatedDate]                           DATETIME2 (7)  NOT NULL,
    [UpdatedDate]                           DATETIME2 (7)  NOT NULL,
    [IsActive]                              BIT            NOT NULL,
    [IsDeleted]                             BIT            NOT NULL,
    [MasterCompanyId]                       INT            NOT NULL,
    [IsDocument]                            BIT            NOT NULL,
    CONSTRAINT [PK_WorkOrderPreAssemblyInspectionAudit] PRIMARY KEY CLUSTERED ([WorkOrderPreAssemblyInspectionAuditId] ASC)
);

