CREATE TABLE [dbo].[YearEndCloseProcessAudit] (
    [YearEndCloseProcessAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [YearEndCloseProcessId]      BIGINT          NOT NULL,
    [Year]                       INT             NULL,
    [StartPeriodId]              BIGINT          NULL,
    [EndPeriodId]                BIGINT          NULL,
    [ExecuteDate]                DATETIME2 (7)   NULL,
    [MasterCompanyId]            INT             NOT NULL,
    [CreatedBy]                  VARCHAR (256)   NULL,
    [UpdatedBy]                  VARCHAR (256)   NULL,
    [CreatedDate]                DATETIME2 (7)   NULL,
    [UpdatedDate]                DATETIME2 (7)   NULL,
    [IsActive]                   BIT             NULL,
    [IsDeleted]                  BIT             NULL,
    [LegalEntity]                VARCHAR (100)   NULL,
    [LegalEntityId]              VARCHAR (100)   NULL,
    [Memo]                       VARCHAR (MAX)   NULL,
    [VersionNumber]              VARCHAR (50)    NULL,
    [CurrentVersionNumber]       BIGINT          NULL,
    [IsVersionIncrease]          BIT             NULL,
    [YearEndDate]                DATETIME        NULL,
    [Revenue]                    DECIMAL (18, 2) NULL,
    [Expenses]                   DECIMAL (18, 2) NULL,
    [NetEarning]                 DECIMAL (18, 2) NULL,
    [PreviousYearRevenue]        DECIMAL (18, 2) NULL,
    [NetRevenue]                 DECIMAL (18, 2) NULL,
    CONSTRAINT [PK_YearEndCloseProcessAudit] PRIMARY KEY CLUSTERED ([YearEndCloseProcessAuditId] ASC)
);

