CREATE TYPE [dbo].[AddexchangeloanType] AS TABLE (
    [ItemMasterLoanExchId]  BIGINT          NULL,
    [ItemMasterId]          BIGINT          NULL,
    [IsLoan]                BIT             NULL,
    [IsExchange]            BIT             NULL,
    [ExchangeCurrencyId]    BIGINT          NULL,
    [LoanCurrencyId]        BIGINT          NULL,
    [ExchangeListPrice]     DECIMAL (18, 6) NULL,
    [ExchangeCorePrice]     DECIMAL (18, 6) NULL,
    [ExchangeOverhaulPrice] DECIMAL (18, 6) NULL,
    [ExchangeOutrightPrice] DECIMAL (18, 6) NULL,
    [ExchangeCoreCost]      DECIMAL (18, 6) NULL,
    [LoanCorePrice]         DECIMAL (18, 6) NULL,
    [LoanOutrightPrice]     DECIMAL (18, 6) NULL,
    [LoanFees]              DECIMAL (18, 6) NULL,
    [MasterCompanyId]       INT             NULL,
    [CreatedBy]             VARCHAR (250)   NULL,
    [CreatedDate]           DATETIME2 (7)   NULL,
    [UpdatedBy]             VARCHAR (250)   NULL,
    [UpdatedDate]           DATETIME2 (7)   NULL,
    [IsActive]              BIT             NULL,
    [IsDeleted]             BIT             NULL,
    [ExchangeOverhaulCost]  DECIMAL (18, 6) NULL,
    [EFcogs]                INT             NULL,
    [OPcogs]                INT             NULL,
    [EFcogsamount]          DECIMAL (18, 6) NULL,
    [OPcogsamount]          DECIMAL (18, 6) NULL);

