CREATE TYPE [dbo].[AircraftPublicationType] AS TABLE (
    [AircraftPublicationId]   BIGINT         NULL,
    [PubDate]                 DATETIME2 (7)  NULL,
    [PublicationTypeId]       BIGINT         NULL,
    [PubNum]                  VARCHAR (50)   NULL,
    [RevisionNum]             VARCHAR (50)   NULL,
    [AircraftSectionId]       BIGINT         NULL,
    [Subject]                 NVARCHAR (MAX) NULL,
    [PublishedById]           BIGINT         NULL,
    [PublishedByRefId]        BIGINT         NULL,
    [PublishedByOthers]       VARCHAR (100)  NULL,
    [ComplianceCategoryId]    BIGINT         NULL,
    [ComplianceCategory]      VARCHAR (50)   NULL,
    [Timeframe]               NVARCHAR (MAX) NULL,
    [PurposeReasonBackground] NVARCHAR (MAX) NULL,
    [EntryDate]               DATETIME2 (7)  NULL,
    [VerifiedBy]              BIGINT         NULL,
    [MasterCompanyId]         INT            NULL,
    [CreatedBy]               VARCHAR (256)  NULL,
    [UpdatedBy]               VARCHAR (256)  NULL,
    [CreatedDate]             DATETIME2 (7)  NULL,
    [UpdatedDate]             DATETIME2 (7)  NULL,
    [IsActive]                BIT            NULL,
    [IsDeleted]               BIT            NULL);

