CREATE TYPE [dbo].[BillingInvoicingItemsType] AS TABLE (
    [BillingInvoicingItemId]  BIGINT          NULL,
    [BillingInvoicingId]      BIGINT          NULL,
    [ModuleId]                INT             NULL,
    [ReferenceId]             BIGINT          NULL,
    [SubModuleId]             INT             NULL,
    [SubReferenceId]          BIGINT          NULL,
    [ItemMasterId]            BIGINT          NULL,
    [StocklineId]             BIGINT          NULL,
    [ConditionId]             BIGINT          NULL,
    [CostPlusType]            VARCHAR (50)    NULL,
    [UnitPrice]               DECIMAL (18, 2) NULL,
    [QtyBilled]               INT             NULL,
    [PartCost]                DECIMAL (18, 2) NULL,
    [IsTotalCheck]            BIT             NULL,
    [TotalBillingCost]        DECIMAL (18, 2) NULL,
    [TotalBillingCostPercent] BIGINT          NULL,
    [TotalBillingCostPlus]    DECIMAL (18, 2) NULL,
    [IsMaterialCheck]         BIT             NULL,
    [MaterialCost]            DECIMAL (18, 2) NULL,
    [MaterialCostPercent]     BIGINT          NULL,
    [MaterialCostPlus]        DECIMAL (18, 2) NULL,
    [IsLaborCheck]            BIT             NULL,
    [LaborCost]               DECIMAL (18, 2) NULL,
    [LaborCostPercent]        BIGINT          NULL,
    [LaborCostPlus]           DECIMAL (18, 2) NULL,
    [IsFreightCheck]          BIT             NULL,
    [Freight]                 DECIMAL (18, 2) NULL,
    [FreightCostPercent]      BIGINT          NULL,
    [FreightCostPlus]         DECIMAL (18, 2) NULL,
    [IsMiscChargesCheck]      BIT             NULL,
    [MiscCharges]             DECIMAL (18, 2) NULL,
    [MiscChargesCostPercent]  BIGINT          NULL,
    [MiscChargesCostPlus]     DECIMAL (18, 2) NULL,
    [SubTotal]                DECIMAL (18, 2) NULL,
    [SalesTaxPercent]         BIGINT          NULL,
    [SalesTax]                DECIMAL (18, 2) NULL,
    [OtherTaxPercent]         BIGINT          NULL,
    [OtherTax]                DECIMAL (18, 2) NULL,
    [GrandTotal]              DECIMAL (18, 2) NULL,
    [PDFPath]                 NVARCHAR (MAX)  NULL,
    [VersionNo]               VARCHAR (20)    NULL,
    [IsVersionIncrease]       BIT             NULL,
    [IsPerformaInvoice]       BIT             NULL,
    [MasterCompanyId]         INT             NULL,
    [CreatedBy]               VARCHAR (256)   NULL,
    [UpdatedBy]               VARCHAR (256)   NULL,
    [CreatedDate]             DATETIME2 (7)   NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [IsActive]                BIT             NULL,
    [IsDeleted]               BIT             NULL,
    [ShippingId]              BIGINT          NULL,
    [UnitSalePrice]           DECIMAL (18, 2) NULL,
    [MarkUpPercentage]        DECIMAL (18, 2) NULL,
    [DiscountPercentage]      DECIMAL (18, 2) NULL,
    [MarkUpAmount]            DECIMAL (18, 2) NULL,
    [DiscountAmount]          DECIMAL (18, 2) NULL);





