CREATE TYPE [dbo].[BulkStockLineAdjustmentDetailsType] AS TABLE (
    [BulkStockLineAdjustmentDetailsId] BIGINT          NULL,
    [BulkStkLineAdjId]                 BIGINT          NOT NULL,
    [StockLineId]                      BIGINT          NULL,
    [Qty]                              DECIMAL (18, 6) NOT NULL,
    [NewQty]                           DECIMAL (18, 6) NULL,
    [QtyAdjustment]                    DECIMAL (18, 6) NULL,
    [UnitCost]                         DECIMAL (18, 6) NULL,
    [NewUnitCost]                      DECIMAL (18, 6) NULL,
    [UnitCostAdjustment]               DECIMAL (18, 6) NULL,
    [AdjustmentAmount]                 DECIMAL (18, 6) NULL,
    [FreightAdjustment]                DECIMAL (18, 6) NULL,
    [TaxAdjustment]                    DECIMAL (18, 6) NULL,
    [StockLineAdjustmentTypeId]        INT             NOT NULL,
    [ManagementStructureId]            BIGINT          NULL,
    [FromManagementStructureId]        BIGINT          NULL,
    [ToManagementStructureId]          BIGINT          NULL,
    [LastMSLevel]                      VARCHAR (200)   NULL,
    [AllMSlevels]                      VARCHAR (MAX)   NULL,
    [IsDeleted]                        BIT             NOT NULL,
    [NewUnitCostTotransfer]            DECIMAL (18, 6) NULL,
    [QuantityOnHand]                   DECIMAL (18, 6) NULL,
    [UnitOfMeasure]                    VARCHAR (100)   NULL,
    [AdjustmentReasonId]               BIGINT          NULL);

