CREATE TYPE [dbo].[BulkPODetailType] AS TABLE (
    [ItemMasterId]            BIGINT          NOT NULL,
    [StockType]               VARCHAR (50)    NULL,
    [ManufacturerId]          BIGINT          NULL,
    [Manufacturer]            VARCHAR (50)    NULL,
    [PN]                      VARCHAR (250)   NULL,
    [PNDescription]           NVARCHAR (MAX)  NULL,
    [PriorityId]              BIGINT          NULL,
    [Priority]                NVARCHAR (MAX)  NULL,
    [ConditionId]             BIGINT          NULL,
    [Condition]               VARCHAR (256)   NULL,
    [Quantity]                DECIMAL (18, 6) NULL,
    [UnitCost]                DECIMAL (18, 6) NULL,
    [VendorId]                BIGINT          NULL,
    [VendorName]              VARCHAR (100)   NULL,
    [VendorCode]              VARCHAR (100)   NULL,
    [GlAccountId]             BIGINT          NULL,
    [GlAccount]               VARCHAR (250)   NULL,
    [UOMId]                   BIGINT          NULL,
    [UnitOfMeasure]           VARCHAR (50)    NULL,
    [WorkOrderId]             BIGINT          NULL,
    [WorkOrderNo]             VARCHAR (250)   NULL,
    [ManagementStructureId]   BIGINT          NULL,
    [MasterCompanyId]         INT             NULL,
    [NeedBy]                  DATETIME2 (7)   NULL,
    [EstReceivedDate]         DATETIME2 (7)   NULL,
    [StatusId]                INT             NULL,
    [WorkOrderMaterialsId]    BIGINT          NULL,
    [WorkOrderMaterialsKitId] BIGINT          NULL,
    [SalesOrderId]            BIGINT          NULL,
    [SalesOrderPartId]        BIGINT          NULL,
    [SONum]                   VARCHAR (250)   NULL,
    [SourceType]              VARCHAR (10)    NULL);

