CREATE TYPE [dbo].[CustomerRfqPartsBaseType] AS TABLE (
    [RfqId]               BIGINT         NULL,
    [RfqCreatedDate]      DATETIME       NULL,
    [IntegrationPortalId] INT            NULL,
    [Type]                NVARCHAR (50)  NULL,
    [Notes]               NVARCHAR (MAX) NULL,
    [BuyerName]           NVARCHAR (200) NULL,
    [BuyerCompanyName]    NVARCHAR (200) NULL,
    [BuyerAddress]        NVARCHAR (300) NULL,
    [BuyerCity]           NVARCHAR (100) NULL,
    [BuyerCountry]        NVARCHAR (100) NULL,
    [BuyerState]          NVARCHAR (100) NULL,
    [BuyerZip]            NVARCHAR (20)  NULL,
    [LinePartNumber]      NVARCHAR (100) NULL,
    [LineDescription]     NVARCHAR (500) NULL,
    [AltPartNumber]       NVARCHAR (100) NULL,
    [Quantity]            INT            NULL,
    [Condition]           NVARCHAR (50)  NULL,
    [IsMRO]               BIT            NULL,
    [Guid]                NVARCHAR (100) NULL,
    [PriorityCodeId]      NVARCHAR (50)  NULL,
    [PriorityCodeName]    NVARCHAR (100) NULL,
    [ResponsesDueBy]      DATETIME       NULL,
    [CloseDate]           DATETIME       NULL,
    [BuyerId]             BIGINT         NULL,
    [BuyerCompanyPhone]   NVARCHAR (50)  NULL,
    [BuyerContactId]      BIGINT         NULL,
    [BuyerPhone]          NVARCHAR (50)  NULL,
    [BuyerEmail]          NVARCHAR (200) NULL,
    [SellerId]            BIGINT         NULL,
    [SellerSiteId]        BIGINT         NULL,
    [SellerCompanyId]     BIGINT         NULL,
    [SellerCompany]       NVARCHAR (200) NULL,
    [SellerName]          NVARCHAR (200) NULL,
    [SellerPhone]         NVARCHAR (50)  NULL,
    [SellerEmail]         NVARCHAR (200) NULL,
    [SellerUserName]      NVARCHAR (200) NULL,
    [RfqItemId]           BIGINT         NULL,
    [StatusId]            INT            NULL,
    [StatusName]          NVARCHAR (100) NULL,
    [ConditionCode]       NVARCHAR (50)  NULL,
    [IsOverhaul]          BIT            NULL,
    [ReqDeliveryDays]     INT            NULL,
    [SenderInvQuantity]   INT            NULL,
    [SenderListingInv]    BIT            NULL,
    [SupplierPartNumber]  NVARCHAR (100) NULL,
    [SupplierQuantity]    INT            NULL);

