CREATE TYPE [dbo].[CycleCountDetailType] AS TABLE (
    [CycleCountDetailId]    BIGINT          NULL,
    [CycleCountId]          BIGINT          NULL,
    [StockLineId]           BIGINT          NULL,
    [StockLineNumber]       VARCHAR (50)    NULL,
    [ControlNumber]         VARCHAR (50)    NULL,
    [IdNumber]              VARCHAR (50)    NULL,
    [SerialNumber]          VARCHAR (50)    NULL,
    [ItemMasterId]          BIGINT          NULL,
    [PartNumber]            VARCHAR (50)    NULL,
    [PartDescription]       NVARCHAR (MAX)  NULL,
    [ManufacturerId]        BIGINT          NULL,
    [ManufacturerName]      VARCHAR (50)    NULL,
    [ConditionId]           BIGINT          NULL,
    [ConditionName]         VARCHAR (50)    NULL,
    [UnitOfMeasureId]       BIGINT          NULL,
    [UnitOfMeasureName]     VARCHAR (50)    NULL,
    [UnitCost]              DECIMAL (18, 2) NULL,
    [CurrencyId]            BIGINT          NULL,
    [CurrencyName]          VARCHAR (50)    NULL,
    [SiteId]                BIGINT          NULL,
    [Site]                  VARCHAR (50)    NULL,
    [WarehouseId]           BIGINT          NULL,
    [Warehouse]             VARCHAR (50)    NULL,
    [LocationId]            BIGINT          NULL,
    [Location]              VARCHAR (50)    NULL,
    [ShelfId]               BIGINT          NULL,
    [Shelf]                 VARCHAR (50)    NULL,
    [BinId]                 BIGINT          NULL,
    [Bin]                   VARCHAR (50)    NULL,
    [CurrentStockQuantity]  INT             NULL,
    [CountedQuantity]       INT             NULL,
    [DifferenceQuantity]    INT             NULL,
    [DifferenceAmount]      DECIMAL (18, 2) NULL,
    [IsCustomerStock]       BIT             NULL,
    [ManagementStructureId] BIGINT          NULL,
    [LegalEntityId]         BIGINT          NULL,
    [MasterCompanyId]       INT             NULL,
    [CreatedBy]             VARCHAR (256)   NULL,
    [UpdatedBy]             VARCHAR (256)   NULL,
    [AdjustmentReasonId]    BIGINT          NULL);

