CREATE TYPE [dbo].[EmailRfqQuoteDetailsType] AS TABLE (
    [CustomerRfqQuoteDetailsId] BIGINT          NULL,
    [CustomerRfqQuoteId]        BIGINT          NULL,
    [ServiceType]               INT             NULL,
    [QuotePrice]                DECIMAL (18, 2) NULL,
    [QuoteTat]                  DECIMAL (18, 2) NULL,
    [Low]                       DECIMAL (18, 2) NULL,
    [Mid]                       DECIMAL (18, 2) NULL,
    [High]                      DECIMAL (18, 2) NULL,
    [AvgTat]                    DECIMAL (18, 2) NULL,
    [QuoteTatQty]               INT             NULL,
    [QuoteCond]                 VARCHAR (MAX)   NULL,
    [QuoteTrace]                VARCHAR (MAX)   NULL,
    [IlsQty]                    INT             NULL,
    [IlsTraceability]           VARCHAR (MAX)   NULL,
    [IlsUom]                    VARCHAR (MAX)   NULL,
    [IlsPrice]                  DECIMAL (18, 2) NULL,
    [IlsPriceType]              VARCHAR (MAX)   NULL,
    [IlsTagDate]                DATETIME2 (7)   NULL,
    [IlsLeadTime]               VARCHAR (MAX)   NULL,
    [IlsMinQty]                 INT             NULL,
    [IlsComment]                VARCHAR (MAX)   NULL,
    [IlsCondition]              VARCHAR (MAX)   NULL,
    [ConditionId]               BIGINT          NULL,
    [CustomerRfqPartMappingId]  BIGINT          NULL,
    [QuoteSendReviewId]         INT             NULL,
    [ExpirationDate]            DATETIME2 (7)   NULL);

