CREATE TYPE [dbo].[EngineRegistryTableType] AS TABLE (
    [EngineRegistryId]    BIGINT          NULL,
    [MakeTypeId]          BIGINT          NULL,
    [MakeType]            VARCHAR (100)   NULL,
    [EngineModelId]       BIGINT          NULL,
    [EngineModel]         VARCHAR (100)   NULL,
    [EngineSubModel]      VARCHAR (100)   NULL,
    [NumOfEngines]        INT             NULL,
    [TailNum]             VARCHAR (50)    NULL,
    [SerialNum]           VARCHAR (100)   NULL,
    [ManufacturedDate]    DATETIME2 (7)   NULL,
    [PlaceInServiceDate]  DATETIME2 (7)   NULL,
    [TotalTSN]            DECIMAL (18, 2) NULL,
    [TotalTSNMM]          DECIMAL (18, 6) NULL,
    [TotalCSN]            DECIMAL (18, 2) NULL,
    [TotalCSNMM]          DECIMAL (18, 6) NULL,
    [Hobbs]               DECIMAL (18, 2) NULL,
    [EngineLocation]      VARCHAR (200)   NULL,
    [NextScheduled]       DATETIME2 (7)   NULL,
    [MEL]                 VARCHAR (100)   NULL,
    [EngineStatusId]      BIGINT          NULL,
    [EngineStatus]        VARCHAR (100)   NULL,
    [MaintenanceStatusId] BIGINT          NULL,
    [MaintenanceStatus]   VARCHAR (100)   NULL,
    [CustomerId]          BIGINT          NULL,
    [CustomerName]        VARCHAR (100)   NULL,
    [Memo]                VARCHAR (MAX)   NULL,
    [IsActive]            BIT             NULL,
    [IsDeleted]           BIT             NULL,
    [MasterCompanyId]     INT             NULL,
    [CreatedBy]           VARCHAR (256)   NULL,
    [UpdatedBy]           VARCHAR (256)   NULL,
    [CreatedDate]         DATETIME2 (7)   NULL,
    [UpdatedDate]         DATETIME2 (7)   NULL,
    [Description]         VARCHAR (256)   NULL);

