CREATE TYPE [dbo].[ItemMasterAircraftMappingType] AS TABLE (
    [ItemMasterAircraftMappingID] BIGINT         NULL,
    [ItemMasterId]                BIGINT         NULL,
    [AircraftTypeId]              INT            NULL,
    [AircraftModelId]             BIGINT         NULL,
    [DashNumberId]                BIGINT         NULL,
    [PartNumber]                  VARCHAR (50)   NULL,
    [DashNumber]                  VARCHAR (250)  NULL,
    [AircraftType]                VARCHAR (250)  NULL,
    [AircraftModel]               VARCHAR (250)  NULL,
    [Memo]                        NVARCHAR (MAX) NULL,
    [MasterCompanyId]             INT            NULL,
    [CreatedBy]                   VARCHAR (256)  NULL,
    [UpdatedBy]                   VARCHAR (256)  NULL,
    [CreatedDate]                 DATETIME2 (7)  NULL,
    [UpdatedDate]                 DATETIME2 (7)  NULL,
    [IsActive]                    BIT            NULL,
    [IsDeleted]                   BIT            NULL,
    [ATAReferenceId]              BIGINT         NULL,
    [ATAReference]                VARCHAR (250)  NULL,
    [Level1]                      VARCHAR (50)   NULL,
    [Level2]                      VARCHAR (50)   NULL,
    [Level3]                      VARCHAR (50)   NULL,
    [ATAChapterId]                BIGINT         NULL);

