CREATE TYPE [dbo].[ItemMasterCapesType] AS TABLE (
    [ItemMasterCapesId]      BIGINT         NULL,
    [ItemMasterId]           BIGINT         NULL,
    [CapabilityTypeId]       INT            NULL,
    [ManagementStructureId]  BIGINT         NULL,
    [ManagementStructureIds] NVARCHAR (MAX) NULL,
    [IsVerified]             BIT            NULL,
    [VerifiedById]           BIGINT         NULL,
    [VerifiedDate]           DATETIME       NULL,
    [AddedDate]              DATETIME       NULL,
    [Memo]                   NVARCHAR (MAX) NULL,
    [PartNumber]             NVARCHAR (100) NULL,
    [PartDescription]        NVARCHAR (500) NULL,
    [CapabilityType]         NVARCHAR (200) NULL,
    [VerifiedBy]             NVARCHAR (200) NULL,
    [CreatedBy]              NVARCHAR (100) NULL,
    [CreatedDate]            DATETIME       NULL,
    [UpdatedBy]              NVARCHAR (100) NULL,
    [UpdatedDate]            DATETIME       NULL,
    [IsActive]               BIT            NULL,
    [IsDeleted]              BIT            NULL,
    [MasterCompanyId]        BIGINT         NULL,
    [EntityStructureId]      BIGINT         NULL,
    [Level1]                 NVARCHAR (200) NULL,
    [Level2]                 NVARCHAR (200) NULL,
    [Level3]                 NVARCHAR (200) NULL,
    [Level4]                 NVARCHAR (200) NULL);

