CREATE TYPE [dbo].[LeaseShippingType] AS TABLE (
    [LeaseShippingId]         BIGINT          NULL,
    [LeaseHeaderId]           BIGINT          NOT NULL,
    [LeaseShippingStatusId]   BIGINT          NULL,
    [Shipment]                VARCHAR (100)   NULL,
    [OpenDate]                DATETIME2 (7)   NULL,
    [ShipDate]                DATETIME2 (7)   NOT NULL,
    [ShipViaId]               BIGINT          NOT NULL,
    [IsCustomerShipping]      BIT             NULL,
    [ShippingAccountInfo]     VARCHAR (200)   NULL,
    [TrackingNum]             VARCHAR (100)   NULL,
    [AirwayBill]              VARCHAR (50)    NULL,
    [HouseAirwayBill]         VARCHAR (50)    NULL,
    [IsManualShipping]        BIT             NULL,
    [isIgnoreAWB]             BIT             NULL,
    [Weight]                  DECIMAL (18, 6) NULL,
    [ShipWeightUnit]          BIGINT          NULL,
    [ShipSizeLength]          DECIMAL (18, 6) NULL,
    [ShipSizeWidth]           DECIMAL (18, 6) NULL,
    [ShipSizeHeight]          DECIMAL (18, 6) NULL,
    [ShipSizeUnitOfMeasureId] BIGINT          NULL,
    [NoOfItems]               DECIMAL (18, 6) NULL,
    [NoOfContainer]           INT             NULL,
    [ManufactureCountryId]    INT             NULL,
    [QtyUOM]                  BIGINT          NULL,
    [UnitPrice]               DECIMAL (20, 2) NULL,
    [UnitPriceCurrencyId]     INT             NULL,
    [Notes]                   VARCHAR (MAX)   NULL,
    [SoldToName]              VARCHAR (256)   NOT NULL,
    [SoldToAddress1]          VARCHAR (256)   NOT NULL,
    [SoldToAddress2]          VARCHAR (256)   NULL,
    [SoldToCity]              VARCHAR (256)   NOT NULL,
    [SoldToState]             VARCHAR (256)   NOT NULL,
    [SoldToZip]               VARCHAR (20)    NOT NULL,
    [SoldToCountryId]         SMALLINT        NOT NULL,
    [SoldToCountryName]       VARCHAR (256)   NULL,
    [SoldAttention]           VARCHAR (100)   NULL,
    [SoldToSiteId]            BIGINT          NULL,
    [SoldToSiteName]          VARCHAR (256)   NULL,
    [ShipToName]              VARCHAR (256)   NOT NULL,
    [ShipToAddress1]          VARCHAR (256)   NOT NULL,
    [ShipToAddress2]          VARCHAR (256)   NULL,
    [ShipToCity]              VARCHAR (256)   NOT NULL,
    [ShipToState]             VARCHAR (256)   NOT NULL,
    [ShipToZip]               VARCHAR (20)    NOT NULL,
    [ShipToCountryId]         SMALLINT        NOT NULL,
    [ShipToCountryName]       VARCHAR (256)   NULL,
    [ShipAttention]           VARCHAR (100)   NULL,
    [ShipToSiteId]            BIGINT          NULL,
    [ShipToSiteName]          VARCHAR (256)   NULL,
    [ShipToCustomerId]        BIGINT          NULL,
    [OriginName]              VARCHAR (256)   NOT NULL,
    [OriginAddress1]          VARCHAR (256)   NOT NULL,
    [OriginAddress2]          VARCHAR (256)   NULL,
    [OriginCity]              VARCHAR (256)   NOT NULL,
    [OriginState]             VARCHAR (256)   NOT NULL,
    [OriginZip]               VARCHAR (256)   NOT NULL,
    [OriginCountryId]         SMALLINT        NOT NULL,
    [OriginCountryName]       VARCHAR (256)   NULL,
    [OriginSiteId]            BIGINT          NULL,
    [IsSameForShipTo]         BIT             NULL,
    [MasterCompanyId]         INT             NOT NULL,
    [CreatedBy]               VARCHAR (256)   NOT NULL,
    [UpdatedBy]               VARCHAR (256)   NOT NULL);

