CREATE TYPE [dbo].[LotCalculationDetailsType] AS TABLE (
    [LotCalculationId]         BIGINT          NULL,
    [LotId]                    BIGINT          NULL,
    [LotTransInOutId]          BIGINT          NULL,
    [Type]                     VARCHAR (100)   NULL,
    [ReferenceId]              BIGINT          NULL,
    [ChildId]                  BIGINT          NULL,
    [OriginalCost]             DECIMAL (18, 6) NULL,
    [RepairCost]               DECIMAL (18, 6) NULL,
    [AdjustedLotCost]          DECIMAL (18, 6) NULL,
    [RepCost]                  DECIMAL (18, 6) NULL,
    [Qty]                      DECIMAL (18, 6) NULL,
    [TransferredInCost]        DECIMAL (18, 6) NULL,
    [TransferredOutCost]       DECIMAL (18, 6) NULL,
    [RemainingCost]            DECIMAL (18, 6) NULL,
    [OtherCost]                DECIMAL (18, 6) NULL,
    [TotalLotCost]             DECIMAL (18, 6) NULL,
    [Revenue]                  DECIMAL (18, 6) NULL,
    [CogsPartsCost]            DECIMAL (18, 6) NULL,
    [CommissionExpense]        DECIMAL (18, 6) NULL,
    [TotalExpense]             DECIMAL (18, 6) NULL,
    [MarginAmt]                DECIMAL (18, 6) NULL,
    [MarginPercent]            DECIMAL (18, 6) NULL,
    [FreightCost]              DECIMAL (18, 6) NULL,
    [InsuranceCost]            DECIMAL (18, 6) NULL,
    [HandlingCost]             DECIMAL (18, 6) NULL,
    [TeardownCost]             DECIMAL (18, 6) NULL,
    [SoldCost]                 DECIMAL (18, 6) NULL,
    [PreCostStocklinePrice]    DECIMAL (18, 6) NULL,
    [ExtPreCostStocklinePrice] DECIMAL (18, 6) NULL,
    [IsFromPreCostStk]         BIT             NULL);

