CREATE TYPE [dbo].[PurchaseOrderFreightType] AS TABLE (
    [PurchaseOrderFreightId]    BIGINT          NULL,
    [PurchaseOrderId]           BIGINT          NULL,
    [PurchaseOrderPartRecordId] BIGINT          NULL,
    [ItemMasterId]              BIGINT          NULL,
    [PartNumber]                VARCHAR (150)   NULL,
    [ShipViaId]                 BIGINT          NULL,
    [ShipViaName]               VARCHAR (100)   NULL,
    [MarkupPercentageId]        BIGINT          NULL,
    [MarkupFixedPrice]          DECIMAL (18, 6) NULL,
    [HeaderMarkupId]            BIGINT          NULL,
    [BillingMethodId]           INT             NULL,
    [BillingRate]               DECIMAL (18, 6) NULL,
    [BillingAmount]             DECIMAL (18, 6) NULL,
    [HeaderMarkupPercentageId]  BIGINT          NULL,
    [Weight]                    VARCHAR (50)    NULL,
    [UOMId]                     BIGINT          NULL,
    [UOMName]                   VARCHAR (100)   NULL,
    [Length]                    DECIMAL (18, 6) NULL,
    [Width]                     DECIMAL (18, 6) NULL,
    [Height]                    DECIMAL (18, 6) NULL,
    [DimensionUOMId]            BIGINT          NULL,
    [DimensionUOMName]          VARCHAR (100)   NULL,
    [CurrencyId]                INT             NULL,
    [CurrencyName]              VARCHAR (100)   NULL,
    [Amount]                    DECIMAL (18, 6) NULL,
    [Memo]                      NVARCHAR (MAX)  NULL,
    [MasterCompanyId]           INT             NULL,
    [CreatedBy]                 VARCHAR (256)   NULL,
    [UpdatedBy]                 VARCHAR (256)   NULL,
    [CreatedDate]               DATETIME2 (7)   NULL,
    [UpdatedDate]               DATETIME2 (7)   NULL,
    [IsActive]                  BIT             NULL,
    [IsDeleted]                 BIT             NULL,
    [LineNum]                   INT             NULL,
    [ManufacturerId]            BIGINT          NULL,
    [Manufacturer]              VARCHAR (100)   NULL);

