CREATE TYPE [dbo].[PurchaseOrderApprovalType] AS TABLE (
    [PurchaseOrderApprovalId] BIGINT         NOT NULL,
    [PurchaseOrderId]         BIGINT         NULL,
    [PurchaseOrderPartId]     BIGINT         NULL,
    [Memo]                    NVARCHAR (MAX) NULL,
    [SentDate]                DATETIME2 (7)  NULL,
    [ApprovedDate]            DATETIME2 (7)  NULL,
    [ApprovedById]            BIGINT         NULL,
    [ApprovedByName]          NVARCHAR (MAX) NULL,
    [RejectedDate]            DATETIME2 (7)  NULL,
    [RejectedBy]              BIGINT         NULL,
    [RejectedByName]          NVARCHAR (MAX) NULL,
    [ActionId]                BIGINT         NULL,
    [StatusId]                BIGINT         NULL,
    [StatusName]              NVARCHAR (MAX) NULL,
    [InternalEmails]          NVARCHAR (MAX) NULL,
    [Approvers]               NVARCHAR (MAX) NULL,
    [LegalEntityId]           BIGINT         NULL,
    [PurchaseOrderNumber]     NVARCHAR (MAX) NULL,
    [InternalSentToId]        BIGINT         NULL,
    [InternalSentById]        BIGINT         NULL,
    [InternalSentToName]      NVARCHAR (MAX) NULL,
    [CreatedBy]               NVARCHAR (MAX) NULL,
    [UpdatedBy]               NVARCHAR (MAX) NULL,
    [MasterCompanyId]         BIGINT         NULL);

