CREATE TYPE [dbo].[PurchaseOrderPartType] AS TABLE (
    [PoPartSrNum]               INT             NULL,
    [PurchaseOrderPartRecordId] BIGINT          NULL,
    [PurchaseOrderId]           BIGINT          NULL,
    [ItemMasterId]              BIGINT          NULL,
    [PartNumber]                NVARCHAR (MAX)  NULL,
    [PartDescription]           NVARCHAR (MAX)  NULL,
    [AltEquiPartNumberId]       BIGINT          NULL,
    [AltEquiPartNumber]         NVARCHAR (MAX)  NULL,
    [AltEquiPartDescription]    NVARCHAR (MAX)  NULL,
    [StockType]                 NVARCHAR (MAX)  NULL,
    [ManufacturerId]            BIGINT          NULL,
    [Manufacturer]              NVARCHAR (MAX)  NULL,
    [PriorityId]                BIGINT          NULL,
    [Priority]                  NVARCHAR (MAX)  NULL,
    [NeedByDate]                DATETIME        NULL,
    [ConditionId]               BIGINT          NULL,
    [Condition]                 NVARCHAR (MAX)  NULL,
    [QuantityOrdered]           INT             DEFAULT ((0)) NULL,
    [QuantityBackOrdered]       INT             DEFAULT ((0)) NULL,
    [QuantityRejected]          INT             DEFAULT ((0)) NULL,
    [VendorListPrice]           DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [DiscountPercent]           BIGINT          DEFAULT ((0)) NULL,
    [DiscountPerUnit]           DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [DiscountAmount]            DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [UnitCost]                  DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [ExtendedCost]              DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [FunctionalCurrencyId]      INT             NULL,
    [FunctionalCurrency]        NVARCHAR (MAX)  NULL,
    [ForeignExchangeRate]       DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [ReportCurrencyId]          INT             NULL,
    [ReportCurrency]            NVARCHAR (MAX)  NULL,
    [WorkOrderId]               BIGINT          NULL,
    [WorkOrderNo]               NVARCHAR (MAX)  NULL,
    [SubWorkOrderId]            BIGINT          NULL,
    [SubWorkOrderNo]            NVARCHAR (MAX)  NULL,
    [RepairOrderId]             BIGINT          NULL,
    [ReapairOrderNo]            NVARCHAR (MAX)  NULL,
    [SalesOrderId]              BIGINT          NULL,
    [SalesOrderNo]              NVARCHAR (MAX)  NULL,
    [ItemTypeId]                INT             NULL,
    [ItemType]                  NVARCHAR (MAX)  NULL,
    [GlAccountId]               BIGINT          NULL,
    [GLAccount]                 NVARCHAR (MAX)  NULL,
    [UOMId]                     BIGINT          NULL,
    [UnitOfMeasure]             NVARCHAR (MAX)  NULL,
    [ManagementStructureId]     BIGINT          NULL,
    [Level1]                    NVARCHAR (MAX)  NULL,
    [Level2]                    NVARCHAR (MAX)  NULL,
    [Level3]                    NVARCHAR (MAX)  NULL,
    [Level4]                    NVARCHAR (MAX)  NULL,
    [Memo]                      NVARCHAR (MAX)  NULL,
    [isParent]                  BIT             DEFAULT ((1)) NULL,
    [ParentId]                  BIGINT          NULL,
    [POPartSplitUserTypeId]     INT             NULL,
    [POPartSplitUserType]       NVARCHAR (MAX)  NULL,
    [POPartSplitUserId]         BIGINT          NULL,
    [POPartSplitUser]           NVARCHAR (MAX)  NULL,
    [POPartSplitSiteId]         BIGINT          NULL,
    [POPartSplitSiteName]       NVARCHAR (MAX)  NULL,
    [POPartSplitAddressId]      BIGINT          NULL,
    [POPartSplitAddress1]       NVARCHAR (MAX)  NULL,
    [POPartSplitAddress2]       NVARCHAR (MAX)  NULL,
    [POPartSplitAddress3]       NVARCHAR (MAX)  NULL,
    [POPartSplitCity]           NVARCHAR (MAX)  NULL,
    [POPartSplitState]          NVARCHAR (MAX)  NULL,
    [POPartSplitPostalCode]     NVARCHAR (MAX)  NULL,
    [POPartSplitCountryId]      INT             NULL,
    [POPartSplitCountryName]    NVARCHAR (MAX)  NULL,
    [DiscountPercentValue]      DECIMAL (18, 2) DEFAULT ((0)) NULL,
    [EstDeliveryDate]           DATETIME        NULL,
    [ExchangeSalesOrderId]      BIGINT          NULL,
    [ExchangeSalesOrderNo]      NVARCHAR (MAX)  NULL,
    [ManufacturerPN]            NVARCHAR (MAX)  NULL,
    [AssetModel]                NVARCHAR (MAX)  NULL,
    [AssetClass]                NVARCHAR (MAX)  NULL,
    [IsLotAssigned]             BIT             NULL,
    [LotId]                     BIGINT          NULL,
    [WorkOrderMaterialsId]      BIGINT          NULL,
    [VendorRFQPOPartRecordId]   BIGINT          NULL,
    [TraceableTo]               BIGINT          NULL,
    [TraceableToName]           NVARCHAR (MAX)  NULL,
    [TraceableToType]           INT             NULL,
    [TagTypeId]                 BIGINT          NULL,
    [TaggedBy]                  BIGINT          NULL,
    [TaggedByName]              NVARCHAR (MAX)  NULL,
    [TaggedByType]              INT             NULL,
    [TaggedByTypeName]          NVARCHAR (MAX)  NULL,
    [TagDate]                   DATETIME        NULL,
    [MasterCompanyId]           INT             NULL,
    [CreatedBy]                 NVARCHAR (MAX)  NULL,
    [CreatedDate]               DATETIME        DEFAULT (getutcdate()) NULL,
    [UpdatedBy]                 NVARCHAR (MAX)  NULL,
    [UpdatedDate]               DATETIME        DEFAULT (getutcdate()) NULL,
    [IsActive]                  BIT             DEFAULT ((1)) NULL,
    [IsDeleted]                 BIT             DEFAULT ((0)) NULL,
    [EmployeeID]                BIGINT          NULL,
    [CoreDueDate]               DATETIME        NULL,
    [IsCreateExchange]          BIT             NULL,
    [ExpectedSerialNumber]      VARCHAR (100)   NULL,
    [RequestedQtyFromWO]        INT             NULL,
    [ModuleId]                  INT             NULL,
    [IsFromSubWorkOrder]        BIT             DEFAULT ((0)) NULL,
    [IsKit]                     BIT             DEFAULT ((0)) NULL);





