CREATE TYPE [dbo].[ReceivingReconciliationDetailsBulkType] AS TABLE (
    [ReceivingReconciliationId] BIGINT          NOT NULL,
    [StocklineId]               BIGINT          NULL,
    [StocklineNumber]           VARCHAR (50)    NULL,
    [ItemMasterId]              BIGINT          NULL,
    [PartNumber]                VARCHAR (100)   NULL,
    [PartDescription]           VARCHAR (MAX)   NULL,
    [SerialNumber]              VARCHAR (50)    NULL,
    [POReference]               VARCHAR (50)    NULL,
    [POQtyOrder]                DECIMAL (18, 6) NULL,
    [ReceivedQty]               DECIMAL (18, 6) NULL,
    [POUnitCost]                DECIMAL (18, 6) NULL,
    [POExtCost]                 DECIMAL (18, 6) NULL,
    [InvoicedQty]               DECIMAL (18, 6) NULL,
    [InvoicedUnitCost]          DECIMAL (18, 6) NULL,
    [InvoicedExtCost]           DECIMAL (18, 6) NULL,
    [AdjQty]                    DECIMAL (18, 6) NULL,
    [AdjUnitCost]               DECIMAL (18, 6) NULL,
    [AdjExtCost]                DECIMAL (18, 6) NULL,
    [APNumber]                  VARCHAR (50)    NULL,
    [PurchaseOrderId]           BIGINT          NULL,
    [PurchaseOrderPartRecordId] BIGINT          NULL,
    [IsManual]                  BIT             NULL,
    [PackagingId]               INT             NULL,
    [Description]               VARCHAR (200)   NULL,
    [GlAccountId]               BIGINT          NULL,
    [Type]                      INT             NULL,
    [StockType]                 VARCHAR (50)    NULL,
    [RemainingRRQty]            DECIMAL (18, 6) NULL,
    [FreightAdjustment]         DECIMAL (18, 6) NULL,
    [TaxAdjustment]             DECIMAL (18, 6) NULL,
    [FreightAdjustmentPerUnit]  DECIMAL (18, 6) NULL,
    [TaxAdjustmentPerUnit]      DECIMAL (18, 6) NULL,
    [QtyVariance]               DECIMAL (18, 6) NULL,
    [PriceVariance]             DECIMAL (18, 6) NULL,
    [VendorProformaAmount]      DECIMAL (18, 6) NULL,
    [VendorProformaInvoiceId]   BIGINT          NULL);

