CREATE TYPE [dbo].[SOPartListType] AS TABLE (
    [SalesOrderPartId]      BIGINT          NULL,
    [SalesOrderId]          BIGINT          NULL,
    [ItemMasterId]          BIGINT          NULL,
    [ConditionId]           BIGINT          NULL,
    [PriorityId]            BIGINT          NULL,
    [StocklineId]           BIGINT          NULL,
    [SalesOrderStocklineId] BIGINT          NULL,
    [StatusId]              INT             NULL,
    [QtyRequested]          INT             NULL,
    [QtyOrder]              INT             NULL,
    [QtyAvailable]          INT             NULL,
    [QtyOH]                 INT             NULL,
    [CurrencyId]            INT             NULL,
    [FxRate]                DECIMAL (18, 4) NULL,
    [GrossSaleAmount]       DECIMAL (18, 4) NULL,
    [DiscountPercentage]    DECIMAL (18, 4) NULL,
    [DiscountAmount]        DECIMAL (18, 4) NULL,
    [NetSaleAmount]         DECIMAL (18, 4) NULL,
    [TaxAmount]             DECIMAL (18, 4) NULL,
    [UnitCostExtended]      DECIMAL (18, 4) NULL,
    [MarginAmount]          DECIMAL (18, 4) NULL,
    [CustomerRequestDate]   DATETIME2 (7)   NULL,
    [PromisedDate]          DATETIME2 (7)   NULL,
    [EstimatedShipDate]     DATETIME2 (7)   NULL,
    [UnitSalesPrice]        DECIMAL (18, 4) NULL,
    [MarkUpPercentage]      DECIMAL (18, 4) NULL,
    [MarkUpAmount]          DECIMAL (18, 4) NULL,
    [SalesPriceExtended]    DECIMAL (18, 4) NULL,
    [UnitCost]              DECIMAL (18, 4) NULL,
    [MarginPercentage]      DECIMAL (18, 4) NULL,
    [TaxPercentage]         DECIMAL (18, 4) NULL,
    [StatusName]            VARCHAR (100)   NULL,
    [AltOrEqType]           VARCHAR (25)    NULL,
    [Notes]                 NVARCHAR (MAX)  NULL,
    [MasterCompanyId]       INT             NULL,
    [CreatedBy]             VARCHAR (100)   NULL);

