CREATE TYPE [dbo].[SOQPartListType] AS TABLE (
    [SalesOrderQuotePartId]      BIGINT          NULL,
    [SalesOrderQuoteId]          BIGINT          NULL,
    [ItemMasterId]               BIGINT          NULL,
    [ConditionId]                BIGINT          NULL,
    [PriorityId]                 BIGINT          NULL,
    [StocklineId]                BIGINT          NULL,
    [QuantityQuote]              DECIMAL (18, 6) NULL,
    [SalesOrderQuoteStocklineId] BIGINT          NULL,
    [StatusId]                   INT             NULL,
    [QtyRequested]               DECIMAL (18, 6) NULL,
    [QtyQuoted]                  DECIMAL (18, 6) NULL,
    [QtyAvailable]               DECIMAL (18, 6) NULL,
    [QtyOH]                      DECIMAL (18, 6) NULL,
    [CurrencyId]                 INT             NULL,
    [FxRate]                     DECIMAL (18, 6) NULL,
    [GrossSaleAmount]            DECIMAL (18, 6) NULL,
    [DiscountPercentage]         DECIMAL (18, 6) NULL,
    [DiscountAmount]             DECIMAL (18, 6) NULL,
    [NetSaleAmount]              DECIMAL (18, 6) NULL,
    [TaxAmount]                  DECIMAL (18, 6) NULL,
    [UnitCostExtended]           DECIMAL (18, 6) NULL,
    [MarginAmount]               DECIMAL (18, 6) NULL,
    [CustomerRequestDate]        DATETIME2 (7)   NULL,
    [PromisedDate]               DATETIME2 (7)   NULL,
    [EstimatedShipDate]          DATETIME2 (7)   NULL,
    [UnitSalesPrice]             DECIMAL (18, 6) NULL,
    [MarkUpPercentage]           DECIMAL (18, 6) NULL,
    [MarkUpAmount]               DECIMAL (18, 6) NULL,
    [SalesPriceExtended]         DECIMAL (18, 6) NULL,
    [UnitCost]                   DECIMAL (18, 6) NULL,
    [MarginPercentage]           DECIMAL (18, 6) NULL,
    [TaxPercentage]              DECIMAL (18, 6) NULL,
    [StatusName]                 VARCHAR (100)   NULL,
    [AltOrEqType]                VARCHAR (25)    NULL,
    [Notes]                      NVARCHAR (MAX)  NULL,
    [MasterCompanyId]            INT             NULL,
    [CreatedBy]                  VARCHAR (100)   NULL,
    [IsNoQuote]                  BIT             NULL,
    [IsLotAssigned]              BIT             NULL,
    [LotId]                      BIGINT          NULL);

