CREATE TYPE [dbo].[SubWOMaterialsStocklineType] AS TABLE (
    [WorkOrderId]             BIGINT          NULL,
    [SubWorkOrderId]          BIGINT          NULL,
    [SubWOPartNoId]           BIGINT          NULL,
    [SubWorkOrderMaterialsId] BIGINT          NULL,
    [StockLineId]             BIGINT          NULL,
    [ItemMasterId]            BIGINT          NULL,
    [ConditionId]             BIGINT          NULL,
    [ProvisionId]             BIGINT          NULL,
    [TaskId]                  BIGINT          NULL,
    [ReservedById]            BIGINT          NULL,
    [Condition]               VARCHAR (500)   NULL,
    [PartNumber]              VARCHAR (500)   NULL,
    [PartDescription]         VARCHAR (MAX)   NULL,
    [Quantity]                DECIMAL (18, 6) NULL,
    [QtyToBeReserved]         DECIMAL (18, 6) NULL,
    [QuantityActReserved]     DECIMAL (18, 6) NULL,
    [QuantityActIssued]       DECIMAL (18, 6) NULL,
    [QuantityActUnReserved]   DECIMAL (18, 6) NULL,
    [QuantityActUnIssued]     DECIMAL (18, 6) NULL,
    [ControlNo]               NVARCHAR (500)  NULL,
    [ControlId]               NVARCHAR (500)  NULL,
    [StockLineNumber]         NVARCHAR (500)  NULL,
    [SerialNumber]            NVARCHAR (500)  NULL,
    [ReservedBy]              NVARCHAR (500)  NULL,
    [IsStocklineAdded]        BIT             NULL,
    [KitId]                   BIGINT          NULL,
    [IsAltPart]               BIT             NULL,
    [IsEquPart]               BIT             NULL,
    [AltPartMasterPartId]     BIGINT          NULL,
    [EquPartMasterPartId]     BIGINT          NULL);

