CREATE TYPE [dbo].[SubWorkOrderPartNumberType] AS TABLE (
    [SubWOPartNoId]           BIGINT         NULL,
    [WorkOrderId]             BIGINT         NULL,
    [SubWorkOrderId]          BIGINT         NULL,
    [ItemMasterId]            BIGINT         NULL,
    [SubWorkOrderScopeId]     BIGINT         NULL,
    [EstimatedShipDate]       DATETIME2 (7)  NULL,
    [CustomerRequestDate]     DATETIME2 (7)  NULL,
    [PromisedDate]            DATETIME2 (7)  NULL,
    [EstimatedCompletionDate] DATETIME2 (7)  NULL,
    [NTE]                     INT            NULL,
    [Quantity]                DECIMAL (18, 6) NULL,
    [StockLineId]             BIGINT         NULL,
    [CMMIds]                  VARCHAR (256)  NULL,
    [WorkflowId]              BIGINT         NULL,
    [SubWorkOrderStageId]     BIGINT         NULL,
    [SubWorkOrderStatusId]    BIGINT         NULL,
    [SubWorkOrderPriorityId]  BIGINT         NULL,
    [IsPMA]                   BIT            NULL,
    [IsDER]                   BIT            NULL,
    [TechStationId]           BIGINT         NULL,
    [TATDaysStandard]         INT            NULL,
    [TechnicianId]            BIGINT         NULL,
    [ConditionId]             BIGINT         NULL,
    [RevisedItemmasterid]     BIGINT         NULL,
    [TATDaysCurrent]          INT            NULL,
    [IsTraveler]              BIT            NULL,
    [IsManualForm]            BIT            NULL,
    [WorkOrderMaterialsId]    BIGINT         NULL,
    [UpdatedById]             BIGINT         NULL,
    [IsClosed]                BIT            NULL,
    [PDFPath]                 NVARCHAR (MAX) NULL,
    [isLocked]                BIT            NULL,
    [IsFinishGood]            BIT            NULL,
    [RevisedConditionId]      BIGINT         NULL,
    [IsTransferredToParentWO] BIT            NULL,
    [RevisedSerialNumber]     VARCHAR (50)   NULL,
    [CustomerReference]       VARCHAR (256)  NULL,
    [RevisedStockLineId]      BIGINT         NULL,
    [PublicationNo]           VARCHAR (MAX)  NULL,
    [TravelerNumber]          VARCHAR (100)  NULL,
    [MasterCompanyId]         INT            NULL,
    [CreatedBy]               VARCHAR (256)  NULL,
    [UpdatedBy]               VARCHAR (256)  NULL,
    [CreatedDate]             DATETIME2 (7)  NULL,
    [UpdatedDate]             DATETIME2 (7)  NULL,
    [IsActive]                BIT            NULL,
    [IsDeleted]               BIT            NULL);

