CREATE TYPE [dbo].[SubWorkOrderMaterialsType] AS TABLE (
    [SubWorkOrderMaterialsId]       BIGINT          NULL,
    [WorkOrderId]                   BIGINT          NULL,
    [SubWorkOrderId]                BIGINT          NULL,
    [SubWOPartNoId]                 BIGINT          NULL,
    [ItemMasterId]                  BIGINT          NULL,
    [TaskId]                        BIGINT          NULL,
    [ConditionCodeId]               BIGINT          NULL,
    [ItemClassificationId]          BIGINT          NULL,
    [Quantity]                      INT             NULL,
    [UnitOfMeasureId]               BIGINT          NULL,
    [UnitCost]                      DECIMAL (13, 2) NULL,
    [ExtendedCost]                  DECIMAL (13, 2) NULL,
    [Price]                         DECIMAL (13, 2) NULL,
    [ExtendedPrice]                 DECIMAL (13, 2) NULL,
    [Memo]                          NVARCHAR (MAX)  NULL,
    [IsDeferred]                    BIT             NULL,
    [QuantityReserved]              INT             NULL,
    [QuantityIssued]                INT             NULL,
    [IssuedDate]                    DATETIME2 (7)   NULL,
    [ReservedDate]                  DATETIME2 (7)   NULL,
    [IsAltPart]                     BIT             NULL,
    [AltPartMasterPartId]           BIGINT          NULL,
    [IsFromWorkFlow]                BIT             NULL,
    [PartStatusId]                  INT             NULL,
    [IssuedById]                    BIGINT          NULL,
    [ReservedById]                  BIGINT          NULL,
    [IsEquPart]                     BIT             NULL,
    [ParentSubWorkOrderMaterialsId] BIGINT          NULL,
    [ItemMappingId]                 BIGINT          NULL,
    [TotalReserved]                 INT             NULL,
    [TotalIssued]                   INT             NULL,
    [ProvisionId]                   INT             NULL,
    [MaterialMandatoriesId]         INT             NULL,
    [MasterCompanyId]               INT             NULL,
    [CreatedBy]                     NVARCHAR (MAX)  NULL,
    [CreatedDate]                   DATETIME2 (7)   NULL,
    [UpdatedBy]                     NVARCHAR (MAX)  NULL,
    [UpdatedDate]                   DATETIME2 (7)   NULL,
    [IsActive]                      BIT             NULL,
    [IsDeleted]                     BIT             NULL,
    [QuantityTurnIn]                INT             NULL,
    [Condition]                     VARCHAR (50)    NULL,
    [UOM]                           VARCHAR (50)    NULL,
    [ItemClassification]            VARCHAR (100)   NULL,
    [Provision]                     VARCHAR (50)    NULL,
    [TaskName]                      VARCHAR (50)    NULL,
    [Site]                          VARCHAR (50)    NULL,
    [WareHouse]                     VARCHAR (50)    NULL,
    [Locations]                     VARCHAR (50)    NULL,
    [Shelf]                         VARCHAR (50)    NULL,
    [Bin]                           VARCHAR (50)    NULL,
    [TotalStocklineQtyReq]          INT             NULL,
    [POId]                          BIGINT          NULL,
    [PONum]                         VARCHAR (50)    NULL,
    [PONextDlvrDate]                DATETIME2 (7)   NULL,
    [QtyOnOrder]                    INT             NULL,
    [QtyOnBkOrder]                  INT             NULL,
    [QtyToTurnIn]                   INT             NULL,
    [Figure]                        NVARCHAR (100)  NULL,
    [Item]                          NVARCHAR (100)  NULL,
    [EquPartMasterPartId]           BIGINT          NULL,
    [UnReservedQty]                 INT             NULL,
    [UnIssuedQty]                   INT             NULL,
    [TotalUnIssued]                 INT             NULL,
    [TotalUnReserved]               INT             NULL,
    [StockLineId]                   BIGINT          NULL,
    [StocklineQuantity]             INT             NULL,
    [IsStocklineEdit]               BIT             NULL,
    [isExistingMaterilas]           BIT             NULL,
    [IsAlternatePart]               BIGINT          NULL,
    [IsKitType]                     BIT             NULL,
    [KitId]                         BIGINT          NULL);

