CREATE TYPE [dbo].[TBL_ItemMasterUpdateType] AS TABLE (
    [ItemMasterId]                      BIGINT          NULL,
    [ItemTypeId]                        INT             NULL,
    [PartNumber]                        VARCHAR (200)   NULL,
    [PartDescription]                   VARCHAR (500)   NULL,
    [RevisedPartId]                     BIGINT          NULL,
    [IsOEM]                             BIT             NULL,
    [IsPma]                             BIT             NULL,
    [IsOemPNId]                         BIGINT          NULL,
    [IsDER]                             BIT             NULL,
    [IsSerialized]                      BIT             NULL,
    [IsTimeLife]                        BIT             NULL,
    [NationalStockNumber]               VARCHAR (200)   NULL,
    [ItemClassificationId]              BIGINT          NULL,
    [ItemGroupId]                       BIGINT          NULL,
    [ItemMasterAssetTypeId]             BIGINT          NULL,
    [IsExpirationDateAvailable]         BIT             NULL,
    [ExpirationDate]                    DATETIME2 (7)   NULL,
    [IsReceivedDateAvailable]           BIT             NULL,
    [DaysReceived]                      INT             NULL,
    [IsManufacturingDateAvailable]      BIT             NULL,
    [ManufacturingDays]                 INT             NULL,
    [IsTagDateAvailable]                BIT             NULL,
    [TagDays]                           INT             NULL,
    [IsOpenDateAvailable]               BIT             NULL,
    [OpenDays]                          INT             NULL,
    [IsShippedDateAvailable]            BIT             NULL,
    [ShippedDays]                       INT             NULL,
    [IsOtherDateAvailable]              BIT             NULL,
    [OtherDays]                         INT             NULL,
    [ShelfLife]                         BIT             NULL,
    [ShelfLifeAvailable]                DECIMAL (18, 2) NULL,
    [OverhaulHours]                     INT             NULL,
    [RPHours]                           INT             NULL,
    [TestHours]                         INT             NULL,
    [mfgHours]                          DECIMAL (18, 2) NULL,
    [TurnTimeOverhaulHours]             INT             NULL,
    [TurnTimeRepairHours]               INT             NULL,
    [turnTimeBenchTest]                 DECIMAL (18, 2) NULL,
    [turnTimeMfg]                       DECIMAL (18, 2) NULL,
    [IsHazardousMaterial]               BIT             NULL,
    [ManufacturerId]                    BIGINT          NULL,
    [RFQTracking]                       BIT             NULL,
    [PurchaseUnitOfMeasureId]           BIGINT          NULL,
    [StockUnitOfMeasureId]              BIGINT          NULL,
    [ConsumeUnitOfMeasureId]            BIGINT          NULL,
    [IsSchematic]                       BIT             NULL,
    [GLAccountId]                       BIGINT          NULL,
    [LeadTimeDays]                      INT             NULL,
    [StockLevel]                        DECIMAL (18, 6) NULL,
    [ReorderPoint]                      DECIMAL (18, 6) NULL,
    [ReorderQuantiy]                    DECIMAL (18, 6) NULL,
    [MinimumOrderQuantity]              DECIMAL (18, 6) NULL,
    [PriorityId]                        BIGINT          NULL,
    [Memo]                              VARCHAR (MAX)   NULL,
    [SiteId]                            BIGINT          NULL,
    [WarehouseId]                       BIGINT          NULL,
    [LocationId]                        BIGINT          NULL,
    [ShelfId]                           BIGINT          NULL,
    [BinId]                             BIGINT          NULL,
    [IsHotItem]                         BIT             NULL,
    [SalesLastSalePriceDate]            DATETIME2 (7)   NULL,
    [SalesLastSalesDiscountPercentDate] DATETIME2 (7)   NULL,
    [RevisedPart]                       VARCHAR (200)   NULL,
    [OEMPN]                             VARCHAR (200)   NULL,
    [ItemClassificationName]            VARCHAR (200)   NULL,
    [ItemGroup]                         VARCHAR (200)   NULL,
    [AssetAcquistionType]               VARCHAR (200)   NULL,
    [ManufacturerName]                  VARCHAR (200)   NULL,
    [PurchaseUnitOfMeasure]             VARCHAR (200)   NULL,
    [StockUnitOfMeasure]                VARCHAR (200)   NULL,
    [ConsumeUnitOfMeasure]              VARCHAR (200)   NULL,
    [PurchaseCurrency]                  VARCHAR (50)    NULL,
    [SalesCurrency]                     VARCHAR (50)    NULL,
    [GLAccount]                         VARCHAR (200)   NULL,
    [Priority]                          VARCHAR (200)   NULL,
    [SiteName]                          VARCHAR (200)   NULL,
    [WarehouseName]                     VARCHAR (200)   NULL,
    [LocationName]                      VARCHAR (200)   NULL,
    [ShelfName]                         VARCHAR (200)   NULL,
    [BinName]                           VARCHAR (200)   NULL,
    [Figure]                            VARCHAR (200)   NULL,
    [Item]                              VARCHAR (200)   NULL,
    [PartAlternatePartId]               BIGINT          NULL,
    [PurchaseCurrencyId]                INT             NULL,
    [SalesCurrencyId]                   INT             NULL,
    [CurrentStlNo]                      BIGINT          NULL,
    [MTBUR]                             INT             NULL,
    [NE]                                INT             NULL,
    [NS]                                INT             NULL,
    [OH]                                INT             NULL,
    [REP]                               INT             NULL,
    [SVC]                               INT             NULL,
    [UNCode]                            BIT             NULL,
    [InventoryGLSettingId]              BIGINT          NULL,
    [GoodsReceivedNotInvoicesGLAccId]   BIGINT          NULL,
    [GoodsReceivedNotInvoicesGLAccName] VARCHAR (200)   NULL,
    [WorkInProgressGLAccId]             BIGINT          NULL,
    [WorkInProgressGLAccName]           VARCHAR (200)   NULL,
    [InventoryToBillGLAccId]            BIGINT          NULL,
    [InventoryToBillGLAccName]          VARCHAR (200)   NULL,
    [FinishedGoodsGLAccId]              BIGINT          NULL,
    [FinishedGoodsGLAccName]            VARCHAR (200)   NULL,
    [InventoryExchAgreementGLAccId]     BIGINT          NULL,
    [InventoryExchAgreementGLAccName]   VARCHAR (200)   NULL,
    [InventoryReserveGLAccId]           BIGINT          NULL,
    [InventoryReserveGLAccName]         VARCHAR (200)   NULL,
    [COGS_WorkOrderGLAccId]             BIGINT          NULL,
    [COGS_WorkOrderGLAccName]           VARCHAR (200)   NULL,
    [COGS_SalesOrderGLAccId]            BIGINT          NULL,
    [COGS_SalesOrderGLAccName]          VARCHAR (200)   NULL,
    [COGS_ExchSalesOrderGLAccId]        BIGINT          NULL,
    [COGS_ExchSalesOrderGLAccName]      VARCHAR (200)   NULL,
    [COGS_QtyVarianceGLAccId]           BIGINT          NULL,
    [COGS_QtyVarianceGLAccName]         VARCHAR (200)   NULL,
    [COGS_UnitCostVarianceGLAccId]      BIGINT          NULL,
    [COGS_UnitCostVarianceGLAccName]    VARCHAR (200)   NULL,
    [RevenueMroGLAccId]                 BIGINT          NULL,
    [RevenueMroGLAccName]               VARCHAR (200)   NULL,
    [RevenueSoGLAccId]                  BIGINT          NULL,
    [RevenueSoGLAccName]                VARCHAR (200)   NULL,
    [RevenueExchGLAccId]                BIGINT          NULL,
    [RevenueExchGLAccName]              VARCHAR (200)   NULL,
    [IsUpdated]                         BIT             NULL,
    [WorkOrderFormTypeId]               INT             NULL,
    [CoreUnitCost]                      VARCHAR (100)   NULL,
    [UnitSalesPrice]                    VARCHAR (100)   NULL,
    [ConditionId]                       BIGINT          NULL,
    [POUnitCost]                        VARCHAR (100)   NULL,
    [ExportECCN]                        VARCHAR (100)   NULL,
    [IntegrationPortal]                 VARCHAR (500)   NULL,
    [IntegrationPortalIds]              VARCHAR (500)   NULL,
    [ITARNumber]                        VARCHAR (200)   NULL,
    [Classification]                    VARCHAR (200)   NULL,
    [MasterCompanyId]                   VARCHAR (200)   NULL,
    [UpdatedBy]                         VARCHAR (200)   NULL,
    [RepairUnitOfMeasureId]             BIGINT          NULL,
    [IsFlightHoursAvailable]            BIT             NULL,
    [IsFlightCyclesAvailable]           BIT             NULL,
    [IsLandingsAvailable]               BIT             NULL,
    [IsStartsAvailable]                 BIT             NULL,
    [IsCalendarTimeAvailable]           BIT             NULL,
    [FlightHours]                       VARCHAR (200)   NULL,
    [FlightMinutes]                     VARCHAR (200)   NULL,
    [FlightCycles]                      INT             NULL,
    [Landings]                          INT             NULL,
    [Starts]                            INT             NULL,
    [CalendarDate]                      DATETIME2 (7)   NULL,
    [Model]                             VARCHAR (200)   NULL,
    [IsKitAssy]                         BIT             NULL);

