CREATE TYPE [dbo].[VendorRMADetailType] AS TABLE (
    [VendorRMADetailId]       BIGINT          NULL,
    [VendorRMAId]             BIGINT          NULL,
    [RMANum]                  VARCHAR (100)   NULL,
    [StockLineId]             BIGINT          NULL,
    [ReferenceId]             BIGINT          NULL,
    [ItemMasterId]            BIGINT          NULL,
    [SerialNumber]            VARCHAR (50)    NULL,
    [Qty]                     DECIMAL (18, 6) NULL,
    [UnitCost]                DECIMAL (18, 6) NULL,
    [ExtendedCost]            DECIMAL (18, 6) NULL,
    [VendorRMAReturnReasonId] BIGINT          NULL,
    [VendorRMAStatusId]       INT             NULL,
    [VendorShippingAddressId] BIGINT          NULL,
    [Notes]                   NVARCHAR (MAX)  NULL,
    [MasterCompanyId]         INT             NULL,
    [CreatedBy]               VARCHAR (256)   NULL,
    [CreatedDate]             DATETIME2 (7)   NULL,
    [UpdatedBy]               VARCHAR (256)   NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [IsActive]                BIT             NULL,
    [IsDeleted]               BIT             NULL,
    [QuantityBackOrdered]     DECIMAL (18, 6) NULL,
    [QuantityRejected]        DECIMAL (18, 6) NULL,
    [ModuleId]                INT             NULL);

