CREATE TYPE [dbo].[VendorProformaInvoicePartDetailsType] AS TABLE (
    [VendorProformaInvoicePartDetailsId] BIGINT          NULL,
    [VendorProformaInvoiceId]            BIGINT          NULL,
    [EntryDate]                          DATETIME2 (7)   NULL,
    [Amount]                             DECIMAL (18, 6) NULL,
    [CurrencyId]                         BIGINT          NULL,
    [FXRate]                             DECIMAL (18, 6) NULL,
    [GlAccountId]                        BIGINT          NULL,
    [InvoiceNumber]                      VARCHAR (256)   NULL,
    [InvoiceDate]                        DATETIME2 (7)   NULL,
    [ManagementStructureId]              INT             NULL,
    [LastMSLevel]                        VARCHAR (200)   NULL,
    [AllMSlevels]                        VARCHAR (MAX)   NULL,
    [Memo]                               VARCHAR (MAX)   NULL,
    [JournalType]                        VARCHAR (200)   NULL,
    [MasterCompanyId]                    INT             NULL,
    [CreatedBy]                          VARCHAR (50)    NULL,
    [UpdatedBy]                          VARCHAR (50)    NULL,
    [IsDeleted]                          BIT             NULL,
    [Item]                               VARCHAR (250)   NULL,
    [Description]                        VARCHAR (500)   NULL,
    [UnitOfMeasureId]                    BIGINT          NULL,
    [Qty]                                DECIMAL (18, 6) NULL,
    [ExtendedPrice]                      DECIMAL (18, 6) NULL,
    [TaxTypeId]                          BIGINT          NULL);

