CREATE TYPE [dbo].[VendorRFQPartType] AS TABLE (
    [VendorRFQPartId]    BIGINT          NULL,
    [ILSRFQDetailId]     BIGINT          NULL,
    [ItemId]             BIGINT          NULL,
    [ItemSupplierPartId] BIGINT          NULL,
    [VendorName]         VARCHAR (150)   NULL,
    [VendorId]           BIGINT          NULL,
    [Email]              VARCHAR (100)   NULL,
    [Phone]              VARCHAR (100)   NULL,
    [PartNumber]         VARCHAR (150)   NULL,
    [RfqId]              NVARCHAR (200)  NULL,
    [Description]        VARCHAR (MAX)   NULL,
    [AltPartNumber]      VARCHAR (150)   NULL,
    [ReferenceNumber]    VARCHAR (200)   NULL,
    [Traceability]       VARCHAR (200)   NULL,
    [UnitOfMeasure]      VARCHAR (100)   NULL,
    [Price]              DECIMAL (18, 2) NULL,
    [PriceType]          VARCHAR (100)   NULL,
    [LeadTime]           VARCHAR (100)   NULL,
    [Qty]                INT             NULL,
    [RequestedQty]       INT             NULL,
    [MinQuantity]        INT             NULL,
    [Condition]          VARCHAR (20)    NULL,
    [Address1]           VARCHAR (250)   NULL,
    [Address2]           VARCHAR (250)   NULL,
    [City]               VARCHAR (50)    NULL,
    [Country]            VARCHAR (50)    NULL,
    [PostalCode]         VARCHAR (50)    NULL,
    [StateProvince]      VARCHAR (50)    NULL,
    [MasterCompanyId]    INT             NULL,
    [CreatedBy]          VARCHAR (256)   NULL,
    [UpdatedBy]          VARCHAR (256)   NULL);

