CREATE TYPE [dbo].[WorkflowEquipmentListType] AS TABLE (
    [WorkflowEquipmentListId] BIGINT          NULL,
    [WorkflowId]              BIGINT          NULL,
    [AssetId]                 BIGINT          NULL,
    [AssetTypeId]             BIGINT          NULL,
    [AssetDescription]        VARCHAR (500)   NULL,
    [Quantity]                DECIMAL (18, 6) NULL,
    [TaskId]                  BIGINT          NULL,
    [MasterCompanyId]         INT             NULL,
    [CreatedBy]               VARCHAR (256)   NULL,
    [UpdatedBy]               VARCHAR (256)   NULL,
    [CreatedDate]             DATETIME2 (7)   NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [IsActive]                BIT             NULL,
    [IsDeleted]               BIT             NULL,
    [PartNumber]              VARCHAR (256)   NULL,
    [Order]                   INT             NULL,
    [Memo]                    VARCHAR (1000)  NULL,
    [WFParentId]              BIGINT          NULL,
    [IsVersionIncrease]       BIT             NULL,
    [AssetAttributeTypeId]    BIGINT          NULL);

