CREATE TYPE [dbo].[WorkOrderQuoteMaterialType] AS TABLE (
    [WorkOrderQuoteMaterialId] BIGINT          NULL,
    [WorkOrderQuoteDetailsId]  BIGINT          NULL,
    [ItemMasterId]             BIGINT          NULL,
    [ConditionCodeId]          BIGINT          NULL,
    [ItemClassificationId]     BIGINT          NULL,
    [Quantity]                 DECIMAL (18, 6) NULL,
    [UnitOfMeasureId]          BIGINT          NULL,
    [UnitCost]                 DECIMAL (18, 6) NULL,
    [ExtendedCost]             DECIMAL (18, 6) NULL,
    [Memo]                     NVARCHAR (MAX)  NULL,
    [IsDefered]                BIT             NULL,
    [MasterCompanyId]          INT             NULL,
    [CreatedBy]                VARCHAR (256)   NULL,
    [UpdatedBy]                VARCHAR (256)   NULL,
    [CreatedDate]              DATETIME2 (7)   NULL,
    [UpdatedDate]              DATETIME2 (7)   NULL,
    [IsActive]                 BIT             NULL,
    [IsDeleted]                BIT             NULL,
    [MarkupPercentageId]       BIGINT          NULL,
    [TaskId]                   BIGINT          NULL,
    [MarkupFixedPrice]         VARCHAR (15)    NULL,
    [BillingAmount]            DECIMAL (18, 6) NULL,
    [BillingRate]              DECIMAL (18, 6) NULL,
    [HeaderMarkupId]           BIGINT          NULL,
    [ProvisionId]              INT             NULL,
    [MaterialMandatoriesId]    INT             NULL,
    [BillingMethodId]          INT             NULL,
    [TaskName]                 VARCHAR (100)   NULL,
    [PartNumber]               VARCHAR (50)    NULL,
    [PartDescription]          VARCHAR (500)   NULL,
    [Provision]                VARCHAR (50)    NULL,
    [UomName]                  VARCHAR (50)    NULL,
    [Conditiontype]            VARCHAR (50)    NULL,
    [Stocktype]                VARCHAR (50)    NULL,
    [BillingName]              VARCHAR (50)    NULL,
    [MarkUp]                   VARCHAR (50)    NULL,
    [ManufacturerName]         VARCHAR (100)   NULL,
    [UOM]                      VARCHAR (100)   NULL,
    [MandatoryOrSupplemental]  VARCHAR (50)    NULL,
    [ItemClassification]       VARCHAR (100)   NULL,
    [Figure]                   VARCHAR (50)    NULL,
    [Item]                     VARCHAR (50)    NULL,
    [WOQMaterialKitMappingId]  BIGINT          NULL,
    [KitId]                    BIGINT          NULL,
    [Partqty]                  DECIMAL (18, 6) NULL);

