CREATE TYPE [dbo].[WorkOrderQuoteFreightType] AS TABLE (
    [WorkOrderQuoteFreightId] BIGINT          NULL,
    [WorkOrderQuoteDetailsId] BIGINT          NULL,
    [ShipViaId]               BIGINT          NULL,
    [Weight]                  VARCHAR (50)    NULL,
    [Memo]                    NVARCHAR (MAX)  NULL,
    [Amount]                  DECIMAL (20, 3) NULL,
    [MasterCompanyId]         INT             NULL,
    [CreatedBy]               VARCHAR (256)   NULL,
    [UpdatedBy]               VARCHAR (256)   NULL,
    [CreatedDate]             DATETIME2 (7)   NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [IsActive]                BIT             NULL,
    [IsDeleted]               BIT             NULL,
    [MarkupPercentageId]      BIGINT          NULL,
    [MarkupFixedPrice]        VARCHAR (15)    NULL,
    [TaskId]                  BIGINT          NULL,
    [HeaderMarkupId]          BIGINT          NULL,
    [BillingRate]             DECIMAL (20, 2) NULL,
    [BillingAmount]           DECIMAL (20, 2) NULL,
    [Length]                  DECIMAL (10, 2) NULL,
    [Width]                   DECIMAL (10, 2) NULL,
    [Height]                  DECIMAL (10, 2) NULL,
    [UOMId]                   BIGINT          NULL,
    [DimensionUOMId]          BIGINT          NULL,
    [CurrencyId]              INT             NULL,
    [BillingMethodId]         INT             NULL,
    [TaskName]                VARCHAR (100)   NULL,
    [Shipvia]                 VARCHAR (50)    NULL,
    [UomName]                 VARCHAR (50)    NULL,
    [DimensionUomName]        VARCHAR (50)    NULL,
    [Currency]                VARCHAR (50)    NULL,
    [BillingName]             VARCHAR (50)    NULL,
    [MarkUp]                  VARCHAR (50)    NULL);

