CREATE TYPE [dbo].[WorkOrderMPNType] AS TABLE (
    [ID]                             BIGINT          NULL,
    [WorkOrderId]                    BIGINT          NULL,
    [WorkOrderScopeId]               BIGINT          NULL,
    [EstimatedShipDate]              DATETIME2 (7)   NULL,
    [CustomerRequestDate]            DATETIME2 (7)   NULL,
    [PromisedDate]                   DATETIME2 (7)   NULL,
    [EstimatedCompletionDate]        DATETIME2 (7)   NULL,
    [NTE]                            VARCHAR (30)    NULL,
    [Quantity]                       INT             NULL,
    [StockLineId]                    BIGINT          NULL,
    [CMMIds]                         VARCHAR (256)   NULL,
    [WorkflowId]                     BIGINT          NULL,
    [WorkOrderStageId]               BIGINT          NULL,
    [WorkOrderStatusId]              BIGINT          NULL,
    [WorkOrderPriorityId]            BIGINT          NULL,
    [IsPMA]                          BIT             NULL,
    [IsDER]                          BIT             NULL,
    [TechStationId]                  BIGINT          NULL,
    [TATDaysStandard]                INT             NULL,
    [MasterCompanyId]                INT             NULL,
    [CreatedBy]                      VARCHAR (256)   NULL,
    [UpdatedBy]                      VARCHAR (256)   NULL,
    [CreatedDate]                    DATETIME2 (7)   NULL,
    [UpdatedDate]                    DATETIME2 (7)   NULL,
    [IsActive]                       BIT             NULL,
    [IsDeleted]                      BIT             NULL,
    [ItemMasterId]                   BIGINT          NULL,
    [TechnicianId]                   BIGINT          NULL,
    [ConditionId]                    BIGINT          NULL,
    [TATDaysCurrent]                 INT             NULL,
    [RevisedPartId]                  BIGINT          NULL,
    [ManagementStructureId]          BIGINT          NULL,
    [IsMPNContract]                  BIT             NULL,
    [ContractNo]                     VARCHAR (20)    NULL,
    [WorkScope]                      VARCHAR (200)   NULL,
    [isLocked]                       BIT             NULL,
    [ReceivedDate]                   DATETIME        NULL,
    [IsClosed]                       BIT             NULL,
    [ACTailNum]                      NVARCHAR (500)  NULL,
    [ClosedDate]                     DATETIME        NULL,
    [PDFPath]                        NVARCHAR (MAX)  NULL,
    [IsFinishGood]                   BIT             NULL,
    [RevisedConditionId]             BIGINT          NULL,
    [CustomerReference]              VARCHAR (256)   NULL,
    [Level1]                         VARCHAR (200)   NULL,
    [Level2]                         VARCHAR (200)   NULL,
    [Level3]                         VARCHAR (200)   NULL,
    [Level4]                         VARCHAR (200)   NULL,
    [AssignDate]                     DATETIME2 (7)   NULL,
    [ReceivingCustomerWorkId]        BIGINT          NULL,
    [ExpertiseId]                    SMALLINT        NULL,
    [RevisedItemmasterid]            BIGINT          NULL,
    [RevisedPartNumber]              VARCHAR (50)    NULL,
    [RevisedPartDescription]         VARCHAR (MAX)   NULL,
    [IsTraveler]                     BIT             NULL,
    [AllowInvoiceBeforeShipping]     BIT             NULL,
    [WOFPrintDate]                   DATETIME        NULL,
    [CurrentSerialNumber]            VARCHAR (100)   NULL,
    [StocklineCost]                  DECIMAL (18, 2) NULL,
    [TendorStocklineCost]            DECIMAL (18, 2) NULL,
    [RepairOrderId]                  BIGINT          NULL,
    [RONumber]                       VARCHAR (50)    NULL,
    [RevisedSerialNumber]            VARCHAR (50)    NULL,
    [IsROCreated]                    BIT             NULL,
    [PartNumber]                     VARCHAR (200)   NULL,
    [PartDescription]                NVARCHAR (MAX)  NULL,
    [WorkOrderStatus]                VARCHAR (MAX)   NULL,
    [Priority]                       VARCHAR (100)   NULL,
    [WorkOrderStage]                 VARCHAR (150)   NULL,
    [ManufacturerName]               VARCHAR (250)   NULL,
    [TechName]                       VARCHAR (100)   NULL,
    [EmployeeStation]                VARCHAR (100)   NULL,
    [PublicationNo]                  VARCHAR (MAX)   NULL,
    [SerialNumber]                   VARCHAR (100)   NULL,
    [MasterPartId]                   BIGINT          NULL,
    [Notes]                          NVARCHAR (MAX)  NULL,
    [AircraftRegistryNumber]         VARCHAR (30)    NULL,
    [IsFromAircraft]                 BIT             NULL,
    [AircraftInstalledPartDetailsId] BIGINT          NULL,
    [AircraftSerialNumber]           VARCHAR (100)   NULL,
    [AircraftRegistryId]             BIGINT          NULL,
    [ProgramId]                      BIGINT          NULL,
    [IsFromLease]                    BIT             NULL,
    [LeaseStocklineId]               BIGINT          NULL);

