CREATE TYPE [dbo].[WorkflowPublicationsListType] AS TABLE (
    [WorkflowPublicationsId] BIGINT         NULL,
    [CreatedBy]              VARCHAR (50)   NULL,
    [CreatedDate]            DATETIME       NULL,
    [UpdatedBy]              VARCHAR (50)   NULL,
    [UpdatedDate]            DATETIME       NULL,
    [IsDeleted]              BIT            NULL,
    [PublicationId]          BIGINT         NULL,
    [PublicationDescription] VARCHAR (256)  NULL,
    [PublicationType]        VARCHAR (256)  NULL,
    [Sequence]               VARCHAR (256)  NULL,
    [Source]                 VARCHAR (256)  NULL,
    [AircraftManufacturer]   INT            NULL,
    [Model]                  BIGINT         NULL,
    [Location]               VARCHAR (256)  NULL,
    [Revision]               VARCHAR (256)  NULL,
    [RevisionDate]           VARCHAR (256)  NULL,
    [VerifiedBy]             VARCHAR (256)  NULL,
    [VerifiedDate]           VARCHAR (256)  NULL,
    [Status]                 VARCHAR (256)  NULL,
    [Image]                  VARCHAR (256)  NULL,
    [TaskId]                 BIGINT         NULL,
    [WorkflowId]             BIGINT         NULL,
    [MasterCompanyId]        INT            NULL,
    [Order]                  INT            NULL,
    [IsActive]               BIT            NULL,
    [Memo]                   NVARCHAR (MAX) NULL,
    [WFParentId]             BIGINT         NULL,
    [IsVersionIncrease]      BIT            NULL);

