CREATE TYPE [dbo].[WorkflowMaterialType] AS TABLE (
    [WorkflowMaterialListId]  BIGINT          NULL,
    [WorkflowId]              BIGINT          NULL,
    [ItemMasterId]            BIGINT          NULL,
    [TaskId]                  BIGINT          NULL,
    [Quantity]                DECIMAL (18, 6) NULL,
    [UnitOfMeasureId]         BIGINT          NULL,
    [ConditionCodeId]         BIGINT          NULL,
    [UnitCost]                DECIMAL (18, 6) NULL,
    [ExtendedCost]            DECIMAL (18, 6) NULL,
    [Price]                   DECIMAL (18, 6) NULL,
    [ProvisionId]             INT             NULL,
    [IsDeferred]              BIT             NULL,
    [WorkflowActionId]        TINYINT         NULL,
    [Memo]                    NVARCHAR (MAX)  NULL,
    [MasterCompanyId]         INT             NULL,
    [CreatedBy]               VARCHAR (256)   NULL,
    [UpdatedBy]               VARCHAR (256)   NULL,
    [CreatedDate]             DATETIME2 (7)   NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [IsActive]                BIT             NULL,
    [IsDeleted]               BIT             NULL,
    [MaterialMandatoriesName] VARCHAR (256)   NULL,
    [PartNumber]              VARCHAR (256)   NULL,
    [PartDescription]         NVARCHAR (MAX)  NULL,
    [ItemClassificationId]    BIGINT          NULL,
    [ExtendedPrice]           DECIMAL (18, 6) NULL,
    [Order]                   INT             NULL,
    [MaterialMandatoriesId]   INT             NULL,
    [WFParentId]              BIGINT          NULL,
    [IsVersionIncrease]       BIT             NULL,
    [Figure]                  NVARCHAR (100)  NULL,
    [Item]                    NVARCHAR (100)  NULL);

