CREATE TYPE [dbo].[WorkflowExclusionListType] AS TABLE (
    [WorkflowExclusionId]     BIGINT          NULL,
    [WorkflowId]              BIGINT          NULL,
    [ItemMasterId]            BIGINT          NULL,
    [UnitCost]                DECIMAL (18, 6) NULL,
    [Quantity]                DECIMAL (18, 6) NULL,
    [ExtendedCost]            DECIMAL (18, 6) NULL,
    [EstimtPercentOccurrance] TINYINT         NULL,
    [Memo]                    NVARCHAR (MAX)  NULL,
    [TaskId]                  BIGINT          NULL,
    [MasterCompanyId]         INT             NULL,
    [CreatedBy]               VARCHAR (256)   NULL,
    [UpdatedBy]               VARCHAR (256)   NULL,
    [CreatedDate]             DATETIME2 (7)   NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [IsActive]                BIT             NULL,
    [IsDeleted]               BIT             NULL,
    [PartNumber]              VARCHAR (256)   NULL,
    [PartDescription]         VARCHAR (256)   NULL,
    [Order]                   INT             NULL,
    [ConditionId]             BIGINT          NULL,
    [ItemClassificationId]    BIGINT          NULL,
    [WFParentId]              BIGINT          NULL,
    [IsVersionIncrease]       BIT             NULL);

