CREATE TYPE [dbo].[WorkOrderQuoteDetailsType] AS TABLE (
    [WorkOrderQuoteDetailsId]       BIGINT          NULL,
    [WorkOrderQuoteId]              BIGINT          NULL,
    [ItemMasterId]                  BIGINT          NULL,
    [BuildMethodId]                 BIGINT          NULL,
    [MasterCompanyId]               INT             NULL,
    [CreatedBy]                     VARCHAR (256)   NULL,
    [UpdatedBy]                     VARCHAR (256)   NULL,
    [CreatedDate]                   DATETIME2 (7)   NULL,
    [UpdatedDate]                   DATETIME2 (7)   NULL,
    [IsActive]                      BIT             NULL,
    [IsDeleted]                     BIT             NULL,
    [WorkflowWorkOrderId]           BIGINT          NULL,
    [WOPartNoId]                    BIGINT          NULL,
    [MaterialCost]                  DECIMAL (18, 6) NULL,
    [MaterialBilling]               DECIMAL (18, 6) NULL,
    [MaterialRevenuePercentage]     DECIMAL (18, 6) NULL,
    [MaterialMargin]                DECIMAL (18, 6) NULL,
    [LaborHours]                    INT             NULL,
    [LaborCost]                     DECIMAL (18, 6) NULL,
    [LaborBilling]                  DECIMAL (18, 6) NULL,
    [LaborRevenuePercentage]        DECIMAL (18, 6) NULL,
    [LaborMargin]                   DECIMAL (18, 6) NULL,
    [ChargesCost]                   DECIMAL (18, 6) NULL,
    [ChargesBilling]                DECIMAL (18, 6) NULL,
    [ChargesRevenuePercentage]      DECIMAL (18, 6) NULL,
    [ChargesMargin]                 DECIMAL (18, 6) NULL,
    [ExclusionsCost]                DECIMAL (18, 6) NULL,
    [ExclusionsBilling]             DECIMAL (18, 6) NULL,
    [ExclusionsRevenuePercentage]   DECIMAL (18, 6) NULL,
    [ExclusionsMargin]              DECIMAL (18, 6) NULL,
    [FreightCost]                   DECIMAL (18, 6) NULL,
    [FreightBilling]                DECIMAL (18, 6) NULL,
    [FreightRevenuePercentage]      DECIMAL (18, 6) NULL,
    [FreightMargin]                 DECIMAL (18, 6) NULL,
    [MaterialMarginPer]             DECIMAL (18, 6) NULL,
    [LaborMarginPer]                DECIMAL (18, 6) NULL,
    [ChargesMarginPer]              DECIMAL (18, 6) NULL,
    [ExclusionsMarginPer]           DECIMAL (18, 6) NULL,
    [FreightMarginPer]              DECIMAL (18, 6) NULL,
    [OverHeadCost]                  DECIMAL (18, 6) NULL,
    [AdjustmentHours]               INT             NULL,
    [AdjustedHours]                 INT             NULL,
    [LaborFlatBillingAmount]        DECIMAL (18, 6) NULL,
    [MaterialFlatBillingAmount]     DECIMAL (18, 6) NULL,
    [ChargesFlatBillingAmount]      DECIMAL (18, 6) NULL,
    [FreightFlatBillingAmount]      DECIMAL (18, 6) NULL,
    [MaterialBuildMethod]           INT             NULL,
    [LaborBuildMethod]              INT             NULL,
    [ChargesBuildMethod]            INT             NULL,
    [FreightBuildMethod]            INT             NULL,
    [ExclusionsBuildMethod]         INT             NULL,
    [MaterialMarkupId]              BIGINT          NULL,
    [LaborMarkupId]                 BIGINT          NULL,
    [ChargesMarkupId]               BIGINT          NULL,
    [FreightMarkupId]               BIGINT          NULL,
    [ExclusionsMarkupId]            BIGINT          NULL,
    [FreightRevenue]                DECIMAL (18, 6) NULL,
    [LaborRevenue]                  DECIMAL (18, 6) NULL,
    [MaterialRevenue]               DECIMAL (18, 6) NULL,
    [ExclusionsRevenue]             DECIMAL (18, 6) NULL,
    [ChargesRevenue]                DECIMAL (18, 6) NULL,
    [OverHeadCostRevenuePercentage] DECIMAL (18, 6) NULL,
    [QuoteParentId]                 BIGINT          NULL,
    [IsVersionIncrease]             BIT             NULL,
    [QuoteMethod]                   BIT             NULL,
    [CommonFlatRate]                DECIMAL (18, 6) NULL,
    [EvalFees]                      DECIMAL (18, 6) NULL);
