CREATE TYPE [dbo].[WorkOrderMaterialListType] AS TABLE (
    [WorkOrderMaterialsId]       BIGINT          NULL,
    [WorkOrderId]                BIGINT          NULL,
    [WorkFlowWorkOrderId]        BIGINT          NULL,
    [ItemMasterId]               BIGINT          NULL,
    [TaskId]                     BIGINT          NULL,
    [ConditionCodeId]            BIGINT          NULL,
    [ItemClassificationId]       BIGINT          NULL,
    [Quantity]                   DECIMAL (18, 6) NULL,
    [UnitOfMeasureId]            BIGINT          NULL,
    [UnitCost]                   DECIMAL (18, 6) NULL,
    [ExtendedCost]               DECIMAL (18, 6) NULL,
    [Memo]                       VARCHAR (500)   NULL,
    [IsDeferred]                 BIT             NULL,
    [QuantityReserved]           DECIMAL (18, 6) NULL,
    [QuantityIssued]             DECIMAL (18, 6) NULL,
    [IssuedById]                 BIGINT          NULL,
    [IssuedDate]                 DATETIME        NULL,
    [ReservedById]               BIGINT          NULL,
    [ReservedDate]               DATETIME        NULL,
    [IsAltPart]                  BIT             NULL,
    [AltPartMasterPartId]        BIGINT          NULL,
    [PartStatusId]               INT             NULL,
    [UnReservedQty]              DECIMAL (18, 6) NULL,
    [UnIssuedQty]                DECIMAL (18, 6) NULL,
    [ParentWorkOrderMaterialsId] BIGINT          NULL,
    [ItemMappingId]              BIGINT          NULL,
    [TotalReserved]              DECIMAL (18, 6) NULL,
    [TotalIssued]                DECIMAL (18, 6) NULL,
    [TotalUnReserved]            DECIMAL (18, 6) NULL,
    [TotalUnIssued]              DECIMAL (18, 6) NULL,
    [ProvisionId]                INT             NULL,
    [MaterialMandatoriesId]      INT             NULL,
    [IsFromWorkFlow]             BIT             NULL,
    [IsEquPart]                  BIT             NULL,
    [IsDeleted]                  BIT             NULL);

