CREATE TYPE [dbo].[WorksheetHeaderTableType] AS TABLE (
    [WorksheetHeaderId]            BIGINT         NULL,
    [WorksheetNumber]              VARCHAR (50)   NULL,
    [MakeTypeId]                   BIGINT         NULL,
    [MakeType]                     VARCHAR (100)  NULL,
    [AircraftModelId]              BIGINT         NULL,
    [AircraftModel]                VARCHAR (100)  NULL,
    [WorksheetType]                VARCHAR (50)   NULL,
    [WorksheetTypeId]              BIGINT         NULL,
    [WorkOrderNo]                  VARCHAR (50)   NULL,
    [TailNum]                      VARCHAR (50)   NULL,
    [SerialNum]                    VARCHAR (50)   NULL,
    [AFHours]                      VARCHAR (50)   NULL,
    [InspectionDate]               DATETIME       NULL,
    [QualitySafetyDeptSignOutDate] DATETIME       NULL,
    [QualitySafetyDeptSignInDate]  DATETIME       NULL,
    [ReleaseDate]                  DATETIME       NULL,
    [ReleaseLicenseNumber]         VARCHAR (100)  NULL,
    [AMONumber]                    VARCHAR (100)  NULL,
    [AircraftReg]                  VARCHAR (50)   NULL,
    [TechnicalRecordsWO]           VARCHAR (100)  NULL,
    [CalmSysWO]                    VARCHAR (100)  NULL,
    [CertificationStatement]       VARCHAR (2000) NULL,
    [InspectionType]               BIGINT         NULL,
    [QualitySafetyDeptSignOutBy]   BIGINT         NULL,
    [QualitySafetyDeptSignInBy]    BIGINT         NULL,
    [ReleaseToServiceBy]           BIGINT         NULL,
    [IsActive]                     BIT            NULL,
    [IsDeleted]                    BIT            NULL,
    [MasterCompanyId]              INT            NOT NULL,
    [CreatedBy]                    VARCHAR (256)  NULL,
    [UpdatedBy]                    VARCHAR (256)  NULL);

