CREATE TYPE [dbo].[WorkOrderQuoteLaborType] AS TABLE (
    [WorkOrderQuoteLaborId]       BIGINT          NULL,
    [WorkOrderQuoteLaborHeaderId] BIGINT          NULL,
    [ExpertiseId]                 SMALLINT        NULL,
    [Hours]                       DECIMAL (10, 2) NULL,
    [BillableId]                  INT             NULL,
    [CreatedBy]                   VARCHAR (256)   NULL,
    [UpdatedBy]                   VARCHAR (256)   NULL,
    [CreatedDate]                 DATETIME2 (7)   NULL,
    [UpdatedDate]                 DATETIME2 (7)   NULL,
    [IsActive]                    BIT             NULL,
    [IsDeleted]                   BIT             NULL,
    [TaskId]                      BIGINT          NULL,
    [DirectLaborOHCost]           DECIMAL (18, 6) NULL,
    [MarkupPercentageId]          BIGINT          NULL,
    [BurdenRateAmount]            DECIMAL (18, 6) NULL,
    [TotalCostPerHour]            DECIMAL (18, 6) NULL,
    [TotalCost]                   DECIMAL (18, 6) NULL,
    [BillingRate]                 DECIMAL (18, 6) NULL,
    [BillingAmount]               DECIMAL (18, 6) NULL,
    [BurdaenRatePercentageId]     BIGINT          NULL,
    [BillingMethodId]             INT             NULL,
    [MasterCompanyId]             INT             NULL,
    [TaskName]                    VARCHAR (100)   NULL,
    [Expertise]                   VARCHAR (50)    NULL,
    [Billabletype]                VARCHAR (50)    NULL,
    [BurdaenRatePercentage]       VARCHAR (50)    NULL,
    [BillingName]                 VARCHAR (50)    NULL,
    [MarkUp]                      VARCHAR (50)    NULL,
    [EmployeeId]                  BIGINT          NULL);

