CREATE TYPE [dbo].[WorkflowExpertiseListType] AS TABLE (
    [WorkflowExpertiseListId] BIGINT          NULL,
    [WorkflowId]              BIGINT          NULL,
    [ExpertiseTypeId]         SMALLINT        NULL,
    [EstimatedHours]          DECIMAL (18, 2) NULL,
    [LaborDirectRate]         DECIMAL (18, 2) NULL,
    [DirectLaborRate]         DECIMAL (18, 2) NULL,
    [OverheadBurden]          DECIMAL (18, 2) NULL,
    [OverheadCost]            DECIMAL (18, 2) NULL,
    [StandardRate]            DECIMAL (18, 2) NULL,
    [LaborOverheadCost]       DECIMAL (18, 2) NULL,
    [TaskId]                  BIGINT          NULL,
    [MasterCompanyId]         INT             NULL,
    [CreatedBy]               VARCHAR (256)   NULL,
    [UpdatedBy]               VARCHAR (256)   NULL,
    [CreatedDate]             DATETIME2 (7)   NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [IsActive]                BIT             NULL,
    [IsDeleted]               BIT             NULL,
    [Order]                   INT             NULL,
    [Memo]                    NVARCHAR (MAX)  NULL,
    [WFParentId]              BIGINT          NULL,
    [IsVersionIncrease]       BIT             NULL,
    [OverheadburdenPercentId] BIGINT          NULL);

