CREATE TYPE [dbo].[WorkOrderQuoteChargesType] AS TABLE (
    [WorkOrderQuoteChargesId] BIGINT          NULL,
    [WorkOrderQuoteDetailsId] BIGINT          NULL,
    [ChargesTypeId]           BIGINT          NULL,
    [VendorId]                BIGINT          NULL,
    [Quantity]                DECIMAL (18, 6) NULL,
    [MarkupPercentageId]      BIGINT          NULL,
    [Description]             VARCHAR (256)   NULL,
    [UnitCost]                DECIMAL (20, 2) NULL,
    [ExtendedCost]            DECIMAL (20, 2) NULL,
    [MasterCompanyId]         INT             NULL,
    [CreatedBy]               VARCHAR (256)   NULL,
    [UpdatedBy]               VARCHAR (256)   NULL,
    [CreatedDate]             DATETIME2 (7)   NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [IsActive]                BIT             NULL,
    [IsDeleted]               BIT             NULL,
    [TaskId]                  BIGINT          NULL,
    [MarkupFixedPrice]        VARCHAR (15)    NULL,
    [BillingAmount]           DECIMAL (20, 2) NULL,
    [BillingRate]             DECIMAL (20, 2) NULL,
    [HeaderMarkupId]          BIGINT          NULL,
    [RefNum]                  VARCHAR (20)    NULL,
    [BillingMethodId]         INT             NULL,
    [TaskName]                VARCHAR (100)   NULL,
    [ChargeType]              VARCHAR (50)    NULL,
    [GlAccountName]           VARCHAR (50)    NULL,
    [VendorName]              VARCHAR (50)    NULL,
    [BillingName]             VARCHAR (50)    NULL,
    [MarkUp]                  VARCHAR (50)    NULL,
    [UOMId]                   BIGINT          NULL);

