CREATE TYPE [dbo].[WorkflowChargesListType] AS TABLE (
    [WorkflowChargesListId] BIGINT          NULL,
    [WorkflowId]            BIGINT          NULL,
    [WorkflowChargeTypeId]  TINYINT         NULL,
    [Description]           VARCHAR (500)   NULL,
    [Quantity]              SMALLINT        NULL,
    [UnitCost]              DECIMAL (18, 2) NULL,
    [ExtendedCost]          DECIMAL (18, 2) NULL,
    [UnitPrice]             DECIMAL (18, 2) NULL,
    [ExtendedPrice]         DECIMAL (18, 2) NULL,
    [VendorId]              BIGINT          NULL,
    [TaskId]                BIGINT          NULL,
    [MasterCompanyId]       INT             NULL,
    [CreatedBy]             VARCHAR (256)   NULL,
    [UpdatedBy]             VARCHAR (256)   NULL,
    [CreatedDate]           DATETIME2 (7)   NULL,
    [UpdatedDate]           DATETIME2 (7)   NULL,
    [IsActive]              BIT             NULL,
    [VendorName]            VARCHAR (256)   NULL,
    [Order]                 INT             NULL,
    [IsDeleted]             BIT             NULL,
    [Memo]                  NVARCHAR (MAX)  NULL,
    [WFParentId]            BIGINT          NULL,
    [IsVersionIncrease]     BIT             NULL);

