CREATE TYPE [dbo].[CashReceiptSearchParamsType] AS TABLE (
    [UrlName]                   VARCHAR (500) NULL,
    [FromInvoiceDate]           DATETIME2 (7) NULL,
    [ToInvoiceDate]             DATETIME2 (7) NULL,
    [FromCheckNum]              VARCHAR (150) NULL,
    [ToCheckNum]                VARCHAR (150) NULL,
    [FromReceiptDate]           DATETIME2 (7) NULL,
    [ToReceiptDate]             DATETIME2 (7) NULL,
    [FromInvoiceNum]            VARCHAR (150) NULL,
    [ToInvoiceNum]              VARCHAR (150) NULL,
    [FromPostDate]              DATETIME2 (7) NULL,
    [ToPostDate]                DATETIME2 (7) NULL,
    [PaymentMethodId]           VARCHAR (50)  NULL,
    [BankAcct]                  VARCHAR (150) NULL,
    [CustomerId]                VARCHAR (150) NULL,
    [Level1]                    VARCHAR (150) NULL,
    [Level2]                    VARCHAR (150) NULL,
    [Level3]                    VARCHAR (150) NULL,
    [Level4]                    VARCHAR (150) NULL,
    [Level5]                    VARCHAR (150) NULL,
    [Level6]                    VARCHAR (150) NULL,
    [Level7]                    VARCHAR (150) NULL,
    [Level8]                    VARCHAR (150) NULL,
    [Level9]                    VARCHAR (150) NULL,
    [Level10]                   VARCHAR (150) NULL,
    [MasterCompanyId]           INT           NOT NULL,
    [CreatedBy]                 VARCHAR (256) NOT NULL,
    [CashReceiptSearchParamsId] BIGINT        NULL);

