CREATE TYPE [dbo].[CustomerRMADeatilsType] AS TABLE (
    [RMADeatilsId]           BIGINT          NOT NULL,
    [RMAHeaderId]            BIGINT          NOT NULL,
    [ItemMasterId]           BIGINT          NOT NULL,
    [PartNumber]             VARCHAR (100)   NULL,
    [PartDescription]        VARCHAR (MAX)   NULL,
    [AltPartNumber]          VARCHAR (100)   NULL,
    [CustPartNumber]         VARCHAR (100)   NULL,
    [SerialNumber]           VARCHAR (100)   NULL,
    [StocklineId]            BIGINT          NULL,
    [StocklineNumber]        VARCHAR (100)   NULL,
    [ControlNumber]          VARCHAR (100)   NULL,
    [ControlId]              VARCHAR (100)   NULL,
    [ReferenceId]            BIGINT          NULL,
    [ReferenceNo]            VARCHAR (100)   NULL,
    [Qty]                    INT             NULL,
    [UnitPrice]              DECIMAL (18, 2) NULL,
    [Amount]                 DECIMAL (18, 2) NULL,
    [RMAReasonId]            INT             NULL,
    [RMAReason]              VARCHAR (500)   NULL,
    [Notes]                  NVARCHAR (MAX)  NULL,
    [isWorkOrder]            BIT             NULL,
    [MasterCompanyId]        INT             NOT NULL,
    [CreatedBy]              VARCHAR (256)   NOT NULL,
    [UpdatedBy]              VARCHAR (256)   NOT NULL,
    [CreatedDate]            DATETIME2 (7)   NOT NULL,
    [UpdatedDate]            DATETIME2 (7)   NOT NULL,
    [IsActive]               BIT             NOT NULL,
    [IsDeleted]              BIT             NOT NULL,
    [InvoiceId]              BIGINT          NULL,
    [BillingInvoicingItemId] BIGINT          NULL,
    [CustomerReference]      VARCHAR (100)   NULL);



