CREATE TYPE [dbo].[ItemMasterTableType] AS TABLE (
    [ItemTypeId]                        INT             NOT NULL,
    [PartAlternatePartId]               BIGINT          NULL,
    [ItemGroupId]                       BIGINT          NULL,
    [ItemClassificationId]              BIGINT          NOT NULL,
    [IsHazardousMaterial]               BIT             NOT NULL,
    [IsExpirationDateAvailable]         BIT             NOT NULL,
    [ExpirationDate]                    DATE            NULL,
    [IsReceivedDateAvailable]           BIT             NOT NULL,
    [DaysReceived]                      INT             NOT NULL,
    [IsManufacturingDateAvailable]      BIT             NOT NULL,
    [ManufacturingDays]                 INT             NOT NULL,
    [IsTagDateAvailable]                BIT             NOT NULL,
    [TagDays]                           INT             NOT NULL,
    [IsOpenDateAvailable]               BIT             NOT NULL,
    [OpenDays]                          INT             NOT NULL,
    [IsShippedDateAvailable]            BIT             NOT NULL,
    [ShippedDays]                       INT             NOT NULL,
    [IsOtherDateAvailable]              BIT             NOT NULL,
    [OtherDays]                         INT             NOT NULL,
    [ManufacturerId]                    BIGINT          NULL,
    [IsDER]                             BIT             NOT NULL,
    [NationalStockNumber]               VARCHAR (50)    NULL,
    [IsSchematic]                       BIT             NOT NULL,
    [OverhaulHours]                     INT             NOT NULL,
    [RPHours]                           INT             NOT NULL,
    [TestHours]                         INT             NOT NULL,
    [RFQTracking]                       BIT             NOT NULL,
    [GLAccountId]                       BIGINT          NOT NULL,
    [PurchaseUnitOfMeasureId]           BIGINT          NOT NULL,
    [StockUnitOfMeasureId]              BIGINT          NULL,
    [ConsumeUnitOfMeasureId]            BIGINT          NULL,
    [LeadTimeDays]                      INT             NOT NULL,
    [ReorderPoint]                      INT             NOT NULL,
    [ReorderQuantiy]                    INT             NOT NULL,
    [MinimumOrderQuantity]              INT             NOT NULL,
    [PriorityId]                        BIGINT          NULL,
    [Memo]                              NVARCHAR (MAX)  NULL,
    [ExportSizeUnit]                    VARCHAR (30)    NULL,
    [PurchaseCurrencyId]                INT             NOT NULL,
    [SalesCurrencyId]                   INT             NOT NULL,
    [SalesLastSalePriceDate]            DATETIME2 (7)   NULL,
    [SalesLastSalesDiscountPercentDate] DATETIME2 (7)   NULL,
    [IsActive]                          BIT             NULL,
    [MasterCompanyId]                   INT             NOT NULL,
    [CreatedBy]                         VARCHAR (256)   NULL,
    [UpdatedBy]                         VARCHAR (256)   NULL,
    [CreatedDate]                       DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                       DATETIME2 (7)   NOT NULL,
    [TurnTimeOverhaulHours]             INT             NOT NULL,
    [TurnTimeRepairHours]               INT             NOT NULL,
    [IsDeleted]                         BIT             NULL,
    [partnumber]                        VARCHAR (50)    NULL,
    [PartDescription]                   NVARCHAR (MAX)  NULL,
    [isTimeLife]                        BIT             NOT NULL,
    [isSerialized]                      BIT             NOT NULL,
    [ShelfLife]                         BIT             NOT NULL,
    [StockLevel]                        INT             NOT NULL,
    [ShelfLifeAvailable]                NUMERIC (18, 2) NOT NULL,
    [mfgHours]                          NUMERIC (18, 2) NOT NULL,
    [IsPma]                             BIT             NOT NULL,
    [turnTimeMfg]                       NUMERIC (18, 2) NOT NULL,
    [turnTimeBenchTest]                 NUMERIC (18, 2) NOT NULL,
    [IsOemPNId]                         BIGINT          NULL,
    [MasterPartId]                      BIGINT          NULL,
    [RepairUnitOfMeasureId]             BIGINT          NULL,
    [RevisedPartId]                     BIGINT          NULL,
    [SiteId]                            BIGINT          NOT NULL,
    [WarehouseId]                       BIGINT          NULL,
    [LocationId]                        BIGINT          NULL,
    [ShelfId]                           BIGINT          NULL,
    [BinId]                             BIGINT          NULL,
    [ItemMasterAssetTypeId]             BIGINT          NOT NULL,
    [IsHotItem]                         BIT             NOT NULL,
    [IsOEM]                             BIT             NOT NULL,
    [RevisedPart]                       VARCHAR (250)   NULL,
    [OEMPN]                             VARCHAR (250)   NULL,
    [ItemClassificationName]            VARCHAR (250)   NULL,
    [ItemGroup]                         VARCHAR (250)   NULL,
    [AssetAcquistionType]               VARCHAR (250)   NULL,
    [ManufacturerName]                  VARCHAR (250)   NULL,
    [PurchaseUnitOfMeasure]             VARCHAR (250)   NULL,
    [StockUnitOfMeasure]                VARCHAR (250)   NULL,
    [ConsumeUnitOfMeasure]              VARCHAR (250)   NULL,
    [PurchaseCurrency]                  VARCHAR (50)    NULL,
    [SalesCurrency]                     VARCHAR (50)    NULL,
    [GLAccount]                         VARCHAR (250)   NULL,
    [Priority]                          VARCHAR (250)   NULL,
    [SiteName]                          VARCHAR (250)   NULL,
    [WarehouseName]                     VARCHAR (250)   NULL,
    [LocationName]                      VARCHAR (250)   NULL,
    [ShelfName]                         VARCHAR (250)   NULL,
    [BinName]                           VARCHAR (250)   NULL,
    [CurrentStlNo]                      BIGINT          NULL,
    [MTBUR]                             INT             NOT NULL,
    [NE]                                INT             NOT NULL,
    [NS]                                INT             NOT NULL,
    [OH]                                INT             NOT NULL,
    [REP]                               INT             NOT NULL,
    [SVC]                               INT             NOT NULL,
    [Figure]                            VARCHAR (15)    NULL,
    [Item]                              VARCHAR (15)    NULL,
    [UNCode]                            BIT             NULL,
    [InventoryGLSettingId]              BIGINT          NULL,
    [GoodsReceivedNotInvoicesGLAccId]   BIGINT          NULL,
    [WorkInProgressGLAccId]             BIGINT          NULL,
    [InventoryToBillGLAccId]            BIGINT          NULL,
    [FinishedGoodsGLAccId]              BIGINT          NULL,
    [InventoryExchAgreementGLAccId]     BIGINT          NULL,
    [InventoryReserveGLAccId]           BIGINT          NULL,
    [COGS_WorkOrderGLAccId]             BIGINT          NULL,
    [COGS_SalesOrderGLAccId]            BIGINT          NULL,
    [COGS_QtyVarianceGLAccId]           BIGINT          NULL,
    [COGS_UnitCostVarianceGLAccId]      BIGINT          NULL,
    [RevenueMroGLAccId]                 BIGINT          NULL,
    [RevenueSoGLAccId]                  BIGINT          NULL,
    [RevenueExchGLAccId]                BIGINT          NULL,
    [COGS_ExchSalesOrderGLAccId]        BIGINT          NULL,
    [GoodsReceivedNotInvoicesGLAccName] VARCHAR (255)   NULL,
    [WorkInProgressGLAccName]           VARCHAR (255)   NULL,
    [InventoryToBillGLAccName]          VARCHAR (255)   NULL,
    [FinishedGoodsGLAccName]            VARCHAR (255)   NULL,
    [InventoryExchAgreementGLAccName]   VARCHAR (255)   NULL,
    [InventoryReserveGLAccName]         VARCHAR (255)   NULL,
    [COGS_WorkOrderGLAccName]           VARCHAR (255)   NULL,
    [COGS_SalesOrderGLAccName]          VARCHAR (255)   NULL,
    [COGS_QtyVarianceGLAccName]         VARCHAR (255)   NULL,
    [COGS_UnitCostVarianceGLAccName]    VARCHAR (255)   NULL,
    [RevenueMroGLAccName]               VARCHAR (255)   NULL,
    [RevenueSoGLAccName]                VARCHAR (255)   NULL,
    [RevenueExchGLAccName]              VARCHAR (255)   NULL,
    [COGS_ExchSalesOrderGLAccName]      VARCHAR (255)   NULL,
    [IsUpdated]                         BIT             NULL,
    [WorkOrderFormTypeId]               INT             NULL,
    [ItemMasterRankingIds]              VARCHAR (MAX)   NULL,
    [IsFlightHoursAvailable]            BIT             NULL,
    [IsFlightCyclesAvailable]           BIT             NULL,
    [IsLandingsAvailable]               BIT             NULL,
    [IsStartsAvailable]                 BIT             NULL,
    [IsCalendarTimeAvailable]           BIT             NULL,
    [FlightHours]                       VARCHAR (200)   NULL,
    [FlightMinutes]                     VARCHAR (200)   NULL,
    [FlightCycles]                      INT             NULL,
    [Landings]                          INT             NULL,
    [Starts]                            INT             NULL,
    [CalendarDate]                      DATETIME2 (7)   NULL);

