CREATE TYPE [dbo].[PurchaseSalesType] AS TABLE (
    [ItemMasterPurchaseSaleId]                BIGINT          NULL,
    [ItemMasterId]                            BIGINT          NULL,
    [PartNumber]                              NVARCHAR (50)   NULL,
    [ConditionId]                             BIGINT          NULL,
    [PP_UOMId]                                BIGINT          NULL,
    [PP_CurrencyId]                           INT             NULL,
    [PP_FXRatePerc]                           DECIMAL (18, 2) NULL,
    [PP_VendorListPrice]                      DECIMAL (18, 2) NULL,
    [PP_LastListPriceDate]                    DATETIME        NULL,
    [PP_PurchaseDiscPerc]                     INT             NULL,
    [PP_PurchaseDiscAmount]                   DECIMAL (18, 2) NULL,
    [PP_LastPurchaseDiscDate]                 DATETIME        NULL,
    [PP_UnitPurchasePrice]                    DECIMAL (18, 2) NULL,
    [SP_FSP_UOMId]                            BIGINT          NULL,
    [SP_FSP_CurrencyId]                       INT             NULL,
    [SP_FSP_FXRatePerc]                       DECIMAL (18, 2) NULL,
    [SP_FSP_FlatPriceAmount]                  DECIMAL (18, 2) NULL,
    [SP_FSP_LastFlatPriceDate]                DATETIME        NULL,
    [SP_CalSPByPP_MarkUpPercOnListPrice]      INT             NULL,
    [SP_CalSPByPP_MarkUpAmount]               DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_LastMarkUpDate]             DATETIME        NULL,
    [SP_CalSPByPP_BaseSalePrice]              DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_SaleDiscPerc]               INT             NULL,
    [SP_CalSPByPP_SaleDiscAmount]             DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_LastSalesDiscDate]          DATETIME        NULL,
    [SP_CalSPByPP_UnitSalePrice]              DECIMAL (18, 2) NULL,
    [SalePriceSelectId]                       INT             NULL,
    [ConditionName]                           NVARCHAR (200)  NULL,
    [PP_UOMName]                              NVARCHAR (200)  NULL,
    [PP_CurrencyName]                         NVARCHAR (200)  NULL,
    [SP_FSP_UOMName]                          NVARCHAR (200)  NULL,
    [SP_FSP_CurrencyName]                     NVARCHAR (200)  NULL,
    [PP_PurchaseDiscPercValue]                DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_MarkUpPercOnListPriceValue] DECIMAL (18, 2) NULL,
    [SP_CalSPByPP_SaleDiscPercValue]          DECIMAL (18, 2) NULL,
    [SalePriceSelectName]                     NVARCHAR (200)  NULL,
    [ManufacturerName]                        NVARCHAR (200)  NULL,
    [SP_CalSPByPP_MarkUpPercValueOnListPrice] INT             NULL,
    [SuggestedPrice]                          DECIMAL (18, 2) NULL,
    [MasterCompanyId]                         INT             NULL,
    [CreatedBy]                               VARCHAR (256)   NULL,
    [CreatedDate]                             DATETIME2 (7)   NULL,
    [UpdatedBy]                               VARCHAR (256)   NULL,
    [UpdatedDate]                             DATETIME2 (7)   NULL,
    [IsActive]                                BIT             NULL,
    [IsDeleted]                               BIT             NULL,
    [EffectiveDate]                           DATETIME2 (7)   NULL);

