CREATE TYPE [dbo].[SalesOrderReserveIssueParts] AS TABLE (
    [SalesOrderReservePartId] BIGINT          NULL,
    [SalesOrderId]            BIGINT          NULL,
    [SalesOrderPartId]        BIGINT          NULL,
    [StockLineId]             BIGINT          NULL,
    [ItemMasterId]            BIGINT          NULL,
    [PartNumber]              VARCHAR (500)   NULL,
    [PartDescription]         VARCHAR (500)   NULL,
    [AltPartDescription]      VARCHAR (500)   NULL,
    [EquPartDescription]      VARCHAR (500)   NULL,
    [EquPartId]               BIGINT          NULL,
    [EquPartNumber]           VARCHAR (500)   NULL,
    [AltPartNumber]           VARCHAR (500)   NULL,
    [AltPartId]               BIGINT          NULL,
    [QuantityOnHand]          INT             NULL,
    [QuantityAvailable]       INT             NULL,
    [ConditionId]             BIGINT          NULL,
    [Condition]               VARCHAR (200)   NULL,
    [IsAltPart]               BIT             NULL,
    [AltPartMasterPartId]     BIGINT          NULL,
    [Quantity]                INT             NULL,
    [QuantityReserved]        INT             NULL,
    [QuantityIssued]          INT             NULL,
    [QuantityOnOrder]         INT             NULL,
    [QuantityToReceive]       INT             NULL,
    [QtyToReserve]            INT             NULL,
    [QtyToIssued]             INT             NULL,
    [QtyToUnReserve]          INT             NULL,
    [QtyToUnIssued]           INT             NULL,
    [QtyToReserveAndIssue]    INT             NULL,
    [IssuedById]              BIGINT          NULL,
    [IssuedDate]              DATETIME2 (7)   NULL,
    [ReservedById]            BIGINT          NULL,
    [ReservedDate]            DATETIME2 (7)   NULL,
    [OemDer]                  VARCHAR (200)   NULL,
    [StockType]               VARCHAR (200)   NULL,
    [IsEquPart]               BIT             NULL,
    [EquPartMasterPartId]     BIGINT          NULL,
    [PartStatusId]            INT             NULL,
    [TotalReserved]           INT             NULL,
    [TotalIssued]             INT             NULL,
    [UnitCost]                DECIMAL (18, 4) NULL,
    [ExtendedCost]            DECIMAL (18, 4) NULL,
    [UnitPrice]               DECIMAL (18, 4) NULL,
    [ExtendedPrice]           DECIMAL (18, 4) NULL,
    [AlternateFor]            VARCHAR (200)   NULL,
    [StockLineNumber]         VARCHAR (200)   NULL,
    [ControlNumber]           VARCHAR (200)   NULL,
    [QtyToBeReserved]         INT             NULL,
    [ManufacturerName]        VARCHAR (200)   NULL,
    [LotId]                   BIGINT          NULL,
    [IsLotQty]                BIT             NULL,
    [MasterCompanyId]         INT             NULL,
    [CreatedBy]               VARCHAR (100)   NULL,
    [UpdatedBy]               VARCHAR (256)   NULL,
    [CreatedDate]             DATETIME2 (7)   NULL,
    [UpdatedDate]             DATETIME2 (7)   NULL,
    [IsActive]                BIT             NULL,
    [IsDeleted]               BIT             NULL);

