CREATE TYPE [dbo].[StockInvenorySearchParamsType] AS TABLE (
    [UrlName]                      VARCHAR (500) NULL,
    [FromReceivedDate]             DATETIME2 (7) NULL,
    [ToReceivedDate]               DATETIME2 (7) NULL,
    [FromControlNumber]            VARCHAR (50)  NULL,
    [ToControlNumber]              VARCHAR (50)  NULL,
    [FromUnitCost]                 VARCHAR (100) NULL,
    [ToUnitCost]                   VARCHAR (100) NULL,
    [ItemMasterId]                 BIGINT        NULL,
    [VendorId]                     BIGINT        NULL,
    [ConditionId]                  BIGINT        NULL,
    [LotId]                        BIGINT        NULL,
    [TraceableTo]                  BIGINT        NULL,
    [SiteId]                       BIGINT        NULL,
    [WarehouseId]                  BIGINT        NULL,
    [LocationId]                   BIGINT        NULL,
    [ShelfId]                      BIGINT        NULL,
    [BinId]                        BIGINT        NULL,
    [PoRoRefrences]                VARCHAR (50)  NULL,
    [Level1]                       VARCHAR (100) NULL,
    [Level2]                       VARCHAR (100) NULL,
    [Level3]                       VARCHAR (100) NULL,
    [Level4]                       VARCHAR (100) NULL,
    [Level5]                       VARCHAR (100) NULL,
    [Level6]                       VARCHAR (100) NULL,
    [Level7]                       VARCHAR (100) NULL,
    [Level8]                       VARCHAR (100) NULL,
    [Level9]                       VARCHAR (100) NULL,
    [Level10]                      VARCHAR (100) NULL,
    [MasterCompanyId]              INT           NOT NULL,
    [CreatedBy]                    VARCHAR (50)  NOT NULL,
    [StockInventorySearchParamsId] BIGINT        NULL);

