CREATE TYPE [dbo].[TimeLifeType] AS TABLE (
    [TimeLifeCyclesId]          BIGINT        NULL,
    [CyclesRemaining]           VARCHAR (20)  NULL,
    [CyclesSinceNew]            VARCHAR (20)  NULL,
    [CyclesSinceOVH]            VARCHAR (20)  NULL,
    [CyclesSinceInspection]     VARCHAR (20)  NULL,
    [CyclesSinceRepair]         VARCHAR (20)  NULL,
    [TimeRemaining]             VARCHAR (20)  NULL,
    [TimeSinceNew]              VARCHAR (20)  NULL,
    [TimeSinceOVH]              VARCHAR (20)  NULL,
    [TimeSinceInspection]       VARCHAR (20)  NULL,
    [TimeSinceRepair]           VARCHAR (20)  NULL,
    [LastSinceNew]              VARCHAR (20)  NULL,
    [LastSinceOVH]              VARCHAR (20)  NULL,
    [LastSinceInspection]       VARCHAR (20)  NULL,
    [MasterCompanyId]           INT           NULL,
    [CreatedBy]                 VARCHAR (256) NULL,
    [UpdatedBy]                 VARCHAR (256) NULL,
    [CreatedDate]               DATETIME2 (7) NULL,
    [UpdatedDate]               DATETIME2 (7) NULL,
    [IsActive]                  BIT           NULL,
    [PurchaseOrderId]           BIGINT        NULL,
    [PurchaseOrderPartRecordId] BIGINT        NULL,
    [StockLineId]               BIGINT        NULL,
    [DetailsNotProvided]        BIT           NULL,
    [RepairOrderId]             BIGINT        NULL,
    [RepairOrderPartRecordId]   BIGINT        NULL,
    [VendorRMAId]               BIGINT        NULL,
    [VendorRMADetailId]         BIGINT        NULL);

