CREATE TYPE [dbo].[UpdateNonStocklineReceivingPOType] AS TABLE (
    [NonStockInventoryDraftId]     BIGINT          NOT NULL,
    [NonStockDraftNumber]          VARCHAR (50)    NULL,
    [PurchaseOrderId]              BIGINT          NOT NULL,
    [PurchaseOrderPartRecordId]    BIGINT          NOT NULL,
    [PurchaseOrderNumber]          VARCHAR (50)    NULL,
    [IsParent]                     BIT             NULL,
    [ParentId]                     BIGINT          NULL,
    [MasterPartId]                 BIGINT          NOT NULL,
    [PartNumber]                   VARCHAR (50)    NULL,
    [PartDescription]              NVARCHAR (50)   NULL,
    [NonStockInventoryId]          BIGINT          NULL,
    [NonStockInventoryNumber]      VARCHAR (50)    NULL,
    [ControlNumber]                VARCHAR (50)    NULL,
    [ControlID]                    VARCHAR (50)    NULL,
    [IdNumber]                     VARCHAR (100)   NULL,
    [ReceiverNumber]               VARCHAR (50)    NULL,
    [ReceivedDate]                 DATETIME2 (7)   NULL,
    [isSerialized]                 BIT             NOT NULL,
    [SerialNumber]                 VARCHAR (50)    NULL,
    [Quantity]                     INT             NOT NULL,
    [QuantityRejected]             INT             NULL,
    [QuantityOnHand]               INT             NULL,
    [CurrencyId]                   BIGINT          NULL,
    [Currency]                     VARCHAR (50)    NULL,
    [ConditionId]                  BIGINT          NULL,
    [Condition]                    VARCHAR (250)   NULL,
    [GLAccountId]                  BIGINT          NULL,
    [GLAccount]                    VARCHAR (250)   NULL,
    [UnitOfMeasureId]              BIGINT          NULL,
    [UnitOfMeasure]                VARCHAR (250)   NULL,
    [ManufacturerId]               BIGINT          NULL,
    [Manufacturer]                 VARCHAR (50)    NULL,
    [MfgExpirationDate]            DATETIME2 (7)   NULL,
    [UnitCost]                     DECIMAL (18, 2) NULL,
    [ExtendedCost]                 DECIMAL (18, 2) NULL,
    [Acquired]                     INT             NULL,
    [IsHazardousMaterial]          BIT             NULL,
    [ItemNonStockClassificationId] BIGINT          NULL,
    [NonStockClassification]       VARCHAR (50)    NULL,
    [SiteId]                       BIGINT          NOT NULL,
    [Site]                         VARCHAR (250)   NULL,
    [WarehouseId]                  BIGINT          NULL,
    [Warehouse]                    VARCHAR (250)   NULL,
    [LocationId]                   BIGINT          NULL,
    [Location]                     VARCHAR (250)   NULL,
    [ShelfId]                      BIGINT          NULL,
    [Shelf]                        VARCHAR (250)   NULL,
    [BinId]                        BIGINT          NULL,
    [Bin]                          VARCHAR (250)   NULL,
    [ShippingViaId]                BIGINT          NULL,
    [ShippingVia]                  VARCHAR (250)   NULL,
    [ShippingAccount]              NVARCHAR (400)  NULL,
    [ShippingReference]            NVARCHAR (400)  NULL,
    [IsSameDetailsForAllParts]     BIT             NULL,
    [VendorId]                     BIGINT          NULL,
    [VendorName]                   VARCHAR (100)   NULL,
    [RequisitionerId]              BIGINT          NULL,
    [Requisitioner]                VARCHAR (100)   NULL,
    [OrderDate]                    DATETIME2 (7)   NULL,
    [EntryDate]                    DATETIME2 (7)   NULL,
    [ManagementStructureEntityId]  BIGINT          NOT NULL,
    [Level1]                       VARCHAR (200)   NULL,
    [Level2]                       VARCHAR (200)   NULL,
    [Level3]                       VARCHAR (200)   NULL,
    [Level4]                       VARCHAR (200)   NULL,
    [Memo]                         NVARCHAR (MAX)  NULL,
    [MasterCompanyId]              INT             NOT NULL,
    [CreatedBy]                    VARCHAR (256)   NULL,
    [UpdatedBy]                    VARCHAR (256)   NULL,
    [CreatedDate]                  DATETIME2 (7)   NULL,
    [UpdatedDate]                  DATETIME2 (7)   NULL,
    [isActive]                     BIT             NULL,
    [isDeleted]                    BIT             NULL);

