CREATE TYPE [dbo].[WorkOrderSettlementDetailsUpdateType] AS TABLE (
    [WorkOrderSettlementDetailId] BIGINT         NULL,
    [WorkOrderId]                 BIGINT         NULL,
    [WorkFlowWorkOrderId]         BIGINT         NULL,
    [workOrderPartNoId]           BIGINT         NULL,
    [WorkOrderSettlementId]       INT            NULL,
    [WorkOrderSettlementName]     VARCHAR (500)  NULL,
    [IsMastervalue]               BIT            NULL,
    [Isvalue_NA]                  BIT            NULL,
    [Memo]                        NVARCHAR (MAX) NULL,
    [ConditionId]                 BIGINT         NULL,
    [UserId]                      BIGINT         NULL,
    [conditionName]               VARCHAR (200)  NULL,
    [UserName]                    VARCHAR (500)  NULL,
    [sattlement_DateTime]         DATETIME       NULL,
    [MasterCompanyId]             INT            NULL,
    [CreatedBy]                   VARCHAR (256)  NULL,
    [UpdatedBy]                   VARCHAR (256)  NULL,
    [CreatedDate]                 DATETIME       NULL,
    [UpdatedDate]                 DATETIME       NULL,
    [IsActive]                    BIT            NULL,
    [IsDeleted]                   BIT            NULL,
    [RevisedPartId]               BIGINT         NULL);

