CREATE TYPE [dbo].[WorkflowMeasurementListType] AS TABLE (
    [WorkflowMeasurementId] BIGINT          NULL,
    [WorkflowId]            BIGINT          NULL,
    [Sequence]              VARCHAR (50)    NULL,
    [Stage]                 VARCHAR (50)    NULL,
    [Min]                   DECIMAL (18, 2) NULL,
    [Max]                   DECIMAL (18, 2) NULL,
    [Expected]              DECIMAL (18, 2) NULL,
    [DiagramURL]            NVARCHAR (1024) NULL,
    [Memo]                  NVARCHAR (MAX)  NULL,
    [TaskId]                BIGINT          NULL,
    [MasterCompanyId]       INT             NULL,
    [CreatedBy]             VARCHAR (256)   NULL,
    [UpdatedBy]             VARCHAR (256)   NULL,
    [CreatedDate]           DATETIME2 (7)   NULL,
    [UpdatedDate]           DATETIME2 (7)   NULL,
    [IsActive]              BIT             NULL,
    [IsDeleted]             BIT             NULL,
    [ItemMasterId]          BIGINT          NULL,
    [PartNumber]            VARCHAR (256)   NULL,
    [Order]                 INT             NULL,
    [PartDescription]       VARCHAR (MAX)   NULL,
    [WFParentId]            BIGINT          NULL,
    [IsVersionIncrease]     BIT             NULL);

