CREATE TYPE [dbo].[WorkOrderMaterialsType] AS TABLE (
    [WorkOrderMaterialsId]       BIGINT          NULL,
    [WorkOrderId]                BIGINT          NULL,
    [WorkFlowWorkOrderId]        BIGINT          NULL,
    [ItemMasterId]               BIGINT          NULL,
    [TaskId]                     BIGINT          NULL,
    [ConditionCodeId]            BIGINT          NULL,
    [ItemClassificationId]       BIGINT          NULL,
    [Quantity]                   INT             NULL,
    [UnitOfMeasureId]            BIGINT          NULL,
    [UnitCost]                   DECIMAL (18, 2) NULL,
    [ExtendedCost]               DECIMAL (18, 2) NULL,
    [Memo]                       NVARCHAR (MAX)  NULL,
    [IsDeferred]                 BIT             NULL,
    [QuantityReserved]           INT             NULL,
    [QuantityIssued]             INT             NULL,
    [IssuedById]                 BIGINT          NULL,
    [IssuedDate]                 DATETIME2 (7)   NULL,
    [ReservedById]               BIGINT          NULL,
    [ReservedDate]               DATETIME2 (7)   NULL,
    [IsAltPart]                  BIT             NULL,
    [AltPartMasterPartId]        BIGINT          NULL,
    [PartStatusId]               INT             NULL,
    [UnReservedQty]              INT             NULL,
    [UnIssuedQty]                INT             NULL,
    [ParentWorkOrderMaterialsId] BIGINT          NULL,
    [ItemMappingId]              BIGINT          NULL,
    [TotalReserved]              INT             NULL,
    [TotalIssued]                INT             NULL,
    [TotalUnReserved]            INT             NULL,
    [TotalUnIssued]              INT             NULL,
    [QtyToTurnIn]                INT             NULL,
    [ProvisionId]                INT             NULL,
    [MaterialMandatoriesId]      INT             NULL,
    [WOPartNoId]                 BIGINT          NULL,
    [TotalStocklineQtyReq]       INT             NULL,
    [QtyOnOrder]                 INT             NULL,
    [QtyOnBkOrder]               INT             NULL,
    [IsFromWorkFlow]             BIT             NULL,
    [IsEquPart]                  BIT             NULL,
    [StockLineId]                BIGINT          NULL,
    [StocklineQuantity]          INT             NULL,
    [Provision]                  NVARCHAR (MAX)  NULL,
    [WareHouse]                  VARCHAR (100)   NULL,
    [Location]                   VARCHAR (100)   NULL,
    [Shelf]                      VARCHAR (100)   NULL,
    [Bin]                        VARCHAR (100)   NULL,
    [TaskName]                   VARCHAR (200)   NULL,
    [Condition]                  VARCHAR (256)   NULL,
    [MandatoryOrSupplemental]    VARCHAR (50)    NULL,
    [StockLineNumber]            VARCHAR (50)    NULL,
    [PartNumber]                 VARCHAR (50)    NULL,
    [PartDescription]            NVARCHAR (MAX)  NULL,
    [AltPartNumber]              VARCHAR (50)    NULL,
    [SerialNumber]               VARCHAR (30)    NULL,
    [StockType]                  VARCHAR (30)    NULL,
    [ControlId]                  VARCHAR (50)    NULL,
    [ControlNo]                  VARCHAR (50)    NULL,
    [ItemType]                   VARCHAR (100)   NULL,
    [QunatityRequried]           INT             NULL,
    [QunatityReserved]           INT             NULL,
    [QunatityTurnIn]             INT             NULL,
    [QunatityBackOrder]          INT             NULL,
    [QunatityRemaining]          INT             NULL,
    [Currency]                   VARCHAR (20)    NULL,
    [PurchaseOrderNumber]        VARCHAR (50)    NULL,
    [RepairOrderNumber]          VARCHAR (50)    NULL,
    [PartQuantityOnHand]         INT             NULL,
    [PartQuantityAvailable]      INT             NULL,
    [PartQuantityOnOrder]        INT             NULL,
    [Receiver]                   VARCHAR (50)    NULL,
    [WorkOrderNumber]            VARCHAR (500)   NULL,
    [SubWorkOrder]               VARCHAR (50)    NULL,
    [SalesOrder]                 VARCHAR (50)    NULL,
    [TimeLife]                   INT             NULL,
    [PurchaseUnitOfMeasureId]    BIGINT          NULL,
    [IsStocklineEdit]            BIT             NULL,
    [isExistingMaterilas]        BIT             NULL,
    [Figure]                     NVARCHAR (50)   NULL,
    [Item]                       NVARCHAR (50)   NULL,
    [IsAlternatePart]            BIGINT          NULL,
    [EquPartMasterPartId]        BIGINT          NULL,
    [KitId]                      BIGINT          NULL,
    [IsKitType]                  BIT             NULL,
    [isfromsubWorkOrder]         BIT             NULL,
    [ExpectedSerialNumber]       VARCHAR (30)    NULL,
    [POId]                       BIGINT          NULL,
    [PONum]                      NVARCHAR (50)   NULL,
    [PONextDlvrDate]             DATETIME2 (7)   NULL,
    [IsExchangeTender]           BIT             NULL,
    [MasterCompanyId]            INT             NULL,
    [CreatedBy]                  VARCHAR (256)   NULL,
    [UpdatedBy]                  VARCHAR (256)   NULL,
    [CreatedDate]                DATETIME2 (7)   NULL,
    [UpdatedDate]                DATETIME2 (7)   NULL,
    [IsActive]                   BIT             NULL,
    [IsDeleted]                  BIT             NULL,
    -- Notes column for WorkOrderMaterialsType UDT
    [Notes]                      NVARCHAR (MAX)  NULL);

