CREATE TYPE [dbo].[WorkFlowType] AS TABLE (
    [WorkflowId]                   BIGINT          NULL,
    [WorkflowDescription]          NVARCHAR (500)  NULL,
    [Version]                      NVARCHAR (10)   NULL,
    [WorkScopeId]                  BIGINT          NULL,
    [ItemMasterId]                 BIGINT          NULL,
    [PartNumberDescription]        NVARCHAR (MAX)  NULL,
    [CustomerId]                   BIGINT          NULL,
    [CurrencyId]                   INT             NULL,
    [WorkflowExpirationDate]       DATETIME2 (7)   NULL,
    [IsCalculatedBERThreshold]     BIT             NULL,
    [IsFixedAmount]                BIT             NULL,
    [FixedAmount]                  DECIMAL (18, 2) NULL,
    [IsPercentageOfNew]            BIT             NULL,
    [CostOfNew]                    DECIMAL (18, 2) NULL,
    [PercentageOfNew]              BIT             NULL,
    [IsPercentageOfReplacement]    BIT             NULL,
    [CostOfReplacement]            DECIMAL (18, 2) NULL,
    [PercentageOfReplacement]      INT             NULL,
    [Memo]                         NVARCHAR (MAX)  NULL,
    [ManagementStructureId]        BIGINT          NULL,
    [MasterCompanyId]              INT             NULL,
    [CreatedBy]                    NVARCHAR (256)  NULL,
    [UpdatedBy]                    NVARCHAR (256)  NULL,
    [CreatedDate]                  DATETIME2 (7)   NULL,
    [UpdatedDate]                  DATETIME2 (7)   NULL,
    [IsActive]                     BIT             NULL,
    [IsDeleted]                    BIT             NULL,
    [PartNumber]                   NVARCHAR (256)  NULL,
    [CustomerName]                 NVARCHAR (256)  NULL,
    [FlatRate]                     DECIMAL (18, 2) NULL,
    [BERThresholdAmount]           DECIMAL (18, 2) NULL,
    [WorkOrderNumber]              NVARCHAR (256)  NULL,
    [CustomerCode]                 NVARCHAR (100)  NULL,
    [OtherCost]                    DECIMAL (18, 2) NULL,
    [WorkflowCreateDate]           DATETIME2 (7)   NULL,
    [ChangedPartNumberId]          BIGINT          NULL,
    [PercentageOfMaterial]         INT             NULL,
    [PercentageOfExpertise]        INT             NULL,
    [PercentageOfCharges]          INT             NULL,
    [PercentageOfOthers]           INT             NULL,
    [PercentageOfTotal]            DECIMAL (18, 2) NULL,
    [RevisedPartNumber]            NVARCHAR (200)  NULL,
    [ChangedPartNumberDescription] NVARCHAR (200)  NULL,
    [ChangedPartNumber]            NVARCHAR (200)  NULL,
    [WorkScope]                    NVARCHAR (100)  NULL,
    [Currency]                     NVARCHAR (100)  NULL,
    [WFParentId]                   BIGINT          NULL,
    [IsVersionIncrease]            BIT             NULL,
    [Verified]                     BIT             NULL,
    [VerifiedBy]                   VARCHAR (256)   NULL,
    [VerifiedDate]                 DATETIME2 (7)   NULL,
    [TailNum]                      VARCHAR (50)    NULL,
    [SerialNum]                    VARCHAR (100)   NULL,
    [AircraftModelId]              BIGINT          NULL,
    [MakeTypeId]                   INT             NULL,
    [TemplateType]                 INT             NULL,
    [MaintenanceTypeId]            BIGINT          NULL);

