CREATE TYPE [dbo].[WorkflowMaterialListType] AS TABLE (
    [WorkflowMaterialListId]  BIGINT          NULL,
    [WorkflowId]              BIGINT          NULL,
    [ItemMasterId]            BIGINT          NULL,
    [PartNumber]              VARCHAR (500)   NULL,
    [PartDescription]         VARCHAR (500)   NULL,
    [ItemClassificationId]    BIGINT          NULL,
    [TaskId]                  BIGINT          NULL,
    [Quantity]                SMALLINT        NULL,
    [UnitOfMeasureId]         BIGINT          NULL,
    [ConditionCodeId]         SMALLINT        NULL,
    [UnitCost]                DECIMAL (18, 2) NULL,
    [ExtendedCost]            DECIMAL (18, 2) NULL,
    [Price]                   DECIMAL (18, 2) NULL,
    [ExtendedPrice]           DECIMAL (18, 2) NULL,
    [MaterialMandatoriesName] VARCHAR (500)   NULL,
    [MaterialMandatoriesId]   INT             NULL,
    [ProvisionId]             INT             NULL,
    [IsDeferred]              BIT             NULL,
    [WorkflowActionId]        BIT             NULL,
    [Memo]                    VARCHAR (500)   NULL,
    [Order]                   INT             NULL,
    [IsDeleted]               BIT             NULL);

