CREATE TABLE [dbo].[AccountsReceivableCalendar] (
    [AccountsReceivableCalendarId] BIGINT        IDENTITY (1, 1) NOT NULL,
    [Name]                         VARCHAR (50)  NULL,
    [Description]                  VARCHAR (200) NULL,
    [FiscalName]                   VARCHAR (30)  NOT NULL,
    [FiscalYear]                   INT           NULL,
    [Quater]                       TINYINT       NOT NULL,
    [Period]                       TINYINT       NOT NULL,
    [FromDate]                     DATETIME2 (7) CONSTRAINT [DF_AccountsReceivableCalendar_FromDate] DEFAULT (getutcdate()) NULL,
    [ToDate]                       DATETIME2 (7) CONSTRAINT [DF_AccountsReceivableCalendar_ToDate] DEFAULT (getutcdate()) NULL,
    [PeriodName]                   VARCHAR (30)  NOT NULL,
    [Notes]                        NVARCHAR (1)  NULL,
    [MasterCompanyId]              INT           NOT NULL,
    [CreatedBy]                    VARCHAR (256) NOT NULL,
    [UpdatedBy]                    VARCHAR (256) NOT NULL,
    [CreatedDate]                  DATETIME2 (7) CONSTRAINT [DF_AccountsReceivableCalendar_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedDate]                  DATETIME2 (7) CONSTRAINT [DF_AccountsReceivableCalendar_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]                     BIT           CONSTRAINT [DF_AccountsReceivableCalendar__IsActi__59FA5E80] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                    BIT           CONSTRAINT [DF_AccountsReceivableCalendar__IsDele__5AEE82B9] DEFAULT ((0)) NOT NULL,
    [Status]                       VARCHAR (256) NULL,
    [LegalEntityId]                BIGINT        NULL,
    [isUpdate]                     BIT           NOT NULL,
    [IsAdjustPeriod]               BIT           NOT NULL,
    [NoOfPeriods]                  VARCHAR (50)  NULL,
    [PeriodType]                   VARCHAR (50)  NULL,
    [ledgerId]                     INT           NULL,
    [IsCurrentActivePeriod]        BIT           NULL,
    [StartDate]                    DATETIME2 (7) CONSTRAINT [DF_AccountsReceivableCalendar_StartDate] DEFAULT (getutcdate()) NULL,
    [EndDate]                      DATETIME2 (7) CONSTRAINT [DF_AccountsReceivableCalendar_EndDate] DEFAULT (getutcdate()) NULL,
    CONSTRAINT [PK_AccountsReceivableCalendar] PRIMARY KEY CLUSTERED ([AccountsReceivableCalendarId] ASC)
);

