CREATE TABLE [dbo].[AsOfDateSettings] (
    [Id]                    BIGINT         IDENTITY (1, 1) NOT NULL,
    [ReportType]            INT            NULL,
    [ExecutionDate]         INT            NULL,
    [IsWeeklyOrMonthly]     INT            NULL,
    [WeeklyName]            VARCHAR (10)   NULL,
    [ExcludedLocations]     NVARCHAR (500) NULL,
    [SiteIds]               NVARCHAR (500) NULL,
    [WarehouseIds]          NVARCHAR (500) NULL,
    [LocationIds]           NVARCHAR (500) NULL,
    [ShelfIds]              NVARCHAR (500) NULL,
    [BinIds]                NVARCHAR (500) NULL,
    [Level1Ids]             NVARCHAR (500) NULL,
    [Level2Ids]             NVARCHAR (500) NULL,
    [Level3Ids]             NVARCHAR (500) NULL,
    [Level4Ids]             NVARCHAR (500) NULL,
    [Level5Ids]             NVARCHAR (500) NULL,
    [Level6Ids]             NVARCHAR (500) NULL,
    [Level7Ids]             NVARCHAR (500) NULL,
    [Level8Ids]             NVARCHAR (500) NULL,
    [Level9Ids]             NVARCHAR (500) NULL,
    [Level10Ids]            NVARCHAR (500) NULL,
    [ManagementStructureId] BIGINT         NULL,
    [ViewType]              VARCHAR (20)   NULL,
    [IsInvoice]             BIT            NULL,
    [IsCredits]             BIT            NULL,
    [IsDeposit]             BIT            NULL,
    [IsUnappliedAmounts]    BIT            NULL,
    [MasterCompanyId]       INT            NOT NULL,
    [CreatedBy]             VARCHAR (256)  NOT NULL,
    [UpdatedBy]             VARCHAR (256)  NOT NULL,
    [CreatedDate]           DATETIME2 (7)  CONSTRAINT [DF_AsOfDateSettings_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]           DATETIME2 (7)  CONSTRAINT [DF_AsOfDateSettings_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]              BIT            CONSTRAINT [DF_AsOfDateSettings_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]             BIT            CONSTRAINT [DF_AsOfDateSettings_IsDeleted] DEFAULT ((0)) NOT NULL,
    [GroupById]             INT            NULL,
    CONSTRAINT [PK_AsOfDateSettings] PRIMARY KEY CLUSTERED ([Id] ASC)
);

