CREATE TABLE [dbo].[AssetAttributeTypeAudit] (
    [AuditAssetAttributeTypeId]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [AssetAttributeTypeId]          BIGINT         NOT NULL,
    [TangibleClassId]               BIGINT         NOT NULL,
    [AssetAttributeTypeName]        VARCHAR (30)   NOT NULL,
    [Description]                   VARCHAR (100)  NULL,
    [ConventionType]                BIGINT         NOT NULL,
    [DepreciationMethod]            BIGINT         NOT NULL,
    [ResidualPercentage]            BIGINT         NOT NULL,
    [AssetLife]                     INT            NOT NULL,
    [DepreciationFrequencyId]       BIGINT         NOT NULL,
    [AcquiredGLAccountId]           BIGINT         NOT NULL,
    [DeprExpenseGLAccountId]        BIGINT         NOT NULL,
    [AdDepsGLAccountId]             BIGINT         NOT NULL,
    [AssetSale]                     BIGINT         NOT NULL,
    [AssetWriteOff]                 BIGINT         NOT NULL,
    [AssetWriteDown]                BIGINT         NOT NULL,
    [ManagementStructureId]         BIGINT         NULL,
    [MasterCompanyId]               INT            NOT NULL,
    [CreatedBy]                     VARCHAR (256)  NOT NULL,
    [UpdatedBy]                     VARCHAR (256)  NOT NULL,
    [CreatedDate]                   DATETIME2 (7)  NOT NULL,
    [UpdatedDate]                   DATETIME2 (7)  NOT NULL,
    [IsActive]                      BIT            NOT NULL,
    [IsDeleted]                     BIT            NOT NULL,
    [SelectedCompanyIds]            VARCHAR (1000) NOT NULL,
    [TangibleClassName]             VARCHAR (100)  NULL,
    [ConventionTypeName]            VARCHAR (100)  NULL,
    [AssetDepreciationMethodName]   VARCHAR (100)  NULL,
    [AssetDepreciationIntervalName] VARCHAR (100)  NULL,
    [PercentValue]                  VARCHAR (100)  NULL,
    [AcquiredGLAccount]             VARCHAR (100)  NULL,
    [DeprExpenseGLAccount]          VARCHAR (100)  NULL,
    [AdDepsGLAccount]               VARCHAR (100)  NULL,
    [AssetSaleGLAccount]            VARCHAR (100)  NULL,
    [AssetWriteOffGLAccount]        VARCHAR (100)  NULL,
    [AssetWriteDownLAccount]        VARCHAR (100)  NULL,
    [LegalEntity]                   VARCHAR (MAX)  NULL,
    CONSTRAINT [PK_AssetAttributeTypeAudit] PRIMARY KEY CLUSTERED ([AuditAssetAttributeTypeId] ASC)
);

