CREATE TABLE [dbo].[AssetCalibrationAudit] (
    [AssetCalibrationAuditId]           BIGINT          IDENTITY (1, 1) NOT NULL,
    [AssetCalibrationId]                BIGINT          NOT NULL,
    [AssetRecordId]                     BIGINT          NOT NULL,
    [CalibrationRequired]               BIT             NULL,
    [CertificationRequired]             BIT             NULL,
    [InspectionRequired]                BIT             NULL,
    [VerificationRequired]              BIT             NULL,
    [AssetCalibrationMin]               VARCHAR (30)    NULL,
    [AssetCalibrationMinTolerance]      VARCHAR (30)    NULL,
    [AssetCalibratonMax]                VARCHAR (30)    NULL,
    [AssetCalibrationMaxTolerance]      VARCHAR (30)    NULL,
    [AssetCalibrationExpected]          VARCHAR (30)    NULL,
    [AssetCalibrationExpectedTolerance] VARCHAR (30)    NULL,
    [AssetCalibrationMemo]              NVARCHAR (MAX)  NULL,
    [MasterCompanyId]                   INT             NULL,
    [IsDeleted]                         BIT             NULL,
    [IsActive]                          BIT             NULL,
    [CalibrationDefaultVendorId]        BIGINT          NULL,
    [CertificationDefaultVendorId]      BIGINT          NULL,
    [InspectionDefaultVendorId]         BIGINT          NULL,
    [VerificationDefaultVendorId]       BIGINT          NULL,
    [CertificationFrequencyMonths]      TINYINT         NULL,
    [CertificationFrequencyDays]        BIGINT          NULL,
    [CertificationDefaultCost]          DECIMAL (18, 2) NULL,
    [CertificationGlAccountId]          BIGINT          NULL,
    [CertificationMemo]                 NVARCHAR (MAX)  NULL,
    [InspectionMemo]                    NVARCHAR (MAX)  NULL,
    [InspectionGlaAccountId]            BIGINT          NULL,
    [InspectionDefaultCost]             DECIMAL (18, 2) NULL,
    [InspectionFrequencyMonths]         TINYINT         NULL,
    [InspectionFrequencyDays]           BIGINT          NULL,
    [VerificationFrequencyDays]         BIGINT          NULL,
    [VerificationFrequencyMonths]       TINYINT         NULL,
    [VerificationDefaultCost]           DECIMAL (18, 2) NULL,
    [CalibrationDefaultCost]            DECIMAL (18, 2) NULL,
    [CalibrationFrequencyMonths]        TINYINT         NULL,
    [CalibrationFrequencyDays]          BIGINT          NULL,
    [CalibrationGlAccountId]            BIGINT          NULL,
    [CalibrationMemo]                   NVARCHAR (MAX)  NULL,
    [VerificationMemo]                  NVARCHAR (MAX)  NULL,
    [VerificationGlAccountId]           BIGINT          NULL,
    [CalibrationCurrencyId]             INT             NULL,
    [CertificationCurrencyId]           INT             NULL,
    [InspectionCurrencyId]              INT             NULL,
    [VerificationCurrencyId]            INT             NULL,
    [CreatedBy]                         VARCHAR (256)   NULL,
    [UpdatedBy]                         VARCHAR (256)   NULL,
    [CreatedDate]                       DATETIME2 (7)   NULL,
    [UpdatedDate]                       DATETIME2 (7)   NOT NULL,
    [CalibrationProvider]               VARCHAR (10)    NULL,
    [CertificationProvider]             VARCHAR (10)    NULL,
    [InspectionProvider]                VARCHAR (10)    NULL,
    [VerificationProvider]              VARCHAR (10)    NULL,
    CONSTRAINT [PK__AssetCalibrationAud__88889B1E86626B25] PRIMARY KEY CLUSTERED ([AssetCalibrationAuditId] ASC),
    CONSTRAINT [FK_AssetCalibrationAudit_Asset] FOREIGN KEY ([AssetRecordId]) REFERENCES [dbo].[Asset] ([AssetRecordId]),
    CONSTRAINT [FK_AssetCalibrationAudit_AssetCalibration] FOREIGN KEY ([AssetCalibrationId]) REFERENCES [dbo].[AssetCalibration] ([AssetCalibrationId])
);

