CREATE TABLE [dbo].[ContactAudit] (
    [AuditContactId]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [ModuleId]         BIGINT         NOT NULL,
    [ReferenceId]      BIGINT         NOT NULL,
    [contactId]        BIGINT         NOT NULL,
    [IsDefaultContact] BIT            NULL,
    [Prefix]           VARCHAR (20)   NULL,
    [FirstName]        VARCHAR (100)  NOT NULL,
    [LastName]         VARCHAR (30)   NOT NULL,
    [MiddleName]       VARCHAR (30)   NULL,
    [Suffix]           VARCHAR (20)   NULL,
    [ContactTitle]     VARCHAR (30)   NULL,
    [WorkPhone]        VARCHAR (20)   NULL,
    [WorkPhoneExtn]    VARCHAR (20)   NULL,
    [MobilePhone]      VARCHAR (20)   NULL,
    [AlternatePhone]   VARCHAR (20)   NULL,
    [Fax]              VARCHAR (20)   NULL,
    [Email]            VARCHAR (200)  NULL,
    [WebsiteURL]       VARCHAR (200)  NULL,
    [Notes]            NVARCHAR (MAX) NULL,
    [MasterCompanyId]  INT            NOT NULL,
    [CreatedBy]        VARCHAR (256)  NULL,
    [UpdatedBy]        VARCHAR (256)  NULL,
    [CreatedDate]      DATETIME2 (7)  NOT NULL,
    [UpdatedDate]      DATETIME2 (7)  NOT NULL,
    [IsActive]         BIT            NULL,
    [Tag]              VARCHAR (255)  NULL,
    [IsDeleted]        BIT            CONSTRAINT [ContactAudit_DC_Delete] DEFAULT ((0)) NOT NULL,
    [ContactTagId]     BIGINT         NULL,
    [Attention]        VARCHAR (250)  NULL,
    CONSTRAINT [PK_ContactAudit] PRIMARY KEY CLUSTERED ([AuditContactId] ASC)
);

