CREATE TABLE [dbo].[CycleCountBatchDetails] (
    [CycleCountBatchDetailId]    BIGINT        IDENTITY (1, 1) NOT NULL,
    [JournalBatchHeaderId]       BIGINT        NOT NULL,
    [JournalBatchDetailId]       BIGINT        NOT NULL,
    [CommonJournalBatchDetailId] BIGINT        NOT NULL,
    [StocklineId]                BIGINT        NOT NULL,
    [StocklineNumber]            VARCHAR (50)  NOT NULL,
    [ItemMasterId]               BIGINT        NOT NULL,
    [PartNumber]                 VARCHAR (50)  NOT NULL,
    [SiteId]                     BIGINT        NOT NULL,
    [Site]                       VARCHAR (100) NOT NULL,
    [WarehouseId]                BIGINT        NULL,
    [Warehouse]                  VARCHAR (100) NULL,
    [LocationId]                 BIGINT        NULL,
    [Location]                   VARCHAR (100) NULL,
    [BinId]                      BIGINT        NULL,
    [Bin]                        VARCHAR (100) NULL,
    [ShelfId]                    BIGINT        NULL,
    [Shelf]                      VARCHAR (100) NULL,
    [ReferenceId]                BIGINT        NOT NULL,
    [ReferenceNumber]            VARCHAR (50)  NOT NULL,
    [ReferenceDetailId]          BIGINT        NOT NULL,
    [MasterCompanyId]            INT           NOT NULL,
    [LegalEntityId]              BIGINT        NULL,
    [LedgerId]                   BIGINT        NULL,
    [AccountingCalendarId]       BIGINT        NULL,
    CONSTRAINT [PK_CycleCountBatchDetails] PRIMARY KEY CLUSTERED ([CycleCountBatchDetailId] ASC)
);

