CREATE TABLE [dbo].[DistributionCodeEntry] (
    [DistributionId]  BIGINT        IDENTITY (1, 1) NOT NULL,
    [JournalTypeID]   INT           NOT NULL,
    [JournalTypeName] VARCHAR (500) NULL,
    [CodeName]        VARCHAR (500) NULL,
    [Description]     VARCHAR (500) NULL,
    [GLAccountId]     BIGINT        NULL,
    [GLAccountName]   VARCHAR (500) NULL,
    [Level1Id]        BIGINT        NULL,
    [Level1Name]      VARCHAR (500) NULL,
    [Level2Id]        BIGINT        NULL,
    [Level2Name]      VARCHAR (500) NULL,
    [Level3Id]        BIGINT        NULL,
    [Level3Name]      VARCHAR (500) NULL,
    [Level4Id]        BIGINT        NULL,
    [Level4Name]      VARCHAR (500) NULL,
    [Level5Id]        BIGINT        NULL,
    [Level5Name]      VARCHAR (500) NULL,
    [Level6Id]        BIGINT        NULL,
    [Level6Name]      VARCHAR (500) NULL,
    [Level7Id]        BIGINT        NULL,
    [Level7Name]      VARCHAR (500) NULL,
    [Level8Id]        BIGINT        NULL,
    [Level8Name]      VARCHAR (500) NULL,
    [Level9Id]        BIGINT        NULL,
    [Level9Name]      VARCHAR (500) NULL,
    [Level10Id]       BIGINT        NULL,
    [Level10Name]     VARCHAR (500) NULL,
    [MasterCompanyId] INT           NOT NULL,
    [CreatedBy]       VARCHAR (256) NOT NULL,
    [UpdatedBy]       VARCHAR (256) NOT NULL,
    [CreatedDate]     DATETIME2 (7) CONSTRAINT [DF_DistributionCodeEntry_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]     DATETIME2 (7) CONSTRAINT [DF_DistributionCodeEntry_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]        BIT           CONSTRAINT [DF_DistributionCodeEntry_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]       BIT           CONSTRAINT [DF_DistributionCodeEntry_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_DistributionCodeEntry] PRIMARY KEY CLUSTERED ([DistributionId] ASC)
);

