CREATE TABLE [dbo].[EmployeeTrainingAudit] (
    [EmployeeTrainingAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [EmployeeTrainingId]      BIGINT          NOT NULL,
    [EmployeeId]              BIGINT          NOT NULL,
    [AircraftModelId]         BIGINT          NULL,
    [EmployeeTrainingTypeId]  BIGINT          NOT NULL,
    [ScheduleDate]            DATETIME2 (7)   NULL,
    [CompletionDate]          DATETIME2 (7)   NULL,
    [Cost]                    NUMERIC (18, 2) NULL,
    [Duration]                INT             NULL,
    [Provider]                VARCHAR (256)   NULL,
    [IndustryCode]            VARCHAR (256)   NULL,
    [ExpirationDate]          DATETIME2 (7)   NULL,
    [MasterCompanyId]         INT             NOT NULL,
    [CreatedBy]               VARCHAR (256)   NOT NULL,
    [UpdatedBy]               VARCHAR (256)   NOT NULL,
    [CreatedDate]             DATETIME2 (7)   CONSTRAINT [DF_EmployeeTrainingAudit_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]             DATETIME2 (7)   CONSTRAINT [DF_EmployeeTrainingAudit_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                BIT             CONSTRAINT [DF_EmployeeTrainingAudit_IsActive] DEFAULT ((1)) NOT NULL,
    [FrequencyOfTrainingId]   BIGINT          NULL,
    [AircraftManufacturerId]  INT             NULL,
    [DurationTypeId]          INT             NULL,
    [IsDeleted]               BIT             CONSTRAINT [DF_EmployeeTrainingAudit_IsDeleted] DEFAULT ((0)) NOT NULL,
    [Memo]                    VARCHAR (MAX)   NULL,
    [InternalReference]       VARCHAR (256)   NULL,
    [TrainingNameId]          BIGINT          NULL,
    [ProviderId]              BIGINT          NULL,
    [ProviderType]            VARCHAR (50)    NULL,
    [IsRecurring]             BIT             NULL,
    [DurationHours]           INT             NULL,
    [DurationMinutes]         INT             NULL,
    [CategoryId]              BIGINT          NULL,
    [CategoryType]            VARCHAR (50)    NULL,
    [CurrencyId]              BIGINT          NULL,
    [CurrencyCode]            VARCHAR (200)   NULL,
    CONSTRAINT [PK_EmployeeTrainingAudit] PRIMARY KEY CLUSTERED ([EmployeeTrainingAuditId] ASC)
);

