CREATE TABLE [dbo].[ExchangeSalesOrderReservedStock] (
    [SOReservedStockId]        BIGINT        IDENTITY (1, 1) NOT NULL,
    [ExchangeSalesOrderId]     BIGINT        NOT NULL,
    [ExchangeSalesOrderPartId] BIGINT        NOT NULL,
    [StockLIneId]              BIGINT        NOT NULL,
    [ConditionId]              BIGINT        NOT NULL,
    [ItemMasterId]             BIGINT        NOT NULL,
    [Quantity]                 INT           NOT NULL,
    [AltPartMasterPartId]      BIGINT        NULL,
    [EquPartMasterPartId]      BIGINT        NULL,
    [IsAltPart]                BIT           NULL,
    [IsEquPart]                BIT           NULL,
    [ReservedById]             BIGINT        NOT NULL,
    [ReservedDate]             DATETIME2 (7) NOT NULL,
    [MasterCompanyId]          INT           NOT NULL,
    [CreatedBy]                VARCHAR (256) NOT NULL,
    [UpdatedBy]                VARCHAR (256) NOT NULL,
    [CreatedDate]              DATETIME2 (7) CONSTRAINT [DF_ExchangeSalesOrderReservedStock_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]              DATETIME2 (7) CONSTRAINT [DF_ExchangeSalesOrderReservedStock_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                 BIT           CONSTRAINT [DF_ExchangeSalesOrderReservedStock_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                BIT           CONSTRAINT [DF_ExchangeSalesOrderReservedStock_IsDeleted] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_ExchangeSalesOrderReservedStock] PRIMARY KEY CLUSTERED ([SOReservedStockId] ASC),
    CONSTRAINT [FK_ExchangeSalesOrderReservedStock_Condition] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([ConditionId]),
    CONSTRAINT [FK_ExchangeSalesOrderReservedStock_Employee] FOREIGN KEY ([ReservedById]) REFERENCES [dbo].[Employee] ([EmployeeId]),
    CONSTRAINT [FK_ExchangeSalesOrderReservedStock_ExchangeSalesOrder] FOREIGN KEY ([ExchangeSalesOrderId]) REFERENCES [dbo].[ExchangeSalesOrder] ([ExchangeSalesOrderId]),
    CONSTRAINT [FK_ExchangeSalesOrderReservedStock_ExchangeSalesOrderPart] FOREIGN KEY ([ExchangeSalesOrderPartId]) REFERENCES [dbo].[ExchangeSalesOrderPart] ([ExchangeSalesOrderPartId]),
    CONSTRAINT [FK_ExchangeSalesOrderReservedStock_ItemMaster] FOREIGN KEY ([ItemMasterId]) REFERENCES [dbo].[ItemMaster] ([ItemMasterId]),
    CONSTRAINT [FK_ExchangeSalesOrderReservedStock_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId]),
    CONSTRAINT [FK_ExchangeSalesOrderReservedStock_Stockline] FOREIGN KEY ([StockLIneId]) REFERENCES [dbo].[Stockline] ([StockLineId])
);

