CREATE TABLE [dbo].[JournalManualAudit] (
    [AuditJournalManualId]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [ID]                            BIGINT          NOT NULL,
    [IsManual]                      BIT             NOT NULL,
    [BatchNumber]                   VARCHAR (30)    NOT NULL,
    [BatchName]                     VARCHAR (50)    NOT NULL,
    [BatchDescription]              VARCHAR (50)    NOT NULL,
    [GLAccountId]                   BIGINT          NOT NULL,
    [BalanceTypeId]                 BIGINT          NOT NULL,
    [JournalCategoryId]             BIGINT          NOT NULL,
    [JournalTypeId]                 BIGINT          NOT NULL,
    [EntryDate]                     DATETIME        NOT NULL,
    [EffectiveDate]                 DATETIME        NOT NULL,
    [AccountingCalendarId]          BIGINT          NULL,
    [EmployeeId]                    BIGINT          NOT NULL,
    [LocalCurrencyId]               INT             NOT NULL,
    [ReportingCurrencyId]           INT             NOT NULL,
    [CurrencyDate]                  DATE            NULL,
    [JournalCurrencyTypeId]         BIGINT          NOT NULL,
    [IsReversing]                   BIT             NOT NULL,
    [ReversingDate]                 DATETIME        NULL,
    [ReversingAccountingCalendarId] BIGINT          NULL,
    [IsRecurring]                   BIT             NOT NULL,
    [RecurringDate]                 DATETIME        NULL,
    [MasterCompanyId]               INT             NOT NULL,
    [LocalDebitCurrency]            NUMERIC (18, 2) NULL,
    [LocalCreditCurrency]           NUMERIC (18, 2) NULL,
    [ReportingDebitCurrency]        NUMERIC (18, 2) NULL,
    [ReportingCreditCurrency]       NUMERIC (18, 2) NULL,
    [Description]                   VARCHAR (50)    NULL,
    [ManagementStructureEntityId]   BIGINT          NULL,
    [CreatedBy]                     VARCHAR (256)   NOT NULL,
    [UpdatedBy]                     VARCHAR (256)   NOT NULL,
    [CreatedDate]                   DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                   DATETIME2 (7)   NOT NULL,
    [IsActive]                      BIT             NOT NULL,
    [IsDeleted]                     BIT             NOT NULL,
    [CurrencyRate]                  DECIMAL (18)    NULL,
    CONSTRAINT [PK_JournalManualAudit] PRIMARY KEY CLUSTERED ([AuditJournalManualId] ASC)
);

