CREATE TABLE [dbo].[LaborOverloadCost] (
    [LaborOverloadCostId]                     BIGINT        IDENTITY (1, 1) NOT NULL,
    [UseIndTechLaborRate]                     BIT           NULL,
    [UseAvgRateTechByAction]                  BIT           NULL,
    [UseAvgRateOfAllTech]                     BIT           NULL,
    [AssignHoursBySpecificAction]             BIT           NULL,
    [AssignTotalHoursToWO]                    BIT           NULL,
    [AsPercentOfTechHourlyRate]               TINYINT       NULL,
    [FlatAmtPerHour]                          BIT           NULL,
    [FlatAmtPerWO]                            BIT           NULL,
    [MasterCompanyId]                         INT           NOT NULL,
    [CreatedBy]                               VARCHAR (256) NULL,
    [UpdatedBy]                               VARCHAR (256) NULL,
    [CreatedDate]                             DATETIME2 (7) CONSTRAINT [DF_LaborOverloadCost_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                             DATETIME2 (7) CONSTRAINT [DF_LaborOverloadCost_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                                BIT           CONSTRAINT [DF_LaborOverloadCost_IsActive] DEFAULT ((1)) NULL,
    [IsDeleted]                               BIT           NULL,
    [AVERAGERATEOFALLTECHNICIANMECHANIC]      VARCHAR (256) NULL,
    [ASPercentOFTECHNICIANMECHANICHOURLYRATE] VARCHAR (256) NULL,
    [FLATAMOUNTPERHOUR]                       VARCHAR (256) NULL,
    [FLATAMOUNTPERWORKORDER]                  VARCHAR (256) NULL,
    CONSTRAINT [PK_LaborOverloadCost] PRIMARY KEY CLUSTERED ([LaborOverloadCostId] ASC),
    CONSTRAINT [FK_LaborOverloadCost_MasterCompany] FOREIGN KEY ([MasterCompanyId]) REFERENCES [dbo].[MasterCompany] ([MasterCompanyId])
);

