CREATE TABLE [dbo].[LOTOtherCostDetailsAudit] (
    [AuditLotOtherCostDetailId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [LotOtherCostDetailId]      BIGINT          NOT NULL,
    [LotId]                     BIGINT          NOT NULL,
    [LotNumber]                 VARCHAR (200)   NULL,
    [ReconciledFreight]         DECIMAL (18, 2) NULL,
    [UnReconciledFreight]       DECIMAL (18, 2) NULL,
    [ManualAdjFreight]          DECIMAL (18, 2) NULL,
    [TotalFreight]              DECIMAL (18, 2) NULL,
    [ReconciledCharges]         DECIMAL (18, 2) NULL,
    [UnReconciledCharges]       DECIMAL (18, 2) NULL,
    [ManualAdjCharges]          DECIMAL (18, 2) NULL,
    [TotalOtherCost]            DECIMAL (18, 2) NULL,
    [StocklineId]                BIGINT          NULL,
    [StocklineNumber]           VARCHAR (100)   NULL,
    [ItemMasterId]              BIGINT          NULL,
    [PartNumber]                VARCHAR (200)   NULL,
    [PartDescription]           VARCHAR (MAX)   NULL,
    [ManufacturerId]            BIGINT          NULL,
    [ManufacturerName]          VARCHAR (200)   NULL,
    [ConditionId]                BIGINT          NULL,
    [Condition]                 VARCHAR (200)   NULL,
    [IsNA]                      BIT             NOT NULL,
    [ModuleId]                  INT             NULL,
    [ModuleName]                VARCHAR (100)   NULL,
    [ReferenceId]               BIGINT          NULL,
    [ReferenceNumber]           VARCHAR (100)   NULL,
    [ReferenceDate]             DATETIME2 (7)   NULL,
    [PostedDate]                DATETIME2 (7)   NULL,
    [Memo]                      NVARCHAR (MAX)  NULL,
    [MasterCompanyId]           INT             NOT NULL,
    [CreatedBy]                 VARCHAR (256)   NOT NULL,
    [UpdatedBy]                 VARCHAR (256)   NULL,
    [CreatedDate]               DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                DATETIME2 (7)   NULL,
    [IsActive]                  BIT             NOT NULL,
    [IsDeleted]                 BIT             NOT NULL,
    CONSTRAINT [PK_LOTOtherCostDetailsAudit] PRIMARY KEY CLUSTERED ([AuditLotOtherCostDetailId] ASC)
);

