CREATE TABLE [dbo].[ManualJournalApprovalAudit] (
    [AuditManualJournalApprovalId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [ManualJournalApprovalId]      BIGINT         NOT NULL,
    [ManualJournalHeaderId]        BIGINT         NOT NULL,
    [ManualJournalDetailsId]       BIGINT         NOT NULL,
    [Memo]                         NVARCHAR (MAX) NULL,
    [SentDate]                     DATETIME2 (7)  NULL,
    [ApprovedDate]                 DATETIME2 (7)  NULL,
    [ApprovedById]                 BIGINT         NULL,
    [ApprovedByName]               VARCHAR (200)  NULL,
    [RejectedDate]                 DATETIME2 (7)  NULL,
    [RejectedBy]                   BIGINT         NULL,
    [RejectedByName]               VARCHAR (200)  NULL,
    [StatusId]                     INT            NULL,
    [StatusName]                   VARCHAR (50)   NULL,
    [ActionId]                     INT            NULL,
    [MasterCompanyId]              INT            NOT NULL,
    [CreatedBy]                    VARCHAR (256)  NOT NULL,
    [UpdatedBy]                    VARCHAR (256)  NOT NULL,
    [CreatedDate]                  DATETIME2 (7)  NOT NULL,
    [UpdatedDate]                  DATETIME2 (7)  NOT NULL,
    [IsActive]                     BIT            CONSTRAINT [DF_ManualJournalApprovalAudit_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                    BIT            CONSTRAINT [DF_ManualJournalApprovalAudit_IsDeleted] DEFAULT ((0)) NOT NULL,
    [InternalSentToId]             BIGINT         NULL,
    [InternalSentToName]           VARCHAR (100)  NULL,
    [InternalSentById]             BIGINT         NULL,
    CONSTRAINT [PK_ManualJournalApprovalAudit] PRIMARY KEY CLUSTERED ([AuditManualJournalApprovalId] ASC)
);

