CREATE TABLE [dbo].[MaterialListsAudit] (
    [MaterialListsAuditId]    INT            IDENTITY (1, 1) NOT NULL,
    [Id]                      INT            NOT NULL,
    [CreatedBy]               VARCHAR (50)   NULL,
    [CreatedDate]             DATETIME       NOT NULL,
    [UpdatedBy]               VARCHAR (50)   NULL,
    [UpdatedDate]             DATETIME       NULL,
    [IsDeleted]               BIT            NULL,
    [PN]                      VARCHAR (256)  NULL,
    [Description]             VARCHAR (256)  NULL,
    [Condition]               VARCHAR (256)  NULL,
    [MandatoryOrSupplemental] VARCHAR (256)  NULL,
    [ItemClassification]      VARCHAR (256)  NULL,
    [Quantity]                VARCHAR (256)  NULL,
    [UOM]                     VARCHAR (256)  NULL,
    [UnitCost]                VARCHAR (256)  NULL,
    [ExtraCost]               VARCHAR (256)  NULL,
    [Price]                   VARCHAR (256)  NULL,
    [Memo]                    NVARCHAR (MAX) NULL,
    [Deffered]                BIT            NOT NULL,
    [ActionId]                BIGINT         NOT NULL,
    [WorkFlowId]              BIGINT         NOT NULL,
    [IsActive]                BIT            NULL,
    CONSTRAINT [PK_MaterialListsAudit] PRIMARY KEY CLUSTERED ([MaterialListsAuditId] ASC)
);

