CREATE TABLE [dbo].[PartRepairStationsDetails] (
    [PartRepairStationsDetailsId] BIGINT        IDENTITY (1, 1) NOT NULL,
    [PartRepairStationsId]        BIGINT        NOT NULL,
    [City]                        VARCHAR (250) NULL,
    [Country]                     VARCHAR (150) NULL,
    [FacilityId]                  BIGINT        NULL,
    [FacilityName]                VARCHAR (250) NULL,
    [OverhaulPrice]               VARCHAR (250) NULL,
    [OverHTat]                    VARCHAR (50)  NULL,
    [Phone]                       VARCHAR (20)  NULL,
    [PostalCode]                  VARCHAR (50)  NULL,
    [QuoteSpeed]                  VARCHAR (50)  NULL,
    [RepairHTat]                  VARCHAR (20)  NULL,
    [RepairPrice]                 VARCHAR (20)  NULL,
    [State]                       VARCHAR (50)  NULL,
    [TestPrice]                   VARCHAR (20)  NULL,
    [TestTat]                     VARCHAR (20)  NULL,
    [WebLink]                     VARCHAR (150) NULL,
    [Response]                    VARCHAR (250) NULL,
    [CreatedBy]                   VARCHAR (50)  NOT NULL,
    [CreatedDate]                 DATETIME2 (7) CONSTRAINT [DF_PartRepairStationsDetails_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [UpdatedBy]                   VARCHAR (50)  NOT NULL,
    [UpdatedDate]                 DATETIME2 (7) CONSTRAINT [DF_PartRepairStationsDetails_UpdatedDate] DEFAULT (getutcdate()) NOT NULL,
    [IsActive]                    BIT           CONSTRAINT [DF_PartRepairStationsDetailsIsActi_59FA5E80] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                   BIT           CONSTRAINT [DF_PartRepairStationsDetailsIsDele_5AEE82B9] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PartRepairStationsDetails] PRIMARY KEY CLUSTERED ([PartRepairStationsDetailsId] ASC),
    CONSTRAINT [FK_PartRepairStationsDetails_PartRepairStations] FOREIGN KEY ([PartRepairStationsId]) REFERENCES [dbo].[PartRepairStations] ([PartRepairStationsId])
);

