CREATE TABLE [dbo].[AssetInventoryAudit] (
    [AssetInventoryAuditId]             BIGINT          IDENTITY (1, 1) NOT NULL,
    [AssetInventoryId]                  BIGINT          NOT NULL,
    [AssetRecordId]                     BIGINT          NOT NULL,
    [AssetId]                           VARCHAR (30)    NOT NULL,
    [AlternateAssetRecordId]            BIGINT          NULL,
    [Name]                              VARCHAR (50)    NOT NULL,
    [Description]                       NVARCHAR (MAX)  NULL,
    [ManagementStructureId]             BIGINT          NOT NULL,
    [CalibrationRequired]               BIT             NULL,
    [CertificationRequired]             BIT             NULL,
    [InspectionRequired]                BIT             NULL,
    [VerificationRequired]              BIT             NULL,
    [IsDepreciable]                     BIT             NULL,
    [IsIntangible]                      BIT             NULL,
    [AssetAcquisitionTypeId]            BIGINT          NULL,
    [ManufacturerId]                    BIGINT          NULL,
    [ManufacturedDate]                  DATETIME2 (7)   NULL,
    [Model]                             VARCHAR (30)    NULL,
    [IsSerialized]                      BIT             NULL,
    [UnitOfMeasureId]                   BIGINT          NULL,
    [CurrencyId]                        INT             NULL,
    [UnitCost]                          DECIMAL (18, 2) NULL,
    [ExpirationDate]                    DATETIME2 (7)   NULL,
    [Memo]                              NVARCHAR (MAX)  NULL,
    [AssetParentRecordId]               BIGINT          NULL,
    [TangibleClassId]                   BIGINT          NULL,
    [AssetIntangibleTypeId]             BIGINT          NULL,
    [AssetCalibrationMin]               VARCHAR (30)    NULL,
    [AssetCalibrationMinTolerance]      VARCHAR (30)    NULL,
    [AssetCalibratonMax]                VARCHAR (30)    NULL,
    [AssetCalibrationMaxTolerance]      VARCHAR (30)    NULL,
    [AssetCalibrationExpected]          VARCHAR (30)    NULL,
    [AssetCalibrationExpectedTolerance] VARCHAR (30)    NULL,
    [AssetCalibrationMemo]              NVARCHAR (MAX)  NULL,
    [AssetIsMaintenanceReqd]            BIT             NULL,
    [AssetMaintenanceIsContract]        BIT             NULL,
    [AssetMaintenanceContractFile]      NVARCHAR (512)  NULL,
    [MaintenanceFrequencyMonths]        TINYINT         NULL,
    [MaintenanceFrequencyDays]          BIGINT          NULL,
    [MaintenanceDefaultVendorId]        BIGINT          NULL,
    [MaintenanceGLAccountId]            BIGINT          NULL,
    [MaintenanceMemo]                   NVARCHAR (MAX)  NULL,
    [IsWarrantyRequired]                BIT             NULL,
    [WarrantyCompany]                   VARCHAR (30)    NULL,
    [WarrantyStartDate]                 DATETIME2 (7)   NULL,
    [WarrantyEndDate]                   DATETIME2 (7)   NULL,
    [WarrantyStatusId]                  BIGINT          NULL,
    [UnexpiredTime]                     TINYINT         NULL,
    [MasterCompanyId]                   INT             NOT NULL,
    [AssetLocationId]                   BIGINT          NULL,
    [IsDeleted]                         BIT             NOT NULL,
    [Warranty]                          BIT             NULL,
    [IsActive]                          BIT             NOT NULL,
    [CalibrationDefaultVendorId]        BIGINT          NULL,
    [CertificationDefaultVendorId]      BIGINT          NULL,
    [InspectionDefaultVendorId]         BIGINT          NULL,
    [VerificationDefaultVendorId]       BIGINT          NULL,
    [CertificationFrequencyMonths]      TINYINT         NULL,
    [CertificationFrequencyDays]        BIGINT          NULL,
    [CertificationDefaultCost]          DECIMAL (18, 2) NULL,
    [CertificationGlAccountId]          BIGINT          NULL,
    [CertificationMemo]                 NVARCHAR (MAX)  NULL,
    [InspectionMemo]                    NVARCHAR (MAX)  NULL,
    [InspectionGlaAccountId]            BIGINT          NULL,
    [InspectionDefaultCost]             DECIMAL (18, 2) NULL,
    [InspectionFrequencyMonths]         TINYINT         NULL,
    [InspectionFrequencyDays]           BIGINT          NULL,
    [VerificationFrequencyDays]         BIGINT          NULL,
    [VerificationFrequencyMonths]       TINYINT         NULL,
    [VerificationDefaultCost]           DECIMAL (18, 2) NULL,
    [CalibrationDefaultCost]            DECIMAL (18, 2) NULL,
    [CalibrationFrequencyMonths]        TINYINT         NULL,
    [CalibrationFrequencyDays]          BIGINT          NULL,
    [CalibrationGlAccountId]            BIGINT          NULL,
    [CalibrationMemo]                   NVARCHAR (MAX)  NULL,
    [VerificationMemo]                  NVARCHAR (MAX)  NULL,
    [VerificationGlAccountId]           BIGINT          NULL,
    [CalibrationCurrencyId]             INT             NULL,
    [CertificationCurrencyId]           INT             NULL,
    [InspectionCurrencyId]              INT             NULL,
    [VerificationCurrencyId]            INT             NULL,
    [CreatedBy]                         VARCHAR (256)   NOT NULL,
    [UpdatedBy]                         VARCHAR (256)   NOT NULL,
    [CreatedDate]                       DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                       DATETIME2 (7)   NOT NULL,
    [AssetMaintenanceContractFileExt]   VARCHAR (50)    NULL,
    [WarrantyFile]                      NVARCHAR (512)  NULL,
    [WarrantyFileExt]                   VARCHAR (50)    NULL,
    [MasterPartId]                      BIGINT          NULL,
    [EntryDate]                         DATETIME2 (7)   NULL,
    [InstallationCost]                  DECIMAL (18, 2) NULL,
    [Freight]                           DECIMAL (18, 2) NULL,
    [Insurance]                         DECIMAL (18, 2) NULL,
    [Taxes]                             DECIMAL (18, 2) NULL,
    [TotalCost]                         DECIMAL (18, 2) NULL,
    [WarrantyDefaultVendorId]           BIGINT          NULL,
    [WarrantyGLAccountId]               BIGINT          NULL,
    [Depreciable]                       BIT             NULL,
    [NonDepreciable]                    BIT             NULL,
    [Amortizable]                       BIT             NULL,
    [NonAmortizable]                    BIT             NULL,
    [SerialNo]                          NVARCHAR (50)   NULL,
    [isInsurance]                       BIT             NULL,
    [AssetLife]                         INT             NULL,
    [WarrantyCompanyId]                 BIGINT          NULL,
    [WarrantyCompanyName]               VARCHAR (100)   NULL,
    [WarrantyCompanySelectId]           INT             NULL,
    [WarrantyMemo]                      NVARCHAR (MAX)  NULL,
    [IsQtyReserved]                     BIT             DEFAULT ((0)) NULL,
    [InventoryStatusId]                 BIGINT          NULL,
    [InventoryNumber]                   VARCHAR (100)   NULL,
    [AssetStatusId]                     BIGINT          NULL,
    [Level1]                            VARCHAR (200)   NULL,
    [Level2]                            VARCHAR (200)   NULL,
    [Level3]                            VARCHAR (200)   NULL,
    [Level4]                            VARCHAR (200)   NULL,
    [ManufactureName]                   VARCHAR (100)   NULL,
    [LocationName]                      VARCHAR (100)   NULL,
    [Qty]                               DECIMAL (13, 2) NULL,
    [StklineNumber]                     VARCHAR (100)   NULL,
    [AvailStatus]                       VARCHAR (100)   NULL,
    [PartNumber]                        VARCHAR (100)   NULL,
    [ControlNumber]                     VARCHAR (100)   NULL,
    [RepairOrderId]                     BIGINT          NULL,
    [RepairOrderPartRecordId]           BIGINT          NULL,
    [PurchaseOrderId]                   BIGINT          NULL,
    [PurchaseOrderPartRecordId]         BIGINT          NULL,
    [ReceiverNumber]                    VARCHAR (100)   NULL,
    [ReceivedDate]                      DATETIME2 (7)   NULL,
    [SiteId]                            BIGINT          NULL,
    [SiteName]                          VARCHAR (250)   NULL,
    [WarehouseId]                       BIGINT          NULL,
    [Warehouse]                         VARCHAR (250)   NULL,
    [LocationId]                        BIGINT          NULL,
    [Location]                          VARCHAR (250)   NULL,
    [ShelfId]                           BIGINT          NULL,
    [ShelfName]                         VARCHAR (250)   NULL,
    [BinId]                             BIGINT          NULL,
    [BinName]                           VARCHAR (250)   NULL,
    CONSTRAINT [PK_AssetInventoryAudit] PRIMARY KEY CLUSTERED ([AssetInventoryAuditId] ASC),
    CONSTRAINT [FK_AssetInventoryAudit_AssetInventory] FOREIGN KEY ([AssetInventoryId]) REFERENCES [dbo].[AssetInventory] ([AssetInventoryId])
);





