CREATE TABLE [dbo].[AssetAudit] (
    [AssetAuditId]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [AssetRecordId]                   BIGINT          NOT NULL,
    [AssetId]                         VARCHAR (30)    NULL,
    [Name]                            VARCHAR (50)    NULL,
    [Description]                     VARCHAR (500)   NULL,
    [ManagementStructureId]           BIGINT          NULL,
    [IsTangible]                      BIT             NULL,
    [IsIntangible]                    BIT             NULL,
    [AssetAcquisitionTypeId]          TINYINT         NULL,
    [ManufacturerId]                  BIGINT          NULL,
    [ManufacturedDate]                DATETIME2 (7)   NULL,
    [Model]                           VARCHAR (30)    NULL,
    [IsSerialized]                    BIT             NULL,
    [UnitOfMeasureId]                 BIGINT          NULL,
    [CurrencyId]                      INT             NULL,
    [UnitCost]                        DECIMAL (18, 2) NULL,
    [ExpirationDate]                  DATETIME2 (7)   NULL,
    [Memo]                            NVARCHAR (MAX)  NULL,
    [TangibleClassId]                 BIGINT          NULL,
    [AssetIntangibleTypeId]           BIGINT          NULL,
    [AssetMaintenanceIsContract]      BIT             NULL,
    [AssetMaintenanceContractFile]    NVARCHAR (512)  NULL,
    [UnexpiredTime]                   TINYINT         NULL,
    [MasterCompanyId]                 INT             NULL,
    [AssetLocationId]                 VARCHAR (100)   NULL,
    [IsDeleted]                       BIT             NULL,
    [IsActive]                        BIT             NULL,
    [CreatedBy]                       VARCHAR (256)   NULL,
    [UpdatedBy]                       VARCHAR (256)   NULL,
    [CreatedDate]                     DATETIME2 (7)   NULL,
    [UpdatedDate]                     DATETIME2 (7)   NOT NULL,
    [EntryDate]                       DATETIME2 (7)   NULL,
    [AssetMaintenanceContractFileExt] VARCHAR (50)    NULL,
    [MasterPartId]                    BIGINT          NULL,
    [IsDepreciable]                   BIT             NULL,
    [IsNonDepreciable]                BIT             NULL,
    [IsAmortizable]                   BIT             NULL,
    [IsNonAmortizable]                BIT             NULL,
    [AlternateAssetRecordId]          BIGINT          NULL,
    [AssetParentRecordId]             BIGINT          NULL,
    [ControlNumber]                   VARCHAR (20)    NULL,
    [Level1]                          VARCHAR (200)   NULL,
    [Level2]                          VARCHAR (200)   NULL,
    [Level3]                          VARCHAR (200)   NULL,
    [Level4]                          VARCHAR (200)   NULL,
    [SiteId]                          BIGINT          NULL,
    [WarehouseId]                     BIGINT          NULL,
    [ShelfId]                         BIGINT          NULL,
    [BinId]                           BIGINT          NULL,
    [ManufacturerPN]                  NVARCHAR (80)   NULL,
    [CntrlNumber]                     INT             NULL,
    [AssetAttributeTypeId]            BIGINT          NULL,
    CONSTRAINT [PK__AssetAud__88889B1E86626B25] PRIMARY KEY CLUSTERED ([AssetAuditId] ASC),
    CONSTRAINT [FK_AssetAudit_Asset] FOREIGN KEY ([AssetRecordId]) REFERENCES [dbo].[Asset] ([AssetRecordId])
);



