CREATE TABLE [dbo].[ExchangeQuoteSettingAudit] (
    [AuditExchangeQuoteSettingId] BIGINT        IDENTITY (1, 1) NOT NULL,
    [ExchangeQuoteSettingId]      BIGINT        NOT NULL,
    [Typeid]                      INT           NOT NULL,
    [Prefix]                      VARCHAR (20)  NULL,
    [Sufix]                       VARCHAR (20)  NULL,
    [StartCode]                   BIGINT        NULL,
    [CurrentNumber]               BIGINT        NOT NULL,
    [DefaultStatusId]             INT           NOT NULL,
    [DefaultPriorityId]           BIGINT        NOT NULL,
    [COGS]                        INT           NOT NULL,
    [DaysForCoreReturn]           INT           NOT NULL,
    [MasterCompanyId]             INT           NOT NULL,
    [CreatedBy]                   VARCHAR (256) NOT NULL,
    [UpdatedBy]                   VARCHAR (256) NOT NULL,
    [CreatedDate]                 DATETIME2 (7) CONSTRAINT [DF_ExchangeQuoteSettingAudit_CreatedDate] DEFAULT (getdate()) NOT NULL,
    [UpdatedDate]                 DATETIME2 (7) CONSTRAINT [DF_ExchangeQuoteSettingAudit_UpdatedDate] DEFAULT (getdate()) NOT NULL,
    [IsActive]                    BIT           CONSTRAINT [DF_ExchangeQuoteSettingAudit_IsActive] DEFAULT ((1)) NOT NULL,
    [IsDeleted]                   BIT           CONSTRAINT [DF_ExchangeQuoteSettingAudit_IsDeleted] DEFAULT ((0)) NOT NULL,
    [IsApprovalRule]              BIT           NULL,
    [ValidDays]                   INT           DEFAULT ((0)) NOT NULL,
    [EffectiveDate]               DATETIME2 (7) NULL,
    CONSTRAINT [PK_ExchangeQuoteSettingAudit] PRIMARY KEY CLUSTERED ([AuditExchangeQuoteSettingId] ASC)
);

