CREATE TABLE [dbo].[ItemMasterNonStockAudit] (
    [ItemMasterNonStockAuditId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [ItemMasterNonStockId]         BIGINT          NOT NULL,
    [MasterPartId]                 BIGINT          NOT NULL,
    [PartNumber]                   VARCHAR (50)    NOT NULL,
    [PartDescription]              NVARCHAR (MAX)  NULL,
    [ItemNonStockClassificationId] BIGINT          NOT NULL,
    [ItemTypeId]                   INT             NOT NULL,
    [ItemGroupId]                  BIGINT          CONSTRAINT [DF_ItemMasterNonStockAudit_ItemGroupId] DEFAULT ((0)) NOT NULL,
    [IsAcquiredMethodBuy]          BIT             CONSTRAINT [DF_ItemMasterNonStockAudit_IsAcquiredMethodBuy] DEFAULT ((0)) NOT NULL,
    [ManufacturerId]               BIGINT          NOT NULL,
    [MasterCompanyId]              INT             NOT NULL,
    [DiscountPurchasePercent]      TINYINT         CONSTRAINT [DF_ItemMasterNonStockAudit_DiscountPurchasePercent] DEFAULT ((0)) NOT NULL,
    [GLAccountId]                  BIGINT          NOT NULL,
    [PurchaseUnitOfMeasureId]      BIGINT          NOT NULL,
    [IsHazardousMaterial]          BIT             CONSTRAINT [DF_ItemMasterNonStockAudit_IsHazardousMaterial] DEFAULT ((0)) NOT NULL,
    [CurrencyId]                   INT             NULL,
    [UnitCost]                     DECIMAL (18, 2) CONSTRAINT [DF_ItemMasterNonStockAudit_UnitCost] DEFAULT ((0)) NOT NULL,
    [ListPrice]                    DECIMAL (18, 2) CONSTRAINT [DF_ItemMasterNonStockAudit_ListPrice] DEFAULT ((0)) NOT NULL,
    [PriceDate]                    DATETIME2 (7)   NULL,
    [IsActive]                     BIT             NOT NULL,
    [IsDeleted]                    BIT             NOT NULL,
    [CreatedBy]                    VARCHAR (256)   NOT NULL,
    [CreatedDate]                  DATETIME2 (7)   NOT NULL,
    [UpdatedBy]                    VARCHAR (256)   NOT NULL,
    [UpdatedDate]                  DATETIME2 (7)   NOT NULL,
    CONSTRAINT [PK_ItemMasterNonStockAudit] PRIMARY KEY CLUSTERED ([ItemMasterNonStockAuditId] ASC)
);

