CREATE TABLE [dbo].[ItemMasterNonStockAudit] (
    [ItemMasterNonStockAuditId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [ItemMasterNonStockId]         BIGINT          NOT NULL,
    [MasterPartId]                 BIGINT          NOT NULL,
    [PartNumber]                   VARCHAR (50)    NOT NULL,
    [PartDescription]              NVARCHAR (MAX)  NULL,
    [ItemNonStockClassificationId] BIGINT          NOT NULL,
    [ItemTypeId]                   INT             NOT NULL,
    [ItemGroupId]                  BIGINT          CONSTRAINT [DF_ItemMasterNonStockAudit_ItemGroupId] DEFAULT ((0)) NOT NULL,
    [IsAcquiredMethodBuy]          BIT             CONSTRAINT [DF_ItemMasterNonStockAudit_IsAcquiredMethodBuy] DEFAULT ((0)) NOT NULL,
    [ManufacturerId]               BIGINT          NOT NULL,
    [MasterCompanyId]              INT             NOT NULL,
    [DiscountPurchasePercent]      SMALLINT        CONSTRAINT [DF_ItemMasterNonStockAudit_DiscountPurchasePercent] DEFAULT ((0)) NULL,
    [GLAccountId]                  BIGINT          NOT NULL,
    [PurchaseUnitOfMeasureId]      BIGINT          NOT NULL,
    [IsHazardousMaterial]          BIT             CONSTRAINT [DF_ItemMasterNonStockAudit_IsHazardousMaterial] DEFAULT ((0)) NOT NULL,
    [CurrencyId]                   INT             NULL,
    [UnitCost]                     DECIMAL (18, 2) CONSTRAINT [DF_ItemMasterNonStockAudit_UnitCost] DEFAULT ((0)) NOT NULL,
    [ListPrice]                    DECIMAL (18, 2) CONSTRAINT [DF_ItemMasterNonStockAudit_ListPrice] DEFAULT ((0)) NOT NULL,
    [PriceDate]                    DATETIME2 (7)   NULL,
    [IsActive]                     BIT             NOT NULL,
    [IsDeleted]                    BIT             NOT NULL,
    [CreatedBy]                    VARCHAR (256)   NOT NULL,
    [CreatedDate]                  DATETIME2 (7)   NOT NULL,
    [UpdatedBy]                    VARCHAR (256)   NOT NULL,
    [UpdatedDate]                  DATETIME2 (7)   NOT NULL,
    [SiteId]                       BIGINT          NULL,
    [WarehouseId]                  BIGINT          NULL,
    [LocationId]                   BIGINT          NULL,
    [ShelfId]                      BIGINT          NULL,
    [BinId]                        BIGINT          NULL,
    [IsSerialized]                 BIT             NULL,
    [IsMfgExpirationDate]          BIT             NULL,
    [LeadTimeDays]                 INT             NULL,
    [StockLevel]                   INT             NULL,
    [ReorderPoint]                 INT             NULL,
    [ReorderQuantiy]               INT             NULL,
    [InWarranty]                   BIT             NULL,
    [CurrentStlNo]                 BIGINT          NULL,
    [Site]                         VARCHAR (50)    NULL,
    [Warehouse]                    VARCHAR (50)    NULL,
    [Location]                     VARCHAR (50)    NULL,
    [Shelf]                        VARCHAR (50)    NULL,
    [Bin]                          VARCHAR (50)    NULL,
    [ItemNonStockClassification]   VARCHAR (50)    NULL,
    [GLAccount]                    VARCHAR (50)    NULL,
    [Currency]                     VARCHAR (50)    NULL,
    [Manufacturer]                 VARCHAR (50)    NULL,
    [MfgExpirationDate]            DATETIME2 (7)   NULL,
    CONSTRAINT [PK_ItemMasterNonStockAudit] PRIMARY KEY CLUSTERED ([ItemMasterNonStockAuditId] ASC)
);



