CREATE TABLE [dbo].[PurchaseOrderPartAudit] (
    [PurchaseOrderPartAuditId]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [PurchaseOrderPartRecordId] BIGINT          NOT NULL,
    [PurchaseOrderId]           BIGINT          NOT NULL,
    [ItemMasterId]              BIGINT          NOT NULL,
    [PartNumber]                VARCHAR (250)   NULL,
    [PartDescription]           VARCHAR (MAX)   NULL,
    [AltEquiPartNumberId]       BIGINT          NULL,
    [AltEquiPartNumber]         VARCHAR (250)   NULL,
    [AltEquiPartDescription]    VARCHAR (MAX)   NULL,
    [StockType]                 VARCHAR (50)    NULL,
    [ManufacturerId]            BIGINT          NOT NULL,
    [Manufacturer]              VARCHAR (250)   NULL,
    [PriorityId]                BIGINT          NOT NULL,
    [Priority]                  VARCHAR (50)    NULL,
    [NeedByDate]                DATETIME2 (7)   NOT NULL,
    [ConditionId]               BIGINT          NOT NULL,
    [Condition]                 VARCHAR (256)   NULL,
    [QuantityOrdered]           INT             NOT NULL,
    [QuantityBackOrdered]       INT             NOT NULL,
    [QuantityRejected]          INT             NULL,
    [VendorListPrice]           DECIMAL (18, 2) NOT NULL,
    [DiscountPercent]           BIGINT          NULL,
    [DiscountPerUnit]           DECIMAL (18, 2) NOT NULL,
    [DiscountAmount]            DECIMAL (18, 2) NOT NULL,
    [UnitCost]                  DECIMAL (18, 2) NOT NULL,
    [ExtendedCost]              DECIMAL (18, 2) NOT NULL,
    [FunctionalCurrencyId]      INT             NOT NULL,
    [FunctionalCurrency]        VARCHAR (50)    NULL,
    [ForeignExchangeRate]       DECIMAL (18, 2) NOT NULL,
    [ReportCurrencyId]          INT             NOT NULL,
    [ReportCurrency]            VARCHAR (50)    NULL,
    [WorkOrderId]               BIGINT          NULL,
    [WorkOrderNo]               VARCHAR (250)   NULL,
    [SubWorkOrderId]            BIGINT          NULL,
    [SubWorkOrderNo]            VARCHAR (250)   NULL,
    [RepairOrderId]             BIGINT          NULL,
    [ReapairOrderNo]            VARCHAR (250)   NULL,
    [SalesOrderId]              BIGINT          NULL,
    [SalesOrderNo]              VARCHAR (250)   NULL,
    [ItemTypeId]                INT             NULL,
    [ItemType]                  VARCHAR (250)   NULL,
    [GlAccountId]               BIGINT          NOT NULL,
    [GLAccount]                 VARCHAR (250)   NULL,
    [UOMId]                     BIGINT          NOT NULL,
    [UnitOfMeasure]             VARCHAR (25)    NULL,
    [ManagementStructureId]     BIGINT          NOT NULL,
    [Level1]                    VARCHAR (200)   NULL,
    [Level2]                    VARCHAR (200)   NULL,
    [Level3]                    VARCHAR (200)   NULL,
    [Level4]                    VARCHAR (200)   NULL,
    [ParentId]                  BIGINT          NULL,
    [isParent]                  BIT             NULL,
    [Memo]                      NVARCHAR (MAX)  NULL,
    [POPartSplitUserTypeId]     INT             NULL,
    [POPartSplitUserType]       VARCHAR (100)   NULL,
    [POPartSplitUserId]         BIGINT          NULL,
    [POPartSplitUser]           VARCHAR (100)   NULL,
    [POPartSplitSiteId]         BIGINT          NULL,
    [POPartSplitSiteName]       VARCHAR (500)   NULL,
    [POPartSplitAddressId]      BIGINT          NULL,
    [POPartSplitAddress1]       VARCHAR (100)   NULL,
    [POPartSplitAddress2]       VARCHAR (100)   NULL,
    [POPartSplitAddress3]       VARCHAR (100)   NULL,
    [POPartSplitCity]           VARCHAR (50)    NULL,
    [POPartSplitState]          VARCHAR (50)    NULL,
    [POPartSplitPostalCode]     VARCHAR (20)    NULL,
    [POPartSplitCountryId]      INT             NULL,
    [POPartSplitCountryName]    VARCHAR (200)   NULL,
    [MasterCompanyId]           INT             NULL,
    [CreatedBy]                 VARCHAR (256)   NOT NULL,
    [UpdatedBy]                 VARCHAR (256)   NOT NULL,
    [CreatedDate]               DATETIME2 (7)   NOT NULL,
    [UpdatedDate]               DATETIME2 (7)   NOT NULL,
    [IsActive]                  BIT             NOT NULL,
    [IsDeleted]                 BIT             NOT NULL,
    [DiscountPercentValue]      DECIMAL (18, 2) NULL,
    [EstDeliveryDate]           DATETIME2 (7)   NULL,
    CONSTRAINT [PK_PurchaseOrderPartAudit] PRIMARY KEY CLUSTERED ([PurchaseOrderPartAuditId] ASC)
);

