CREATE TABLE [dbo].[SalesOrderPartAudit] (
    [AuditSalesOrderPartId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [SalesOrderPartId]      BIGINT         NOT NULL,
    [SalesOrderId]          BIGINT         NOT NULL,
    [ItemMasterId]          BIGINT         NULL,
    [StockLineId]           BIGINT         NULL,
    [FxRate]                NUMERIC (9, 4) NULL,
    [Qty]                   INT            NULL,
    [UnitSalePrice]         NUMERIC (9, 2) NULL,
    [MarkUpPercentage]      INT            NULL,
    [SalesBeforeDiscount]   NUMERIC (9, 2) NULL,
    [Discount]              INT            NULL,
    [DiscountAmount]        NUMERIC (9, 2) NULL,
    [NetSales]              NUMERIC (9, 2) NULL,
    [MasterCompanyId]       INT            NOT NULL,
    [CreatedBy]             VARCHAR (256)  NOT NULL,
    [CreatedDate]           DATETIME2 (7)  NOT NULL,
    [UpdatedBy]             VARCHAR (256)  NOT NULL,
    [UpdatedDate]           DATETIME2 (7)  NOT NULL,
    [IsDeleted]             BIT            NOT NULL,
    [UnitCost]              NUMERIC (9, 2) NOT NULL,
    [MethodType]            CHAR (1)       NULL,
    [SalesPriceExtended]    NUMERIC (9, 2) NOT NULL,
    [MarkupExtended]        NUMERIC (9, 2) NOT NULL,
    [SalesDiscountExtended] NUMERIC (9, 2) NOT NULL,
    [NetSalePriceExtended]  NUMERIC (9, 2) NOT NULL,
    [UnitCostExtended]      NUMERIC (9, 2) NOT NULL,
    [MarginAmount]          NUMERIC (9, 2) NOT NULL,
    [MarginAmountExtended]  NUMERIC (9, 2) NOT NULL,
    [MarginPercentage]      NUMERIC (9, 2) NOT NULL,
    [ConditionId]           BIGINT         NOT NULL,
    [SalesOrderQuoteId]     BIGINT         NULL,
    [SalesOrderQuotePartId] BIGINT         NULL,
    [IsActive]              BIT            NOT NULL,
    [CustomerRequestDate]   DATETIME2 (7)  NOT NULL,
    [PromisedDate]          DATETIME2 (7)  NOT NULL,
    [EstimatedShipDate]     DATETIME2 (7)  NOT NULL,
    [PriorityId]            BIGINT         NOT NULL,
    [StatusId]              INT            NULL,
    [CustomerReference]     VARCHAR (100)  NULL,
    [QtyRequested]          INT            NULL,
    [Notes]                 NVARCHAR (MAX) NULL,
    [CurrencyId]            INT            NULL,
    [MarkupPerUnit]         NUMERIC (9, 2) NULL,
    [GrossSalePricePerUnit] NUMERIC (9, 2) NULL,
    [GrossSalePrice]        NUMERIC (9, 2) NULL,
    [TaxType]               VARCHAR (250)  NULL,
    [TaxPercentage]         NUMERIC (9, 2) NULL,
    [TaxAmount]             NUMERIC (9, 2) NULL,
    [AltOrEqType]           VARCHAR (50)   NULL,
    [ControlNumber]         VARCHAR (50)   NULL,
    [IdNumber]              VARCHAR (100)  NULL,
    [ItemNo]                INT            NULL,
    [POId]                  BIGINT         NULL,
    [PONum]                 VARCHAR (100)  NULL,
    [PONextDlvrDate]        DATETIME       NULL,
    [UnitSalesPricePerUnit] NUMERIC (9, 2) NULL,
    CONSTRAINT [PK_SalesOrderPartAudit] PRIMARY KEY CLUSTERED ([AuditSalesOrderPartId] ASC)
);

