CREATE TABLE [dbo].[SalesOrderShippingAudit] (
    [AuditSalesOrderShippingId]          BIGINT          IDENTITY (1, 1) NOT NULL,
    [SalesOrderShippingId]               BIGINT          NOT NULL,
    [SalesOrderId]                       BIGINT          NOT NULL,
    [SOShippingNum]                      VARCHAR (50)    NULL,
    [SOShippingStatusId]                 BIGINT          NOT NULL,
    [OpenDate]                           DATETIME2 (7)   NOT NULL,
    [CustomerId]                         BIGINT          NOT NULL,
    [ShipViaId]                          BIGINT          NOT NULL,
    [ShipDate]                           DATETIME2 (7)   NOT NULL,
    [AirwayBill]                         VARCHAR (50)    NOT NULL,
    [HouseAirwayBill]                    VARCHAR (50)    NOT NULL,
    [TrackingNum]                        VARCHAR (50)    NOT NULL,
    [Weight]                             DECIMAL (10, 2) NULL,
    [SoldToName]                         VARCHAR (256)   NOT NULL,
    [SoldToAddress1]                     VARCHAR (256)   NOT NULL,
    [SoldToAddress2]                     VARCHAR (256)   NULL,
    [SoldToCity]                         VARCHAR (256)   NOT NULL,
    [SoldToState]                        VARCHAR (256)   NOT NULL,
    [SoldToZip]                          VARCHAR (20)    NOT NULL,
    [SoldToCountryId]                    SMALLINT        NOT NULL,
    [ShipToName]                         VARCHAR (256)   NOT NULL,
    [ShipToSiteName]                     VARCHAR (256)   NOT NULL,
    [ShipToSiteId]                       BIGINT          NOT NULL,
    [ShipToAddress1]                     VARCHAR (256)   NOT NULL,
    [ShipToAddress2]                     VARCHAR (256)   NOT NULL,
    [ShipToCity]                         VARCHAR (256)   NOT NULL,
    [ShipToState]                        VARCHAR (256)   NOT NULL,
    [ShipToZip]                          VARCHAR (20)    NOT NULL,
    [ShipToCountryId]                    SMALLINT        NOT NULL,
    [OriginName]                         VARCHAR (256)   NOT NULL,
    [OriginAddress1]                     VARCHAR (256)   NOT NULL,
    [OriginAddress2]                     VARCHAR (256)   NULL,
    [OriginCity]                         VARCHAR (256)   NOT NULL,
    [OriginState]                        VARCHAR (256)   NOT NULL,
    [OriginZip]                          VARCHAR (20)    NOT NULL,
    [OriginCountryId]                    SMALLINT        NOT NULL,
    [Shipment]                           VARCHAR (100)   NULL,
    [SoldToSiteId]                       BIGINT          NOT NULL,
    [SoldToSiteName]                     VARCHAR (256)   NOT NULL,
    [SoldToCountryName]                  VARCHAR (256)   NOT NULL,
    [ShipToCustomerId]                   BIGINT          NOT NULL,
    [ShipToCountryName]                  VARCHAR (256)   NOT NULL,
    [OriginCountryName]                  VARCHAR (256)   NOT NULL,
    [OriginSiteId]                       BIGINT          NOT NULL,
    [IsSameForShipTo]                    BIT             NULL,
    [MasterCompanyId]                    INT             NOT NULL,
    [CreatedBy]                          VARCHAR (256)   NOT NULL,
    [UpdatedBy]                          VARCHAR (256)   NOT NULL,
    [CreatedDate]                        DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                        DATETIME2 (7)   NOT NULL,
    [IsActive]                           BIT             NOT NULL,
    [IsDeleted]                          BIT             NOT NULL,
    [ShipSizeLength]                     DECIMAL (10, 2) NULL,
    [ShipSizeWidth]                      DECIMAL (10, 2) NULL,
    [ShipSizeHeight]                     DECIMAL (10, 2) NULL,
    [ShipWeightUnit]                     BIGINT          NULL,
    [ShipSizeUnitOfMeasureId]            BIGINT          NULL,
    [ServiceClass]                       VARCHAR (50)    NULL,
    [NoOfContainer]                      INT             NULL,
    [ShippingAccountNo]                  VARCHAR (50)    NULL,
    [SmentNum]                           INT             NULL,
    [CustomerDomensticShippingShipViaId] BIGINT          NULL,
    [NoOfItems]                          INT             NULL,
    CONSTRAINT [PK_SalesOrderShippingAudit] PRIMARY KEY CLUSTERED ([AuditSalesOrderShippingId] ASC),
    CONSTRAINT [FK_SalesOrderShippingAudit_SalesOrderShipping] FOREIGN KEY ([SalesOrderShippingId]) REFERENCES [dbo].[SalesOrderShipping] ([SalesOrderShippingId])
);

