CREATE TABLE [dbo].[SubWOCheckInCheckOutWorkOrderAssetAudit] (
    [SubWOCheckInCheckOutWorkOrderAssetAuditId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [SubWOCheckInCheckOutWorkOrderAssetId]      BIGINT         NOT NULL,
    [SubWorkOrderAssetId]                       BIGINT         NOT NULL,
    [WorkOrderId]                               BIGINT         NOT NULL,
    [SubWorkOrderId]                            BIGINT         NOT NULL,
    [SubWOPartNoId]                             BIGINT         NOT NULL,
    [AssetRecordId]                             BIGINT         NOT NULL,
    [AssetInventoryId]                          BIGINT         NOT NULL,
    [CheckOutById]                              BIGINT         NULL,
    [CheckOutDate]                              DATETIME2 (7)  NULL,
    [CheckInById]                               BIGINT         NULL,
    [CheckInDate]                               DATETIME2 (7)  NULL,
    [Quantity]                                  INT            NOT NULL,
    [CheckOutQty]                               INT            NULL,
    [CheckInQty]                                INT            NULL,
    [CheckOutEmpId]                             BIGINT         NULL,
    [CheckInEmpId]                              BIGINT         NULL,
    [IsQtyCheckOut]                             BIT            NOT NULL,
    [Notes]                                     NVARCHAR (MAX) NULL,
    [InventoryStatusId]                         BIGINT         NOT NULL,
    [MasterCompanyId]                           INT            NOT NULL,
    [CreatedBy]                                 VARCHAR (256)  NOT NULL,
    [UpdatedBy]                                 VARCHAR (256)  NOT NULL,
    [CreatedDate]                               DATETIME2 (7)  NOT NULL,
    [UpdatedDate]                               DATETIME2 (7)  NOT NULL,
    [IsActive]                                  BIT            NOT NULL,
    [IsDeleted]                                 BIT            NOT NULL,
    CONSTRAINT [PK_SubWOCheckInCheckOutWorkOrderAssetAudit] PRIMARY KEY CLUSTERED ([SubWOCheckInCheckOutWorkOrderAssetAuditId] ASC)
);

