CREATE TABLE [dbo].[TimeLifeAudit] (
    [TimeLifeCyclesAuditId]     BIGINT        IDENTITY (1, 1) NOT NULL,
    [TimeLifeCyclesId]          BIGINT        NOT NULL,
    [CyclesRemaining]           VARCHAR (20)  NULL,
    [CyclesSinceNew]            VARCHAR (20)  NULL,
    [CyclesSinceOVH]            VARCHAR (20)  NULL,
    [CyclesSinceInspection]     VARCHAR (20)  NULL,
    [CyclesSinceRepair]         VARCHAR (20)  NULL,
    [TimeRemaining]             VARCHAR (20)  NULL,
    [TimeSinceNew]              VARCHAR (20)  NULL,
    [TimeSinceOVH]              VARCHAR (20)  NULL,
    [TimeSinceInspection]       VARCHAR (20)  NULL,
    [TimeSinceRepair]           VARCHAR (20)  NULL,
    [LastSinceNew]              VARCHAR (20)  NULL,
    [LastSinceOVH]              VARCHAR (20)  NULL,
    [LastSinceInspection]       VARCHAR (20)  NULL,
    [MasterCompanyId]           INT           NULL,
    [CreatedBy]                 VARCHAR (256) NULL,
    [UpdatedBy]                 VARCHAR (256) NULL,
    [CreatedDate]               DATETIME2 (7) NOT NULL,
    [UpdatedDate]               DATETIME2 (7) NOT NULL,
    [IsActive]                  BIT           NULL,
    [PurchaseOrderId]           BIGINT        NULL,
    [PurchaseOrderPartRecordId] BIGINT        NULL,
    [StockLineId]               BIGINT        CONSTRAINT [DF_TimeLifeAudit_StockLineId] DEFAULT ((0)) NULL,
    [DetailsNotProvided]        BIT           CONSTRAINT [DF_TimeLifeAudit_DetailsNotProvided] DEFAULT ((1)) NOT NULL,
    [RepairOrderId]             BIGINT        NULL,
    [RepairOrderPartRecordId]   BIGINT        NULL,
    [VendorRMAId]               BIGINT        NULL,
    [VendorRMADetailId]         BIGINT        NULL,
    CONSTRAINT [PK_TimeLifeAudit] PRIMARY KEY CLUSTERED ([TimeLifeCyclesAuditId] ASC)
);



