CREATE TABLE [dbo].[VendorCapabilityAudit] (
    [AuditVendorCapabilityId]   BIGINT          IDENTITY (1, 1) NOT NULL,
    [VendorCapabilityId]        BIGINT          NOT NULL,
    [VendorId]                  BIGINT          NOT NULL,
    [CapabilityTypeId]          INT             NOT NULL,
    [CapabilityTypeName]        VARCHAR (100)   NULL,
    [ItemMasterId]              BIGINT          NOT NULL,
    [CapabilityTypeDescription] VARCHAR (256)   NULL,
    [VendorRanking]             INT             NOT NULL,
    [IsPMA]                     BIT             NOT NULL,
    [IsDER]                     BIT             NOT NULL,
    [Cost]                      DECIMAL (18, 2) NULL,
    [TAT]                       INT             NULL,
    [Memo]                      NVARCHAR (MAX)  NULL,
    [MasterCompanyId]           INT             NOT NULL,
    [CreatedBy]                 VARCHAR (256)   NOT NULL,
    [UpdatedBy]                 VARCHAR (256)   NOT NULL,
    [CreatedDate]               DATETIME2 (7)   NOT NULL,
    [UpdatedDate]               DATETIME2 (7)   NOT NULL,
    [IsActive]                  BIT             NOT NULL,
    [IsDeleted]                 BIT             NOT NULL,
    [PartNumber]                VARCHAR (100)   NULL,
    [PartDescription]           VARCHAR (255)   NULL,
    [ManufacturerId]            BIGINT          NULL,
    [ManufactureName]           VARCHAR (100)   NULL,
    [CostDate]                  DATETIME        NULL,
    [CurrencyId]                INT             NULL,
    [Currency]                  VARCHAR (50)    NULL,
    [EmployeeId]                INT             NULL,
    CONSTRAINT [PK_VendorCapabiliyAudit] PRIMARY KEY CLUSTERED ([AuditVendorCapabilityId] ASC),
    CONSTRAINT [FK_VendorCapabiliyAudit_VendorCapabiliy] FOREIGN KEY ([VendorCapabilityId]) REFERENCES [dbo].[VendorCapability] ([VendorCapabilityId])
);



