CREATE TABLE [dbo].[WorkOrderExclusionsAudit] (
    [WorkOrderExclusionsAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderExclusionsId]      BIGINT          NOT NULL,
    [WorkOrderId]                BIGINT          NOT NULL,
    [WorkFlowWorkOrderId]        BIGINT          NOT NULL,
    [ItemMasterId]               BIGINT          NOT NULL,
    [EstimtPercentOccurranceId]  INT             NULL,
    [Memo]                       NVARCHAR (MAX)  NULL,
    [Quantity]                   INT             NOT NULL,
    [UnitCost]                   DECIMAL (20, 3) NOT NULL,
    [ExtendedCost]               DECIMAL (20, 3) NOT NULL,
    [MasterCompanyId]            INT             NOT NULL,
    [CreatedBy]                  VARCHAR (256)   NOT NULL,
    [UpdatedBy]                  VARCHAR (256)   NOT NULL,
    [CreatedDate]                DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                DATETIME2 (7)   NOT NULL,
    [IsActive]                   BIT             NOT NULL,
    [IsDeleted]                  BIT             NOT NULL,
    [TaskId]                     BIGINT          NOT NULL,
    [IsFromWorkFlow]             BIT             NULL,
    [ConditionCodeId]            BIGINT          NOT NULL,
    [ItemClassificationId]       BIGINT          NULL,
    CONSTRAINT [PK_WorkOrderExclusionsAudit] PRIMARY KEY CLUSTERED ([WorkOrderExclusionsAuditId] ASC)
);

