CREATE TABLE [dbo].[WorkOrderPartNumberAudit] (
    [WOPartNoAuditId]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [WOPartNoId]              BIGINT         NOT NULL,
    [WorkOrderId]             BIGINT         NOT NULL,
    [WorkOrderScopeId]        BIGINT         NOT NULL,
    [EstimatedShipDate]       DATETIME2 (7)  NOT NULL,
    [CustomerRequestDate]     DATETIME2 (7)  NOT NULL,
    [PromisedDate]            DATETIME2 (7)  NOT NULL,
    [EstimatedCompletionDate] DATETIME2 (7)  NOT NULL,
    [NTE]                     VARCHAR (30)   NULL,
    [Quantity]                INT            NOT NULL,
    [StockLineId]             BIGINT         NOT NULL,
    [CMMId]                   BIGINT         NULL,
    [WorkflowId]              BIGINT         NULL,
    [WorkOrderStageId]        BIGINT         NOT NULL,
    [WorkOrderStatusId]       BIGINT         NOT NULL,
    [WorkOrderPriorityId]     BIGINT         NOT NULL,
    [IsPMA]                   BIT            NULL,
    [IsDER]                   BIT            NULL,
    [TechStationId]           BIGINT         NULL,
    [TATDaysStandard]         INT            NULL,
    [MasterCompanyId]         INT            NOT NULL,
    [CreatedBy]               VARCHAR (256)  NOT NULL,
    [UpdatedBy]               VARCHAR (256)  NOT NULL,
    [CreatedDate]             DATETIME2 (7)  NOT NULL,
    [UpdatedDate]             DATETIME2 (7)  NOT NULL,
    [IsActive]                BIT            NOT NULL,
    [IsDeleted]               BIT            NOT NULL,
    [ItemMasterId]            BIGINT         NOT NULL,
    [TechnicianId]            BIGINT         NULL,
    [ConditionId]             BIGINT         NULL,
    [TATDaysCurrent]          INT            NULL,
    [RevisedPartId]           BIGINT         NULL,
    [ManagementStructureId]   BIGINT         NOT NULL,
    [IsMPNContract]           BIT            NULL,
    [ContractNo]              VARCHAR (20)   NULL,
    [WorkScope]               VARCHAR (200)  NULL,
    [PartNo]                  VARCHAR (256)  NOT NULL,
    [PartDescription]         VARCHAR (256)  NOT NULL,
    [RevisedPartNo]           VARCHAR (256)  NULL,
    [ItemGroup]               VARCHAR (256)  NULL,
    [CustRefNo]               VARCHAR (256)  NULL,
    [MangLevel1]              VARCHAR (256)  NULL,
    [MangLevel2]              VARCHAR (256)  NULL,
    [MangLevel3]              VARCHAR (256)  NULL,
    [MangLevel4]              VARCHAR (256)  NULL,
    [Condition]               VARCHAR (256)  NOT NULL,
    [StockLineNum]            VARCHAR (256)  NOT NULL,
    [SerialNum]               VARCHAR (256)  NULL,
    [PublicationNum]          VARCHAR (256)  NULL,
    [WorkflowNum]             VARCHAR (256)  NULL,
    [Stage]                   VARCHAR (256)  NOT NULL,
    [Status]                  VARCHAR (256)  NOT NULL,
    [Priority]                VARCHAR (256)  NOT NULL,
    [TechName]                VARCHAR (256)  NULL,
    [TechStation]             VARCHAR (256)  NULL,
    [isLocked]                BIT            DEFAULT ((0)) NOT NULL,
    [ReceivedDate]            DATETIME       NULL,
    [IsClosed]                BIT            DEFAULT ((0)) NULL,
    [ACTailNum]               NVARCHAR (500) NULL,
    [ClosedDate]              DATETIME       NULL,
    [PDFPath]                 NVARCHAR (MAX) NULL,
    [IsFinishGood]            BIT            DEFAULT ((0)) NULL,
    [RevisedConditionId]      BIGINT         NULL,
    [CustomerReference]       VARCHAR (256)  NULL,
    [AssignDate]              DATETIME2 (7)  NULL,
    [ReceivingCustomerWorkId] BIGINT         NULL,
    [ExpertiseId]             SMALLINT       NULL,
    CONSTRAINT [PK_WorkOrderPartNumberAudit] PRIMARY KEY CLUSTERED ([WOPartNoAuditId] ASC)
);







