CREATE TABLE [dbo].[WorkOrderExpertiseAudit] (
    [WorkOrderExpertiseAuditId] BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderExpertiseId]      BIGINT          NOT NULL,
    [WorkOrderId]               BIGINT          NOT NULL,
    [WorkFlowWorkOrderId]       BIGINT          NOT NULL,
    [ExpertiseTypeId]           SMALLINT        NULL,
    [EstimatedHours]            DECIMAL (18, 2) NULL,
    [StandardRate]              DECIMAL (18, 2) NULL,
    [TaskId]                    BIGINT          NOT NULL,
    [MasterCompanyId]           INT             NOT NULL,
    [CreatedBy]                 VARCHAR (256)   NOT NULL,
    [UpdatedBy]                 VARCHAR (256)   NOT NULL,
    [CreatedDate]               DATETIME2 (7)   NOT NULL,
    [UpdatedDate]               DATETIME2 (7)   NOT NULL,
    [IsActive]                  BIT             NOT NULL,
    [IsDeleted]                 BIT             NOT NULL,
    [LaborDirectRate]           DECIMAL (20, 2) NULL,
    [DirectLaborRate]           DECIMAL (20, 2) NULL,
    [OverHeadBurden]            DECIMAL (20, 2) NULL,
    [OverHeadCost]              DECIMAL (20, 2) NULL,
    [LaborOverHeadCost]         DECIMAL (20, 2) NULL,
    [IsFromWorkFlow]            BIT             NULL,
    CONSTRAINT [PK_WorkOrderExpertiseAudit] PRIMARY KEY CLUSTERED ([WorkOrderExpertiseAuditId] ASC)
);

