CREATE TABLE [dbo].[WorkOrderQuoteAudit] (
    [WorkOrderQuoteAuditId]     BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkOrderQuoteId]          BIGINT          NOT NULL,
    [WorkOrderId]               BIGINT          NOT NULL,
    [QuoteNumber]               VARCHAR (100)   NULL,
    [OpenDate]                  DATETIME2 (7)   NOT NULL,
    [QuoteDueDate]              DATETIME2 (7)   NOT NULL,
    [ValidForDays]              INT             NULL,
    [ExpirationDate]            DATETIME2 (7)   NULL,
    [QuoteStatusId]             BIGINT          NOT NULL,
    [CustomerId]                BIGINT          NOT NULL,
    [CurrencyId]                INT             NOT NULL,
    [DSO]                       VARCHAR (256)   NULL,
    [AccountsReceivableBalance] DECIMAL (20, 3) NULL,
    [SalesPersonId]             BIGINT          NULL,
    [EmployeeId]                BIGINT          NOT NULL,
    [MasterCompanyId]           INT             NOT NULL,
    [CreatedBy]                 VARCHAR (256)   NOT NULL,
    [UpdatedBy]                 VARCHAR (256)   NOT NULL,
    [CreatedDate]               DATETIME2 (7)   NOT NULL,
    [UpdatedDate]               DATETIME2 (7)   NOT NULL,
    [IsActive]                  BIT             NOT NULL,
    [IsDeleted]                 BIT             NOT NULL,
    [Memo]                      NVARCHAR (MAX)  NULL,
    [Warnings]                  VARCHAR (256)   NULL,
    [SentDate]                  DATETIME2 (7)   NULL,
    [ApprovedDate]              DATETIME2 (7)   NULL,
    [VersionNo]                 VARCHAR (20)    NULL,
    [IsApprovalBypass]          BIT             NULL,
    [QuoteParentId]             BIGINT          NULL,
    [IsVersionIncrease]         BIT             NULL,
    [Notes]                     NVARCHAR (MAX)  NULL,
    [CustomerName]              VARCHAR (200)   NULL,
    [CustomerContact]           VARCHAR (200)   NULL,
    [CreditLimit]               DECIMAL (18, 2) NULL,
    [CreditTerms]               VARCHAR (200)   NULL,
    CONSTRAINT [PK_WorkOrderQuoteAudit] PRIMARY KEY CLUSTERED ([WorkOrderQuoteAuditId] ASC)
);

