CREATE TABLE [dbo].[WorkflowAudit] (
    [WorkflowAuditId]              BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkflowId]                   BIGINT          NULL,
    [WorkflowDescription]          VARCHAR (500)   NULL,
    [Version]                      VARCHAR (10)    NULL,
    [WorkScopeId]                  BIGINT          NULL,
    [ItemMasterId]                 BIGINT          NULL,
    [PartNumberDescription]        VARCHAR (MAX)   NULL,
    [CustomerId]                   BIGINT          NULL,
    [CurrencyId]                   INT             NULL,
    [WorkflowExpirationDate]       DATETIME2 (7)   NULL,
    [IsCalculatedBERThreshold]     BIT             NULL,
    [IsFixedAmount]                BIT             NULL,
    [FixedAmount]                  NUMERIC (18, 2) NULL,
    [IsPercentageOfNew]            BIT             NULL,
    [CostOfNew]                    NUMERIC (18, 2) NULL,
    [PercentageOfNew]              INT             NULL,
    [IsPercentageOfReplacement]    BIT             NULL,
    [CostOfReplacement]            NUMERIC (18, 2) NULL,
    [PercentageOfReplacement]      INT             NULL,
    [Memo]                         NVARCHAR (MAX)  NULL,
    [ManagementStructureId]        BIGINT          NULL,
    [MasterCompanyId]              INT             NOT NULL,
    [CreatedBy]                    VARCHAR (256)   NULL,
    [UpdatedBy]                    VARCHAR (256)   NULL,
    [CreatedDate]                  DATETIME2 (7)   NOT NULL,
    [UpdatedDate]                  DATETIME2 (7)   NOT NULL,
    [IsActive]                     BIT             NULL,
    [IsDeleted]                    BIT             NULL,
    [PartNumber]                   VARCHAR (256)   NULL,
    [CustomerName]                 VARCHAR (256)   NULL,
    [FlatRate]                     NUMERIC (18, 2) NULL,
    [BERThresholdAmount]           NUMERIC (18, 2) NULL,
    [WorkOrderNumber]              VARCHAR (256)   NULL,
    [CustomerCode]                 VARCHAR (100)   NULL,
    [OtherCost]                    NUMERIC (18, 2) NULL,
    [WorkflowCreateDate]           DATETIME2 (7)   NULL,
    [ChangedPartNumberId]          BIGINT          NULL,
    [PercentageOfMaterial]         INT             NULL,
    [PercentageOfExpertise]        INT             NULL,
    [PercentageOfCharges]          INT             NULL,
    [PercentageOfOthers]           INT             NULL,
    [PercentageOfTotal]            DECIMAL (18, 2) NULL,
    [RevisedPartNumber]            VARCHAR (200)   NULL,
    [changedPartNumberDescription] VARCHAR (200)   NULL,
    [ChangedPartNumber]            VARCHAR (200)   NULL,
    [WorkScope]                    VARCHAR (100)   NULL,
    [Currency]                     VARCHAR (100)   NULL,
    [WFParentId]                   BIGINT          NULL,
    [IsVersionIncrease]            BIT             NULL,
    CONSTRAINT [PK_WorkflowAudit] PRIMARY KEY CLUSTERED ([WorkflowAuditId] ASC)
);

